### ISSUE TITLE
QR Code support for address display

### ISSUE THREAD

**Issue by lgn21st** [nervosnetwork/neuron#1133]
I'd like to see a qr code for a specific address in query result page, is that possible?

<img width="806" alt="Screen Shot 2019-11-16 at 10 33 23" src="https://user-images.githubusercontent.com/7104/68986667-93ecbb00-085c-11ea-816e-d43c0081bdd8.png">

**Comment by shaojunda** [comment]
move to explorer issues https://github.com/cryptape/ckb-explorer-internal/issues/315
