### ISSUE TITLE
无法获取最新区块

### ISSUE THREAD

**Issue by Wozxd** [nervosnetwork/neuron#1145]

**Comment by ashchan** [comment]
We have a fix for this and will release `v0.25.1` very soon.

**Comment by ashchan** [comment]
@Wozxd Could you try v0.25.1 and see if it works now?

**Comment by Wozxd** [comment]
> @Wozxd Could you try v0.25.1 and see if it works now?
谢谢你 已经成功了 
thank you it`s run well
