### ISSUE TITLE
Crash when copying address tx hash from history view

### ISSUE THREAD

**Issue by ashchan** [nervosnetwork/neuron#1170]
Crash log: https://gist.github.com/Aimeedeer/60ab3fbd9a4529d9d43f51d3b359b8e6

**Comment by Keith-CY** [comment]
@kellyshang Please close this issue after verification.

**Comment by kellyshang** [comment]
> @kellyshang Please close this issue after verification.

OK get.

**Comment by kellyshang** [comment]
Passed verification on Mac with develop branch(commit id: 2582a9b1dca3c856f86a205fcce45886e4342886 ). Tried copy tx hash on History page and address/tx hash on detail page will not crash now. 
BTW, seems I have no permission to close this issue. @Keith-CY you can close it if available.

**Comment by Keith-CY** [comment]
> Passed verification on Mac with develop branch(commit id: [2582a9b](https://github.com/nervosnetwork/neuron/commit/2582a9b1dca3c856f86a205fcce45886e4342886) ). Tried copy tx hash on History page and address/tx hash on detail page will not crash now.
> BTW, seems I have no permission to close this issue. @Keith-CY you can close it if available.

Sure
