### ISSUE TITLE
Deposit into Nervos DAO

### ISSUE THREAD

**Issue by Rodders135** [nervosnetwork/neuron#1245]
i am trying to deposit my CKB into the Nervos DAO, i have tried 4 times today but after about 20 minutes it displays that it has failed, i am running Neuron 0.26.0 on Microsoft.

I have tried again tonight and it is working now, not sure on the original problem but all good now.

**Comment by ashchan** [comment]
What do you men by running on Microsoft? On Windows? What's the failure message it displayed?
