### ISSUE TITLE
Neuron 0.26.0 wont sync above block 310651

### ISSUE THREAD

**Issue by BrianKBit** [nervosnetwork/neuron#1247]
I updated my old wallet 0.25 to the newest as prompted by the wallet and when sync begins it shows 310651 as the highest block. I have re-synced (cleared cache) twice, 2nd time block height when only to 310671,  now and I get the same block height. Any ideas how to correct? Once it was within 10,000 blocks of 310651 syncing slowed down.

**Comment by ashchan** [comment]
We couldn't reproduce this issue. Can you double check and confirm?

**Comment by BrianKBit** [comment]
I was finally able sync the wallet after another a couple of syncing attempts  I let it sync overnight and it now shows the transfer to the DAO has been completed.
Is the wallet very CPU dependent ? I was CPU mining and when I changed threads used by the miner to a lower thread count it began working better.  Thank you.
Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by ashchan** [comment]
@BrianKBit CKB, although bundled inside Neuron, would use CPU (2 cores if I remember correctly) as much as possible when it needs to sync to catch best height. So yes if it hasn't synced yet I think it's CPU dependent.

Once it's synced, considering the average block time is 7~8 seconds ATM, most of the time it shouldn't take more than 5% of CPU.

Talking the Neuron part. It's an electron app with a few renderer processes. So when busy (note that Neuron also has to scan the CKB blocks through RPC) it may cause hight CPU usage as well. And it also eats up 300-400 MB memory - which is sad but out of our engineering control.
