### ISSUE TITLE
Feature request: add language switch option

### ISSUE THREAD

**Issue by lgn21st** [nervosnetwork/neuron#1303]
My operating system default language is English, and I wish I can switch the current language to other one like Chinese, is that possible?

**Comment by ashchan** [comment]
@lgn21st Are you on macOS 10.15? If so you can set preferred language for any app: System Preferences - Language & Region - Apps. An example:

<img width="780" alt="Screen Shot 2020-01-07 at 14 20 06" src="https://user-images.githubusercontent.com/1391/71870311-cf1eb280-3158-11ea-9b5d-fac739db137a.png">
