### ISSUE TITLE
Send Transaction Error

### ISSUE THREAD

**Issue by MRdjwatt** [nervosnetwork/neuron#1345]
When sending a transaction error message appears: {code:-3,message:OutPoint:Dead(OutPoint(0xb0...

This occurs when sending to previously used address. 
Troubleshooting steps:
Firewall is off. 
Wallet recreated from seed.

**Comment by ashchan** [comment]
@MRdjwatt Has the wallet synced to recent block height when you sent the transaction?

**Comment by MRdjwatt** [comment]
Yes. That's what I found strange about the behaviour.

For completeness this is running latest version of neuron wallet on windows
10 (64bit) fully patched.

**Comment by MRdjwatt** [comment]
I have been able to send from a wallet created from same seed running
version 0.26.0

**Comment by ashchan** [comment]
Looks like a sync and cell collect bug. We'll have an eye on this and try to reproduce this issue. (It's New Year's holidays for most our team so this might be slow.)

**Comment by ashchan** [comment]
@MRdjwatt We have release v0.29.0-rc2 with several sync and performance fixes. Can you try that and see if this new version works?
