### ISSUE TITLE
Didn't show right balance 

### ISSUE THREAD

**Issue by TeRvErO** [nervosnetwork/neuron#1347]
I see on explorer that my address is already funded but neuron wallet didn't update it.
![image](https://user-images.githubusercontent.com/23222991/73374007-8cb94300-42ca-11ea-9042-cfa33c6ddff9.png)

BTW, his status is up to date:
![image](https://user-images.githubusercontent.com/23222991/73374092-b5413d00-42ca-11ea-8aa4-00724f89f2b3.png)

**Comment by ashchan** [comment]
From the sync status Neuron is still scanning blocks to update balance. 

* Balance is updating
