### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by richorca** [nervosnetwork/neuron#1358]
![image](https://user-images.githubusercontent.com/54572369/73885024-c41f8500-48b2-11ea-932e-b7d1149239ad.png)

Hi, Receiving this error on both 0.27 & 0.26
Clear cache multiple times, even deleted files in cell folder.
The wallet sync's but show incorrect balance and am unable to send.

**Comment by ashchan** [comment]
We're investigating this issue.

**Comment by RigaSaurusRex** [comment]
Hi,
When I try to Withdraw or deposit to the DAO, I get the error code: {code:-3,message:OutPoint: Dead(OutPoint

![image](https://user-images.githubusercontent.com/60843240/74101147-93e41a80-4b2e-11ea-939d-e27e0608fa3e.png)

The wallet is Synced and is at the correct block height (783,489) at the time of writing this.

The wallet is the lastest version, also had the same issue on the previous versions.

Is there a solution to resolve the issue?

Many thanks in advance

**Comment by magmainger** [comment]
Hi!
I've got the same issue!!!
Is there a solution to resolve the issue?
Many thanks in advance

**Comment by RigaSaurusRex** [comment]
Not as I know of. Re installed the wallet. Installed last two updates and
still the same issue. Sorry

**Comment by josipk** [comment]
So, this is a very common issue, all topics here have the same issue and still not fixed?

**Comment by dwarner301** [comment]
Some response from the developers would be nice.  I have 35,000 CKB stuck in limbo with about 1,800 CKB  per day incoming

**Comment by ashchan** [comment]
Guys we haven't been able to reproduce this issue so it's kind of difficult to troubleshoot. Any one trying importing wallet to `imToken` or other wallet and see if that can send out transaction?

**Comment by swipester** [comment]
I think i know the solution. when you upgrade to v.28 it has an integrated DAO . So to avoid it just reinitialize the original DAO and use that one, ill keep you posted if this works out just waiting for my balance to show 

ckb1qyqf9ucu467fy5jmwkmcrqc0agdywaxtsdnq90kc7v

**Comment by ashchan** [comment]
@swipester We have release [v0.29.0-rc2](https://github.com/nervosnetwork/neuron/releases/tag/v0.29.0-rc2) with several sync and performance fixes. Can you try that and see if this new version works?

**Comment by swipester** [comment]
I had a couple thosand ckb in the DAO and i was able to recover my balance
but the money in the DAO i cannot .. what files are associated with the DAO?
