### ISSUE TITLE
I cannot send CKB.  I get the following error:

### ISSUE THREAD

**Issue by dwarner301** [nervosnetwork/neuron#1371]
![CKBCapture](https://user-images.githubusercontent.com/60974084/74342946-4c50cf00-4d78-11ea-8036-121ca0f79e95.JPG)

**Comment by josipk** [comment]
Exactly the same problem here...
I clear cache but the problem still exists.

**Comment by ashchan** [comment]
Does the balance (amount) show correctly?

We're releasing a new version in a few hours. Please update and try clearing cache again.

**Comment by josipk** [comment]
In my case, balance is not correct, bigger amount is shown that it should. Seams that the system did not calculate output transactions.

**Comment by josipk** [comment]
With v0.28.0 version, the same issue is still present and the wallet is extremely slow and non-responsive. I use AppImage on Linux platform.

**Comment by ashchan** [comment]
If the balance is not correct then the wallet is still syncing. The above error happens when you try to send out transaction but the wallet is not fully synced yet.

**Comment by josipk** [comment]
It was fully synced and balance was not correct, still bigger than it should be.

**Comment by ashchan** [comment]
> It was fully synced and balance was not correct, still bigger than it should be.

Looks like a sync bug to me. Could you drop me a line (ash @ nervos.org) to help troubleshoot this issue? Thanks.

**Comment by josipk** [comment]
![Screenshot from 2020-02-14 08-25-17](https://user-images.githubusercontent.com/682501/74510434-104a7500-4f04-11ea-92b3-15ed56937639.png)

**Comment by josipk** [comment]
After resync, I still have same issue. I have tried wallet on different comps, no difference. What to do next?

**Comment by josipk** [comment]
Any update on this issue? Did anyone manage to solve this?

**Comment by ashchan** [comment]
Can you let us know what is the current block height your wallet has synced to? To check that:

On the Overview view, click the Blockchain Status and check the 'Block Number' value.

When fully synced it should be higher than 914k.

**Comment by josipk** [comment]
Block number 950714
![Screenshot from 2020-02-26 23-22-01](https://user-images.githubusercontent.com/682501/75393746-0c005d80-58ef-11ea-985c-915907b5f0dd.png)

**Comment by ashchan** [comment]
@josipk Looks like Neuron has synced. Do you have any incoming transactions since 2020-02-13? From your screenshot's `Recent Activities` it doesn't show any txs since that day.

We're going to release a new version on March 2nd, which addresses several sync issues (especially for mining wallet receiving daily txs with huge inputs). If you have recent transaction after 2020-02-13 and the wallet doesn't show them, the new version might have a fix for that.

**Comment by ashchan** [comment]
@dwarner301 @josipk We have release [v0.29.0-rc2](https://github.com/nervosnetwork/neuron/releases/tag/v0.29.0-rc2) with several sync and performance fixes. Can you try that and see if this new version works?

**Comment by josipk** [comment]
v0.29 works, I clear cache and reindex all transactions. I am able to send and receive fonds now.
Great, thanx.

**Comment by ashchan** [comment]
> v0.29 works, I clear cache and reindex all transactions. I am able to send and receive fonds now.
> Great, thanx.

That’ great!
