### ISSUE TITLE
Error sending CKB

### ISSUE THREAD

**Issue by trappist** [nervosnetwork/neuron#1374]
Not the same error as other recent reports:
```
{code:-32602,message:Invalid params: invalid length 2, expected fewer elements in array."}
```
After I enter my password for the transaction. No output in the launching console window, or in the devtools console.

**Comment by trappist** [comment]
This in the `develop` branch which is fully up to date as of this issue.

**Comment by ashchan** [comment]
You’ll need to use CKB 0.28.0.

**Comment by trappist** [comment]
After `git checkout rc/v0.28.0`; `yarn cache clean` and a restart, same error.

**Comment by trappist** [comment]
Reran `./scripts/download-ckb.sh` for a fresh ckb and I'm all set. Thanks!

**Comment by ashchan** [comment]
> Reran `./scripts/download-ckb.sh` for a fresh ckb and I'm all set. Thanks!

Glad to hear that!
