### ISSUE TITLE
0.28版本的neuron是否与0.25.1的ckb版本不兼容？

### ISSUE THREAD

**Issue by fuluwwa** [nervosnetwork/neuron#1378]
在存入NervosDAO时有下列错误：
![image](https://user-images.githubusercontent.com/37980938/74655622-9fd37a80-51c7-11ea-8592-c641bd1bc87c.png)

**Comment by kellyshang** [comment]
你是不是单独运行的 v0.28.0 之前版本 CKB 节点？Neuron 从 v0.26.3 版本开始内置了 CKB 节点，可以不用单独运行 CKB 节点了。
图中的报错是由于 CKB 的 v0.28.0 版本有 breaking change 导致的，如果你想单独运行 CKB 节点，建议下载[最新版 CKB ( v0.28.0 以上版本) ](https://github.com/nervosnetwork/ckb/releases/tag/v0.28.0)来运行。

**Comment by ashchan** [comment]
0.28 版本 Neuron 与 0.25.1 版本 CKB 不兼容。请使用 0.28.0 CKB，或是 Neuron 内置的节点。
