### ISSUE TITLE
visual c++ dependency is not checked on neuron (windows)

### ISSUE THREAD

**Issue by mathoticus** [nervosnetwork/neuron#1379]
User reported the issue in attached screenshots.

Installing this library fixed all issues. CKB node will prompt for the dependency and fail before running if not installed.

Visual C++ Redistributable for Visual Studio 2015 

https://www.microsoft.com/en-hk/download/details.aspx?id=48145

![image](https://user-images.githubusercontent.com/22106875/74794984-87239d00-5279-11ea-9482-4aab13065d7e.png)
![image](https://user-images.githubusercontent.com/22106875/74794993-8c80e780-5279-11ea-9ebf-50feac3f251d.png) 

(User reports json file is missing in above screenshot)

**Comment by ashchan** [comment]
@mathoticus Thanks for this info. This is very useful.

Bundling this VC++ redistributable might not be the best option for Neuron. We need to think a way to prompt user to install it from Neuron.

**Comment by ashchan** [comment]
The download page with more versions: https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads.

**Comment by ashchan** [comment]
Next version will add a Help - Neuron FAQ menu linking to https://docs.nervos.org/references/neuron-faq.html at which instruction for installing VC++ redistributable could be found. ATM there'll be no auto installation from Neuron installer.
