### ISSUE TITLE
withdraw DAO error

### ISSUE THREAD

**Issue by sambrown05** [nervosnetwork/neuron#1392]
![image](https://user-images.githubusercontent.com/61309786/75015957-96068b80-54d5-11ea-8a18-c627dd2b2d08.png)

Have updated wallet and cleared cache. Today's transactions are shown in the wallet overview. Attempt to withdraw locked funds from DAO yields this error.

(also History tab: clicking page 2 link froze the wallet - Not Responding)

Windows 10 Pro

**Comment by ashchan** [comment]
Could you provide these information:

* What is the synced block height? (Check that from Overview - Blockchain Status. 
* Does your wallet have transactions from mining pool (we found recently such wallet would have serious performance issue when syncing)?

**Comment by sambrown05** [comment]
Wallet malfunctioned, had to clear cache again. I'll get back to you with
the info once it's done.

It's my mining wallet, so there's one deposit per day from the mining pool.

**Comment by sambrown05** [comment]
OK I have a whole new problem set now. I can neither get my 19k CKB out
from DAO (says I have to wait another 28 days), nor lock any more away
(error in pic)
[image: image.png]

**Comment by lite** [comment]
Neuron 版本0.28.0 (0.28.0.20200212.1)
在NervosDAO中申请取出，显示余额不足
当前补偿周期 进度 120.2/180 epochs 距离结束时间 约10天0小时

**Comment by kellyshang** [comment]
> Neuron 版本0.28.0 (0.28.0.20200212.1)
> 在NervosDAO中申请取出，显示余额不足
> 当前补偿周期 进度 120.2/180 epochs 距离结束时间 约10天0小时

在存入的时候您是不是把所有CKB都存入了？或者钱包里没有可用CKB余额了？“申请取出”的时候交易需要手续费，需要确保钱包里有至少62CKB。
