### ISSUE TITLE
Synchronizing

### ISSUE THREAD

**Issue by cortina440** [nervosnetwork/neuron#1428]
hi l have an apple imac and it is continuously syncing and dosent update my wallet amount.
is there a fix?
l have downloaded the latest version and tried other versions but dosent work?
ls there  a fix for this?

**Comment by ashchan** [comment]
A full sync takes up to 2 hours depending on your network condition. 

Does your wallet receive mining rewards? If so we have a fix for that. We’ll release an RC version next Monday.

**Comment by cortina440** [comment]
Hi thanks for the reply.No mining rewards and the syncing has been on for days.Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: James Chen <notifications@github.com> Date: 1/3/20  1:30 am  (GMT+10:00) To: nervosnetwork/neuron <neuron@noreply.github.com> Cc: cortina440 <csfarrugia@bigpond.com>, Author <author@noreply.github.com> Subject: Re: [nervosnetwork/neuron] Synchronizing (#1428) A full sync takes up to 2 hours depending on your network condition.

Does your wallet receive mining rewards? If so we have a fix for that. We’ll release an RC version next Monday.



—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/nervosnetwork/neuron/issues/1428?email_source=notifications\u0026email_token=AOUO3TVLZPJNTLSGJ2RBWRLRFENZBA5CNFSM4K6XJAJKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOENL3PAY#issuecomment-592951171",

"url": "https://github.com/nervosnetwork/neuron/issues/1428?email_source=notifications\u0026email_token=AOUO3TVLZPJNTLSGJ2RBWRLRFENZBA5CNFSM4K6XJAJKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOENL3PAY#issuecomment-592951171",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Comment by ashchan** [comment]
We released a new RC version: https://github.com/nervosnetwork/neuron/releases/tag/v0.29.0-rc1

Can you download it and see if this version works? When syncing, please check `Overview` - `Blockchain Status` and see what is the `Block Number` value. (it should be higher than `991,000`).
