### ISSUE TITLE
CKB coins sent from Huobi to Neuron

### ISSUE THREAD

**Issue by peace1954** [nervosnetwork/neuron#1444]
Hi 
I sent coins from my Huobi exchange to Neuron but It still has not arrived. I got a message it has been received but I cannot see it on Neuron.
Can you please assist?
Thanks
Prem

**Comment by ashchan** [comment]
Make sure Neuron syncs fully. That could take a few hours or more based on your networking condition.

**Comment by ashchan** [comment]
You could also check your balance on explorer if Neuron hasn't synced yet.
