### ISSUE TITLE
sync problem

### ISSUE THREAD

**Issue by puffanddmx** [nervosnetwork/neuron#1453]
i download new version of neuron.
still syncing & balance updating message!

what is the problem?

**Comment by ashchan** [comment]
Could you provide these information:

## OS

Windows, macOS or Linux (and their version).

## Block number

Check from `Overview` - `Blockchain status`.

**Comment by sjw1au** [comment]
I am having the same issue since upgrading to wallet version 0.29.0-rc2

Running on Windows 10 Enterprise, build 1909

![150320 CKB error](https://user-images.githubusercontent.com/52616879/76713025-e50cad00-6771-11ea-868c-859ccc72871b.jpg)

**Comment by sjw1au** [comment]
Just changed to Mainnet    Sync is slow

**Comment by ashchan** [comment]
When the sync seems hang please restart Neuron.

The bundled CKB has some issue keeping up syncing (at around block height 500k). We're fixing that issue.

**Comment by sjw1au** [comment]
Ok shall try that a few time

**Comment by sjw1au** [comment]
Just very very slow. next to mainnet the spinning green dial has two red blocks

**Comment by ashchan** [comment]
> Just very very slow. next to mainnet the spinning green dial has two red blocks

I still think it's the bundle CKB node that syncs too slow. Is the block number still under 500k?

**Comment by sjw1au** [comment]
all synced now just very very slow

**Comment by sjw1au** [comment]
Still syncing very slow.  Can take up to 4 hours for a transfer from and exchange to the wallet.

**Comment by Keith-CY** [comment]
Hi @sjw1au, does the synchronization work properly now?
