### ISSUE TITLE
Missing dao

### ISSUE THREAD

**Issue by bwollrich** [nervosnetwork/neuron#1458]
My dao deposit is now showing 0. Where is my deposit and why is it now missing?

**Comment by Keith-CY** [comment]
It's probably a synchronization problem and there're two ways to check your assets.

1. Clear the app cache which locates in the setting panel to start the synchronization from scratch.
2. Find the next available change address and visit the explorer https://explorer.nervos.org/address/ckb1qyqdmeuqrsrnm7e5vnrmruzmsp4m9wacf6vsxasryq by replacing the address in the URL.
