### ISSUE TITLE
deposit not in my CKB wallet balance

### ISSUE THREAD

**Issue by LiliumIG** [nervosnetwork/neuron#1462]
I transferred CKB from my exchange account and it has not appeared in my neuron wallet.

transaction ID is: ca4638f07bf54b69625aad2f2124b7c4f8139569873aaaf3d9ffc3c091a011df

receiving wallet is:  ckb1qyqt58hnlumdj28rv4fwxqemvke0yxmtaxgsrvcx4p

Amount of CKB: 202087.91206124

please confirm and advise

regards
Robert

**Comment by Keith-CY** [comment]
The app doesn't synchronize properly for some bugs we're trying to figure out.

For now, tt's better to check the status of specific addresses and transactions in the CKB Explorer(https://explorer.nervos.org/address/ckb1qyqt58hnlumdj28rv4fwxqemvke0yxmtaxgsrvcx4p)

And the workaround to get the correct balance in the app is to restart the synchronization by clicking the **Clear Cache** locates at the Settings.

**Comment by shansen79** [comment]
I am also having the same problem. I have confirmed the transaction in CKB Explorer and cleared cache many many times. I did start off with a small about because of the issues I had read about but I am wanting to stake in the DAO. How am I suppose to do that if the balance will not update?

Thanks,
Shane

**Comment by peterrabbit12** [comment]
I'm experiencing the same issue.  I can see the transaction on the block explorer but nothing in the wallet.  I've found this problem in multiple forums and threads online.  I've installed version 0.29.0 on my windows PC and the mainnet never syncs even if the synced blocks reach the tip amount.  I've uninstalled and reinstalled.  I tried previous wallet versions and none work.  How can you have a blockchain without a wallet?  I regret investing resources into mining.

**Comment by shansen79** [comment]
peterrabbit12,

I hear ya I was getting ready to drop 3k on the new Toddminer but now I'm having second thoughts

**Comment by Keith-CY** [comment]
Hi, @shansen79 @peterrabbit12 

The current version of Neuron bundled CKB@v0.30.1 which usually sticks at 400k blocks. Please check the status of synchronization, if it never ends with synchronization completed, please run the [CKB@v0.31.0-pre2](https://github.com/nervosnetwork/ckb/releases/tag/v0.31.0-pre2) which solves the 400k problem.

Ref: https://github.com/nervosnetwork/neuron/issues/1497
CKB@v0.31.0-pre2: https://github.com/nervosnetwork/ckb/releases/tag/v0.31.0-pre2

**Comment by peterrabbit12** [comment]
I don't understand why the latest wallet isn't posted here -  https://github.com/nervosnetwork/neuron/releases?  But I will try your suggestion.

**Comment by BitEzz** [comment]
i have same problem i sent deposit before it make before Synchronizing i will restive it after Synchronizing or it will lost because it first time for me in neuron wallet  ... it also make Synchronizing from 2 day and still in block 800,815 but it work very slow there is anther way to make it faster anther server

**Comment by Keith-CY** [comment]
> i have same problem i sent deposit before it make before Synchronizing i will restive it after Synchronizing or it will lost because it first time for me in neuron wallet ... it also make Synchronizing from 2 day and still in block 800,815 but it work very slow there is anther way to make it faster anther server

Hi @BitEzz , [the last release](https://github.com/nervosnetwork/neuron/releases/tag/v0.30.0) bundled the CKB Node which has fixed the synchronization. Please have a try.

**Comment by jir-miner** [comment]
I have same problem. I had quite a lot of ckb's in my Nervos DAO but then I was sending large amount 130 000 ckb to my DAO + my daily mining amount of about 1600 but they never came to my DAO!

- I already cleared cache. But the update never ends, balance is showing 0 . 

- I updated it to the 0.30.0 same thing

- I updated it to the 0.30.0-rc2 ... and same thing :(
