### ISSUE TITLE
Wallet Problem

### ISSUE THREAD

**Issue by Kintibace** [nervosnetwork/neuron#1497]
Hello,
I have registered a Wallet for about couple of days. I have sent three times 5000 ckb. The balance  is still zero. I have waited the platform to sychronise but it synce to Block 248 611 and stops, I have cleared the cache couple of times is all the same. I tried re installing, always the same. Can not complete synchronizing procces. Does anyone have a clue how to solve the problem.
Regards

**Comment by ashchan** [comment]
My guess is the bundled CKB has some issue syncing blocks. Is it possible that you download CKB v0.31.0-pre2 from https://github.com/nervosnetwork/ckb/releases/tag/v0.31.0-pre2 and run a separate node, then connect Neuron to it? (Just run 0.31.0 then start Neuron).

**Comment by Keith-CY** [comment]
There's a menu item named <kbd>Export Debug Information</kbd> in the `Help` menu which is used to export logs and basic sync info. It will be great if you can upload it.

**Comment by Kintibace** [comment]
Hello, I downloaded the ckb_v0.31.0-pre2_x86_64-pc-windows-msvc and ran  a separate Node as you advised me and everything worked out just fine. Thank you very much!

**Comment by Keith-CY** [comment]
> Hello, I downloaded the ckb_v0.31.0-pre2_x86_64-pc-windows-msvc and ran a separate Node as you advised me and everything worked out just fine. Thank you very much!

Glad to hear that.
