### ISSUE TITLE
I sent deposit before it make before Synchronizing i will restive it after Synchronizing or it will lost because it first time for me in neuron wallet ...

### ISSUE THREAD

**Issue by BitEzz** [nervosnetwork/neuron#1524]
**Describe the bug**
Please enter details.

**Environment (please complete the following information):**
 - OS & Version: [ Windows 10 ]
 - Neuron Version [e.g. 0.29.0]
 - Block Number: [1,447,556 `Overview` - `Blockchain Status` for v0.29.0-rc2 or 812,812 
![2](https://user-images.githubusercontent.com/63662792/79256305-71ed7800-7e90-11ea-8624-4314ef268b68.jpg)
or hover onto the left bottom syncing status area for v0.29.0 and later]

 i sent deposit before it make before Synchronizing i will restive it after Synchronizing or it will lost because it first time for me in neuron wallet ... it also make Synchronizing from 2 day and still in block 800,815 but it work very slow there is anther way to make it faster anther server

**Screenshots**

**Comment by CipherWang** [comment]
Sorry for the inconvenience. First of all, your deposit won't be lost if you keep your secret key safe. After it has fully synchronized, you will find the deposit shown in Nervos DAO page.

To speed up the sync process, try to connect your computer to your mobile phone's 4G/5G wifi hot spot, and replace your HDD to SDD if it's possible.

**Comment by kellyshang** [comment]
@BitEzz Hi, if there is still any problem, feel free to join the discord support channel ( https://discord.gg/S96Cfwf ), where you will get more prompt and effective support for your issues.

**Comment by BitEzz** [comment]
thanks a lot 5G speed helped .still need long time but at least moving faster ... but why my balance go to DAO ? i can't use it after one month or what because in DAO

**Comment by Keith-CY** [comment]
> thanks a lot 5G speed helped .still need long time but at least moving faster ... but why my balance go to DAO ? i can't use it after one month or what because in DAO

Your balance is updated into Nervos DAO because you've triggered the deposit action as you mentioned in the issue.

The action is valid even the synchronization is not completed because the cell holding your balance is not consumed yet.

**Comment by BitEzz** [comment]
thanks for help all .. last quieten i do mining for CKB do i need to leave my wallet open to receive mining reward ? thanks

**Comment by Keith-CY** [comment]
> thanks for help all .. last quieten i do mining for CKB do i need to leave my wallet open to receive mining reward ? thanks

The wallet is nothing to do with mining if you are mining with an independent CKB node(which means you are not mining with the CKB node bundled in the wallet).

The rewards are recorded on the CKB chain and when you launch the wallet next time they will be synchronized from the CKB chain.
