### ISSUE TITLE
CANT SYNC...

### ISSUE THREAD

**Issue by stoweo112** [nervosnetwork/neuron#1589]
I VE TRIED TO SYNC FOR A WEEK, NOTHING...I USE WINDOWS 10 FAMILLY AND A GAMING PC WITH NVIDIA GTX 1060 6GB AND INTELCORE I7 7TH GENERATION, FINALLY HAD TO IMPORT SEED IN IMTOKEN ANDROID WALLET AND THERE BALANCE SHOWED ASAP.

LAST BUG WITH THE NEW VERSION IMPOSSIBLE TO INSTALL NEURON WALLET IN MY DESKOP IT FAILS EVERYTIME...CAN U PLEASE TELL ME IF I MIGHT DO WRONG SOMETHING OR IT IS A WELLKNOWN ISSUE AND YOU RE WORKING ON IT?

MUCH RESPECT

**Comment by Keith-CY** [comment]
Repeated against https://github.com/nervosnetwork/neuron/issues/1590
