### ISSUE TITLE
CANT INSTALL NEURON IN MY WINDOWS 10 FAMILLY

### ISSUE THREAD

**Issue by stoweo112** [nervosnetwork/neuron#1590]
SINCE NEW VERSION COMES OUT IT IS TOTALLY IMPOSSIBLE FOR ME TO INSTALL NEURON IN MY GAMING PC GRAFIC CARD NVIDIA GTX 1060 6GB, INTELCORE I7 7TH GEN....FROM 2018....

EVERYTIME I TRY TO OPEN IT I GET AN ERROR SHOWING "OXXXCC" SOMETHING LIKE THIS BUT WALLET CANT OPEN, I DID NOT TRY IF ITS A GENERAL ERROR ALSO WITH THE OTHER VERSION, FINALLY I MUST IMPORT SEED IN IMTOKEN ANDROID WALLET THERE I HAD NO TROUBLE BALANCE SHOWED ASAP...
I'M MINING CKB WITH AN ANTMINER K5 BEFORE WITH TWO FPGAS...FROM MONAD TECHNOLOGY

**Comment by Keith-CY** [comment]
Could you provide more details about the error `0XXCC` on opening the Neuron, something like screenshots? Thanks.

**Comment by stoweo112** [comment]
I have bigger trouble than before, I can't even install Neuron anymore, while I install it I get an Error, I don't know where this mistakes comes from but actually I m using only IM Token to deposit my Ckb, but there isn't DAO feature, I'd like to stake some Ckb, do you know another wallet where,DAO feature is implemented?Thank you so much for your nice help

**Comment by Keith-CY** [comment]
> I have bigger trouble than before, I can't even install Neuron anymore, while I install it I get an Error, I don't know where this mistakes comes from but actually I m using only IM Token to deposit my Ckb, but there isn't DAO feature, I'd like to stake some Ckb, do you know another wallet where,DAO feature is implemented?Thank you so much for your nice help

For now, there are no other wallets except Neuron supporting Nervos DAO.

And for better support, could you post some detailed error messages?

BTW, a downside is known that Neuron doesn't work on 32-bit processor. I'm not sure if you encountered this situation due to a lack of information.

**Comment by stoweo112** [comment]
I will make another installation test and tell you which error code I m getting sorry about it
