### ISSUE TITLE
Code -3 OUTPUT UNKNOWN

### ISSUE THREAD

**Issue by ZuluCryptoTrader** [nervosnetwork/neuron#1615]
**Describe the bug**
{code:-3,message:OutPoint: Unknown([OutPoint(0x9c10d167798bf5ab2194c5f973470c9ab5caba39055656170707f090353ae41801000000)])"}

**Environment (please complete the following information):**
 - OS & Version: [e.g. Windows 10, 
 - Neuron Version [e.g. 0.30.0]
 - Block Number: [Check that from `Overview` - `Blockchain Status` for v0.29.0-rc2 or before, or hover onto the left bottom syncing status area for v0.29.0 and later]

**Steps To Reproduce**
1. Go to send
2. Click on 'dend
3. Scroll down to send

**Screenshots**

**Comment by Keith-CY** [comment]
> **Describe the bug**
> {code:-3,message:OutPoint: Unknown([OutPoint(0x9c10d167798bf5ab2194c5f973470c9ab5caba39055656170707f090353ae41801000000)])"}
> 
> **Environment (please complete the following information):**
> 
> * OS & Version: [e.g. Windows 10,
> * Neuron Version [e.g. 0.30.0]
> * Block Number: [Check that from `Overview` - `Blockchain Status` for v0.29.0-rc2 or before, or hover onto the left bottom syncing status area for v0.29.0 and later]
> 
> **Steps To Reproduce**
> Steps to reproduce the behavior:
> 
> 1. Go to send
> 2. Click on 'dend
> 3. Scroll down to send
> 4. See error
> 
> **Screenshots**
> If applicable, add screenshots to help explain your problem.

Could you please provide the environment information exported by <kbd>Menu</kbd>=><kbd>Help</kbd>=><kbd>Export Debug Information</kbd>. The `status.json` file could be extracted from the zip file.

**Comment by zhaxzhax** [comment]
same problem.
status.json is {"neuron":{"version":"0.29.0","blockNumber":"1737042"},"ckb":{"url":"http://localhost:8114","version":"0.29.0 (a6733e6 2020-02-26)","blockNumber":"1737461"}}
