### ISSUE TITLE
Depositing into Nervos DAO

### ISSUE THREAD

**Issue by agains23** [nervosnetwork/neuron#1617]
**Describe the bug**
IT seems my deposit isn't initiating or completing. See screenshot. I began the deposit 10 hours ago and still shows "Pending". I have allowed enough CKB for the 'fuel' to make the deposit. 

**Environment (please complete the following information):**
 - OS & Version: Windows7 64-bit
 - Neuron Version 0.30.0-rc2
 - Block Number: 1697297

**Steps To Reproduce**

**Screenshots**
![Capture](https://user-images.githubusercontent.com/64390012/81475198-8be45700-91bf-11ea-9e64-639ffc50d549.JPG)

**Comment by Keith-CY** [comment]
The screenshot indicates that the CKB Node is unavailable, please check the synchronization status at the left bottom corner.
