### ISSUE TITLE
read ECONNRESET 0.29.0

### ISSUE THREAD

**Issue by James-Sangalli** [nervosnetwork/neuron#1620]
If I enter the wrong password on the UI and then try again, I get this error message on the dashboard which prevents any further action. 

this error message shows up on the full node:

`ERROR panic  thread 'GlobalRuntime-6' panicked at 'failed to open /dev/urandom: Os { code: 24, kind: Other, message: "Too many open files" }': src/libcore/result.rs:1084stack backtrace:
   0: backtrace::backtrace::trace
   1: backtrace::capture::Backtrace::new
   2: ckb_logger::setup_panic_logger::{{closure}}
   3: std::panicking::rust_panic_with_hook
   4: std::panicking::continue_panic_fmt
   5: rust_begin_unwind
   6: core::panicking::panic_fmt
   7: core::result::unwrap_failed
   8: std::thread::local::fast::Key<T>::try_initialize
   9: <std::collections::hash::map::HashMap<K,V,S> as core::iter::traits::collect::FromIterator<(K, V)>>::from_iter
  10: <ckb_tx_pool::process::fetch_txs::FetchTxsProcess as futures::future::Future>::poll
  11: futures::future::chain::Chain<A,B,C>::poll
  12: futures::task_impl::std::set
  13: std::panicking::try::do_call
  14: __rust_maybe_catch_panic
  15: tokio_threadpool::task::Task::run
  16: tokio_threadpool::worker::Worker::run_task
  17: tokio_threadpool::worker::Worker::run
  18: std::thread::local::LocalKey<T>::with
  19: std::thread::local::LocalKey<T>::with
  20: std::thread::local::LocalKey<T>::with
  21: tokio::runtime::threadpool::builder::Builder::build::{{closure}}
  22: std::thread::local::LocalKey<T>::with
  23: std::thread::local::LocalKey<T>::with
  24: std::sys_common::backtrace::__rust_begin_short_backtrace
  25: std::panicking::try::do_call
  26: __rust_maybe_catch_panic
  27: core::ops::function::FnOnce::call_once{{vtable.shim}}
  28: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
  29: std::sys::unix::thread::Thread::new::thread_start
  30: _pthread_start
`

**Comment by quake** [comment]
it looks your operating system has exceeded the file descriptor limit, you may try to restart ckb node or increase the ulimit. btw, suggest upgrading the ckb node to latest version: https://github.com/nervosnetwork/ckb/releases/tag/v0.31.1 which resolved slow synchronization issue.
