### ISSUE TITLE
Withdrawing from the DAO unsuccessful 0.29.0

### ISSUE THREAD

**Issue by James-Sangalli** [nervosnetwork/neuron#1621]
One of my nervos deposits was ready for withdrawal, upon entering the correct password the UI gives back the following:

` {code:-32602,message:Invalid params: invalid length 2, expected fewer elements in array."}`

**Comment by kellyshang** [comment]
> One of my nervos deposits was ready for withdrawal, upon entering the correct password the UI gives back the following:
> 
> ` {code:-32602,message:Invalid params: invalid length 2, expected fewer elements in array."}`

If you are connecting to a solo ckb node, please upgrade the ckb node to the [latest version](https://github.com/nervosnetwork/ckb/releases) .
