### ISSUE TITLE
Bug when deposit ckb into NervosDao

### ISSUE THREAD

**Issue by zhaxzhax** [nervosnetwork/neuron#1634]
**Describe the bug**
{code:-3,message:OutPoint: Dead(OutPoint(0x3ec9a1cfae69ed1ad12b387dc235aa9fc96ce03f526df3fda57856faf20c352301000000))"}

**Environment (please complete the following information):**
{"neuron":{"version":"0.29.0","blockNumber":"1737042"},"ckb":{"url":"http://localhost:8114","version":"0.29.0 (a6733e6 2020-02-26)","blockNumber":"1737461"}}

**Steps To Reproduce**

1. click NervosDao
2. Click on 'deposit'
3. Enter password

**Screenshots**
![W9(X7TQ1)D7O~ANM93E}6VJ](https://user-images.githubusercontent.com/44116759/81639526-bf88e080-944e-11ea-9a07-f4d4d8304405.png)

**Comment by Keith-CY** [comment]
`Dead(OutPoint(0x3ec9a1cfae69ed1ad12b387dc235aa9fc96ce03f526df3fda57856faf20c352301000000))` means the cell used in this transaction has been consumed, it happens when the wallet is not fully synced.

In this case, the tip block number is `1737461` while the synced block number is `1737042`. There should be a transaction including the cell during `1737042` and `1737461`.

Please try the deposition when the synchronization status at the left bottom corner is `synced`.

**Comment by zhaxzhax** [comment]
![P2Y DOK E$E)U1VQP(03( 9](https://user-images.githubusercontent.com/44116759/81660194-07b6fb80-946d-11ea-9d7c-70cee30bd1c6.png)
Thank you! But I am definitely sure that the left bottom corner is synced

**Comment by zhaxzhax** [comment]
![P2Y DOK E$E)U1VQP(03( 9](https://user-images.githubusercontent.com/44116759/81660194-07b6fb80-946d-11ea-9d7c-70cee30bd1c6.png)
Thank you! But I am definitely sure that the left bottom corner is synced

**Comment by zhaxzhax** [comment]
I know what happened now. My  available balance in Neuron is different than in Imtoken. So when I deposit ckb in DAO,I get an error(cause actually i don't have so much ckb.).
That's must be a big bug on Neuron.
Hope you guys can find a way to fix it.

**Comment by Keith-CY** [comment]
> I know what happened now. My available balance in Neuron is different than in Imtoken. So when I deposit ckb in DAO,I get an error(cause actually i don't have so much ckb.).
> That's must be a big bug on Neuron.
> Hope you guys can find a way to fix it.

Thanks for locating the problem and sorry for that. We are working on the synchronization and will fix it ASAP.

**Comment by CipherWang** [comment]
@zhaxzhax will you please try out the latest Neuron? https://github.com/nervosnetwork/neuron/releases/tag/v0.30.0-rc2

**Comment by zhaxzhax** [comment]
@CipherWang  According to your suggestion. I have tried out the latest Neuron today. But the bug still exist. It shows that I have 600 thousand ckb, but actually I only have 10 thousand available ckb.

**Comment by kellyshang** [comment]
> @CipherWang According to your suggestion. I have tried out the latest Neuron today. But the bug still exist. It shows that I have 600 thousand ckb, but actually I only have 10 thousand available ckb.

When your Neuron has completely synced, then would you please check the `Address Book` and compare each address that have balance with the [explorer](https://explorer.nervos.org/) to see if both balance are the same?

**Comment by zhaxzhax** [comment]
![image](https://user-images.githubusercontent.com/44116759/82003402-dd468780-9692-11ea-99b0-b7d1914df657.png)
Completely synced.
![pic2](https://user-images.githubusercontent.com/44116759/82003599-59d96600-9693-11ea-9cbb-7a32a7a411ee.png)
![OAZ68B1A4RJI`QUS96~}L%H](https://user-images.githubusercontent.com/44116759/82003609-6493fb00-9693-11ea-8fc3-17371c3e9c2e.png)
Actually not same.

**Comment by zengbing15** [comment]
Could you please try to clear cache? ( please use the latest version of Neuron, just a reminder)
![image](https://user-images.githubusercontent.com/40650475/82006519-9492cc80-969a-11ea-9fa1-e4db9c12d805.png)
@zhaxzhax

**Comment by zhaxzhax** [comment]
@zengbing15  it works. Thank you for your help.
