### ISSUE TITLE
CKB should not run in the background when it is not needed.

### ISSUE THREAD

**Issue by jordanmack** [nervosnetwork/neuron#1660]
**Describe the bug**
The bundled CKB node should not run in the background when it is not being used, or an option to disable it should be added.

**Environment (please complete the following information):**
 - OS & Version: Windows 10
 - Neuron Version 0.29.0
 - Block Number: 1817914

**Steps To Reproduce**
1. Add a second network source in the network settings.
2. Start task explorer and confirm that ckb.exe is still running.

**Screenshots**
![20200519143803](https://user-images.githubusercontent.com/37931/82381337-e0b57800-99de-11ea-8220-d83fd241b70c.png)

**Comment by Keith-CY** [comment]
Thanks, we're going to find a better strategy for the bundled CKB node.
