### ISSUE TITLE
Sync failed, please check network

### ISSUE THREAD

**Issue by flatratetech** [nervosnetwork/neuron#1668]
[neuron_debug_1590063865800.zip](https://github.com/nervosnetwork/neuron/files/4662456/neuron_debug_1590063865800.zip)
**Describe the bug**
Please enter details.

Red dot in bottom corner say sync failed, please check network, after I was fully synced and connected for the last month, this randomly happened yesterday and I can not figure it out.

 - OS & Version:  Windows 10,
-  Neuron version 0.30.0
 - Block Number: Cannot sync, I was fully functional and synced every day for the last month or so up to block 1,800,000 as far as I remember

Ive downloaded, Visual C++ tried uninstalling Neuron, reinstalling it, and my internet connection seems fine.

Help would be appreciated

**Comment by Keith-CY** [comment]
Hi @flatratetech 
This case is probably the one mentioned in https://github.com/nervosnetwork/neuron/issues/1652 and could be fixed by deleting `%APPDATA%\Neuron\chains\mainnet\data\network\peer_store`.

You can open the `%APPDATA%` by 
> The quick and easy way is to click Start, or the Cortana search icon in Windows 10, type %appdata%, and select the top search result, which should take you to AppData > Roaming.

**Comment by flatratetech** [comment]
Thank you that fixed it🙏
