### ISSUE TITLE
the "實現性功能" in traditional Chinese version should correct into "實驗性功能"

### ISSUE THREAD

**Issue by Rbchi** [nervosnetwork/neuron#1701]
**Describe the bug**
Please enter details.

**Environment (please complete the following information):**
 - OS & Version: [e.g. Windows 10, macOS 10.15.2, Linux Ubuntu 18.04]
 - Neuron Version [e.g. 0.28.0]
 - Block Number: [Check that from `Overview` - `Blockchain Status` for v0.29.0-rc2 or before, or hover onto the left bottom syncing status area for v0.29.0 and later]

**Steps To Reproduce**

**Screenshots**

**Comment by Keith-CY** [comment]
https://github.com/nervosnetwork/neuron/pull/1702

**Comment by Keith-CY** [comment]
Release in https://github.com/nervosnetwork/neuron/releases/tag/v0.31.0
