### ISSUE TITLE
"Sync Failed"

### ISSUE THREAD

**Issue by Cryptogarden** [nervosnetwork/neuron#1776]
Wallet will not sync. Network settings show Mainnet - http://localhost:8114, but will not connect.

Environment:
 - Windows 10
 - Neuron Version 0.32.0-beta.1

The error received is "sync failed, please check network"

**Comment by katat** [comment]
Hi @Cryptogarden, thanks for reporting this issue.
For us to have more information to debug this issue, could you please export the logs via the app menu and upload the file here?

Once we got the logs, I will try to figure out the cause as soon as possible.

**Comment by Cryptogarden** [comment]
Here are the logs. Thanks for your help
[neuron_debug_1594653307668.zip](https://github.com/nervosnetwork/neuron/files/4913426/neuron_debug_1594653307668.zip)

**Comment by Keith-CY** [comment]
It seems that some important info is truncated.

Could you please provide the log file at `C:\Users\{**User Name**}\AppData\Roaming\Neuron\chains\mainnet\data\logs\run.log` that is not truncated?

**Comment by BeniCaj** [comment]
Hi I have the same problem:
Mainnet - http://localhost:8114, but will not connect.

Environment:
Windows 10
Neuron Version 0.32.0-beta.1
The error received is "sync failed, please check network"
[run.log](https://github.com/nervosnetwork/neuron/files/5079944/run.log)

Attached the 'Run.log'
[
Thanks for your help

**Comment by Keith-CY** [comment]
> Hi I have the same problem:
> Mainnet - http://localhost:8114, but will not connect.
> 
> Environment:
> Windows 10
> Neuron Version 0.32.0-beta.1
> The error received is "sync failed, please check network"
> [run.log](https://github.com/nervosnetwork/neuron/files/5079944/run.log)
> 
> Attached the 'Run.log'
> [
> Thanks for your help

The data seem to be malformed according to the log, could you try to delete the `\Users\beni_\AppData\Roaming\Neuron\chains\mainnet\data` directory, then relaunch the Neuron and clear cache in the setting panel to see if the sync works?

The `\Users\beni_\AppData\Roaming` can be navigated by searching `%AppData%` in start menu.

**Comment by BeniCaj** [comment]
Hi
Thanks guys. This was the tip. Deleting the folder 'AppData\Roaming\Neuron\chains\mainnet\data' brought the solution. Now it is synchronizing without problem.

Thanks again for the quick respond.
