### ISSUE TITLE
Feature request: Offline signing through Neuron

### ISSUE THREAD

**Issue by PJok** [nervosnetwork/neuron#1798]
Can [this](https://talk.nervos.org/t/securely-transacting-nervos/1339) be added to neuron?

Basically like the  offline signing mechanism used in Electrum [https://electrum.readthedocs.io/en/latest/coldstorage.html?highlight=usb](url).

Thank you, it would help tremendously with security.

**Comment by katat** [comment]
Hi @PJok 

Thanks for requesting the feature. 
We will take a look and try to prioritize it in the upcoming milestones.

Regards

**Comment by yuche** [comment]
https://github.com/nervosnetwork/neuron/pull/1885 @PJok
