### ISSUE TITLE
Private Key Generation in Nervosnetwork

### ISSUE THREAD

**Issue by AnasSaeed123** [nervosnetwork/neuron#1856]
Which curve is used in generation of private key of nervos network from seed?

tx-wallet.test.ts

`describe('get keys with paths', () => {
  const walletService = WalletService.getInstance()
  const mnemonic = 'tank planet champion pottery together intact quick police asset flower sudden question'
  const password = '1234abc~'
  const receivingPath = `m/44'/309'/0'/0/0`
  const changePath = `m/44'/309'/0'/1/0`
  const receivingPrivateKey = '0x848422863825f69e66dc7f48a3302459ec845395370c23578817456ad6b04b14'
  // const receivingPublicKey = '0x034dc074f2663d73aedd36f5fc2d1a1e4ec846a4dffa62d8d8bae8a4d6fffdf2b0'
  const changePrivateKey = '0x15ec3e9ba7024557a116f37f08a99ee7769882c2cb4cfabeced1662394279747'
  // const changePublicKey = '03f3600eb8f2bd7675fd7763dbe3fc36a1103e45b46629860a88a374bcf015df03'`

**Comment by Keith-CY** [comment]
You might mean the generation of the public key, it's ECDSA-secp256k1
