### ISSUE TITLE
Deposit Dont Show up in Wallet

### ISSUE THREAD

**Issue by farmerxt** [nervosnetwork/neuron#1881]
ckb coin

ckb1qyqpct6wrhh5lkfcn8xuvpylvxrrt7r6c9mssfjef9
821b74060101d05a0310173e698da65c71b7f16927e690b80ea2279625ffbd36

this is the withdrawl to my ckb account in neuron wallet i see it well recieved

and the latest

ckb1qyqw7rgt8vh96xhfz906j8dcyjxrv32dughqt0en3u
1459d8ecbbe6e4eb5b0dbec4555321f6f2dbb397389bcf4728514abc726ac341

this withdrawl of 10.000ckb i see in ckb explorer executed by huobi but not show in my wallet 
how can this happen , the address was created by the program

http://prntscr.com/uqsz7t

**Comment by katat** [comment]
Hi @farmerxt 

Could you please let us know the Neuron version you are currently using? 

Please try to clear the cache in the general setting and see if it resolves.

**Comment by elitedev1314520** [comment]
I would like to help with issues.
Is there anyone I can chat with?

**Comment by farmerxt** [comment]
0.32.2

installing the update - cleared cache ! thanks for info ... will follow up

**Comment by farmerxt** [comment]
updating solved the issue !!!!! big up
