### ISSUE TITLE
add informational text that funds will be locked in DAO until (potential withdraw date)

### ISSUE THREAD

**Issue by matt-quinn** [nervosnetwork/neuron#1896]
A user brought up that they were not aware that a DAO deposit would be locked until 30 days following deposit, request to add an informational message on DAO deposit screen that funds will be locked in the DAO until approximately (date + 30 days)
![deposit nervos dao](https://user-images.githubusercontent.com/22106875/96775980-553d7a00-13b6-11eb-839f-b97ad1e50f37.PNG)

**Comment by Keith-CY** [comment]
Thanks, I'll propose it in the dev meeting.
