### ISSUE TITLE
Unable to deposit into DAO.  I receive and error code after entering my password

### ISSUE THREAD

**Issue by TacoMonkey** [nervosnetwork/neuron#1930]
**Describe the bug**
After entering my PW I receive the response a "Transaction Failed to Resolve" message

**Environment (please complete the following information):**
 - Windows 10
 - Neuron Version 33.1
 - Block Number: 3,325,684

**Steps To Reproduce**
Go to Nervos Dao
   Enter amount to deposit
   enter password
  receive error code

**Screenshots**
![image](https://user-images.githubusercontent.com/75039924/100268677-3167d980-2f0a-11eb-8e3d-74c01e8e1311.png)

**Comment by TacoMonkey** [comment]
I discovered there was an error with the sync.  I cleared my cache , did a re-sync then it worked.

**Comment by katat** [comment]
Thanks for reporting the issue. Would you please let us know the error you got during the sync? This twoukd be helpful for us to prevent the issues in the future releases.

**Comment by TacoMonkey** [comment]
It was error code 301. Then a number of other characters.  I’d send you the
photo but I don’t have it on my phone.
  I had installed the latest version and apparently the sync went bad which
then wouldn’t allow me to deposit into the DAO.
  I cleared the cache.  Did a resync and all was well.
