### ISSUE TITLE
Neuron wallet will not begin synch

### ISSUE THREAD

**Issue by sperry1063** [nervosnetwork/neuron#1939]
Wallet not synching.  Downloaded updates.  Cleared cache................wallet just won't start synching and it's been trying for 4 hours.

**Comment by katat** [comment]
HI @sperry1063 
Please export the debug log under the help menu, then we will take a look.

Also please try keeping your Neuron up for a while in case it is doing node migration. This issue might be relevant https://github.com/nervosnetwork/neuron/issues/1898#issuecomment-732857530

**Comment by sperry1063** [comment]
What specifically from that do you want me to share?  There's a few things there once dl'ed and extracted.

**Comment by katat** [comment]
The while zip file would be helpful.

**Comment by sperry1063** [comment]
[neuron_debug_1607292786286.zip](https://github.com/nervosnetwork/neuron/files/5649659/neuron_debug_1607292786286.zip)

**Comment by katat** [comment]
Thanks for sharing the logs. Based on the logs, it seems the node data on your machine is corrupted. Please follow the instruction below to reset the data for the bundled node:

1. Backup your wallets
2. Close Neuron
3. Delete the folder `C:\Users\[your user name]\AppData\Roaming\Neuron\chains\mainnet\`
4. Start Neuron

Then it should restart the sync for the node, which would take a while but it should resolve the issue you are experiencing.

**Comment by sperry1063** [comment]
> Thanks for sharing the logs. Based on the logs, it seems the node data on your machine is corrupted. Please follow the instruction below to reset the data for the bundled node:
> 
> 1. Backup your wallets
> 2. Close Neuron
> 3. Delete the folder `C:\Users\[your user name]\AppData\Roaming\Neuron\chains\mainnet\`
> 4. Start Neuron
> 
> Then it should restart the sync for the node, which would take a while but it should resolve the issue you are experiencing.

Thank you so much.  Started right away.  Hope I don't jinx it by thanking you too early.........but thank you so much.
