### ISSUE TITLE
更新0.35.0之后，同步出现问题

### ISSUE THREAD

**Issue by fuluwwa** [nervosnetwork/neuron#1998]
**Describe the bug**
已同步区块0%， 0/0

**Environment (please complete the following information):**
 - OS & Version: [e.g. Windows 10]
 - Neuron Version [e.g. 0.35.0]
 - Block Number: 
 - 
**Steps To Reproduce**

**Screenshots**
[neuron_debug_1612415017796.zip](https://github.com/nervosnetwork/neuron/files/5923375/neuron_debug_1612415017796.zip)

**Comment by katat** [comment]
根据日志来看，很可能是本地节点数据损坏。建议通过以下步骤重新同步节点数据：
1. 关掉 Neuron
2. 删掉数据目录 C:\Users\*YourUserName*\AppData\Roaming\Neuron\chains
3. 启动 Neuron

**Comment by fuluwwa** [comment]
> 根据日志来看，很可能是本地节点数据损坏。建议通过以下步骤重新同步节点数据：
> 
> 1. 关掉 Neuron
> 2. 删掉数据目录 C:\Users*YourUserName*\AppData\Roaming\Neuron\chains
> 3. 启动 Neuron

OK，解决了。
