### ISSUE TITLE
dean

### ISSUE THREAD

**Issue by 144breakout** [nervosnetwork/neuron#1999]
**Describe the bug**
Please enter details.installed update to ckb wallet now it will not connect to mainnet version 0.35 windows 10

**Environment (please complete the following information):**
 - OS & Version: [e.g. Windows 10, macOS 10.15.2, Linux Ubuntu 18.04]
 - Neuron Version [e.g. 0.28.0]
 - Block Number: [Check that from `Overview` - `Blockchain Status` for v0.29.0-rc2 or before, or hover onto the left bottom syncing status area for v0.29.0 and later]

**Steps To Reproduce**

**Screenshots**

**Comment by Keith-CY** [comment]
If you've installed previous versions and it broke down after an update, please remove `C:\Users\*YourUserName*\AppData\Roaming\Neuron\chains` and relaunch the Neuron

If your wallet is a fresh one, please make sure `vc_redist.x64.exe` is installed, which can be downloaded from https://support.microsoft.com/en-us/topic/the-latest-supported-visual-c-downloads-2647da03-1eea-4433-9aff-95f26a218cc0

**Comment by 144breakout** [comment]
have done this removed chains and relaunch neuron wallet still not connecting to the mainnet

**Comment by kellyshang** [comment]
> have done this removed chains and relaunch neuron wallet still not connecting to the mainnet 

Have you installed the `vc_redist.x64.exe` from https://support.microsoft.com/en-us/topic/the-latest-supported-visual-c-downloads-2647da03-1eea-4433-9aff-95f26a218cc0 ？

**Comment by 144breakout** [comment]
okay just done that seems to have worked.but have no balance or transactions mainnet says (blocks sync 100%)

**Comment by 144breakout** [comment]
my mistake letting wallet run working fine.thanks for all the help.

**Comment by kellyshang** [comment]
> my mistake letting wallet run working fine.thanks for all the help. 
>>From: kellyshang Sent: Tuesday, February 23, 2021 12:49 PM To: nervosnetwork/neuron Cc: 144breakout ; Author Subject: Re: [nervosnetwork/neuron] dean (#1999) have done this removed chains and relaunch neuron wallet still not connecting to the mainnet Have you installed the vc_redist.x64.exe from https://support.microsoft.com/en-us/topic/the-latest-supported-visual-c-downloads-2647da03-1eea-4433-9aff-95f26a218cc0 ？ — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

Cool.
