### ISSUE TITLE
feature request: add option to point at a different location for "blocks" folder

### ISSUE THREAD

**Issue by matt-quinn** [nervosnetwork/neuron#2005]
Most full nodes allow a user to place the "blocks" folder in an alternative location, I could not find this option in Neuron or CKB node configuration. If a user has a small disk drive it would be convenient to store the blocks on an external drive.

Logging this for Neuron because a user requested the functionality in Neuron, if better in CKB please let me know and I will duplicate/move this.

**Comment by Keith-CY** [comment]
Thanks, I'll propose it in the dev meeting.

**Comment by CipherWang** [comment]
We don't have enough bandwidth to do this unitl Q2. We could postpone this.

**Comment by Keith-CY** [comment]
Shipped with https://github.com/nervosnetwork/neuron/releases/tag/v0.103.2
