### ISSUE TITLE
Insufficient balance withdraw on DAO  

### ISSUE THREAD

**Issue by dml007** [nervosnetwork/neuron#2007]
I can't withdraw my ckb  in my Neuron wallet which is locked in the DAO it says there's Insufficient balance
![ckb error](https://user-images.githubusercontent.com/61104552/112055347-19f1d380-8b2d-11eb-9019-2362f81c8e7f.JPG)

**Comment by Keith-CY** [comment]
Since `withdraw` is an action of sending a transaction, it requires you to have at least 61CKB to pay the transaction fee.

And it's better to keep 62CKB before withdraw because it's `at least 61CKB`.

**Comment by dml007** [comment]
Ok thank you so much i figured that might be the problem from a video i saw from VoskCoin i wish i would have known before i locked it up but, you live and you learn thanks again.

**Comment by aaronV81** [comment]
still cant seem to withdraw. i had 61ckb. now I have topped it up to 500+ckb and I still cannot seem to get my CKB out of the DAO...

How do i withdraw/UNLOCK it from the DAO

**Comment by frizzzdog** [comment]
Took your suggestion and took out 1000 ckb but I still get insufficient balance message to pop up and not complete withdrawal. Also I am on version 0.103.0 if that can help you troubleshoot issue. I did get another 6k of coin during compensation cycle which ends tomorrow hence my worries about getting it withdrawn within this cycle

**Comment by frizzzdog** [comment]
see attached debug report
[neuron_debug_1658351785502.zip](https://github.com/nervosnetwork/neuron/files/9154589/neuron_debug_1658351785502.zip)

**Comment by Keith-CY** [comment]
> Took your suggestion and took out 1000 ckb but I still get insufficient balance message to pop up and not complete withdrawal. Also I am on version 0.103.0 if that can help you troubleshoot issue. I did get another 6k of coin during compensation cycle which ends tomorrow hence my worries about getting it withdrawn within this cycle

Hi @frizzzdog 

The error in the logs is quite simple
```
[2022-07-20 17:14:48.985] [warn] API Controller:	channel handling error: Error: Insufficient balance. Error: Insufficient balance.
    at Function.CellsService.gatherInputs (C:\Users\xxx\AppData\Local\Programs\Neuron\resources\app.asar\dist\services\cells.js:766:15)
    at async Function.TransactionGenerator.startWithdrawFromDao (C:\Users\xxx\AppData\Local\Programs\Neuron\resources\app.asar\dist\services\tx\transaction-generator.js:999:63)
```

Is there at least 62 CKB outside Nervos DAO available? `withdraw from nervos dao` requires less than 1 CKB but holding a change cell requires 61 CKB, so theoretically `61.xxxx` CKB in balance is necessary for this action.

If you have 62 CKB or more outside Nervos DAO, please clear cache without `rebuild index` in the setting panel, it will refresh local cache and try to construct the transaction again.

**Comment by frizzzdog** [comment]
I clicked on clear cache, then attempted another withdrawal (keeping 1000 ckb token for balance but still get get insufficient funds message) so not sure when that clearing of cache will be completed. Block synced states 100%
Any suggestions as to how to complete this process is greatly appreciated!
Marc
    On Wednesday, July 20, 2022 at 09:58:10 PM CST, Chen Yu ***@***.***> wrote:  
 
 



Took your suggestion and took out 1000 ckb but I still get insufficient balance message to pop up and not complete withdrawal. Also I am on version 0.103.0 if that can help you troubleshoot issue. I did get another 6k of coin during compensation cycle which ends tomorrow hence my worries about getting it withdrawn within this cycle


Hi @frizzzdog

The error in the logs is quite simple
[2022-07-20 17:14:48.985] [warn] API Controller:	channel handling error: Error: Insufficient balance. Error: Insufficient balance.
    at Function.CellsService.gatherInputs (C:\Users\xxx\AppData\Local\Programs\Neuron\resources\app.asar\dist\services\cells.js:766:15)
    at async Function.TransactionGenerator.startWithdrawFromDao (C:\Users\xxx\AppData\Local\Programs\Neuron\resources\app.asar\dist\services\tx\transaction-generator.js:999:63)

Is there at least 62 CKB outside Nervos DAO available? withdraw from nervos dao requires less than 1 CKB but holding a change cell requires 61 CKB, so theoretically 61.xxxx CKB in balance is necessary for this action.

If you have 62 CKB or more outside Nervos DAO, please clear cache without rebuild index in the setting panel, it will refresh local cache and try to construct the transaction again.

**Comment by frizzzdog** [comment]
See attached screenshot for details - still cannot withdraw as I get insufficient funds
![Neuron_screenshot_07212022](https://user-images.githubusercontent.com/5787446/180204872-4a6a794c-709a-469a-952c-07bf627c38df.JPG)

**Comment by Keith-CY** [comment]
Hi @frizzzdog 

The screenshot says your balance is 0, all your CKB are deposited into nervos DAO, the withdrawal transaction cannot be constructed because an extra transaction fee should be provided.

![image](https://user-images.githubusercontent.com/7271329/180207268-961c38ab-f7d3-4aae-8741-e860088ea04f.png)

62 available CKB(balance) is required to make a withdrawal, you may have to transfer from otherwhere to neuron 62 CKB to pay the fee(with `61.xxx` change).

BTW, I didn't get `attempted another withdrawal (keeping 1000 ckb token for balance but still get insufficient funds message)`, a withdrawal will return all deposited CKB so they cannot be split into `1000ckb` and `the rest`
