### ISSUE TITLE
password requirement for withdrawals

### ISSUE THREAD

**Issue by bwleung604** [nervosnetwork/neuron#2008]
**Describe the bug**

ability to sign in/out from the wallet with username/pw. thanks

**Environment (please complete the following information):**
 - OS & Version: [e.g. Windows 10, macOS 10.15.2, Linux Ubuntu 18.04]
 - Neuron Version [e.g. 0.28.0]
 - Block Number: [Check that from `Overview` - `Blockchain Status` for v0.29.0-rc2 or before, or hover onto the left bottom syncing status area for v0.29.0 and later]

**Steps To Reproduce**

**Screenshots**

**Comment by Keith-CY** [comment]
Thanks for the feedback.

It's a good point in user experience though, we don't have enough bandwidth for more features at this time.
