### ISSUE TITLE
ASSET IS NOT REFLECTING. I sent some assets to my newly downloaded neuron wallet for about 4 hours ago, its not reflecting on the wallet overview. the have checked the CKB Explorer and have confirmed the transaction address and wallet ID. What should i do now so not to lose my coins. thanks

### ISSUE THREAD

**Issue by Larryroch** [nervosnetwork/neuron#2010]
**Describe the bug**
Please enter details.

**Environment (please complete the following information):**
 - OS & Version: [e.g. Windows 10, macOS 10.15.2, Linux Ubuntu 18.04]
 - Neuron Version [e.g. 0.28.0]
 - Block Number: [Check that from `Overview` - `Blockchain Status` for v0.29.0-rc2 or before, or hover onto the left bottom syncing status area for v0.29.0 and later]

**Steps To Reproduce**

**Screenshots**

**Comment by matt-quinn** [comment]
does "synced" show in the bottom left corner of Neuron?
