### ISSUE TITLE
can't send transaction

### ISSUE THREAD

**Issue by TerenceClark** [nervosnetwork/neuron#2013]
**Describe the bug**
can't send transaction

**Environment (please complete the following information):**
 - Linux Ubuntu 18.04
 - Neuron Version 0.35.0

**Screenshots**
![image](https://user-images.githubusercontent.com/8196612/113396496-35cb6400-93ce-11eb-834a-3757e54625e0.png)

**Comment by kellyshang** [comment]
Hi @TerenceClark , firstly please make sure the wallet has synced fully (which can be checked from the status on the wallet left bottom corner). If the status is "Synced", then try to send the transaction and see if it works.
If still not work, then try out clearing cache from the "Setting" window.

**Comment by TerenceClark** [comment]
Thank you. I think it's a cache problem. I have sent the transaction through imtoken.
