### ISSUE TITLE
Wallet Sync

### ISSUE THREAD

**Issue by Yupy** [nervosnetwork/neuron#2014]
**Describe the bug**
I have downloaded the Wallet for Linux the latest .appimage and is not syncing at all it says only connecting is it normal for the default node to be on local host? **http://localhost:8114**

**Environment (please complete the following information):**
 - OS & Version: Ubuntu-MATE 20.04
 - Neuron Version: 0.36.0-alpha.1

**Comment by kellyshang** [comment]
Hi @Yupy , could you please help export the debug info from menu `Help` > `Export Debug Information` and share it with us? Then we will have a look.

BTW, this issue might be helpful: https://github.com/nervosnetwork/neuron/issues/1939

**Comment by Yupy** [comment]
Sure

[neuron_debug_1617938817438.zip](https://github.com/nervosnetwork/neuron/files/6282984/neuron_debug_1617938817438.zip)

**Comment by kellyshang** [comment]
Thanks for sharing the log. 
Based on the log it seems cannot find the ckb node folder.
Could you help have a look to see if there is a `chains` folder under the path of `~/.config/Neuron` ?

**Comment by kellyshang** [comment]
Also, could you help have a try to download the ckb binary directly from https://github.com/nervosnetwork/ckb/releases/tag/v0.35.1 , and see if the ckb node can be run on your computer?

For how to run a CKB node, can refer to this guide: https://docs.nervos.org/docs/basics/guides/mainnet

**Comment by Yupy** [comment]
> Thanks for sharing the log.
> Based on the log it seems cannot find the ckb node‘s folder. Could you help have a look to see if there is a `chains` folder under the path of `~/.config/Neuron` ?

The folder **chains** is missing from `.config/Neuron`

I tried to run the CKB node `ckb_v0.35.1_x86_64-unknown-linux-gnu` bu throws **Illegal instruction (code dumped)**

**Comment by kellyshang** [comment]
> > Thanks for sharing the log.
> > Based on the log it seems cannot find the ckb node‘s folder. Could you help have a look to see if there is a `chains` folder under the path of `~/.config/Neuron` ?
> 
> The folder `chains` is missing from `.config/Neuron`
> 
> I tried to run the CKB node `ckb_v0.35.1_x86_64-unknown-linux-gnu` but throws `Illegal instruction (code dumped)`

Thanks for your reply. Seems unfortunately the CKB binary is not support for your OS version. ( As to the platforms list of the CKB official binary release supports for, you can refer to this [doc ](https://github.com/nervosnetwork/ckb/blob/develop/docs/platform-support.md)and check the list of `Tier 1` and `Tier 2`.

BTW, could you help provide your OS version for us for more information?  (By `uname -a` and `lsb_release -a` )

If you still want to run the ckb node on your OS, maybe you need to try build the ckb binary by yourself ( guide: https://docs.nervos.org/docs/basics/guides/get-ckb#build-from-source ), and then start the Neuron after running a **solo** ckb node (instead of running ckb node inside the Neuron).

**Comment by Yupy** [comment]
The `uname -a` output:

`Linux my-desktop 5.8.0-48-generic #54~20.04.1-Ubuntu SMP Sat Mar 20 13:40:25 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
`
And the `lsb_release -a` output:

`No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.2 LTS
Release:	20.04
Codename:	focal
`

**Comment by kellyshang** [comment]
Got. Maybe it is the CPU that does not support.. Could you help provide your CPU info for us to confirm: `cat /proc/cpuinfo | grep 'flags' | uniq `

BTW, this issue might be helpful for the CKB node's error of `Illegal instruction (code dumped)`: https://github.com/nervosnetwork/ckb/issues/2623#issuecomment-804542700

**Comment by Yupy** [comment]
> Got. Maybe it is the CPU that does not support.. Could you help provide your CPU flags' info for us to confirm: `cat /proc/cpuinfo | grep 'flags' | uniq `
> 
> BTW, this issue might be helpful for the CKB node's error of `Illegal instruction (code dumped)`: [nervosnetwork/ckb#2623 (comment)](https://github.com/nervosnetwork/ckb/issues/2623#issuecomment-804542700)

You are right, is because of the CPU. I have run the wallet on my other machine and works.

Thank you very much for your time and help!

**Comment by kellyshang** [comment]
> > Got. Maybe it is the CPU that does not support.. Could you help provide your CPU flags' info for us to confirm: `cat /proc/cpuinfo | grep 'flags' | uniq `
> > BTW, this issue might be helpful for the CKB node's error of `Illegal instruction (code dumped)`: [nervosnetwork/ckb#2623 (comment)](https://github.com/nervosnetwork/ckb/issues/2623#issuecomment-804542700)
> 
> You are right, is because of the CPU. I have run the wallet on my other machine and works.
> 
> Thank you very much for your time and help!

Cool！Glad to hear that :)
