### ISSUE TITLE
wallet not syncing. Have not received my deposit

### ISSUE THREAD

**Issue by cryptosick0** [nervosnetwork/neuron#2029]
I downloaded Nurvos wallet and set up. I sent coins to receive address and they have not shown up. Appears the wallet wont sync. This is the transaction ID. 0xe99daa53058009190dc736d476a18bb69baffe4b538aa6c7c14f359ac86d68cb

To this receiving address. ckb1qyqdmfcfazyvgmte7prge8fxcn3prl0rlruq2mrztc

Running windows 10
Version 0.036.0-alpha.1
block 4,457,211

**Describe the bug**
Please enter details. 

**Environment (please complete the following information):**
 - OS & Version: [e.g. Windows 10, macOS 10.15.2, Linux Ubuntu 18.04]
 - Neuron Version [e.g. 0.28.0]
 - Block Number: [Check that from `Overview` - `Blockchain Status` for v0.29.0-rc2 or before, or hover onto the left bottom syncing status area for v0.29.0 and later]

**Steps To Reproduce**

**Screenshots**

**Comment by kellyshang** [comment]
Hi @cryptosick0 , could you please help have a try to `Clear Cache` from the `Setting` window to see if the tx appears after synced completely?

**Comment by cryptosick0** [comment]
All set ,thank you ! Everything is working.  I just didn't understand the
sync process.

**Comment by kellyshang** [comment]
> All set ,thank you ! Everything is working. I just didn't understand the sync process.
> […](#)

Great! Glad to hear that :)
