### ISSUE TITLE
deposit failed to arrive

### ISSUE THREAD

**Issue by aaronV81** [nervosnetwork/neuron#2031]
I have not received my deposit into my wallet

**Comment by aaronV81** [comment]
[Uploading neuron_debug_1623009153673.zip…]()

**Comment by kellyshang** [comment]
> Uploading neuron_debug_1623009153673.zip…

Hi @aaronV81 , seems the debug log did not been uploaded successfully, could you please help try upload it again?

**Comment by aaronV81** [comment]
[neuron_debug_1623009153673.zip](https://github.com/nervosnetwork/neuron/files/6606743/neuron_debug_1623009153673.zip)

**Comment by aaronV81** [comment]
its a good thing i only sent 63ckb instead of the 200k I have.
imagine that disappearing

**Comment by kellyshang** [comment]
From your debug log, seems your sync process has not been fully completed. You can check the sync process by mouse over the left bottom. For now the latest block height is 4488496 (can check from the explorer https://explorer.nervos.org/ ), but your local ckb node's latest height is 363151.

BTW, your CKB will not been lost if the tx has been committed to the Nervos chain, you can check your address from the explorer to check the balance.

**Comment by aaronV81** [comment]
So how long will it take to arrive ?

I want to know when please, if I knew it was such a drama I wouldn't have bothered...

I can let the 63 go and buy more. I don't have time jumping through hoops for the $1.30 it's worth.


I've left my laptop on all night and still it didn't sync...

What a waste of time. And by the time it syncs I will have to pay that same money back in electricity.


What a flipping JOKE !!!

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by kellyshang** [comment]
As the Neuron is a `full node` wallet, the sync speed will rely on many aspects such as your computer's performance / network's status and so on. The sync will take for couples of hours to sync. But from your log seems every time you opened the Neuron but synced only for less than one hour.

If possible, you can use some other light wallet thus will not waste your time to wait for sync.

**Comment by aaronV81** [comment]
Light wallet ?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by kellyshang** [comment]
> Light wallet ? Get Outlook for Android<https://aka.ms/ghei36>

for example, imToken/Bitpie and so on.

**Comment by aaronV81** [comment]
Can I stake my CKB in the light wallet.

The whole point of why j want it moving to Neuron Wallet is so I can stake my CKB whole prices are flat...

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by kellyshang** [comment]
> Can I stake my CKB in the light wallet. The whole point of why j want it moving to Neuron Wallet is so I can stake my CKB whole prices are flat... Get Outlook for Android<https://aka.ms/ghei36>

Oh thus you can use the `Portal Wallet` by typing url of ckb.pw in any wallet's dapp screen.

**Comment by aaronV81** [comment]
What am I waiting for to signify that the process is completed.


This is bordering on ridiculous. I don't want to overcomplicate it and risk losing all my crypto because of your weird wallet..


I just want to simply stake it. I won't be sending my remaining ckb anywhere to be steessed about where it is..

I dont know why this wallet starts again from the beginning every time..
Whats the pojnt in leaving my laptop on burning electric.

I will incur more charges waiting on this seemingly NEVER ENDING SYNCING process.

I'll actually leave it on ALL DAY from now and see if it will actually show up today.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by aaronV81** [comment]
So if it does eventually show up. How long will it take if I send the rest to the neuron Wallet.

Another few days
________________________________

**Comment by kellyshang** [comment]
>What am I waiting for to signify that the process is completed.

As I said before, you can check the sync process from the left bottom of the Neuron.

>I dont know why this wallet starts again from the beginning every time..

The wallet sync won't restart every time. It will start syncing from the block height you closed it last time.

**Comment by aaronV81** [comment]
Hello again.

I have sent my CKB to the wallet using the previous address from the last ckb I sent.

Will this still get to my wallet ?

Because it says I can use a previous address, but yet it's taking much longer to show up in the neuron Wallet compared to the previous ckb I sent ?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by aaronV81** [comment]
Is it going to my wallet or gas it gone elsewhere ?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by aaronV81** [comment]
Has*

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Tylor150** [comment]
So did your first problem get resolved? The small amount of CKB eventually arrived? I'm having the same exact problem, except I sent almost 300K coins. I am so frustrated with Neuron. Left syncing on all night and it actually went backwards. What is going on?

**Comment by aaronV81** [comment]
Yes it does resolve itself once the sync is complete

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by aaronV81** [comment]
It can take up to 12hrs to sync
________________________________

**Comment by Tylor150** [comment]
Hi, thanks for replying! Just seeing your email. It did not resolve,
actually. Been frozen at 17.25% for a day now. Was thinking maybe I could
just reload my address in a light wallet using my original seed phrase?
That would at least make me feel more comfortable.

**Comment by aaronV81** [comment]
Sent them a message

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by aaronV81** [comment]
What did they say when you told them

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by aaronV81** [comment]
Version 0.35.0 is the one I found worked for me.

I think the latest version is 0.36.0 a beta version

0.35.0 is more stable and after I downloaded that version. Eventually after a few hours the wallet synced...

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by aaronV81** [comment]
https://github.com/nervosnetwork/neuron/releases

Not 0.36.0 alpha ✖️

2nd one down 0.35.0

I hope this helps sort out your problem 👍🏾

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Tylor150** [comment]
Thanks Aaron! Yes, I noticed that "alpha" version and started over with
0.35.0. That's what was stuck for a long time at 17.25%. But I noticed it
was moving again recently, and now has been stopped at 82% for a while.
Strange. Maybe just takes really long for some reason.

**Comment by aaronV81** [comment]
Its dependant on your machine and internet speed etc but it should complete if you leave it on.
It doesn't go up 1-2-3 etc it's sporadic but completes eventually 👍🏾

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Tylor150** [comment]
I really appreciate your reassurance and advice! Thank you and wish you
well, from Minnesota, USA.

**Comment by Tylor150** [comment]
It finally synced! Thought I should let you know. Thanks again.

**Comment by aaronV81** [comment]
Finally.  Lol

🙌🏾👍🏾

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
