### ISSUE TITLE
Neuron will not seem to sync

### ISSUE THREAD

**Issue by Tylor150** [nervosnetwork/neuron#2034]
Sent substantial CKB from Kucoin to an address I created in Neuron. Unfortunately I didn't wait for the sync to complete before doing that. Now Neuron has been trying to sync for 8 hours or so. Explorer says transaction went through, but wallet still trying to sync (sometimes goes backwards). Not using a VPN. Latest version of Neuron. Starting to get nervous. Thank you. 

**Environment**
 - OS & Version: macOS 11.4
 - Neuron Version 0.35.0
 - Block Number: 971,647 / 1,413,412

https://explorer.nervos.org/address/ckb1qyqfm6n9q4caj5q6w6myppfu0a84gqqyyzcq3r8seg

<img width="1352" alt="Screen Shot 2021-06-12 at 10 33 57 AM" src="https://user-images.githubusercontent.com/85798683/121781341-d6c26200-cb69-11eb-93bd-3d64d29c00e7.png">
<img width="1454" alt="Screen Shot 2021-06-12 at 10 34 29 AM" src="https://user-images.githubusercontent.com/85798683/121781350-dd50d980-cb69-11eb-9db3-2cc117c4bd78.png">

**Comment by Tylor150** [comment]
Interesting. So I cleared the cache again but this time checked "Fully rebuild index" and the sync process has started over. For a long time it was frozen at the block number I provided. Now at least it is actively syncing. We'll see.

**Comment by Tylor150** [comment]
Been frozen at 17.25% for a day now. If anyone can help me figure this out, I'd be so grateful.

**Comment by kellyshang** [comment]
@Tylor150  Sorry for the late reply, does the problem resolved by now?

**Comment by Tylor150** [comment]
Yes, thank you. It eventually did sync.

**Comment by kellyshang** [comment]
Great, thanks for your reply.
