### ISSUE TITLE
Tranfer Failed

### ISSUE THREAD

**Issue by Kafkama** [nervosnetwork/neuron#2035]
Hey guys.
I tried to transfer, but I don´t receive my token. What´s happend? Can I do something to receive? I´m afraid about this token. I had never facing problems with another coin or token transaction. 

Please enter details.

**Environment (please complete the following information):**
 - OS & Version: [e.g. Windows 10]
 - Neuron Version [e.g. 0.36.0-alpha1]
 - Block Number: [Test: 0xe4506845a2eef084001a706f87752f575a6cb3f4fa72b444a9969ee488d4dad6 - 149 CKB]

**Comment by kellyshang** [comment]
Hi @Kafkama , could you check the synced process from the left bottom of the Neuron? It may take a long time to synced fully, then the token transation should be appeared in the Neuron.

**Comment by pqbernardo** [comment]
Hi, Did you get the tokens back? If you did, how was it? The same thing happened to me
I sent it to this address: ckb1qyqdt5ka8prnrptxncrj2rc8tn6fwp8453hqgxle42 the transaction worked but it never made it to my wallet I used the neuron wallet

**Comment by kellyshang** [comment]
> Hi, Did you get the tokens back? If you did, how was it? The same thing happened to me
> I sent it to this address: ckb1qyqdt5ka8prnrptxncrj2rc8tn6fwp8453hqgxle42 the transaction worked but it never made it to my wallet I used the neuron wallet

Hi @pqbernardo , what's the error message displayed?

**Comment by pqbernardo** [comment]
Hi, there was no error message, I made a transfer through binance, on
binance everything worked out and i waited for my tokens to get in on my
neuron wallet, but it never arrived.
The transaction address: ckb1qyqdt5ka8prnrptxncrj2rc8tn6fwp8453hqgxle42

Em ter., 3 de ago. de 2021 às 07:37, kellyshang ***@***.***>
escreveu:

**Comment by kellyshang** [comment]
> ckb1qyqdt5ka8prnrptxncrj2rc8tn6fwp8453hqgxle42

Check from the CKB explorer ( https://explorer.nervos.org/ ) your assets have been arrived to your address, so don't worry.
After started Neuron you need to be patient to wait for the sync to be complete, which you can check from the left bottom corner of the Neuron. (ps. the sync process may take for couple of hours as it's depend on your PC's performance, network status and so on)
