### ISSUE TITLE
CKB sent from DXpool and binance has not arrived in Neuron Wallet

### ISSUE THREAD

**Issue by ttot1977** [nervosnetwork/neuron#2036]
**Describe the bug**
I have sent CKB coins from DXpool and from Binance to my Neuron wallet but they never arrived.

**Environment (please complete the following information):**
 - OS & Version: Windows 10
 - Neuron Version [e.g. 0.35.0]

So I have installed Neuron wallet on 30.06.2021. and after setup I sent larger amount from Dxpool and after that from Binance account to my Neuron wallet address which I get in "receive" menu.
After that I notice that Wallet was not synced and I let it synced but that never goes on my old lap top, so I changed the laptop and installed Neuron wallet on my new lap top where I had import my existing wallet and on new laptop I succesfully made syncing 100%. But tokens never came? Today I tryed with new 100 tokens transaction and wverything goes well I see 100 tokens in my wallet now.
But I still do not see tokens from 2 transaction from 30.06.2021.
Please help me where are this tokens?

**Comment by kellyshang** [comment]
Hi @ttot1977 , firstly you could check the wallet address from the [CKB Explorer](https://explorer.nervos.org/) to see if there is any ckb tokens under the address, if yes, then don't worry your tokens are truely on the chain.
Then please have a try to clear cache from the `Settings` window and then check if the 2 transactions appears when synced fully.

**Comment by ttot1977** [comment]
Hello

Thank you for Quick Answer.
How can I exactly check the wallet address from ckb Explorer?
Please instructions.

Maybe is problem that I started to sync on my old notebook which never
finished syncing and then I installed Neuron and import the same Wallet on
my new notebook and on new notebook everything synced 100% but I don't see
this 2 transactions from dxpool and binance.
On old notebook I checked the receive address in arhive which are the same
as withdrawal addresses on binance and dx pool. So I've made transactions
on right addresses.
Thank you for help


ned, 4. srp 2021. 05:11 kellyshang ***@***.***> je napisao:

**Comment by kellyshang** [comment]
>How can I exactly check the wallet address from ckb Explorer?

Go to https://explorer.nervos.org/ , type your wallet address in the search box as below, then you will see the address detail page to check your assets' balance:
![image](https://user-images.githubusercontent.com/28836185/124378026-ddb04080-dce1-11eb-899d-a16084be16f5.png)


>I don't see this 2 transactions from dxpool and binance

So please could you have a try to clear cache which is in the `Settings` window of Neuron?
![image](https://user-images.githubusercontent.com/28836185/124378193-bdcd4c80-dce2-11eb-9174-419884819c81.png)

**Comment by ttot1977** [comment]
Hello

so I did check explorer and transactions are visible there, after that I
did again "cash clear" but after that I still dont see tokens in my Wallet.
I see just 100tokens which I transferred as a test yesterday.
I repeat firstly I installed Neuron wallet on my old notebook, after I
couldnt sync Wallet on my old notebook, then I installed the same wallet on
my new notebook which successfully synced Wallet.
Is it possible to have the same wallet on 2 notebooks synced?
I want to stake CKB so please help me solve this issue. Screenshots
attached...
Thank you


[image: image.png]

[image: image.png]

[image: image.png]



ned, 4. srp 2021. u 10:13 kellyshang ***@***.***> napisao je:

**Comment by kellyshang** [comment]
Hi @ttot1977 , seems your screenshots were not uploaded successfully, could you have a try again?

BTW, does the Neuron address on your old notebook the same as the new notebook?

If the same, then could you help export and upload the debug information from the Neuron `Help` menu on the `old notebook`? 
![image](https://user-images.githubusercontent.com/28836185/124386467-2af5d780-dd0d-11eb-8fdc-4cdb9f43ee0b.png)

**Comment by ttot1977** [comment]
Hello

I send screenshots in attachment and also debug file.
No the receive address is not the same on old and new notebook. On new
notebook in address archive I can not find this address from old notebook
on which the tokens were transferred.
thank you

ned, 4. srp 2021. u 15:18 kellyshang ***@***.***> napisao je:

**Comment by ttot1977** [comment]
Hello

Here I send debug file from old notebook. In previous mail it was debug
file from new notebook.
Br

**Comment by kellyshang** [comment]
Seems there is still no attachment...

BTW, are you sure that the address list in the `Address Book` are not the same from old notebook and new notebook? If not the same, maybe the wallet that you imported into Neuron on both notebook are not same wallet. Could you please have a double check?
![image](https://user-images.githubusercontent.com/28836185/124388736-b889f500-dd16-11eb-924d-f942850de793.png)

**Comment by kellyshang** [comment]
> Hello Here I send debug file from old notebook. In previous mail it was debug file from new notebook. Br

I see why there is no attachment.. May be you replied to the official `noreply` email address which actually I cannot receive the attachment file.

If it's ok could you send the debug file to this email: shangke@nervina.io ? Also you can open this issue on PC web browser and then upload the attachments in the comment.

**Comment by ttot1977** [comment]
Hello

I checked again, the wallet which I imported on new notebook was imported
by key words (wallet seeds) and I imported again so now I see 2 wallets in
Neuron on my new notebook but on both just 100 tokens which I
transfer yesterday as a test.
I dont see 12.000+18.000 from Binance and DXpool which I transferred on
30.06.2021.
Here I send again all screenshots in attachment and both debug files from
new notebook. I hope this time you will get it?


ned, 4. srp 2021. u 16:31 kellyshang ***@***.***> napisao je:

**Comment by kellyshang** [comment]
Yes this time I got your attachment file from the email, and I checked the debug log, seems the sync process on your old notbook still not completely synced. On your old notebook's the Neuron is currently synced to block height of 1726201 (which can check by mouse over to the left bottom of Neuron), but the latest block height of CKB chain is  now 4714791 (which can see from the CKB Explorer https://explorer.nervos.org/ ).

The sync process may take a long time which depend on your PC's performance or network status. So maybe you need to be patient to wait for the sync process to complete fully on your old notebook.

**Comment by ttot1977** [comment]
Ok we will wait to sync process on old notebook end. We try to sync it from
30.06. But we will be patient.
Thank you

ned, 4. srp 2021. 17:41 kellyshang ***@***.***> je napisao:

**Comment by ttot1977** [comment]
Hello Kelly

I have the same problem again, Yesterday 31.10.2021. I tried to make
transaction from binance to Neuron wallet 50.001CKB on the CKB address
which I have saved last time on white list on Binance.
And I have synced Neuron and also cleared cash on both lap tops but I still
dont see the balance of 50.000CKB in my Neuron wallet.
Here I send screenshots from Neuron explorer (addresS) and the same address
was in binance for sending...
Now I make update on new Neuron version... can you check why I dont see
50.000ckb in my neuron wallet?
thank you

[image: image.png]

[image: image.png]

ned, 4. srp 2021. u 10:13 kellyshang ***@***.***> napisao je:

**Comment by kellyshang** [comment]
Hi @ttot1977 , we can't see your attached screenshots. **PLZ don't reply the notification email**, as the notification email was sent by the github platform but not from our private email, so we can't receive the file which you attached in the mail.

PLZ paste your screenshots into the comment input box of this issue and better along with your debug info zip file.

**Comment by Anubix8** [comment]
Hi, @kellyshang  I have the same issue here with sending CKB from Binance to neuron.
Debug file is attached down below.
I hope we can fix this issue.
Thank you :)
[neuron_debug_1635843081752.zip](https://github.com/nervosnetwork/neuron/files/7459166/neuron_debug_1635843081752.zip)

**Comment by kellyshang** [comment]
> Hi, @kellyshang I have the same issue here with sending CKB from Binance to neuron. Debug file is attached down below. I hope we can fix this issue. Thank you :) [neuron_debug_1635843081752.zip](https://github.com/nervosnetwork/neuron/files/7459166/neuron_debug_1635843081752.zip)

Hi @Anubix8 , you can check your neuron address( the receive address you filled in the Binance) on the explorer to see if the CKB is there. If yes, then try to clear cash and see if it works.

**Comment by Anubix8** [comment]
I tried clearing cache but still nothing happend.

**Comment by kellyshang** [comment]
> I tried clearing cache but still nothing happend.

Check from the explorer - https://explorer.nervos.org/ is there any CKB in your Neuron address?

**Comment by Anubix8** [comment]
I checked just now and there is my address and CKB

**Comment by ttot1977** [comment]
Hello Kelly,

we have send the CKB from Binance wallet to history address on Neuron
Wallet which was saved on white list in Binance (so we have not generate
new receive address in Neuron wallet)
This history address  on which we send CKB is visible in our Neuron history
wallet and this address is ckb1qyqxngcpv884mq3g4tqqc09jku4g2lkwlnmqhzlrdw.
So we installed new update version of neuron wallet and also synced from
beginning to 100% on both lap tops and we cleared cash few times but we
still dont see our 50.000ckb in Neuron wallet, last visible transaction is
on 02.10.2021. and this one was made on 31.10.2021. and it is still not in
wallet.
Please help us.
Thank you

uto, 2. stu 2021. u 18:07 Anubix8 ***@***.***> napisao je:

**Comment by kellyshang** [comment]
@ttot1977 Could you please explort your debug info zip file drag it to the **comment inputbox** here?

**NOTE:** **PLZ** don't reply to the notification email, as the notification email was sent by the github platform but not from our private email, so we can't receive any files which you attached in the mail.

**Comment by Prekjr** [comment]
I literally have the exact same problem as listed by many above however, I've tried everything recommended by support without success as the sync process takes any incredibly long time and never completely gets to the maximum block height at all, seems to just stall, could be a bug in the sync process? Please advise

**Comment by ttot1977** [comment]
Hello

I have done everything you write, I have also update neuron wallet on new
version, ckbs are visible under this address in neuron explorer but I still
don't see them in neuron wallet. Please help

ned, 4. srp 2021. 05:11 kellyshang ***@***.***> je napisao:

**Comment by kellyshang** [comment]
@ttot1977 **PLZ don't reply to the notification email**, as the notification email was sent by the github platform but not from our private email, so we can't receive any files which you attached in the mail.

We can't get any files you sent before attached to the mail. So please DRAG the files into the COMMENT INPUTBOX.

**Comment by kellyshang** [comment]
> I literally have the exact same problem as listed by many above however, I've tried everything recommended by support without success as the sync process takes any incredibly long time and never completely gets to the maximum block height at all, seems to just stall, could be a bug in the sync process? Please advise

Could you please help export and upload the debug info zip file? (from `Help` - `Export Debug Information`)

**Comment by ttot1977** [comment]
Hello again

finally I sent here folowing datas, files and screenshots:
1) debug file in zip format
2) screenshot that I have made 100% syncing and installed new neuron wallet version
3) screenshot that receiving address is visible in history in Neuron wallet and that on explorer Neuron wallet is visible 50.000CKB from transaction 31.10.2021.

I still dont have 50.000CKB in my Neuron wallet please help!
Thank you

![image](https://user-images.githubusercontent.com/86892611/140550616-fe28f831-3334-4a91-b0b6-5394cd326e5b.png)

![image](https://user-images.githubusercontent.com/86892611/140550229-c41d5944-6dca-4104-bdbe-2299516a31ba.png)
[neuron_debug_1636131335367.zip](https://github.com/nervosnetwork/neuron/files/7487764/neuron_debug_1636131335367.zip)

![image](https://user-images.githubusercontent.com/86892611/140550308-74e41e39-583d-4dbe-a9ce-4ade97c959f7.png)

![image](https://user-images.githubusercontent.com/86892611/140550494-581bc034-3289-47a5-9aef-8be90e4f649f.png)

**Comment by Anubix8** [comment]
I have the same issue @ttot1977 has.
I have also cried all of the above and nothing.

**Comment by ttot1977** [comment]
Hello Kelly

I've made everything you said through github platform, draged debug files,
Screenshots etc. which are the proof that I have made everything properly
but im still without any answer and my ckb's.
Please help


pet, 5. stu 2021. 10:28 kellyshang ***@***.***> je napisao:

**Comment by ttot1977** [comment]
Hello Kelly,

im waiting from 31.10.2021. please any answer and help regarding my case?
thank you

**Comment by Prekjr** [comment]
I don’t know why you’re reach out to me for support but you can refresh the wallet so it synchronizes with the server once again to reflect what’s on the block chain and hopefully 
your CKB

Peter R

**Comment by ttot1977** [comment]
Hello

I tryed to refresh wallet few times until now, I also instaled newest
Wallet app version and have synced my Wallet again from zero, but still no
CKB in my wallet.
Now I will try to refresh wallet from beginning again and then send again
information to you.
br

pon, 22. stu 2021. u 12:07 Peter Rozie Jr ***@***.***>
napisao je:

> I don’t know why you’re reach out to me for support but you can refresh
> the wallet so it synchronizes with the server once again to reflect what’s
> on the block chain and hopefully
> your CKB
>
> Peter R
>

**Comment by kellyshang** [comment]
@ttot1977 Does the address( `ckb1qyq...zlrdw` )  which received the 50000 CKB existing in your Neuron - `Receive` - `Address Book`？
![image](https://user-images.githubusercontent.com/28836185/142892301-c9dcc693-d398-4491-ab97-ca233d807649.png)

**Comment by ttot1977** [comment]
It exist in address history  I have sent screenshot to you

pon, 22. stu 2021. 16:50 kellyshang ***@***.***> je napisao:

**Comment by ttot1977** [comment]
So I did one more time fully index rebuilding and 100% syncing from the
beginning and still nothing.
I have sent to you all screenshot on github platform and you can see that I
have sent 50.000CKB on 31.10.2021. on the same wallet address which I do
have in my history addresses in Neuron wallet and on the same address I
have already sent 30.000ckb on 07.07.2021. The transaction is visible on
explorer (you have screenshot) but not in my wallet.

So I have try everything and Im still without of my 50.000CKB which is not
small amount and it will be more then 3 weeks spinning around without
solution.
Please help me to solve this issue because that is also in your very best
interest and your app must be 100% safe and reliable for users.
Thank you

pon, 22. stu 2021. u 18:03 Tomislav Tot ***@***.***> napisao je:

**Comment by kellyshang** [comment]
>It exist in address history  I have sent screenshot to you

@ttot1977 No you didn't sent the correct screenshot. The transaction `History` is not the same as the `Address Book`. The address displayed in the transaction details not means that the address belongs to the wallet. They are not the same thing.

**Comment by ttot1977** [comment]
The address is visible in history, but it is not visible in address book,
what do you want to say? That the same allready used address is now address
for some other wallet or what? On neuron explorer I see both transaction on
the same address 30.000ckb on 07.07.2021. And 50.000ckb on 31.10.2021. But
30.000ckb has arrived on my wallet and 50.000ckb have not arrived.
Can you fix this problem or you want to say that I lose 50.000ckb which I
hardly have mined more then a month?
I had to register neuron wallet address on binance app on white list so I
supposed that this is my safe address for my neuron wallet because I
allready make successful transaction before on the same address.
Please help.



uto, 23. stu 2021. 02:33 kellyshang ***@***.***> je napisao:

**Comment by Prekjr** [comment]
why are you cc’ing me? I’m not support for CKB, and I told you what you could do but not that it would work or not, please stop emailing me
Peter

**Comment by kellyshang** [comment]
@Prekjr It's the Github platform's notification mail to you because you replied in this issue, and everybody related in this issue will receive the mail.

**Comment by kellyshang** [comment]
>The address is visible in history, but it is not visible in address book

@ttot1977 Yes, I mean that the wallet was not belong to your current Neuron wallet. You'd better try to remember and check where this address was copied from.
The transaction of 30.000ckb on 07.07.2021 you mentioned in the screenshot of the search result, was just filtered all transactions which including the address you searched for. But that not meaning that this address is belongs to you.
ONLY the addresses displayed in the "Address Book" are belongs to you.

**Comment by ttot1977** [comment]
Hello Kelly

thank you for quick response, so I generated that address ( ckb1qyq...zlrdw )
on 07.07.2021. from Neuron wallet, after that I had to register that
address in the white list on the Binance app. So first time on 07.07.2021.
everything went well and 30k ckb arrived in my wallet. On 31.10.2021. I
used that same address ( ckb1qyq...zlrdw ) for new transaction because this
address was already in my white list on binance app and it was generated
from Neuron wallet so I was thinking that is safe and already verified.

Can you please help me, how to return my 50.000ckb which I sent on this
address?
I really can not believe that this address which was generated from Neuron
wallet and on which I have received first time my CKB's now can be address
from some other wallet? How is that possible that the same address can be
used more times for different wallets?
Please give me instructions whom to contact and how to recover 50.000ckb
which were sent on the same wallet address generated from my Neuron wallet.
Thank you

uto, 23. stu 2021. u 09:33 kellyshang ***@***.***> napisao je:

**Comment by kellyshang** [comment]
@ttot1977 I checked that the transaction of 07.07.2021 in your screenshot, the address ( ckb1qyq...zlrdw ) was the sender but not receiver. The transaction's receiver should be ckb1qyqy8a24a6npc63zjrejmwm32u7jv384ncxq84lhxp which belongs to your wallet. Please check.
![image](https://user-images.githubusercontent.com/28836185/143048707-fe67b549-6cba-466f-b178-bc64180a29cf.png)

**Comment by kellyshang** [comment]
@ttot1977 Please check the complete reply from this issue https://github.com/nervosnetwork/neuron/issues/2036 on PC cause I made some additions in previous comment, which may missing from the notification email.

**Comment by ttot1977** [comment]
Hello Kellyshang

thank you for answer, here is screenshot from Binance where I have this address registred for white list (safe transaction)
Can you please explain me how can I switch wallet in Neuron to  see if this address "...zlrdw" exist in other wallet in Neuron?

![image](https://user-images.githubusercontent.com/86892611/143075252-e3f5f6f3-270d-4fe1-85ec-cd57b999be40.png)

**Comment by ttot1977** [comment]
Here I send screenshot from Binance transaction history where is visible that I have used exactly this address "...lrdw" as receiver address

![image](https://user-images.githubusercontent.com/86892611/143077661-15309e7a-a9ad-4e56-b8c7-c115e22edd0d.png)

**Comment by kellyshang** [comment]
>how can I switch wallet in Neuron to see if this address "...zlrdw" exist in other wallet 

@ttot1977 
step1. From menu of `Wallet` > `Select Wallet`, then you can swich to other wallet.
step2. Then goto left menu of `Receive` > click button `Address Book` to check if the address( "...lrdw" ) listed in the address book of current wallet.

step1:
![image](https://user-images.githubusercontent.com/28836185/143155851-9bb070a1-046f-444a-a99f-4e393c810a2e.png)
step2:
![image](https://user-images.githubusercontent.com/28836185/143156071-8e911b7d-ff3c-4be4-a7dc-b74902892775.png)

**Comment by ttot1977** [comment]
Hello Kellyshang

I dont have other wallet in Neuron, just this one and only.
What else can we try to recover this transaction?

**Comment by kellyshang** [comment]
> Hello Kellyshang
> 
> I dont have other wallet in Neuron, just this one and only. What else can we try to recover this transaction?

I think it's better that you try to recall which wallet  the address "...zlrdw" you copied from.

**Comment by kellyshang** [comment]
And for now you'd better update the address that you registered in the white list of Bincance to avoid the later transaction been sent to the old address which you don't have the private key.

**Comment by kellyshang** [comment]
@ttot1977 Are you the same person with  @Anubix8?
Seems you have posted the same issue with https://github.com/nervosnetwork/neuron/issues/2157 , if you are the same person, please do not report duplicate issues.

**Comment by ttot1977** [comment]
Hello Kellyshang

I have contacted binance support and they say that 50.000ckb has been sent on my CKB wallet address "...zlrdw" and that is visible in neuron explorer under TxId which I send in attachment.
So how can I retrieve my Ckb's? It must be some way ? 


![image](https://user-images.githubusercontent.com/86892611/143624371-b62a6e3a-c66a-4a7c-9709-cf506db4449e.png)

![image](https://user-images.githubusercontent.com/86892611/143624331-6455c756-1c9f-4deb-b770-3fff706cff09.png)

**Comment by ttot1977** [comment]
Hello Kellyshang,

here is an answer from Binance support and they tell that definitely only you can see where my Ckb is because they are definitely somewhere in your network from 31.10.2021. so please investigate the case in detail or give me contact from someone else which can and please help me retrieve my funds back to me.
Thank you

![image](https://user-images.githubusercontent.com/86892611/143627022-eb8925d7-b248-4c45-bd9b-d8a29447a369.png)

![image](https://user-images.githubusercontent.com/86892611/143627069-b94e705b-526f-4f4f-a5ad-e851cedaeec5.png)
