### ISSUE TITLE
Neuron Wallet "Sync not started yet" 

### ISSUE THREAD

**Issue by estigan** [nervosnetwork/neuron#2039]
Neuron Wallet has been in use for several weeks without problems. 
When I now start Neuron it first says connecting and some seconds later "Sync not started yet". 
I have cleared cache but nothing happened.
Win 10, Neuron Version 0.36.0-alpha.1 CKB Client Version v0.35.1

Any idea how to solve the issue? Thank you. 

[neuron_debug_1625560500774.zip](https://github.com/nervosnetwork/neuron/files/6768632/neuron_debug_1625560500774.zip)
![Neuron Wallet Sync not started yet](https://user-images.githubusercontent.com/87008839/124570250-fe45db00-de46-11eb-95c9-bdbbf0739af6.jpg)

**Comment by kellyshang** [comment]
Hi @estigan , checked from your debug info, seems some file under the `%appdata%\Neuron\indexer_data\0x92b197aa1fba0f63633922c61c92375c9c074a93e85963554f5499fe1450d0e5` folder cannot been found.
Could you have a try to delete the whole folder of the `%appdata%\Neuron\indexer_data\0x92b197aa1fba0f63633922c61c92375c9c074a93e85963554f5499fe1450d0e5`, then restart the Neuron and wait to see if it start sync again?

**Comment by estigan** [comment]
Thank you so much Kelly. It worked as suggested.

![grafik](https://user-images.githubusercontent.com/87008839/125650889-5fb06a32-f54a-41c0-8900-039d8c5889ef.png)
