### ISSUE TITLE
The Neuron 0.36 for Windows doesn't display my CKB (I have checked on a different wallet to make sure). So I cant do anything with it. Please check it!

### ISSUE THREAD

**Issue by Tung40194** [nervosnetwork/neuron#2043]
**Describe the bug**
Please enter details.

**Environment (please complete the following information):**
 - OS & Version: [e.g. Windows 10, macOS 10.15.2, Linux Ubuntu 18.04]
 - Neuron Version [e.g. 0.28.0]
 - Block Number: [Check that from `Overview` - `Blockchain Status` for v0.29.0-rc2 or before, or hover onto the left bottom syncing status area for v0.29.0 and later]

**Steps To Reproduce**

**Screenshots**

**Comment by Tung40194** [comment]
OS & Version: Windows 10 Pro-64bit-21H1
Neuron Version 0.36.0-alpha.1
Block Number: Block 4,741,257

**Comment by kellyshang** [comment]
Hi @Tung40194 , could you have a try to clear cache from the `Settings` window and then wait to see if your CKB shows up when synced fully?
