### ISSUE TITLE
Ambiguous APC Values across deposits

### ISSUE THREAD

**Issue by jawndiego** [nervosnetwork/neuron#2044]
<img width="1199" alt="Screen_Shot_2021-07-08_at_1 17 47_PM" src="https://user-images.githubusercontent.com/62079777/125122500-833d2880-e0c3-11eb-89fb-47c14875aada.png">

There's some confusion around whether or not the APC at the time of deposit into the DAO is fixed across time. 

I think what adds to the confusion is that we show the APC at the time of your deposit. You can see it decreasing across different deposit times as expected, but at the top you have the Current APC. Then you have a series of decreasing APC amounts.

All of that seems to allude its fixed to your deposit date. So one could assume that my first deposit is still receiving an APC of 3.53%, my second deposit is receiving 3.11% and so on. 

As far as suggestions go, i think perhaps we can find a way to show that the APC is decreasing across ALL your deposits. I'm not sure if its better to show only the Current APC, or change the APC at the deposit level to "APC at time of deposit"

**Comment by 634396b** [comment]
Yes mine is also showing 0.9% APC for some reason...

**Comment by CipherWang** [comment]
> So one could assume that my first deposit is still receiving an APC of 3.53%, my second deposit is receiving 3.11% and so on.

That's ture. Once you deposit to DAO, your APC will be fixed. It's the magic of compound interest.
