### ISSUE TITLE
Neuron wallet not syncing , no blocks , zero % blocks

### ISSUE THREAD

**Issue by bolle307** [nervosnetwork/neuron#2045]
**Describe the bug**
Please enter details.

**Environment (please complete the following information):**
 - OS & Version: [e.g. Windows 10, macOS 10.15.2, Linux Ubuntu 18.04]
 - Neuron Version [e.g. 0.28.0]
 - Block Number: [Check that from `Overview` - `Blockchain Status` for v0.29.0-rc2 or before, or hover onto the left bottom syncing status area for v0.29.0 and later]

**Steps To Reproduce**

**Screenshots**

Neuron wallet not syncing , zero % blocks , keeps saying ''connecting'' but doesn't sync ?
Windows 7 version , 0.35 , did clear cache , plus fully rebuild , nothing happens , doesn't load blocks , doesn't sink ? Is W7 supported ?????
![image](https://user-images.githubusercontent.com/38289136/125204739-1078ac80-e27f-11eb-88d4-e8333a88a0b7.png)

**Comment by bolle307** [comment]
This is on Windows 7 , is that supported ???

**Comment by kellyshang** [comment]
> This is on Windows 7 , is that supported ???

Is your system the x64 OS? If yes, then it should support.
Could you help export the debug info from the `Help` menu?

**Comment by willo009** [comment]
Mine is doing the same thing, how did you fix this error, please.?

**Comment by kellyshang** [comment]
> Mine is doing the same thing, how did you fix this error, please.?

Hi @willo009 , could you help export the debug info from the `Help` menu?

**Comment by willo009** [comment]
Sure thankyou for your help, I have cleared the cache but it did not work.
[neuron_debug_1627973873201.zip](https://github.com/nervosnetwork/neuron/files/6924111/neuron_debug_1627973873201.zip)

**Comment by willo009** [comment]
I use x64 windows 10, thankyou for your help
