### ISSUE TITLE
Neuron wallet not connecting. Previous transactions stuck confirming.

### ISSUE THREAD

**Issue by nappin7** [nervosnetwork/neuron#2048]
**Describe the bug**
Wallet that I have had for about a month now is now stuck connecting. All previous transactions that had already been confirmed are now trying to re-confirm.

**Environment (please complete the following information):**
 - OS & Version: Windows 10
 - Neuron Version  0.35.0
 - Block Number: unknown

**Steps To Reproduce**

**Screenshots**
![Capture](https://user-images.githubusercontent.com/85855795/125904734-ed3ce051-5ee6-4b1b-a956-db8394b617f0.PNG)
![Capture1](https://user-images.githubusercontent.com/85855795/125904745-cee45d43-a63a-4700-aaca-1f870817f041.PNG)

**Comment by kellyshang** [comment]
Hi @nappin7 , sorry for the late replay. Does the sync work by now?

**Comment by kellyshang** [comment]
Will close this issue since there is no news. If any problem you can re-open this issue.
