### ISSUE TITLE
I DONT RECEIVED MY CKB PLEASE HELP ME

### ISSUE THREAD

**Issue by NervosRocket** [nervosnetwork/neuron#2050]
HELLO NERVOS TEAM PLEASE HELP ME
OS & Version: [e.g. Windows 10]
Neuron Version [e.g. 0.36.0-alpha1]
block number : 0x75196beaba21a6d4f174fd2512a8f9a3d140a4db355cb52176c90bf58c92f4b5
in 13 july im settle my ckb after staking 1 month 
so i sent to my address exchange Indodax 
here's my CKB address in Exchange
**ckb1qyqz7qcgxjgmat3tt8ef8vex9xhxxut6vc0s8g4kj0** 

![image](https://user-images.githubusercontent.com/87581783/126046498-1766aec7-bb87-4499-a177-1f3cb5e1dde3.png)
![image](https://user-images.githubusercontent.com/87581783/126046503-eb453749-f677-4784-a6fc-e425dd78cd63.png)
![image](https://user-images.githubusercontent.com/87581783/126046517-6c744bf3-ef2a-4b45-9cbd-a38dc225dea9.png)

Before i sent my CKB im already make sure the address is correct , but when i sent my CKB why the history address is different?
*noted* Lock Time : i released my CKB UTC+7 14 July
until now im not received any CKB 
![image](https://user-images.githubusercontent.com/87581783/126053571-23219ac7-a8b2-4597-961d-6b3680233fec.png)

here's my wallet exchange
![image](https://user-images.githubusercontent.com/87581783/126046573-97970145-39ff-43b4-b7a1-dec790edb644.png)

so please help me to get back my CKB :(((

here's my the receiver address 
![image](https://user-images.githubusercontent.com/87581783/126056164-a82140c8-20c8-46b0-8b72-fd5445e14c38.png)

**Comment by kellyshang** [comment]
Hi @NervosRocket, sorry for the late reply. 
The locked CKB should also be dispalyed in the menu of `Customized Assets`, which you can claim your CKB when the lock time is arrived.
