### ISSUE TITLE
Sent CKB to Asset account i created and i cant remove it to send to my exchange. "Says not main-net address"

### ISSUE THREAD

**Issue by Kiflex** [nervosnetwork/neuron#2051]
I sent CKB to a asset account I created and i have tried multiple addresses to remove it but it continues to tell me " not a main-net address. I don't want an asset account, I just want to remove it from the asset account and place it in my wallet. Please help!

**Comment by kellyshang** [comment]
Hi @Kiflex , as the error message indicated, maybe you were using a testnet address. Please double check.
If problem still exist, then you can reopen this issue.

**Comment by Kiflex** [comment]
No I’m not using a test net address, I was trying to send the CKB to my
Crypto.com CKB address. So let me be a little more clear. I sent 8000ckb to
an assest account that I created in the wallet. I have currently 8k CKB
there. when I try to put in my crypto.com address to transfer the CKB it
says, not a main net node address. Even if I try to just send it bad to the
normal CKB wallet address it tells me the same thing. please help.

**Comment by kellyshang** [comment]
We are considering to provide the destroy `CKB Account` feature in the future.
For now maybe you can have a try on Bitpie wallet which support the acp lock address.

**Comment by Kiflex** [comment]
Ok, thanks.
