### ISSUE TITLE
Tokens did not arrive from binance to neuron wallet 

### ISSUE THREAD

**Issue by pqbernardo** [nervosnetwork/neuron#2052]
I sent 1594,403 CKB to my neuron wallet that I use on windows 10 and it didn't arrive. 

Address: ckb1qyqdt5ka8prnrptxncrj2rc8tn6fwp8453hqgxle42

**Environment (please complete the following information):**
 - Windows 10
 - Neuron Version 0.36.0-alpha.1

![adress print](https://user-images.githubusercontent.com/88173147/127591108-5128faab-d8c0-4b8f-8a20-86f88ee00261.jpg)
![binance print](https://user-images.githubusercontent.com/88173147/127591112-9641d47c-a90b-476a-8de0-de0612f3b059.jpg)
![neuron](https://user-images.githubusercontent.com/88173147/127591116-e8461625-edff-4cc9-ab86-7f35b9e00e02.png)

The binance print is in portuguese because i live in brazil and portuguese is my native language.

Can I do something to receive my tokens?

**Comment by kellyshang** [comment]
Hi @pqbernardo ,  please make sure the synchronization is finilzed before you do any operation, when the sync is completed then your balance should be displayed.
You can mouse over the left bottom corner of the Neuron screen to check the sync process.
The sync process may take for many hours which depends on your network status/PC performance and so on.
