### ISSUE TITLE
Token Did not  receive  Neuron Wallet from Kucoin

### ISSUE THREAD

**Issue by jaksonsunny** [nervosnetwork/neuron#2058]
My tokens did not receive the neuron wallet from Kucoin. Wallet address is correct and I saw my transaction under
https://explorer.nervos.org. Please the transaction ID
0x214e5a360bb475cb203df0e05cd836d85005622e026b221f3bc6bee87696e6cd. Could you please help

**Comment by kellyshang** [comment]
Hi @jaksonsunny , please make sure the synchronization is finilzed before you do any operation, when the sync is completed then your balance should be displayed.
You can mouse over the left bottom corner of the Neuron screen to check the sync process.
The sync process may take for many hours which depends on your network status/PC performance and so on.
