### ISSUE TITLE
Missing Balance on my Neuron Wallet after Transaction from Binance

### ISSUE THREAD

**Issue by carioca1977** [nervosnetwork/neuron#2078]
**Missing Balance on my Neuron Wallet**
Hello, 
i did transfer from Binance -Exchange (CKB Tokens) to my Neuron Wallet but unfortunately, i can not  see any balance on my neuron wallet? I don't see even anything in the transaction History from the neuron wallet. But the transaction has been performed, as per attachedTransaction history of Binance-Exchange ? I copied the public address under "Receive-menu"  and took at the target address , so where is the mistake or what did went wrong?  
Youre prompt support is highley appriciated looking forward to hear from you.
Thank you and kind regards 
Ali 
**Environment (please complete the following information):**
 - OS & Version: [e.g. Windows 10 Pro]
 - Neuron Version [e.g. 0.35.1]
 - Block Number: [Check that from `Overview` - `Blockchain Status` for v0.29.0-rc2 or before, or hover onto the left bottom syncing status area for v0.29.0 and later]
![20210825_CKB_NEURON_Binance](https://user-images.githubusercontent.com/89524267/130791499-4a1e4026-3004-4009-aa0a-1b8389ba37a2.PNG)

**Steps To Reproduce**

**Screenshots**

**Comment by kellyshang** [comment]
Great. 
Neuron is a full node wallet which dictates that it needs to be synchronized first :)
