### ISSUE TITLE
not syncing 

### ISSUE THREAD

**Issue by payso112** [nervosnetwork/neuron#2083]
**Describe the bug**
Please enter details.
my wallet will not sync just keeps saying connecting 0%  windows 10  ver 0,36.0
**Environment (please complete the following information):**
 - OS & Version: [e.g. Windows 10, macOS 10.15.2, Linux Ubuntu 18.04]
 - Neuron Version [e.g. 0.28.0]
 - Block Number: [Check that from `Overview` - `Blockchain Status` for v0.29.0-rc2 or before, or hover onto the left bottom syncing status area for v0.29.0 and later]

**Steps To Reproduce**

**Screenshots**

**Comment by payso112** [comment]
I deposited some $ckb to the wallet to and its not syncing 0% just says connecting

**Comment by kellyshang** [comment]
@payso112 , could you have a try to restart the wallet? If after 10 mins it's still connecting, could you please help export and upload the debug info from the menu of `Help` - `Export Debug Information`?

**Comment by payso112** [comment]
No that didn't work still the same

**Comment by payso112** [comment]
Do what with the debug?where to

**Comment by kellyshang** [comment]
> Do what with the debug?where to

export the debug info and then upload here, we will have a look and try to check what's the problem

**Comment by Dowshajanin** [comment]
Hi, I'm having the exact same issue as described here by payso112. Here is my debug information. Please help.
[neuron_debug_1630512233731.zip](https://github.com/nervosnetwork/neuron/files/7092797/neuron_debug_1630512233731.zip)

**Comment by Dowshajanin** [comment]
...*correction: am using windows 8.1

**Comment by payso112** [comment]
[
[neuron_debug_1630456350355.zip](https://github.com/nervosnetwork/neuron/files/7093213/neuron_debug_1630456350355.zip)

**Comment by kellyshang** [comment]
Hi @payso112 and @Dowshajanin , seems both of your Neuron's bundled CKB node were not running, you need to download and install the latest `Microsoft Visual C++ Redistributable for Visual Studio 2015, 2017 and 2019`, which can be found from https://support.microsoft.com/en-us/topic/the-latest-supported-visual-c-downloads-2647da03-1eea-4433-9aff-95f26a218cc0 .

Please make sure to install the x64 one:
![image](https://user-images.githubusercontent.com/28836185/131770376-9dbba22a-6937-4a73-bb53-2c5e918a69ea.png)

**Comment by payso112** [comment]
THANK YOU ...that worked I really apricate it ...
