### ISSUE TITLE
DAO feature request 

### ISSUE THREAD

**Issue by CryptoGumby** [nervosnetwork/neuron#2088]
DAO feature request 
Please enter details.

**Environment (please complete the following information):**
 - OS & Version: [e.g. Windows 10, macOS 10.15.2, Linux Ubuntu 18.04]
 - Neuron Version [e.g. 0.28.0]
 - Block Number: [Check that from `Overview` - `Blockchain Status` for v0.29.0-rc2 or before, or hover onto the left bottom syncing status area for v0.29.0 and later]

**Steps To Reproduce**

**Screenshots**
![Screenshot_20210904-081152_Chrome](https://user-images.githubusercontent.com/89602488/132132094-3916cdc1-91e4-4749-a57a-011560b7ad17.jpg)

**Comment by CryptoGumby** [comment]
Would it be possible to add a real time CKB quote to the DAO and show the value of the locked and unlocked portion as well as a overall total?

Thank you,
Dean

**Comment by Keith-CY** [comment]
It's not possible to introduce price because external APIs are not allowed for security, but this function will be delivered with a portfolio tracker https://github.com/Magickbase/ckb-wallet-and-explorer/issues/29
