### ISSUE TITLE
Receiving from Australian exchange not working

### ISSUE THREAD

**Issue by notegridy** [nervosnetwork/neuron#2090]
**Describe the bug**
Have from CKB from Swyftx, have tried creating two wallets, for the withdrawal from the exchange. copying them in manually, QR code and cutting and pasting has not worked. 

**Environment (please complete the following information):**
 - Mac OS Big Sur 11.5.2
 - Neuron Version 0.36.0
 - Block Number: 5,307,874

**Steps To Reproduce**

Swyftx Exchange
![557295EB-CFEF-43C5-92FD-7494D343B5B7_1_102_o](https://user-images.githubusercontent.com/90373206/132629835-d9796fcb-f34f-42cd-a113-e152a551fe61.jpeg)
go to CKB
go to withdraw
name the withdrawal address (can be anything)
input the address

this always comes up with 'this is not a recognised CKB wallet address

any help would be great!

**Comment by kellyshang** [comment]
Hi @notegridy , maybe you'd better ask the Swyftx's customer service what rule of the CKB address they are using.
