### ISSUE TITLE
Unable to sync mainet after reset pc

### ISSUE THREAD

**Issue by tbt700** [nervosnetwork/neuron#2091]
**Describe the bug**
Unable to sync mainet after reset pc and i already imported my using my phrase my account balance is zero and it says connecting  but didnt even connect or sync .
please help

**Environment (please complete the following information):**
 - OS & Version: [e.g. Windows 10, macOS 10.15.2, Linux Ubuntu 18.04]
 - Neuron Version [e.g. 0.28.0]
 - Block Number: [Check that from `Overview` - `Blockchain Status` for v0.29.0-rc2 or before, or hover onto the left bottom syncing status area for v0.29.0 and later]

**Steps To Reproduce**

**Screenshots**

**Comment by kellyshang** [comment]
Hi @tbt700 , please upload the debug info from `Help` - `Export Debug Information` and we will check what happened.

**Comment by tbt700** [comment]
hi there I already fix this by installing windows file

**Comment by tbt700** [comment]
after installing windows visual c++

>

**Comment by kellyshang** [comment]
Cool!
