### ISSUE TITLE
Syncing wont stop - 

### ISSUE THREAD

**Issue by DanWeik73** [nervosnetwork/neuron#2092]
Neuron wallet keeps syncing but never showing tokens in Wallet. Gets to 99 % and goes down. I invested in tokens to this project and I am unable to receive them in my wallet.  I need help as soon as possible.

**Comment by kellyshang** [comment]
Hi @DanWeik73 , could you have a try to `fully rebuild index`(Which can be found from the `Settings` window - `General` ) and then see if it works when sync finalized?

![image](https://user-images.githubusercontent.com/28836185/133183563-9bd718dd-99a0-4a01-9d81-d0fc86e2a4d2.png)
