### ISSUE TITLE
Can't Sync

### ISSUE THREAD

**Issue by Andym7** [nervosnetwork/neuron#2096]
**Describe the bug** (Please enter details, the more detail the better)
been trying for many days to sync my Neuron wallet, keeps getting stuck same place. I have tried clear cache many times both fully and refresh, same think stops at 96.18 was higher before I think.
[neuron_debug_1631623666488.zip](https://github.com/nervosnetwork/neuron/files/7162076/neuron_debug_1631623666488.zip)

I have upgraded to the newest version 

**Debug info** (Please upload the debug info from `Help` - `Export Debug Information`)

**Screenshots** (If applicable, add screenshots to help explain your problem.)

**Comment by kellyshang** [comment]
Hi @Andym7 , according to the debug info there might be some broken to your local ckb node data, may be you need to mannually delete the whole ckb data and re-sync.
The data folder is: %APPDATA%\Neuron\chains\mainnet\data
