### ISSUE TITLE
Balance not showing

### ISSUE THREAD

**Issue by AysbergICE** [nervosnetwork/neuron#2097]
The amount received in my account is visible, but the balance is showing as zero. And I can't send this amount.
![Screenshot_12](https://user-images.githubusercontent.com/38535116/133283418-e12efbf9-aaf2-44ad-8c87-c692f827982d.jpg)

thats my account txid: https://explorer.nervos.org/address/ckb1qyqdfs73mfrw24x5qkyexeg7zcrchv7zyqwsanc9ut

**Comment by kellyshang** [comment]
Please submit the issue according to the issue template -- especially upload the debug info please.
