### ISSUE TITLE
Wallet Password

### ISSUE THREAD

**Issue by dastley3** [nervosnetwork/neuron#2103]
Is there a way to reset / change password on account. 

I currently can not stake/ move my CKB in my wallet as it does not recognise what I set up as my password. 

My CKB is just stuck. There does not seem to be an option on creating / edting my password to change it. 

I have my key for my wallet but that not does not seem to help me.

Thanks in advance.

**Comment by kellyshang** [comment]
Hi @dastley3 , you can re-import the Wallet Seed then you can re-set your password with a new wallet. (the old wallet can be deleted directly)

**Comment by dastley3** [comment]
> Hi @dastley3 , you can re-import the Wallet Seed then you can re-set your password with a new wallet. (the old wallet can be deleted directly)

Thank you Kelly for responding. Do i just delete the whole Neuron app of my macbook and reinstall it and recover my wallet this way. Or can i do it from the existing wallet and just create a new wallet and import key. Thank you again.

**Comment by kellyshang** [comment]
Hi @dastley3 , no need to delete the whole Neuron app. You can see the related items  from the menu of `Wallet` - `Import Wallet` - `Import Wallet Seed` to re-import, and see `Wallet` - `Delete Current Wallet` to delete the wallet you don't need.

**Comment by dastley3** [comment]
@kellyshang  Thank you so much for your help. it worked perfect and now fully staked :)

**Comment by Faggione** [comment]
Good Morning!
@kellyshang I have the same problem, I followed the step by step above, I imported the wallet with my seed, but the balance did not appear, it was zero!

And to delete the old wallet, it asks for the password that I forgot or was it a Neuron bug

how can i reset my password?

**Comment by Faggione** [comment]
Good Morning!
@kellyshang I have the same problem, I followed the step by step above, I imported the wallet with my seed, but the balance did not appear, it was zero!

And to delete the old wallet, it asks for the password that I forgot or was it a Neuron bug

how can i reset my password?

**Comment by kellyshang** [comment]
@Faggione 
> I imported the wallet with my seed, but the balance did not appear, it was zero!

The balance should be appear when the Neuron's sync been finalized, which can be indicated from the left bottom of the Neuron.

>how can i reset my password?

Now deleting wallet needs password. You can re-import your seed to create a wallet with new password.

**Comment by DannielTM** [comment]
I imported the wallet (a hardware wallet), waited for 100% synchronization but my balance is still zero. What I need to do? :(

**Comment by Keith-CY** [comment]
> I imported the wallet (a hardware wallet), waited for 100% synchronization but my balance is still zero. What I need to do? :(

Hi @DannielTM would you mind opening a new issue for tracking your case specifically? We have an issue template that leads you to upload debug information so we can figure out what happened under the hood.

Open a new issue by https://github.com/nervosnetwork/neuron/issues/new?assignees=Keith-CY&labels=bug&projects=&template=synchronization-issue.yml&title=%5BSynchronization%5D+%2A%2Abrief+description%2A%2A
