### ISSUE TITLE
Attempting to withdrawal NFT from Neuron results in unknown out point error.

### ISSUE THREAD

**Issue by jordanmack** [nervosnetwork/neuron#2109]
**Describe the bug** (Please enter details, the more detail the better)
Trying to send an NFT from Neuron to another address results in an unknown out point error. 

I am using an external CKB node running v0.43.2. I tried clearing the cache and rebuilding the indexer data from within Neuron, but it did not help. I also tried deleting the node data and doing a full chain resync with a cache clear and rebuild, but the error still persists.

**Debug info** (Please upload the debug info from `Help` - `Export Debug Information`)
[neuron_debug_1632429284964.zip](https://github.com/nervosnetwork/neuron/files/7220707/neuron_debug_1632429284964.zip)

**Screenshots** (If applicable, add screenshots to help explain your problem.)
![20210923133119](https://user-images.githubusercontent.com/37931/134579802-7d955a20-04e6-471b-b405-405067bcb9fc.png)

**Comment by yuche** [comment]
The code hash of Neuron's NFT cell deps is outdated. This will be fixed in the next release.
