### ISSUE TITLE
Nervos wallet wont update after new update

### ISSUE THREAD

**Issue by mobilewebpage** [nervosnetwork/neuron#2116]
Ckb /nervos wallet wont sync just says connecting since last update today 

[neuron_debug_1632691423727.zip](https://github.com/nervosnetwork/neuron/files/7232288/neuron_debug_1632691423727.zip)

**Comment by burnbytes** [comment]
Hi , I had the same problem, its a problem with the new update wallet.
I had to install the old version again, and next to sync some hours later, you will have you ckb again.
