### ISSUE TITLE
Block not Syncing above 0% 

### ISSUE THREAD

**Issue by ruhaan626** [nervosnetwork/neuron#2117]
So I am using MacOS and I was looking for updating the Neuron wallet, now it is not syncing and is stuck at 0%, am I missing something?

**Comment by burnbytes** [comment]
Hi , I had the same problem, its a problem with the new update wallet.
I had to install the old version again, and next to sync some hours later, you will have you ckb again.

**Comment by bradtho** [comment]
> Hi , I had the same problem, its a problem with the new update wallet. I had to install the old version again, and next to sync some hours later, you will have you ckb again.

For me it required rolling back both the Wallet and CKB tool - running MacOS Big Sur 11.15.2

Neuron Version: 0.36.0
CKB Client Version: v0.35.2

**ckb_v0.43.2_x86_64-apple-darwin**
    ckb-cli 0.43.0 (aa18f6c 2021-06-22)
    ckb 0.43.2 (db778ec 2021-08-09)

**Comment by brstra** [comment]
I've just run into this issue too. I solved it by restarting Neuron app AND by quitting from 'ckb' and 'ckb-indexer' in Activity Monitor. It will re-start automatically upon next time you run Neuron. No re-install is needed.

**Comment by kellyshang** [comment]
@ruhaan626 , could you please upload the debug info zip file from `Help` - `Export Debug Information`?

**Comment by kellyshang** [comment]
Will close this issue as there is no more news. You can report a new one if still any problems.
