### ISSUE TITLE
无法同步。 更新0.100版本后

### ISSUE THREAD

**Issue by hhaovr** [nervosnetwork/neuron#2119]
**Describe the bug** (Please enter details, the more detail the better)

**Debug info** (Please upload the debug info from `Help` - `Export Debug Information`)

**Screenshots** (If applicable, add screenshots to help explain your problem.)

**Comment by yuche** [comment]
Export Debug Information

麻烦提供一下 zip 文件

**Comment by hhaovr** [comment]
提供什么zip。是下载的钱包吗?



---原始邮件---
发件人: "Yu ***@***.***&gt;
发送时间: 2021年9月29日(周三) 上午10:07
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [nervosnetwork/neuron] 无法同步。 更新0.100版本后 (#2119)




 
Export Debug Information
 
麻烦提供一下 zip 文件
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by kellyshang** [comment]
@hhaovr 发布了 [Neuron v0.100.1](https://github.com/nervosnetwork/neuron/releases/tag/v0.100.1)，麻烦您有空升级一下看看同步是否生效了？

**Comment by hhaovr** [comment]
现在可以同步了&nbsp; &nbsp;



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年9月29日(周三) 晚上7:09
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [nervosnetwork/neuron] 无法同步。 更新0.100版本后 (#2119)




 
@hhaovr 发布了 Neuron v0.100.1，麻烦您有空升级一下看看同步是否生效了？
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
