### ISSUE TITLE
CKB not in my wallet?

### ISSUE THREAD

**Issue by gilsilverbird** [nervosnetwork/neuron#2125]
**Describe the bug** (Please enter details, the more detail the better)
I sent CKB from Binance account into Neuron wallet. Has not showed up in wallet. Transaction completed on Binance.

**Debug info** (Please upload the debug info from `Help` - `Export Debug Information`)

**Screenshots** (If applicable, add screenshots to help explain your problem.)

**Comment by gilsilverbird** [comment]
I am wondering where my CKB went. i sent it from my Binance account and it has not arrived. the CKB is no longer in my binance account. 0.35.1 version. 
gilsilverbird@gmail.c
<img width="1440" alt="Screenshot 2021-10-03 at 9 03 32 PM" src="https://user-images.githubusercontent.com/90421227/135767876-5ae2e7ac-c3ba-43e3-a147-466ced07dd22.png">
o
<img width="1440" alt="Screenshot 2021-10-03 at 9 03 35 PM" src="https://user-images.githubusercontent.com/90421227/135767880-b4798779-71e1-47ea-9f54-6557d4203dac.png">
m

**Comment by gilsilverbird** [comment]
I have a MACBOOK PRO

**Comment by kellyshang** [comment]
Hi @gilsilverbird, your Neuron has not complete the sync process ( can check from the left bottom of the Neuron), please make sure your Neuron's sync has been finalized before check your balance.

BTW, you can also check the balance of the address from the explorer - https://explorer.nervos.org/
