### ISSUE TITLE
Neuron Wallet 0.100.1 update sync problem

### ISSUE THREAD

**Issue by srrmike** [nervosnetwork/neuron#2126]
I had Neuron Wallet 0.36.0, running OS X 11.5.2 with no problems.  It said update was available 0.100.1. Update went well and resynced wallet and all was as expected. Now when I open the Wallet. The Sync is at 0% and says "sync not started yet". If I let it sit nothing changes.  If I go to preferences and clear the Cache. It will sync for 1 or 2 hours  and my wallet is fine.  I have cleared Cache and got wallet working this way serveral times. 

I have two computers running same OS X. Same wallets, same update, with same results.

**Comment by yuche** [comment]
Please upload the debug info zip file from Help - Export Debug Information

**Comment by COMHOME** [comment]
Got the same problem, here the log:
[neuron_debug_1633375975793.zip](https://github.com/nervosnetwork/neuron/files/7280782/neuron_debug_1633375975793.zip)

**Comment by srrmike** [comment]
Here is the bug report from my home computer. It didn't sync when I opened it tonight.
[neuron_debug_1633476777272.zip](https://github.com/nervosnetwork/neuron/files/7289826/neuron_debug_1633476777272.zip)

**Comment by kellyshang** [comment]
[v0.100.2](https://github.com/nervosnetwork/neuron/releases/tag/v0.100.2) released.

**Comment by matejlajgut** [comment]
Hi, I'm also having a sync problem. On one PC, everything works like it has for 2 years. Now I downloaded appiimage Neuron v0.103.2 and it won't start syncing the node at all. I use Linux Mint 21 (new installation). I tried clearing the cache - it didn't help. Could you please help me?
[neuron_debug_1661528923847.zip](https://github.com/nervosnetwork/neuron/files/9434576/neuron_debug_1661528923847.zip)

**Comment by yanguoyu** [comment]
`Neuron`  can't start ckb node because there is no `ckb.exe`.

<img width="802" alt="image" src="https://user-images.githubusercontent.com/12881040/187009656-494dae44-f616-4715-a5de-deccb26cf4b4.png">
@Cedar67 Do we have linux test environment to recurring it?

**Comment by Keith-CY** [comment]
> `Neuron` can't start ckb node because there is no `ckb.exe`.
> 
> <img alt="image" width="802" src="https://user-images.githubusercontent.com/12881040/187009656-494dae44-f616-4715-a5de-deccb26cf4b4.png">
> 
> @Cedar67 Do we have linux test environment to recurring it?

Neuron's behavior varies on different Linux distributions so we'd better test it on Mint 21 in Virtualbox(we have a Linux test environment but it's not Mint).

And the version of Mint does affect, I have handled an issue that only happened on Mint 19.

**Comment by matejlajgut** [comment]
@yanguoyu yes this is no ckb.exe..
but on the other PC where it works for me (Linux Mint 20.3), I have these 2 processes running in the process manager. (I am attaching a picture). On the new PC where I have Linux mint 21, the two processes do not start and the synchronization does not start either. I don't know how to get it to work so I can use the wallet.
![Snímka obrazovky z 2022-08-29 07-31-52](https://user-images.githubusercontent.com/78679863/187130293-9fbed127-d30a-469d-b878-0c5dbb79bc40.png)

**Comment by yanguoyu** [comment]
@matejlajgut I will  download and install mint 21 on my vmware to find what causes this problem. I will update this after I find something.

**Comment by matejlajgut** [comment]
@yanguoyu thank you.

**Comment by yanguoyu** [comment]
@matejlajgut I found maybe the default `openssl` version caused it.
Linux mint 21 `openssl` version is 3.0.2. Linux mint 20.3 `openssl` version is 1.1.1f.
I'm trying to downgrade `openssl` to 1.1.1 on Linux mint 21.

**Comment by yanguoyu** [comment]
@Keith-CY https://github.com/nervosnetwork/ckb/issues/3560#issuecomment-1231219127
Because the ckb binary file in `Neuron` is downloaded from https://github.com/nervosnetwork/ckb/releases.
So shall we only support the platforms in [tier 1 and 2](https://github.com/nervosnetwork/ckb/blob/develop/docs/platform-support.md)

**Comment by Keith-CY** [comment]
> @Keith-CY [nervosnetwork/ckb#3560 (comment)](https://github.com/nervosnetwork/ckb/issues/3560#issuecomment-1231219127) Because the ckb binary file in `Neuron` is downloaded from [nervosnetwork/ckb/releases](https://github.com/nervosnetwork/ckb/releases). So shall we only support the platforms in [tier 1 and 2](https://github.com/nervosnetwork/ckb/blob/develop/docs/platform-support.md?rgh-link-date=2022-08-30T06%3A51%3A37Z)

I think supporting tier 3 or not totally depends on CKB binary so we can simply follow the metrix of CKB binaries.

We'd better elaborate on this case in an independent, pinned issue and append a simple todo list for users to check by themselves if their platforms are in tier 3, solutions mentioned in https://github.com/nervosnetwork/ckb/issues/3560#issuecomment-1231219127 are preferable too.

**Comment by yanguoyu** [comment]
@matejlajgut I have tried to install openssl 1.1.1q and `Neuron` is starting sync now. These are my installation steps, hope to help you.
1. download openssl1.1.1q sourcecode from https://www.openssl.org/source/
2. unzip sourcecode and `cd openssl-1.1.1q`
3. sudo apt-get install libz-dev
4. sudo apt-get install gc++
5. sudo ./config --prefix=/usr/local/openssl --openssldir=/usr/local/openssl shared zlib
6. sudo make
7. sudo make test
8. sudo make install
9. cd /etc/ld.so.conf.d/
    
    sudo nano openssl-1.1.1k.conf

    Add `/usr/local/ssl/lib`

    Save and exist.
10. sudo ldconfig -v
11. sudo nano /etc/environment

    Add `/usr/local/openssl/bin` to the path end. Add result like this: `PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/local/ssl/bin"`. Save and exist.
12. source /etc/environment

Here is the result.
<img width="1162" alt="image" src="https://user-images.githubusercontent.com/12881040/187640335-669d317e-3ae9-4b67-8eb8-1f7821a7fd08.png">

**Comment by matejlajgut** [comment]
@yanguoyu thank you but 
I don't know why, but when I enter the command: sudo apt-get install gc++ I get error messages (I'm attaching a txt.file).
I tried to continue but the sync failed. Obviously, this point will be problematic. I have a fresh install of Linux and I don't know why the error is there.
[error message.tar.gz](https://github.com/nervosnetwork/neuron/files/9471608/error.message.tar.gz)

**Comment by yanguoyu** [comment]
> @yanguoyu thank you but I don't know why, but when I enter the command: sudo apt-get install gc++ I get error messages (I'm attaching a txt.file). I tried to continue but the sync failed. Obviously, this point will be problematic. I have a fresh install of Linux and I don't know why the error is there. [error message.tar.gz](https://github.com/nervosnetwork/neuron/files/9471608/error.message.tar.gz)

The error message looks like your system has installed gc++, maybe you can skip this step.
If you can't install openssl 1.1.1q, you can install mint 20.3. It works without any more extra operation.
