### ISSUE TITLE
Wallet stopped syncing midway,  tried clearing cache and restaring the sync, it comes to the same point and stalls.

### ISSUE THREAD

**Issue by Coldheat22** [nervosnetwork/neuron#2127]
**Debug info** (Please upload the debug info from `Help` - `Export Debug Information`)

I have exported the debug information.   there are 4 files in the zip file,  should i attach the entire zip file. or a specific log file ?

![image](https://user-images.githubusercontent.com/66181207/135813807-5abc4626-e0a4-4ac3-9c09-f6de241e35ca.png)

![image](https://user-images.githubusercontent.com/66181207/135814236-fbc5c2e0-bd5e-41cf-887d-62f6596eeccc.png)

**Comment by Coldheat22** [comment]
to add i have downloaded the version 
![image](https://user-images.githubusercontent.com/66181207/135813713-202322c7-491d-43d7-bc2d-0c9d42a261bf.png)

**Comment by yuche** [comment]
drag and drop the entire  zip file to input box and click comment button

**Comment by Coldheat22** [comment]
Thanks , Done

[(W514046)ClientReports.Zip](https://github.com/nervosnetwork/neuron/files/7277813/W514046.ClientReports.Zip)

**Comment by Coldheat22** [comment]
Thanks , 
[neuron_debug_1633332583804.zip](https://github.com/nervosnetwork/neuron/files/7277823/neuron_debug_1633332583804.zip)
