### ISSUE TITLE
Wallet Update v 035 to v 100, 100.1

### ISSUE THREAD

**Issue by freespirit8614** [nervosnetwork/neuron#2143]
**Describe the bug** (Please enter details, the more detail the better)
I don't know what is going on over there as far as moving from v 035 to 100 and 100.1. (have been unable to do update 100.2 so far)
I have been trying to complete this update for over 6 days now. 

I have cleared cache three times. Furthest I have been able to get ever in the synch is 5, 402,093.
Currently it is stuck going between 5,134,053 and 5,134,054, Back and forth, Back and forth between 053 and 054 for over an hour and a half now. VERY frustrating.
Currently it is showing 5,134,054/5, 516,293. Right side of slash mark keeps going up and left side of hash stays stuck bouncing betwee 5,134,053 and 5,134,054

As others have commented
Synch of blocks on right side of the synching always goes so fast in relation to actual wallet blocks synching and then percentage keeps dropping until I have to restart the app for the wallet and start over.

In addition

It crashes my computer, (Windows 7) on multiple crash report:

MEMORY MANAGEMENT
IRQL_NOT_LESS_OR_EQUAL
SYSTEM SERVICE EXCEPTION
PAGE FAULT
INTERRUPT EXCEPTION NOT HANDLED
CLOCK INTERRUPT
DRIVER NOT LESS BUT EQUAL TO

The current Neuron synch upload is my very WORST EVER wallet experience ever. It has been the longest, most tedious, most unsuccessful, tiring, frustrating, wallet of any of the 20 different investments I have made in the future of blockchain technology.

 And if you over at NERVOS intend to be the leader in the Next Generation Blockchain, and I have heard GREAT THINGS ABOUT YOU, YOUR TECHNOLOGY, YOUR FUTURE in the Next GEneration Blockchain space. this wallet SERIOUSLY has to get fixed. The other end user experience so far is AWFUL.

Hope you can get it fixed soon before people like me, early investors who really WANT to believe in you and stick with you long term, don't get so frustrated that they cash up and leave you for other opportunities in this space.

And it is 2 hours now and the synch is still stucl moving between 5, 134,054/5,582,293 and 5,134,053/ 5,584, 293.....After six days of this, rebooting your app every 5-15 minutes, with no success or completion, I have about had it....

**Debug info** (Please upload the debug info from `Help` - `Export Debug Information`)

**Screenshots** (If applicable, add screenshots to help explain your problem.)

**Comment by kellyshang** [comment]
Hi @freespirit8614 , firstly apologize for the inconvinience. 
As an POW chain and for the safety to your property's reasons, the CKB node is now bundled in the Neuron and will be launched by default when start Neuron, so Neuron is connect to the bundled CKB node by default but not from a centralized rpc node. Thus the multi-process may stall the computer's performance.
Even so, you can connect to a remote centralized rpc node which you think is safe thus the bundled ckb node won't be launch and may have less impact on your PC's performance.

So that we can check the problem more accurately:
1. Could you provide your PC's Computer configuration, including how many CPUs & Memory of your PC?
2. Could you help upload your Debug info zip file from the menu `Help` - `Export Debug Information`?
3. When it crash, could you please provide the screenshot of the task manager (especially expand the `Neuron` process) as an evidence to us?

**Comment by freespirit8614** [comment]
Hi Kelly

Thank you for your assistance resolving this matter.

I have attached 2 photos and the debug zip file from my NEURON DAO WALLET information as requested.

Just so you know this wallet remains stuck now at the 053 and 054 synching still going back and forth back and forth and not getting passed that point.

We have 361 of 465 gigs left free with the wallet open and stuck in synching.

Let me know if there is any more information you require to solve this synching problem.

Keep in mind I am now at v 0100.2 version uploaded, and have already cleared the cache 4 X back to zero and started again with the Neuron wallet. Farthese I got in the synch was about 400K more than the present location in the synch.

Thanks for your help. I look forward to getting this synching issue resolved.

MA

-- 
  Mary Anne Dorward
  ***@***.***

**Comment by freespirit8614** [comment]
Here are the documents you requested to follow up on this issue.

[neuron_debug_1634700317032.zip](https://github.com/nervosnetwork/neuron/files/7378150/neuron_debug_1634700317032.zip)


General Computer Information Photo as requested
(https://user-images.githubusercontent.com/92659079/138028756-e1e9530f-664b-4937-a954-1518af1f40b0.PNG)

NERVOS WALLET DAO PHOTO 1 stuck at 5 134 154
](https://user-images.githubusercontent.com/92659079/138028762-6c3d99b3-b07a-4b70-aea5-064e35239d2b.PNG)

NEURON WALLET DAO PHOTO 2 Stuck at 5 134 053
](https://user-images.githubusercontent.com/92659079/138028873-510ec568-bc13-4b0b-b928-786b872e8182.PNG)

Crash REPORT. Note this was one of MANY DIFFERENT unexpected shut down of my computer during the now ten days of trying to synch from v 0.035.0 to v 0.100.0, 0.100.1 and 0.100.2. Currently I am at v 0.100.2

**Comment by freespirit8614** [comment]
Crash repor
[WINDOWS UNEXPECTED SHUT DOWN ERROR MESSAGE.docx](https://github.com/nervosnetwork/neuron/files/7378166/WINDOWS.UNEXPECTED.SHUT.DOWN.ERROR.MESSAGE.docx)
t

**Comment by freespirit8614** [comment]
hi KellyShang,

Thank you for looking into this.

Before I screw anything up further let me just confirm:

So when I type in %AppData%\Neuron\chains\mainnet\data as advised I see the following. See screenshot.

![NEURON Dara folder](https://user-images.githubusercontent.com/92659079/138185727-d0a02ae8-5e6c-4cb0-8049-f26f9d81fa47.PNG)

So do I simplu delete EVERYTHING in that folder or just PART of it?

2) Next when I use your install full CKB node data, synched to block height 5662203, How EXACTLY do I do that? I am not experienced in these matters and a step 1,2,3,4 would be most helpful so I get it crorectly installed.

I will wait to hear from you before I go charging into deleting or adding anything so I don't make a royal mess off it! Lol. 

Thanks for your help. Much appreciated.

Thanks.

**Comment by freespirit8614** [comment]
Thank you Kelly Shang. I am downloading now and it looks like it will take some time in the zipping of the file. 
However once downloaded, I will follow your directions exactly as written in your message above. 
I will also respond again when all is completed or if I have any further issues we can solve together.
Your help is greatly appreciated. Thanks.

**Comment by freespirit8614** [comment]
Well I downloaded the zip file, unzipped it and saved the files. I then asked it to replace and save.
I opened the wallet again and wallet opened BUT started NOT at your block height of 5,662,203 but reverted back to where it stuck before at 5,134,054 block height.
I have attached screenshots of both the download process unzipping the RAR file and also where it is stuck now.
NOTE
The wallet says it is still synching in green under default node, 
Screen also says it is Block Synched 100%. 5,134,054/5/134,054, but the blocks are stuck at 5,134,054 and not increasing. 

However,  they are no longer going back and forth between 5,134,053 and 5,134,054 so that is some progress I suppose?

Well it is not progressing at all now, after waiting a half an hour longer, even though wallet still says synching it appears to be frozen. 

And also, none of my Nervos DAO staking rewards show up at all, where as before in my previous screenshots I sent you, the DAO Wallet staking rewards were stuck not fully loaded at 700 something.

Did I do something incorrectly? 
What do you suggest I do now?
Thanks.
![UNZIP PROCESSING](https://user-images.githubusercontent.com/92659079/138216595-afd8cb22-f5ae-4e0d-b26a-8797af8b4673.PNG)
![Data Unzipping file](https://user-images.githubusercontent.com/92659079/138216612-a9f9bb97-267c-4c9f-b780-101a8b1f59da.PNG)
![AFTER SUPPORT TASKS COMPLETED RE LAUNCH NERVOS NEURON WALLET](https://user-images.githubusercontent.com/92659079/138216620-b8719ddb-1163-4386-8a43-be68c4c3814b.PNG)

**Comment by kellyshang** [comment]
Have a try to clear cache and see if it works:
![image](https://user-images.githubusercontent.com/28836185/138217755-d2cb7dbf-b936-400e-9618-a5b8143f8bfd.png)

**Comment by freespirit8614** [comment]
OK still not synching past where it was after 30 minutes.

I will try double clearing cache from 0.

If not doing anything after 10 minutes will send debug again to you. 

Stand by.

**Comment by kellyshang** [comment]
Better to keep it open to let it run till the sync been finalized.
If you shut it off the sync will be stopped untill the next time you start it.

**Comment by freespirit8614** [comment]
SYNCH BLUE SCREEN Crash Number 3. 15.5 hours intocurrent synch. 

Blue screen error message different on blue screen crash number 3: MEMORY_MANAGEMENT

Restarted Synch now at 3371510/3373691 (see attached image)

I don't know what else to do at this point but keep trying to nudge the synch along again after each crash.

Your update file  block height 5662203 is obviously a LONG way away from where I am now. But unless I hear back form you I will keep trying to get to that block height synch in your restore file of 5662203, even though we both decided I had to try both a partial and full clear of cache back to 0 zero..

Any other ideas from your tech end?


![SYNCH PROGRESS after Blue Screen Crash number 3 at 15 5 hours synching](https://user-images.githubusercontent.com/92659079/138374034-d2ba09f5-c137-4031-8c29-8556edba147f.PNG)

Thanks!

BLUE SCREEN CRASH number 4 at 2:20 PM approx 18 hours.

CRASH MESSAGe: IRQL_NOT_LESS_OR_EQUAL
Also the blue screen this time said to disable BIOS memory options such as cacheing or shadowing. Suggested restarting in safe mode and disabling any recently installed hardware or software.

So where does that leave us now?

**Comment by freespirit8614** [comment]
BLUE SCREEN CRASH number 4 at 2:20 PM approx 18 hours.

CRASH MESSAGe: IRQL_NOT_LESS_OR_EQUAL
Also the blue screen this time said to disable BIOS memory options such as cacheing or shadowing. Suggested restarting in safe mode and disabling any recently installed hardware or software.

So where does that leave us now?

**Comment by freespirit8614** [comment]
![SYNCH STATUS after Crash number 4 at approx 18 hours into synch](https://user-images.githubusercontent.com/92659079/138379100-341f05a9-1e92-4ee0-8732-b0e512601315.PNG)

**Comment by freespirit8614** [comment]
Thanks. I will look into this. 

Should I simply stop trying to synch the Nervos NEURON wallet at this time then?

And leave this support ticket OPEN for now?

I am very concerned that without the full synch, my CKB tokens and everything in the NEURON wallet DAO staking will be lost. How can we deal with this issue?

Your thoughts? Thanks kellyshang.

**Comment by freespirit8614** [comment]
NEW ISSUE:

Have now tried to install the new version 0.100.2 NEURON Wallet for Windows from the GitHub for the NEURON WALLET on an ENTIRELY DIFFERENT COMPUTER and v 0.100.2 won't even open. I get the error message below. Can you explain this error message? I obviously cannot even proceed to try a different computer if I cannot get the new version of the NEURON wallet to even load from github.

Thanks KellyShang.

Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	Neuron-v0.100.2-setup.exe
  Application Version:	0.100.2.0
  Application Timestamp:	5c157f86
  Fault Module Name:	System.dll
  Fault Module Version:	0.0.0.0
  Fault Module Timestamp:	5c157efa
  Exception Code:	c0000005
  Exception Offset:	00001581
  OS Version:	6.1.7601.2.1.0.256.48
  Locale ID:	5129
  Additional Information 1:	0a9e
  Additional Information 2:	0a9e372d3b4ad19135b953a78882e789
  Additional Information 3:	0a9e
  Additional Information 4:	0a9e372d3b4ad19135b953a78882e789

Read our privacy statement online:
  http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0409

If the online privacy statement is not available, please read our privacy statement offline:
  C:\Windows\system32\en-US\erofflps.txt

**Comment by freespirit8614** [comment]
KellyShang

I am trouble shooting the FIRST computer now with one of the links you sent me; This one:

https://www.drivereasy.com/knowledge/irql_not_less_or_equal-windows-7-solved/

Thanks for that assistance with the trouble shooting link. I had not realized you sent one specific to Windows 7 operating system. My bad.

I am running the sfc scan now and will write again after I have gone through all the prompts, done what is asked for any and all error messages, and then see if NEURON wallet will synch using your download zip file you sent earlier in this process.

THis still does not explain why the NEURON wallet would not even download on a DIFFERENT WINDOWS computer running Windows 7. Can you figure that one out?

I won;t give up.

**Comment by freespirit8614** [comment]
Thank you for this analysis. Very thought provoking.

BTW, my wallet now is syncing beautifully on the other windows computer now. Just to be sure before I got back to you with a report,  I now have tried syncing it over several different days, including today, and always syncs just fine. What a relief!

I agree with you that the overall CKB staking experience can be improved.

A automatic compound model is a great idea! And yes juicy for a long term holder like me!
The token economy of the future is still a bit unclear to me, and it obviously is evolving every single day from the tech and build perspective.
With all the hype about fad cryptos these days, (i mean like the recent "squid coin"?!) those of us investing in the fundamental blockchain ecosystem for long term hold and looking forward to a full token economy are still more in the minority.
However I do appreciate the DAO wallet hedging a bit of inflation with giving a 3% reward for my investment long term
I am trying to manually compound in some other tokens I am invested in and it is tedious and time consuming to try to do it by hand every week or so. But the compound model really does add up. 
If CKB could do something automatic compound and then you on your end in the NERVOS DAO calculate that automatically, then it would be very attractive to future investors I think. 

In other staking experiences, they make it so hard to understand how to actually get back and claim your tokens once the staking period is completed, that it has been very frustrating for me personally.

I will look into OHM and sOHM and also Tokemak and Curve as you suggest for more clarity on  what is currently going on in the staking models of the paradigms you think are great for the token economy of the future. These references are great for my own individual education. Thanks for that. Really appreciate it. 

Always more to learn for ALL of us wherever we are in this new blockchain ecosystem universe right?!

Are there any other things you think from your perspective that I should consider before we close this support ticket? I don't want to be taking up your time when you could be helping other people.

**Comment by kellyshang** [comment]
>Always more to learn for ALL of us wherever we are in this new blockchain ecosystem universe right?!

Yes I agree with you.

>Are there any other things you think from your perspective that I should consider before we close this support ticket?

Seems there is no other usage problem about Neuron for you, I will close this ticket for now :)
