### ISSUE TITLE
Sync warning displays before the sync status is visible.

### ISSUE THREAD

**Issue by jordanmack** [nervosnetwork/neuron#2148]
**Describe the bug** (Please enter details, the more detail the better)
The screenshot below was provided by a user who was confused by the sync message given. It says not to do anything until the sync has been completed, but since he has not created a wallet yet, the sync status cannot be seen.

**Screenshots** (If applicable, add screenshots to help explain your problem.)
![unknown](https://user-images.githubusercontent.com/37931/138035202-929de725-8eb5-4d97-91b1-c853a2542dba.png)

**Comment by kellyshang** [comment]
Sorry for the misleading. The message was meaned to better not do any operation related to tx or clearing cache before sync finalized.
We will fix it in next version.

Thanks for your report.

**Comment by kellyshang** [comment]
[Neuron v0.101.0](https://github.com/nervosnetwork/neuron/releases/tag/v0.101.0) was released.

**Comment by jordanmack** [comment]
> [Neuron v0.101.0](https://github.com/nervosnetwork/neuron/releases/tag/v0.101.0) was released.

This issue is still present in v0.101.0.

**Comment by kellyshang** [comment]
Just adjusted the warning text a little bit with `transaction related`.

> > [Neuron v0.101.0](https://github.com/nervosnetwork/neuron/releases/tag/v0.101.0) was released.
> 
> This issue is still present in v0.101.0.
