### ISSUE TITLE
0.100.1 for Windows 10 not syncing

### ISSUE THREAD

**Issue by mick-hub** [nervosnetwork/neuron#2149]
I cant get my Neuron wallet to sync. Help please.

Windows 10

I Downloaded and ran vc_redist.x64

Bug Info:
[neuron_debug_1634763721279.zip](https://github.com/nervosnetwork/neuron/files/7384305/neuron_debug_1634763721279.zip)

**Comment by mick-hub** [comment]
I'll try it on another pc with a faster network speed and report back.

**Comment by mick-hub** [comment]
No luck,tried it on another pc and its the same problem.Think iv lost my CKB

**Comment by kellyshang** [comment]
Hi @mick-hub , can you please help upload the debug info again and we will see what problem is.

BTW, you can check your wallet address on the explorer (https://explorer.nervos.org/ ) to check if your CKB is there or not, if yes then it's on the chain and will not lost if you have the priv-key.

If the address is correct with CKB inthere and your Neuron has been synced completed but the CKB still not show up, you can  try to clear cache (in `Settings` window) and wait to see if it works.

**Comment by Minnsy88** [comment]
> I cant get my Neuron wallet to sync. Help please.
> 
> Windows 10
> 
> I Downloaded and ran vc_redist.x64
> 
> Bug Info: [neuron_debug_1634763721279.zip](https://github.com/nervosnetwork/neuron/files/7384305/neuron_debug_1634763721279.zip)

Hi, I'm not very technically minded but whatdo you do/how do you run the debug Zip files??

**Comment by kellyshang** [comment]
@Minnsy88 You can export the debug info from the menu of `Help` - `Export Debug Information`, then drag into the comment input box to upload it.

**Comment by kellyshang** [comment]
I will close this issue since there is no more update. Feel free to report a new issue if still any problem.
