### ISSUE TITLE
APC is not clearly defined in the app.

### ISSUE THREAD

**Issue by jordanmack** [nervosnetwork/neuron#2152]
**Describe the bug** (Please enter details, the more detail the better)

The definition of "APC" is not clearly defined anywhere in the app. It would be helpful if there was a better tooltip or an info button. This is one of the more common questions we see on Discord. 

I'm actually not sure what it means myself. Someone told me "Annual Percentage per Cycle", but I don't know where to verify that. It seems to be the same as APY.

**Comment by kellyshang** [comment]
new version of [v0.101.2](https://github.com/nervosnetwork/neuron/releases/tag/v0.101.2) is released.
