### ISSUE TITLE
Neuron wallet not connecting

### ISSUE THREAD

**Issue by bakshiji** [nervosnetwork/neuron#2154]
OS: Mac 10.13.6
Neuron Version: 0.100.2

The wallet is unable to connect, it only shows connecting at the bottom left window. I tried using legacy versions of Neuron wallet to see of this could solve the problem, but it didn't change. 
 
[neuron_debug_1635269876174.zip](https://github.com/nervosnetwork/neuron/files/7420272/neuron_debug_1635269876174.zip)

![Screen Shot 2021-10-26 at 23 15 13](https://user-images.githubusercontent.com/93217253/138932676-fc749404-d9c4-4898-b556-92f359693a9f.png)

**Comment by hoandang** [comment]
Hi, I'm having the exact same issue but my OS is updated to 10.15.7. It was working fine though, I quit the app and reopened it then it's stuck

OS: Mac 10.15.7
Neuron Version:  0.101.0

**Comment by kellyshang** [comment]
> Hi, I'm having the exact same issue but my OS is updated to 10.15.7. It was working fine though, I quit the app and reopened it then it's stuck
> 
> OS: Mac 10.15.7 Neuron Version: 0.101.0

@hoandang Could you help export and upload the debug info zip file? (from `Help` - `Export Debug Information`)

**Comment by hoandang** [comment]
@kellyshang Soz, I was too impatient so I completely deleted the app and reinstalled fresh and it is now syncing fine again (from 0% unfortunately). Will export those debug info if I encounter the same error next time. Cheers

**Comment by kellyshang** [comment]
> @kellyshang Soz, I was too impatient so I completely deleted the app and reinstalled fresh and it is now syncing fine again (from 0% unfortunately). Will export those debug info if I encounter the same error next time. Cheers

Great
