### ISSUE TITLE
Neuron wallet didn't show balance no matter what

### ISSUE THREAD

**Issue by Minnsy88** [nervosnetwork/neuron#2158]
Fully synced wallet, not showing any balance no matter what I try. My ckb is in the wallet I sent it to because I can see it on explorer. I'm sick if it now, does anyone know anyway I can send my ckb back to where I sent it from?? 

**Debug info** (Please upload the debug info from `Help` - `Export Debug Information`)

**Screenshots** (If applicable, add screenshots to help explain your problem.)

**Comment by kellyshang** [comment]
@Minnsy88 Does the address existed in the Neuron address book list? ( from `Receive` page - click the `Adress Book` button)

**Comment by kellyshang** [comment]
Will close this issue cause there is no more news. You can report a new one if still any problems.
