### ISSUE TITLE
block synced 0% in v0.101.0

### ISSUE THREAD

**Issue by deskertw** [nervosnetwork/neuron#2159]
OS: Windows 10 Home edition 21H1
I have cleared the cache, installed vc_redist_x64.exe, changed DNS, restarted my PC. But these actions above are invalid to solve this issue.
[neuron_debug_1636163381672.zip](https://github.com/nervosnetwork/neuron/files/7489631/neuron_debug_1636163381672.zip)
![211106](https://user-images.githubusercontent.com/25059362/140594807-b9ac006d-7b5a-4c6e-bade-5cae0b90185c.jpg)

**Comment by Gravetothemoon** [comment]
https://docs.microsoft.com/en-US/cpp/windows/latest-supported-vc-redist?view=msvc-160

download this and restart neuron wallet should work fine

**Comment by deskertw** [comment]
It is not work for me!
The block synced is still 0% after I executed vc_redist_x64.exe and restart PC and Neuron.

**Comment by Gravetothemoon** [comment]
Brother I know it’s a pain in the bottom I have had this issue for about 3 days. Have u uninstalled the neuron wallet and then reinstalled? It? By the way I’m still on sync Modus it will take ages,damn hope in the near future they make a wallet light don’t understand why u have to download the hole blockchain!!

**Comment by deskertw** [comment]
I reinstall Neuron several times, include v0.36.0, but it still not work!

**Comment by kellyshang** [comment]
@deskertw v0.100.x version is not compatible with older version, so please not try to install the older version.

The other thing need to be noted is that it's better to **keep your PC not sleeping** when the Neuron is syncing.

But for now as you had downgrading the node, there maybe some broken to your local ckb node data. So now please follow these steps:
1. Reinstall the [Neuron v0.101.0](https://github.com/nervosnetwork/neuron/releases/tag/v0.101.0);
2. Close Neuron (to make sure there is no Neuron/ckb.exe/ckb-indexer.exe process running on your PC);
3. Goto folder `%APPDATA%/Neuron/chains/mainnet`, you will see a `data` folder there, delete the `data` folder;
4. Restart Neuron, wait for the sync process start (see the left bottom of the Neuron);
5. Keep your PC not sleeping when the Neuron is sycing.

**Comment by kellyshang** [comment]
>don’t understand why u have to download the hole blockchain!!

@Gravetothemoon the Neuron is a Full-Node Desktop Wallet. 

As a POW chain and for the safety to your property's reasons, the CKB node is now bundled in the Neuron and will be launched by default when start Neuron, so Neuron is connect to the bundled CKB node by default but not to a centralized rpc node. Thus the multi-process may stall the computer's performance.
Even so, you can connect to a remote centralized rpc node which you think is safe thus the bundled ckb node won't be launch and may have less impact on your PC's performance.

**Comment by Gravetothemoon** [comment]
Thnx for the message I have another question is it possible in the near future that there will be just a simple wallet where u store the coins And you just hold them without all this pc knowledge. Don’t try to be rude but at the moment it’s quite hard to make this work I’m still syncing the wallet and it’s going on like this 5 days , love the project btw ...

Best regards

**Comment by hxz41713** [comment]
please please make this wallet lighter!

**Comment by kellyshang** [comment]
@Gravetothemoon @hxz41713 Maybe there will be a Neuron lite in the future.
