### ISSUE TITLE
Did a withdrawal from the DOA and my locked CKB has not shown up in my wallet 

### ISSUE THREAD

**Issue by cryptosick0** [nervosnetwork/neuron#2161]
**Describe the bug** (Please enter details, the more detail the better)

**Debug info** (Please upload the debug info from `Help` - `Export Debug Information`)

**Screenshots** (If applicable, add screenshots to help explain your problem.)

**Comment by cryptosick0** [comment]
0xaa7918f7fccd568e1a423fb8d06e56dd23424896976969565f74fbb440229f84

**Comment by cryptosick0** [comment]
[neuron_debug_1636208960540.zip](https://github.com/nervosnetwork/neuron/files/7490625/neuron_debug_1636208960540.zip)

**Comment by kellyshang** [comment]
@cryptosick0 after withdrawal the CKB won't get back to your wallet directly. You should see there still a record in the DAO but the button changed to `Unlock`, you need to wait for the Compensated Period completed and then the `Unlock` button will be clickable, then you can unlock it and the CKB will be show up in your wallet.
