### ISSUE TITLE
Wallet not Synch after latest update

### ISSUE THREAD

**Issue by jol1nly** [nervosnetwork/neuron#2162]
![image](https://user-images.githubusercontent.com/93840448/140621607-cc6cd0c1-50b5-4cbb-9ef1-f1d9d13283a9.png)

Wallet is not able to synch after latest update. Using :+1: 

![image](https://user-images.githubusercontent.com/93840448/140621641-42e27206-0154-4e3f-ab42-8ad89305b810.png)

Have tried clearing cache any ideas. I am running the my wallet on Ubunt 20.

**Comment by kellyshang** [comment]
@jol1nly Can you upload the debug zip info which mentioned in the issue template instruction? (upload the debug info from `Help` - `Export Debug Information`)

**Comment by kellyshang** [comment]
Close this issue as there is no more news.
