### ISSUE TITLE
Multiple users have reported that CKB is not migrating automatically.

### ISSUE THREAD

**Issue by jordanmack** [nervosnetwork/neuron#2163]
**Describe the bug** (Please enter details, the more detail the better)
Several users on Discord reported problems with synchronization. They were all using Windows 10 and the newest Neuron, v0.101.0. After inspecting their log, it was found that CKB was not running because it needed to be migrated.

A command similar to this was given in the logs: 

```"C:\Users\<username>\AppData\Local\Programs\Neuron\bin\ckb.exe" migrate -C "C:\Users\<username>\AppData\Roaming\Neuron\chains\mainnet"```

This command needs to be executed automatically, or at the very least prompt the user in the GUI. For these users there was no indication given at all, and Neuron just failed to sync.

**Comment by kellyshang** [comment]
The ckb node v0.100.x is not compatible with older version, so PLZ do not re-install the older version below Neuron v0.100.0.

From Neuron v0.100.0 there is already a warning poped up to tell user that the whole data will be deleted and re-sync will take a long time (depending on the PC's performance and network status).

If they did so (e.g. downgrading the Neuron or ckb node), please ask them to re-install with latest version, and delete the whole `data` folder under `%APPDATA%/Neuron/chains/mainnet`, then restart Neuron and wait for sync, make sure to keep the PC **not sleeping**.

Detailed steps for your reference: https://github.com/nervosnetwork/neuron/issues/2159#issuecomment-962780783
