### ISSUE TITLE
Instructions are needed for adding Force Bridge assets to Neuron.

### ISSUE THREAD

**Issue by jordanmack** [nervosnetwork/neuron#2164]
We need a page of instructions on how to add all of the supported assets from Force Bridge to Neuron as customized assets so they can be managed. I have a user who sent ckETH into Neuron directly from Force Bridge.

**Comment by kellyshang** [comment]
Seems the yokai sudt transfer does not support the ACP address, so the transfered udt from yokai will not been displayed/managed on Neuron.
