### ISSUE TITLE
Overview CKB balance is confusing to users because does not include CKB in token cells.

### ISSUE THREAD

**Issue by jordanmack** [nervosnetwork/neuron#2165]
**Describe the bug** (Please enter details, the more detail the better)
A new user who is using Force Bridge for the first time was confused about why his balance was shown as 150 CKB instead of 950 CKB. The first two transfers are ckETH. Something is needed here to explain more about what is included and not included in this balance. An ideal solution would probably have an expandable box that reveals multiple totals for, available CKB, occupied CKB (tokens), and total (both combined).

**Screenshots** (If applicable, add screenshots to help explain your problem.)
![unknown](https://user-images.githubusercontent.com/37931/140635472-3f399a75-faa2-4fe6-8461-4732a870e589.png)

**Comment by kellyshang** [comment]
Now the Neuron balance only show the normal CKB cells' balance, the occupied ckb value by sUDT will not been displayed in the Balance.

We will try to fix the `Amount` displaying on the Overview page to avoid misleading.
e.g. they will been displayed like this: 
![image](https://user-images.githubusercontent.com/28836185/140686480-eaa851db-cbff-4b90-b1e7-fac50b401b16.png)

**Comment by kellyshang** [comment]
Expected result update:
Neuron will not display the sudt transactions from third-party's Dapp which are not the "ACP lock+sudt type" cells.

**Comment by kellyshang** [comment]
A new tool to handle this kind of UDT will be released by 2022/05/20, mentioned in [#2223 (comment)](https://github.com/nervosnetwork/neuron/issues/2223#issuecomment-1001901666)
