### ISSUE TITLE
Feature Request: Allow Portal Wallet compatible addresses.

### ISSUE THREAD

**Issue by jordanmack** [nervosnetwork/neuron#2166]
Several users have inquired or tried to use their MetaMask recovery phrase with Neuron in an attempt to access their CKBytes stored on their Portal Wallet address. It would be a beneficial feature to support a Portal Wallet compatible account type that can import a MetaMask recovery phrase and access PW long addresses.

**Comment by kellyshang** [comment]
They can try to transfer the CKB from Portal Wallet to the Neuron address.

**Comment by jordanmack** [comment]
> They can try to transfer the CKB from Portal Wallet to the Neuron address.

Yes, it is understood that they can move the balance from one wallet to the other, but this is not what this feature request is about. It is about interoperability with MetaMask/PW-Lock, which would improve the experience for users.

We have helped many users in Discord work through their problems using different wallets. We always present the wallet options as equal and allow them to decide which is best for them to use. Sometimes they need to change wallets because they are having a problem with one. It is very helpful that Neuron and imToken can use the same recovery phrase to generate the same addresses because this gives them an option to switch easily when there are problems. It would also be very helpful if Neuron had an option to import a recovery phrase and use MetaMask/PW-Lock instead of the default lock.

This is not an urgent problem, so this is just a feature request for the future. We provided support to a number of people who have asked about features like this several times. It is users who have experience with wallets from other blockchains, like Ethereum, where the same recovery phrase can work across multiple different wallets to generate the same addresses.

**Comment by kellyshang** [comment]
PW-Lock is not the default lock by offical, and the signature from Metamask is not transparent to the user in Neuron. 
Neuron cannot support all the Dapp from third-party as there will be more and more Dapp with more and more lock in the future.
