### ISSUE TITLE
Ledger Unknown Error 0x9405 and 0x6b0c

### ISSUE THREAD

**Issue by benthurmeier** [nervosnetwork/neuron#2169]
I receive Ledger Unknown Error 0x9405 when attempting to withdraw CKB from the DAO using a Ledger Nano X.  The error is 0x6b0c when trying to send CKB.

I have tried resetting the Nano X and installing the Neuron wallet on a separate computer but the issue remains.
Mac OS 11.6.1 and Linux.

Neuronwallet: v0.101, Nano X: v2.0.0, Nervos Ledger: 0.5.2

https://user-images.githubusercontent.com/53025510/140832297-3d167848-b368-447c-8672-ac26ff884945.mov

..

**Comment by damienkeating** [comment]
actually it can't be sent from a desktop wallet as well.
<img width="1131" alt="Screen Shot 2021-11-09 at 12 31 40 AM" src="https://user-images.githubusercontent.com/3681983/140839890-807a6def-208e-497c-a54c-5c84cbd299ec.png">

**Comment by benthurmeier** [comment]
I was able to get around the error by sending the max amount of CKB out of the wallet and then redepositing it.  After those transactions were completed I was able to withdraw from the DAO successfully.

**Comment by kellyshang** [comment]
> actually it can't be sent from a desktop wallet as well. <img alt="Screen Shot 2021-11-09 at 12 31 40 AM" width="1131" src="https://user-images.githubusercontent.com/3681983/140839890-807a6def-208e-497c-a54c-5c84cbd299ec.png">

You can restart the connected CKB node when encounter this error.
