### ISSUE TITLE
Neuron Wallet not syncing

### ISSUE THREAD

**Issue by MikeL2149** [nervosnetwork/neuron#2170]
Downloaded the wallet 0.101.0 on my windows 8 pc. It doesn't sync. showing connecting for several days already. Tried clearing cache, restarting the wallet. Nothing worked so far.
![Screen Shot 11-08-21 at 08 02 PM](https://user-images.githubusercontent.com/93963329/140860572-4056b8df-1d57-4531-9b14-7f7c0b596cd9.PNG)

**Comment by chkhorlucas** [comment]
I have the exact same issue, running on Mac

**Comment by hxz41713** [comment]
me too. it started cyncing once but then 3 days later still 40%. uninstalled/reinstalled it then not syncing at all!

**Comment by kellyshang** [comment]
@MikeL2149 @chkhorlucas @hxz41713 Can you all please upload the debug zip file as required? (from `Help` - `Export Debug Information`)

**Comment by MikeL2149** [comment]
Here is the debug file
[neuron_debug_1637603150906.zip](https://github.com/nervosnetwork/neuron/files/7583244/neuron_debug_1637603150906.zip)

**Comment by hxz41713** [comment]
hi,
and here is my debug file.

**Comment by kellyshang** [comment]
> Here is the debug file [neuron_debug_1637603150906.zip](https://github.com/nervosnetwork/neuron/files/7583244/neuron_debug_1637603150906.zip)

@MikeL2149 Seems the bundled CKB node didn't start on your PC. Please make sure you have installed the `vc_redist.x64.exe` from https://docs.microsoft.com/en-US/cpp/windows/latest-supported-vc-redist?view=msvc-160 , then restart Neuron to see if it works.

**Comment by kellyshang** [comment]
> hi, and here is my debug file.
> […](#)

@hxz41713 **PLZ don't reply to the notifiaction email** as the mail was sent by the GitHub platform but not our private email, so we can't receive the files you attached to the mail.

PLZ drag the zip file into the comment input box of this issue - https://github.com/nervosnetwork/neuron/issues/2170.

**Comment by hxz41713** [comment]
apologies, here is my debug
[neuron_debug_1637611229980.zip](https://github.com/nervosnetwork/neuron/files/7586399/neuron_debug_1637611229980.zip)

**Comment by kellyshang** [comment]
> apologies, here is my debug [neuron_debug_1637611229980.zip](https://github.com/nervosnetwork/neuron/files/7586399/neuron_debug_1637611229980.zip)

@hxz41713 Not sure why your bundled ckb node sycn process is far behind the Neuron's sync block height. But seems they were still all under processing.
Next time BEFORE you start the Neuron, could you have a look to see if there is  a process of ckb-indexer exsiting? If yes, you can manually end it and then restart the Neuron.

**Comment by majic0918** [comment]
Here is the debug fi
[neuron_debug_1637724107038.zip](https://github.com/nervosnetwork/neuron/files/7592492/neuron_debug_1637724107038.zip)
le

**Comment by majic0918** [comment]
![12](https://user-images.githubusercontent.com/41669852/143169520-7a7c0f60-3ac2-48ba-9327-f56842a97979.png)

**Comment by kellyshang** [comment]
@majic0918 seems there is no space left on your device:
![image](https://user-images.githubusercontent.com/28836185/143221165-916948cf-8728-46da-9c75-b0d7d0cfcc05.png)
