### ISSUE TITLE
Wallet not syncing

### ISSUE THREAD

**Issue by CMason87** [nervosnetwork/neuron#2171]
Since updating to the latest version of Neuron, the wallet no longer connects to the network to sync. I have attached my debug logs to hopefully provide some insight as to why this is happening. 

[main.log](https://github.com/nervosnetwork/neuron/files/7505837/main.log)

**Comment by dounisaur** [comment]
I have just come across the same issue - wallet has not been able to sync for almost 24 hrs

**Comment by dounisaur** [comment]
> Since updating to the latest version of Neuron, the wallet no longer connects to the network to sync. I have attached my debug logs to hopefully provide some insight as to why this is happening.
> 
> [main.log](https://github.com/nervosnetwork/neuron/files/7505837/main.log)

Hi, Not sure what OS you are running, but i found this on another forum and this worked for me (im on macos)

"the problem is caused by the ckb-indexer process didn't quit when close the Neuron, we will try to fix this problem in next version. For now you can mannually quit the ckb-indexer in Activity Monitor then restart the Neuron."

**Comment by hakankocar** [comment]
what is it i transfer my coin but my balance zero i check transaction it trasfer already but i didnt show to balance all my coin is gone how i will get back my coin

**Comment by kellyshang** [comment]
@CMason87 Has your problem been resolved?

**Comment by kellyshang** [comment]
> 

@hakankocar Can you please open a new issue and describe & upload the debug info as required?

**Comment by kellyshang** [comment]
> what is it i transfer my coin but my balance zero i check transaction it trasfer already but i didnt show to balance all my coin is gone how i will get back my coin

@hakankocar Can you please open a new issue and describe & upload the debug info as required?

**Comment by hakankocar** [comment]
Yes thank you

**Comment by kellyshang** [comment]
Greate.
