### ISSUE TITLE
Withdrawing from the DAO recommendations

### ISSUE THREAD

**Issue by reidandrew91** [nervosnetwork/neuron#2172]
Hey, I submitted a request a few months ago in August. It was regarding withdrawing CKB from the DAO. 

I have staked all my CKB to the DAO and did not know that there needed to be any left in the wallet to withdraw. A pop up did appear, but it said only that it "Recommends" keeping 61 in your main wallet. I recommend in the future that this pop up includes telling the user that they must have CKB in their main wallet, and to not stake everything they have, so keeping 61 CKB in their wallet is critical to be able to withdraw from the DAO. 

This would save a lot of headache in the future and let new users know this is crucial for them to withdraw so they aren't stuck like me for a few months.

Just a thought. 
Thank you

**Comment by jordanmack** [comment]
I've helped several users in the past month who had the same issue as @reidandrew91. It would be helpful if the message was improved to emphasize more clearly that withdrawal will not be possible until more CKBytes are added to the wallet.

**Comment by CipherWang** [comment]
We will add a "force empty" checkbox to avoid this.
