### ISSUE TITLE
Deposit missing 

### ISSUE THREAD

**Issue by 31Delrancho** [nervosnetwork/neuron#2174]
**Describe the bug** (Please enter details, the more detail the better)

**Debug info** (Please upload the debug info from `Help` - `Export Debug Information`)

**Screenshots** (If applicable, add screenshots to help explain your problem.)

**Comment by 31Delrancho** [comment]
Did a test deposit into Neuron Wallet. It has over 1000 confirmations.  Never received the CKB.

**Comment by kellyshang** [comment]
@31Delrancho Can you please try to describe the issue more detailed? Deposit from where? And Can you please upload the debug info zip file as required?

**Comment by kellyshang** [comment]
Will close this issue as there is no more news.
