### ISSUE TITLE
Send to field does not allow enough characters for some addresses.

### ISSUE THREAD

**Issue by jordanmack** [nervosnetwork/neuron#2175]
**Describe the bug** (Please enter details, the more detail the better)
When sending CKBytes from Neuron wallet, the "Send to" field allows only up to 100 characters. However, addresses can be much longer. BestDAS.com uses addresses that are 130 characters in length so it ends up being cut off.

**Screenshots** (If applicable, add screenshots to help explain your problem.)
![20211116160706](https://user-images.githubusercontent.com/37931/142086201-dbd69bdb-c2ab-4a89-9fd5-92ff213fc6a5.png)

**Comment by kellyshang** [comment]
Thanks for your report, we will enlarge the input length limitation in next version.

**Comment by kellyshang** [comment]
https://github.com/nervosnetwork/neuron/releases/tag/v0.101.1 released and fixed this issue.
