### ISSUE TITLE
Request for enabling contract data on Ledger Nano X

### ISSUE THREAD

**Issue by vdubbed** [nervosnetwork/neuron#2179]
Hi, I’m currently using v0.5.2 CKB app on Ledger Nano X and Neuron Wallet 0.101.0. I don’t recall updating the App from 0.5.1 to 0.5.2 but I’ve recently had to update my Ledger Live to 2.35.1. Now when I try to send out CKB the ledger device is asking me to enable Contract data to be on - which only seems to be required for NFT or custom tokens according to the article on github. I’ve had multiples users reporting the same on Nervos subreddit. I was wondering if it is normal to have this function on when we send out CKB - it never requested it with my last transaction at the end of October or with previous version. Only by enabling contract data I can send out from Neuron wallet now. 

On a side note, I’ve noticed that MetaMask is also requesting something similar saying, enable Smart Contract Data or Blind Signing when sending out of ckb.pw to Neuron wallet - since the recent update and some partnership with Ledger. I’ve enabled it once and was able to send it out but later on with it Off I could still send it out. I don’t know if it had changed anything on CKB app but below is the article I found - no technical details. 

https://www.ledger.com/blog/metamask-and-ledger-integration-fixed-new-partnership-between-metamask-and-ledger-to-ensure-ease-of-use-and-security-for-our-shared-customers

**Comment by kellyshang** [comment]
Maybe you'd better report the issue to https://github.com/obsidiansystems/ledger-app-nervos
