### ISSUE TITLE
My wallet cannot be synced after five days

### ISSUE THREAD

**Issue by majic0918** [nervosnetwork/neuron#2181]
[neuron_debug_1637724107038.zip](https://github.com/nervosnetwork/neuron/files/7593816/neuron_debug_1637724107038.zip)
Every time you synchronize to a certain value, you can’t continue to interrupt。
Troubled for a long time, physically exhausted。

**Comment by kellyshang** [comment]
@majic0918 seems there is no space left on your device:
![image](https://user-images.githubusercontent.com/28836185/143221735-0de54785-0fbe-4fc6-bd40-80ac2cf3be8f.png)
https://github.com/nervosnetwork/neuron/issues/2170#issuecomment-977740917
