### ISSUE TITLE
Neuron lost my password

### ISSUE THREAD

**Issue by Tomsdings** [nervosnetwork/neuron#2182]
Hi, I have received some $CKB on my neuron wallet. 
Now I tried to send 200 CKB to the portal wallet.
For this I had to put in my neuron wallet password.
Sending starts and after one second it is reported
that the password is incorrect. That is impossible IMAO. 
And it is not possible to create another one. 
I cannot find any instructions in the help documents regarding the password setting.
What can I do now?

<img width="1286" alt="Bildschirmfoto 2021-11-24 um 19 10 32" src="https://user-images.githubusercontent.com/94990140/143292702-2f4be7c4-8cec-4ee1-a11e-842aded47b3f.png">

**Comment by kellyshang** [comment]
@Tomsdings You can re-import the wallet by the mnemonic seed and set a new password with new wallet.
![image](https://user-images.githubusercontent.com/28836185/143376573-3681bb9e-e982-4cc8-ad31-6e6fdc7dc46c.png)

**Comment by Tomsdings** [comment]
Thank you!

Viele Grüße
Thomas Förg
