### ISSUE TITLE
balance display error

### ISSUE THREAD

**Issue by tianlitao** [nervosnetwork/neuron#2184]
Neuron balance display 1000592CKB，but transfer error. And I use imtoken it's display balance 529CKB , last transfer

https://explorer.nervos.org/address/ckb1qyqxj6rdzwf0dqdrgpma3k0vud05gvq5zzsqj9z8wk

![39c6b4f631044b1e8bef634dcd42a82](https://user-images.githubusercontent.com/7892962/143389779-f508ade0-4310-41c1-87c9-345d2c64a692.jpg)

**Comment by kellyshang** [comment]
@tianlitao Neuron 的同步有时候可能因为某些原因导致余额统计不准确，我们也正在排查中，你可以试下单清缓存（`Settings` - `Clear Cache` ）然后再看下余额是否正确：
![image](https://user-images.githubusercontent.com/28836185/143402448-ed378ba5-1036-449b-8260-028034fdcc76.png)

**Comment by tianlitao** [comment]
清空重新同步之后正常了，感谢
