### ISSUE TITLE
Ledger Nano X disconnected - Neuron

### ISSUE THREAD

**Issue by alexcasama** [nervosnetwork/neuron#2185]
I'm using:
- Ledger Nano X, with Nervos app installed v 0.5.2
- Ledger Live 2.35.2
- Neuron wallet 0.101.0

When I try to send some CKBs to another wallet and the Ledger Nano X is connected to the Mac, in the last step when I have to sign the operation, it shows the following message:

![image](https://user-images.githubusercontent.com/6854536/143424945-13c70bf0-9d4d-4db9-8862-a8936c9da883.png)

In that moment, obviusly the Ledger is connected and the app on the Ledger is open but still appears the same error. I press "Rescan" so many times and still does not connect.

Also I cleared the cache on Neuron and still the same error...

Please I need to solve this asap, I can't move my CKBs and I am very afraid...

**Comment by yuche** [comment]
Counld you confirm that the following steps are all correct?

1. You can see in Ledger Live that your device is connected (this means your device is not damaged)
2. Close Ledger Live before open Neuron
3. You have the nervos app open in your device

**Comment by jordanmack** [comment]
Multiple users have reported problems with connecting Ledger devices using Ledger firmware v2.0.0 + Nervos Ledger app v.0.5.2. Pressing the rescan button several times fixes the issue in most cases. However, this does not appear to be the case with alexcasama. I do not recall having this issue prior to the latest upgrade.

**Comment by alexcasama** [comment]
> Could you confirm that the following steps are all correct?
> 
> 1. You can see in Ledger Live that your device is connected (this means your device/usb cable/usb port is not damaged)
> 2. Close Ledger Live before open Neuron
> 3. You have the nervos app open in your device

That was ok....I got the error....
On the Nervos app configuration within Ledger I had disabled the sign and contract.....so I put it on and it works!!
Thanks guys
