### ISSUE TITLE
Unknown Outpoint (Neuron Wallet)

### ISSUE THREAD

**Issue by finnerbahce** [nervosnetwork/neuron#2186]
I'm running Neuron Version 0.101.0 on Windows 10 Pro.

I'm trying to transfer CKB from the Neuron Wallet to an exchange. If I choose 10,000 CKB then the transfer occurs no problem but anything over that seems to fail.

I've cleared cache numerous times. I've also installed the wallet on another laptop and I get the same problem. Any suggestions/resolution?

![image](https://user-images.githubusercontent.com/83966348/143477844-9003682a-8c45-4b92-8fb7-ea8792d559f5.png)

EDIT: 10,000 doesn't always work. Success is random.

**Comment by kellyshang** [comment]
@finnerbahce try single-clear cache, then wait for the sync complete and see if it works:
![image](https://user-images.githubusercontent.com/28836185/143515290-7e8e7132-dcef-4a23-b197-30d28f84dbd7.png)

**Comment by finnerbahce** [comment]
This worked. Every time I chose to fully rebuild index as well it continued to fail. Thank you so much.
