### ISSUE TITLE
New MacBook Neuron not Syncing

### ISSUE THREAD

**Issue by srrmike** [nervosnetwork/neuron#2187]
I got a new 2021 M1 MacBook. Used backup from 2021 M1 Mac Mini. New MacBook running 12.0.1. Not sure what the Mini was running. Might be one version down. However Neuron wallet was running fine. All my other programs seem to transfer with no problem. Neuron Wallet knows about all my wallets. It just says connecting and Block Sync 0%.  Can't seem to load a fresh copy of Neuron. It always knows about my wallets. 
[neuron_debug_1637875197090.zip](https://github.com/nervosnetwork/neuron/files/7605275/neuron_debug_1637875197090.zip)

**Comment by kellyshang** [comment]
Seems there is error when running the CKB node on your device. I have reported the issue to the ckb-core team. Will return to you when I get any feedback from them.

**Comment by kellyshang** [comment]
Maybe your CKB node's data was broken. Try to delete the whole folder of : `~/Library/Application Support/Neuron/chains/mainnet/data` , then restart Neuron and wait for the re-sync be complete.

**Comment by srrmike** [comment]
I found the file "~/library/ApplicationSupport/“ there is no “Neuron” file. Looking at my Mac that works. It doesn’t have this file either.

Thanks
Mike Smith
352-215-5942
***@***.***

**Comment by kellyshang** [comment]
Please make sure that in "Application Support" there is a blank space in there.
Here is an video to help how to locate the "Application Support" folder: https://www.youtube.com/watch?v=a10BiE9t7RY

**Comment by srrmike** [comment]
Thanks deleting that file seems to of did the trick. The YouTube Video was good way to help me find it.

**Comment by kellyshang** [comment]
That's great.
