### ISSUE TITLE
History search bar placeholder example for date doesn't reflect actual usage.

### ISSUE THREAD

**Issue by tantommy** [nervosnetwork/neuron#2190]
The history search bar's placeholder shows that we can search for a date using the format `yyyy-mm-dd` but in actuality, we have to enter `yyyy-mm-dd HH:MM:SS`.

![image](https://user-images.githubusercontent.com/7282254/143664432-cb95034c-01bf-4263-a6c5-cbecec6de980.png)

Searched with date format per placeholder:
![image](https://user-images.githubusercontent.com/7282254/143624012-3735323a-821d-44c6-bc79-0ce7ed3b8f2c.png)

Searched with full datetime format:
![image](https://user-images.githubusercontent.com/7282254/143624089-1b5363ed-264b-4ae4-93cd-7c6a09422c86.png)

I think two possible solutions are:
1) change the placeholder to include `HH:MM:SS` (I can submit a PR for this)
2) fix the API

**Comment by kellyshang** [comment]
Seems the search for `yyyy-mm-dd` works for me. Can you please double check if there is any txs of the date listed in your history?

**Comment by tantommy** [comment]
> Seems the search for `yyyy-mm-dd` works for me. Can you please double check if there is any txs of the date listed in your history?

Yes, in the screenshot i provided above, there is a transaction with the date `2021-11-16`.  In the second screenshot above, i searched for it with that date format but no results appeared.  In the third screenshot, I added the time and then it appeared.

**Comment by kellyshang** [comment]
Could you tell me your Neuron version and your OS version?

**Comment by tantommy** [comment]
> Could you tell me your Neuron version and OS version?

![image](https://user-images.githubusercontent.com/7282254/143773019-a80c0772-83bc-488b-b0c3-8bd6ef1830c6.png)
![image](https://user-images.githubusercontent.com/7282254/143773028-517ae66b-5c6c-471e-8984-c306972022bc.png)

**Comment by tantommy** [comment]
> Could you tell me your Neuron version and OS version?
