### ISSUE TITLE
Deposit missing

### ISSUE THREAD

**Issue by dootie1723** [nervosnetwork/neuron#2191]
Hi, I withdrew CKB from crypto.com to deposit into the Neuron Wallet on 11/25 at 1:30pm. I still have yet to see it in my Neuron Wallet. I checked the explorer and can see that the transaction was there. Can someone help me trouble shoot this or is it just taking a long time for the transaction to complete. Normally when I move CKB from my crypto.com to Neuron Wallet it is completed w/in minutes. Please advise, thank you.

**Comment by kyleecodes** [comment]
If you verified your transaction was successful on ckbexplorer, it will go through, it may just take some time to show up in Neuron. Transactions on CKB are deterministic, meaning they either happen as expected or not at all. Have you tried clearing your cache in Neurons settings?

**Comment by dootie1723** [comment]
Hello, yes I have cleared cache several times. So are you saying if I verified on CKBexplorer it will go through, it’s just a matter of time? How long should I wait to reach out again if I don’t see it show up in Neuron Wallet? Thanks for all your help!


Sent from Yahoo Mail for iPhone


On Saturday, November 27, 2021, 12:31 AM, Kylee Fields ***@***.***> wrote:




If you verified your transaction was successful on ckbexplorer, it will go through, it may just take some time to show up in Neuron. Transactions on CKB are deterministic, meaning they either happen as expected or not at all. Have you tried clearing your cache in Neurons settings?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by kyleecodes** [comment]
The Neuron wallet needs to be fully synchronized with the CKB blockchain for an accurate display of $CKB.
Therefore, if Neuron is not synced, the display will not be an accurate representation of the blockchain.
Also, do you have the latest release? You may be due for an upgrade. https://github.com/nervosnetwork/neuron/releases 
If your Neuron wallet is still not fully synced or your $CKB doesn't show up after an extended period of time, feel free to consult the #general or #support channels in our Discord for further assistance!

**Comment by dootie1723** [comment]
Hi, the block seems to be stuck at 99.93%. Also I am running version 0.100.1 do you think I should upgrade to a later release?

**Comment by dootie1723** [comment]
Hi, I installed latest version and the deposit is not showing up. Also it seems to be stuck at around 98% syncing. Any thoughts on what to do now? Thank you.
