### ISSUE TITLE
withdraw issue

### ISSUE THREAD

**Issue by bulletproofliffe** [nervosnetwork/neuron#2194]
I had withdrawn 15000ckb from neuron Dao to binance and the amount has still not reflected in my binance wallet. It's been 2 days and the ckb has been deducted from my wallet. The status is still showing pending. Any help regarding this?

Transaction id -    0x578ecca48ac033b637618e4a1fb2929e645a9ab1a22c1ab5065f3c3794e67c59

**Comment by kellyshang** [comment]
Seems the transactions didn'n onchain. Please check the tx status in your Neuron history.
