### ISSUE TITLE
Block Sync at 0% and stuck at connecting

### ISSUE THREAD

**Issue by damichmich** [nervosnetwork/neuron#2195]
Hi, I noticed this yesterday and it's still stuck today. Anything I should do?

**Comment by kellyshang** [comment]
Please report your problem follow the issue template which have told you what you should do.

**Comment by damichmich** [comment]
I"m sorry -- I am reporting it. Where should I go exactly? Where is the template?

**Comment by damichmich** [comment]
[neuron_debug_1638140798063.zip](https://github.com/nervosnetwork/neuron/files/7622144/neuron_debug_1638140798063.zip)

**Comment by kellyshang** [comment]
Hi @damichmich , that's great you upload the debug info and that can save time for both of us.

According to your debug info, there is data broken happened to the bundled CKB node.

For now you have to delete the whole folder of : `~/Library/Application Support/Neuron/chains/mainnet/data` , then re-start Neuron and see if the sync process works. It's better that to keep your PC not sleeping when syncing.

**Comment by hoandang** [comment]
@kellyshang Hi Kelly, I did remove that folder and the sync seems to start picking up but it's now stuck at 100% syncing ~~ left [176018.02428517](https://share.getcloudapp.com/9ZuRZqAW)

Here is my log
[neuron_debug_1638845390210.zip](https://github.com/nervosnetwork/neuron/files/7665124/neuron_debug_1638845390210.zip)

**Comment by kellyshang** [comment]
> @kellyshang Hi Kelly, I did remove that folder and the sync seems to start picking up but it's now stuck at 100% syncing ~~ left https://share.getcloudapp.com/9ZuRZqAW
> 
> Here is my log [neuron_debug_1638845390210.zip](https://github.com/nervosnetwork/neuron/files/7665124/neuron_debug_1638845390210.zip)

Your bundled ckb node has not catch up to the latest block height. Try single-clear cache or restart the Neuron:
![image](https://user-images.githubusercontent.com/28836185/144965839-969c3292-be73-44bb-b572-fba3b235364c.png)

**Comment by sfont012** [comment]
Hi guys/gals, i'm having difficulty getting Neuron to sync and I've uploaded the debug file. If i need to open a separate thread just let me know and i will. 

Issue - When i start Neuron it stays at 0% and will not sync. It has never moved past 0%. 
[neuron_debug_1639319065520.zip](https://github.com/nervosnetwork/neuron/files/7698911/neuron_debug_1639319065520.zip)

**Comment by hoandang** [comment]
@sfont012 Clear your cache and restart your comp, if it's still not syncing then just reinstall and resync everything from scratch again. It seems like a known issue but don't think there is a permanent fix yet. So prevent it from ever happening again, just keep the app open all the time and don't close it (at least from my experience from my Mac)

**Comment by kellyshang** [comment]
@sfont012 The bundled CKB node didn't start on your PC. Try install the redist and then restart Neuron: https://docs.microsoft.com/en-US/cpp/windows/latest-supported-vc-redist?view=msvc-170
![image](https://user-images.githubusercontent.com/28836185/145717276-bfde420e-f7fd-49d6-8769-7d64cf4548b1.png)

**Comment by sfont012** [comment]
> @sfont012 The bundled CKB node didn't start on your PC. Try install the redist and then restart Neuron: https://docs.microsoft.com/en-US/cpp/windows/latest-supported-vc-redist?view=msvc-170 ![image](https://user-images.githubusercontent.com/28836185/145717276-bfde420e-f7fd-49d6-8769-7d64cf4548b1.png)

Worked, thank you! Luckily all my ckb is in there even though wallet never synced up until today.
