### ISSUE TITLE
wallet won't connect

### ISSUE THREAD

**Issue by numnallover** [nervosnetwork/neuron#2200]
[neuron_debug_1638209873983.zip](https://github.com/nervosnetwork/neuron/files/7620384/neuron_debug_1638209873983.zip)

**Comment by kellyshang** [comment]
@numnallover 
First of all, let me confirm one thing with you: 
Is there a warning window like below poped up when you open the Neuron? 
![image](https://user-images.githubusercontent.com/28836185/143973653-667beb4b-c7ca-4396-9d59-5f71b220f06a.png)


Then you should install the `vc_redist.x64.exe` from https://docs.microsoft.com/en-US/cpp/windows/latest-supported-vc-redist?view=msvc-160 , then restart the Neuron.

**Comment by numnallover** [comment]
Visual c++ is installed. I have tried reinstalling Neuron, but with no luck
![nerbug](https://user-images.githubusercontent.com/95183268/144023889-4afe0cdc-8688-43cd-9a8e-0ce49237efee.png)
.

**Comment by kellyshang** [comment]
@numnallover Could you please help export and upload the debug info again?

**Comment by numnallover** [comment]
[neuron_debug_1638638224831.zip](https://github.com/nervosnetwork/neuron/files/7654320/neuron_debug_1638638224831.zip)
there you go

**Comment by kellyshang** [comment]
Seems your bundled CKB node still not been started.
Please make sure that the vc-redist you installed is the `x64` version:
![image](https://user-images.githubusercontent.com/28836185/144853700-aacee238-4f25-4d6a-9fe7-5cf251fcecf4.png)

**Comment by dmatsumoto** [comment]
@kellyshang I have the same problem, but I definitely have the x64 redist installed.  I was syncing for 300k blocks, and then it just stopped and was stuck at the Connecting state.  I restarted Neuron and now it just says "Sync not started yet".

Here's my debug log.  Could you please take a look and suggest next step
[neuron_debug_1638900840183.zip](https://github.com/nervosnetwork/neuron/files/7670712/neuron_debug_1638900840183.zip)
s?

**Comment by kellyshang** [comment]
Hi @dmatsumoto , could you have a try the latest version of [v0.101.2](https://github.com/nervosnetwork/neuron/releases/tag/v0.101.2) and see if it works?
