### ISSUE TITLE
not able to use ledger nano x to withdraw ckb

### ISSUE THREAD

**Issue by oii123ggwp** [nervosnetwork/neuron#2203]
**Describe the bug** (Please enter details, the more detail the better)
I'm not able to use ledger nano x to sign and withdraw ckb, but I can unlock Nervos DAO. The version is 0.101.1

**Debug info** (Please upload the debug info from `Help` - `Export Debug Information`)

[neuron_debug_1638340975394.zip](https://github.com/nervosnetwork/neuron/files/7631423/neuron_debug_1638340975394.zip)

**Screenshots** (If applicable, add screenshots to help explain your problem.)

**Comment by oii123ggwp** [comment]
[neuron_debug_1638340975394.zip](https://github.com/nervosnetwork/neuron/files/7631419/neuron_debug_1638340975394.zip)

**Comment by yuche** [comment]
Please make sure the Nervos app on your device has the configuration “allow contract data” enabled.

**Comment by oii123ggwp** [comment]
I enabled it, but nothing happen

**Comment by oii123ggwp** [comment]
![Screenshot 2021-12-02 163317](https://user-images.githubusercontent.com/89623892/144386082-1af90501-9bf7-4ff0-a980-fecb0ce3ff8f.png)
and nothing happen on my ledger nano x

**Comment by oii123ggwp** [comment]
I'm able to withdraw my ckb!! But it take about 3 minutes to show the confirmation.
