### ISSUE TITLE
default node: Sync is slow indicator

### ISSUE THREAD

**Issue by lightandsaltckb** [nervosnetwork/neuron#2207]
[neuron_debug_1638515763381.zip](https://github.com/nervosnetwork/neuron/files/7647616/neuron_debug_1638515763381.zip)

Made a withdrawal last November 26, 2021 and it's already for unlocking today. However after syncing fine and reaching 100%, Synced will turn into Sync is slow. repeated the whole syncing but still the same. Around 11am, hours remaning to unlock is 0.2 hours. It is already 3:30pm on our time and still says 0.2 hours to unlock. Don't even know if it's working because it is already 100% synced. We are running on version 0.35.1 on Mac OS Sierra 10
<img width="1419" alt="Screen Shot 2021-12-03 at 3 27 57 PM" src="https://user-images.githubusercontent.com/95467274/144563530-c31bb138-21f9-4c6b-9423-af3789e1033b.png">

**Comment by kellyshang** [comment]
Your Neuron version is an old version and the bundled CKB node is too old that may not be compatible very well with the latest CKB version.
You can try to restart the Neuron, while it's better to upgrade the Neuron to the latest version once you are free, cause the re-sync will take a long time.
