### ISSUE TITLE
Unable to withdraw from Nervos DOA

### ISSUE THREAD

**Issue by tonydnut** [nervosnetwork/neuron#2208]
I have tried to withdraw my CKB from the DOA, it is within the withdrawal period, 2 days to go. It has said limit 200000 at the top in a red banner. Is there any way around this?
<img width="1470" alt="Screen Shot 2021-12-03 at 8 46 14 pm" src="https://user-images.githubusercontent.com/89505607/144581918-e130aae7-a2e3-49d9-b557-705a88aac646.png">

**Comment by dp181221** [comment]
same thing happening with me. i put a withdrawal request before 2 days. the transaction was showing failed. i update the software, sync it for few hours. still shows withdrawing after 4 days and not able to unlock after the time frame finished and now new cycle has started.

**Comment by hypn0chain** [comment]
i too, cannot withdraw from my Neuron wallet, my Nervos DAO. I receive 2 different error messages upon attempting to withdraw from Neuron. I am re-syncing my Neuron wallet now.

**Comment by kellyshang** [comment]
Try install the latest version and restart: https://github.com/nervosnetwork/neuron/releases/latest
