### ISSUE TITLE
Deposit pending

### ISSUE THREAD

**Issue by Rags-nomore** [nervosnetwork/neuron#2209]
**Describe the bug** 
I deposited CKB in to the Nervos DAO via Neuron on November 28th, 2021 and the deposit is still pending. I have checked numerous times since this date, ensuring synchronization but the deposit is still pending. 

Also, I am unable to deposit other CKB from the same wallet in to the DAO until this deposit has been verified.

Please advise how to troubleshoot?

**Debug info** 

[neuron_debug_1638648081010.zip](https://github.com/nervosnetwork/neuron/files/7654605/neuron_debug_1638648081010.zip)

**Screenshots** 
[20211205 Nervos DAO screenshot.docx](https://github.com/nervosnetwork/neuron/files/7654607/20211205.Nervos.DAO.screenshot.docx)

**Comment by gabisena424** [comment]
withdrawing pendente... apos sacar cbk da neuron com sincronização incompleta meu saque não foi realizado 

como devo proceder ?

**Comment by kellyshang** [comment]
Try install the latest version of [v0.101.2](https://github.com/nervosnetwork/neuron/releases/tag/v0.101.2) .
BTW I will close this issue as it's duplicated with https://github.com/nervosnetwork/neuron/issues/2214
