### ISSUE TITLE
Deposit not Showing in Neuron Wallet

### ISSUE THREAD

**Issue by ISME-2008** [nervosnetwork/neuron#2212]
Hi, I have just created a CKB Nervos Neuron Wallet and have deposited 10000 CKB from an exchange and whilst the status on the exchange is showing completed, the CKB is not showing in my Neuron Wallet.

I have input the TX hash address into the history section of the wallet but it does not recognise or find the transaction.

Hope someone can help/advise ?

**Comment by kellyshang** [comment]
Why not export and upload the debug zip file that the issue template required? Thus I can check more exactly what cause of your problem.

**Comment by rolllin** [comment]
i have the same problem

**Comment by kamarajj** [comment]
My deposit from finance is not showing also.

**Comment by kellyshang** [comment]
@rolllin @kamarajj can you please help export the debug info zip file from menu `Help` - `Export Debug Information` and upload it here, I will check what was happend.

**Comment by kamarajj** [comment]
I got the deposit after the sync completion. Thanks.

________________________________

**Comment by rolllin** [comment]
https://explorer.nervos.org/transaction/0x911d7db2dcdf3ef67da2e29ddffb6bbaf84b2835df06992e591d3401801087be?lang=en_US this is my transaction but ckb it dosnt show in my wallet

**Comment by kellyshang** [comment]
> https://explorer.nervos.org/transaction/0x911d7db2dcdf3ef67da2e29ddffb6bbaf84b2835df06992e591d3401801087be?lang=en_US this is my transaction but ckb it dosnt show in my wallet

Can you please help export the debug info zip file from menu Help - Export Debug Information and upload it here?

**Comment by rolllin** [comment]
i cant find export debug information

**Comment by kellyshang** [comment]
> i cant find export debug information

![image](https://user-images.githubusercontent.com/28836185/150450928-ccf34402-c788-49cd-8da1-f51b2f0e1eba.png)

**Comment by rolllin** [comment]
[neuron_debug_1643252365989.zip](https://github.com/nervosnetwork/neuron/files/7947213/neuron_debug_1643252365989.zip)

**Comment by kellyshang** [comment]
@rolllin Seems your Neuron's syncing was worked as normal. Please be patient and wait for the sync to be finalized.

When syncing please keep the Neuron is opened and better keep the PC not sleeping.

When the sync is finalized, the status will be shown as `Synced` and then your CKB will be shown up:
![image](https://user-images.githubusercontent.com/28836185/151695742-4c94ff9a-2b03-43c9-abd5-4beb4f5b3344.png)
