### ISSUE TITLE
retirada pendente

### ISSUE THREAD

**Issue by gabisena424** [nervosnetwork/neuron#2213]
retirada pendente... após sacar cbk staking do neurôn com sincronização incompleta meu saque não foi realizado

como devo proceder?

informações de depuração

neuron_debug_1638868734614

capturas de tela'

[20211205.Nervos.DAO.screenshot.docx](https://github.com/nervosnetwork/neuron/files/7669356/20211205.Nervos.DAO.screenshot.docx)

output captura de tela 

0         ckb1qyqrepsd6p2epkumtfs6u2fpfvndlfnhrgkss6pkyg

1         ckb1qyq25k75f08z4rssusj6vuj5vvec0rze3awsr24ttt

taxa hash 

0x839b68c5df835bd0b204fc178810ef2904710a21529c71f7288303c3f7dce58a

**Comment by kellyshang** [comment]
duplicate issue with https://github.com/nervosnetwork/neuron/issues/2214
