### ISSUE TITLE
retirada cbk nao validada 

### ISSUE THREAD

**Issue by gabisena424** [nervosnetwork/neuron#2214]
efetuei uma retirada de ckbs após 4 dias de staking e meus 101 mil ckbs nao foram retirados nem aparecem com locked 

capitura de tela 

[20211205.Nervos.DAO.screenshot.docx](https://github.com/nervosnetwork/neuron/files/7669857/20211205.Nervos.DAO.screenshot.docx)

debug informaation 

[neuron_debug_1638893466608.zip](https://github.com/nervosnetwork/neuron/files/7669853/neuron_debug_1638893466608.zip)

**Comment by kellyshang** [comment]
@gabisena424 try the latest version of [v0.101.2](https://github.com/nervosnetwork/neuron/releases/tag/v0.101.2)

**Comment by gabisena424** [comment]
gostaria de saber se corro risco de perder meu CKBs ?

estou temerosa

**Comment by kellyshang** [comment]
Your ckb won't lose as it's on chain. The version you are using may have bug on compatibility. The latest version should have fixed the bug.

**Comment by gabisena424** [comment]
E AGORA O QUE DEVO FAZER ?

JA FAZEM 7 DIAS QUA TRANSACAO ESTA PENDENTE
