### ISSUE TITLE
transação pendente

### ISSUE THREAD

**Issue by gabisena424** [nervosnetwork/neuron#2218]
fiz a ultima atualização da carteira neurom  como sugerido e minha retirada ainda esta pendente.

caso faça withdraw antes da epoca 53 acontece?

O que devo fazer ?

debug information

[neuron_debug_1639169423416.zip](https://github.com/nervosnetwork/neuron/files/7695394/neuron_debug_1639169423416.zip)

foto de tela
[20211205.Nervos.DAO.screenshot.docx](https://github.com/nervosnetwork/neuron/files/7695401/20211205.Nervos.DAO.screenshot.docx)

**Comment by kellyshang** [comment]
Hi @gabisena424 , try to **double**-clear cache and wait for re-sync to see if it works:
![image](https://user-images.githubusercontent.com/28836185/145717937-ffe13923-bb6a-41a2-8afc-3517dcef4c08.png)
