### ISSUE TITLE
Neuron wallet update 0.101.2

### ISSUE THREAD

**Issue by vdubbed** [nervosnetwork/neuron#2219]
I’ve just updated my NW to 0.101.2 with the option of “myself” only as a user whereas with the previous version with the option of “anyone who uses this computer “. Now I have two identical icons on my desktop  - an old version and an updated one. Both old and new versions sync and show the correct balance. On switching to my other Microsoft account, as expected I only see an old version of NW software on desktop that’s never been synced - which I’ve chosen “anyone who uses this computer” previously on my original Microsoft account. 

 I was wondering why I’ve got 2 versions of Neuron wallet and how I could remove the old version on my original Microsoft account and keep only the updated version? Would choosing “Uninstall” in the Neuron folder uninstall both old and new versions? Or do I simply just delete the Neuron icon of the old version on desktop? I’ve only connected my hardware wallet to Neuron wallet when I first installed, so would my ledger device’s 24 word seed phrase be the only thing that I’d need if I chose to reinstall the Neuron wallet? Thanks for the help.

**Comment by kellyshang** [comment]
@vdubbed :
1. Yes you can choose "Uninstall" to uninstall the one you don't need (the installation path should be different for "anyone" and "myself). 
2. Yes the 24 word seed phrase is the only thing that you need to reinstall. You can also backup your wallet to export as an keystore as a double guarantee.

**Comment by vdubbed** [comment]
Thanks very much for the advice. 👍
