### ISSUE TITLE
Mainet not sync

### ISSUE THREAD

**Issue by Ajotago** [nervosnetwork/neuron#2220]
**Describe the bug** (Please enter details, the more detail the better)
Wallet not synced

**Debug info** (Please upload the debug info from `Help` - `Export Debug Information`)
[neuron_debug_1639334763984.zip](https://github.com/nervosnetwork/neuron/files/7699346/neuron_debug_1639334763984.zip)

**Screenshots** (If applicable, add screenshots to help explain your problem.)
![image](https://user-images.githubusercontent.com/96021191/145725487-4d2076af-f147-43aa-ae53-0018dc29c247.png)

**Comment by Ajotago** [comment]
I Try install the redist and then restart Neuron, I cleared cache, restart pc, unisntall and reinstall Neuron. 
Nothing happend. I'm confused because I wont move my earnings from mining into a exchange :/

**Comment by Ajotago** [comment]
I dont know what to do next......

[neuron_debug_1639350183963.zip](https://github.com/nervosnetwork/neuron/files/7700042/neuron_debug_1639350183963.zip)

**Comment by kellyshang** [comment]
@Ajotago The bundled CKB node didn't start on your PC. Try install the redist and then restart Neuron: https://docs.microsoft.com/en-US/cpp/windows/latest-supported-vc-redist?view=msvc-170 
![image](https://user-images.githubusercontent.com/28836185/145760126-4cbae39f-c054-44f4-964c-f8bf4e9476b2.png)
