### ISSUE TITLE
Allow Neuron Wallet to accept sUDT assets on Neuron addresses?

### ISSUE THREAD

**Issue by VISQonSpotify** [nervosnetwork/neuron#2223]
I had used NexisDAO to mint dCKB on their platform and I accidentally transferred my dCKB to my Neuron address. The asset is there, however, there is no way to access it. This has also happened to others in the Nervos community and we would love it if this can be implemented so others can not have the same issue as we are having. Not only would it help, but it'll make it future-proof to where others can't make the same mistake we've made.

You can see the asset here: https://explorer.nervos.org/address/ckb1qyq08w7ustegc63wd85x9u6rzlmntsjnxuasefafvq

**Comment by blockchainRick** [comment]
I also have this same issue. I was under the impression it was treated the same as CKB and sent it to the neuron wallet not knowing after getting it stuck in Yokaiswap and not being able to send it back to NexisDAO. Thanks for any help in the matter. It can be seen here:

https://explorer.nervos.org/address/ckb1qyqfvdfhwu0t27ykc6yn6mzlszdpw3gnyq5qt5cgev

**Comment by Keith-CY** [comment]
Hi @VISQonSpotify and @blockchainRick

We've got several feedbacks about this annoying problem and had a discussion recently.

The neuron is kind of conservative and follows all well-grained RFCs, so it won't handle the unofficial assets until they are included in RFC.

To unlock these unrecognized assets in neuron, we're going to make a new tool featuring full interoperability that can handle UDT mentioned above.

An alpha version will be released by 2022/05/20 and I'll update in this issue.

**Comment by VISQonSpotify** [comment]
> Hi @VISQonSpotify and @blockchainRick
> 
> We've got several feedbacks about this annoying problem and had a discussion recently.
> 
> The neuron is kind of conservative and follows all well-grained RFCs, so it won't handle the unofficial assets until they are included in RFC.
> 
> To unlock these unrecognized assets in neuron, we're going to make a new tool featuring full interoperability that can handle UDT mentioned above.
> 
> An alpha version will be released by 2022/05/20 and I'll update in this issue.

I really appreciate this! Thank you for working on it.

**Comment by blockchainRick** [comment]
> Hi @VISQonSpotify and @blockchainRick
> 
> We've got several feedbacks about this annoying problem and had a discussion recently.
> 
> The neuron is kind of conservative and follows all well-grained RFCs, so it won't handle the unofficial assets until they are included in RFC.
> 
> To unlock these unrecognized assets in neuron, we're going to make a new tool featuring full interoperability that can handle UDT mentioned above.
> 
> An alpha version will be released by 2022/05/20 and I'll update in this issue.

This is great news. Thank you so much!

**Comment by jimsrc** [comment]
I have the same problem.
I bridged some ETH from Ethereum network to Nervos, but I can't see them in Neuron wallet.
I do see them in explorer.nervos.org though.

**Comment by E-Coder1987** [comment]
Hi there!

Is this still planned and on the way?

I got 4.2 bnb stuck as sUDT which I cannot access 😩

> > Hi @VISQonSpotify and @blockchainRick
> 
> > 
> 
> > We've got several feedbacks about this annoying problem and had a discussion recently.
> 
> > 
> 
> > The neuron is kind of conservative and follows all well-grained RFCs, so it won't handle the unofficial assets until they are included in RFC.
> 
> > 
> 
> > To unlock these unrecognized assets in neuron, we're going to make a new tool featuring full interoperability that can handle UDT mentioned above.
> 
> > 
> 
> > An alpha version will be released by 2022/05/20 and I'll update in this issue.
> 
> 
> 
> I really appreciate this! Thank you for working on it.

**Comment by Keith-CY** [comment]
> Hi there!
> 
> Is this still planned and on the way?
> 
> I got 4.2 bnb stuck as sUDT which I cannot access 😩
> 
> > > Hi @VISQonSpotify and @blockchainRick
> > 
> > 
> > > 
> > 
> > 
> > > We've got several feedbacks about this annoying problem and had a discussion recently.
> > 
> > 
> > > 
> > 
> > 
> > > The neuron is kind of conservative and follows all well-grained RFCs, so it won't handle the unofficial assets until they are included in RFC.
> > 
> > 
> > > 
> > 
> > 
> > > To unlock these unrecognized assets in neuron, we're going to make a new tool featuring full interoperability that can handle UDT mentioned above.
> > 
> > 
> > > 
> > 
> > 
> > > An alpha version will be released by 2022/05/20 and I'll update in this issue.
> > 
> > 
> > I really appreciate this! Thank you for working on it.

We've started the technical designing of the new product last week.

**Comment by Keith-CY** [comment]
Hi @VISQonSpotify @blockchainRick @jimsrc @E-Coder1987 

We have delivered this feature in [Neuron@v0.103.0](https://github.com/nervosnetwork/neuron/releases/tag/v0.103.0) with this [PR](https://github.com/nervosnetwork/neuron/pull/2330)

The simplest workflow is as follows,


https://user-images.githubusercontent.com/7271329/167488244-15ae0b8d-7e8e-4c1a-a192-9f87da2d173b.mov


This video shows how to turn a `sudt/secp256k1` asset into an sudt asset account in neuron.

Also, we support migrating the entire asset into an existing acp asset account with the second tab.

BTW, the new tool I mentioned above is hung :(

**Comment by E-Coder1987** [comment]
Thanks so much
I got bnb stuck there as an sudt 

Can I send it to my metamask address after I do that what is seen in the video?

**Comment by Keith-CY** [comment]
There's an undetected bug in v0.101.3 that `check for updates` in settings does not work, you may update neuron from `menu -> neuron -> check for updates`

Ref: https://github.com/nervosnetwork/neuron/issues/2372

**Comment by Keith-CY** [comment]
> Thanks so much I got bnb stuck there as an sudt
> 
> Can I send it to my metamask address after I do that what is seen in the video?

It's possible if you are using portal wallet https://ckb.pw/ , the pw address(portal wallet address) is allowed in sudt transfer and each pw address has a corresponding eth address so you can transfer them with metamask.

This feature has been implemented by [PR](https://github.com/nervosnetwork/neuron/pull/1928) two years ago, and the test environment of pw address is not available. I need some days to double check this function.

**Comment by E-Coder1987** [comment]
Damn that's all so complicated for me sorry!

I bridged them into the wrong address the bnb and now they are an sudt.

Could you maybe be so very very kind as to guide me how I get those bnb out of my wallet and into my bsc metamask address?

On ckb.pw I don't see them when I connect:
![image](https://user-images.githubusercontent.com/100139700/167497447-87213a49-5363-4313-a056-c9f86921f05d.png)

**Comment by VISQonSpotify** [comment]
> Damn that's all so complicated for me sorry!
> 
> I bridged them into the wrong address the bnb and now they are an sudt.
> 
> Could you maybe be so very very kind as to guide me how I get those bnb out of my wallet and into my bsc metamask address?
> 
> On ckb.pw I don't see them when I connect: ![image](https://user-images.githubusercontent.com/100139700/167497447-87213a49-5363-4313-a056-c9f86921f05d.png)

Maybe you can try using the Force Bridge. [https://forcebridge.com/bridge/Nervos/Bsc](https://forcebridge.com/bridge/Nervos/Bsc)

**Comment by VISQonSpotify** [comment]
> Damn that's all so complicated for me sorry!
> 
> I bridged them into the wrong address the bnb and now they are an sudt.
> 
> Could you maybe be so very very kind as to guide me how I get those bnb out of my wallet and into my bsc metamask address?
> 
> On ckb.pw I don't see them when I connect: ![image](https://user-images.githubusercontent.com/100139700/167497447-87213a49-5363-4313-a056-c9f86921f05d.png)

I believe if you send your bnb to your YokaiSwap L1 Address, that should work and then you can use the bridge to correct it. I'm double checking on my end first to see if my dckb will. 

![image](https://user-images.githubusercontent.com/1677300/167536527-28ab16d5-9df5-40c5-a9fa-946f3667e47e.png)

**Comment by blockchainRick** [comment]
@Keith-CY thank you so much! Worked great and I got my assets unstuck and send to NexisDAO so I could unlock my funds there. Thanks again!

**Comment by finnj7** [comment]
Hey guys. I had a customized asset in Neuron. I added a new SUDT [dCKB*] as per the video above. 

Now when I try to send the asset, I get an error to state that "There isn't an account wallet associated with this address"

The address I'm trying to send my dCKB to is my Yokaiswap L1 address. Can anyone help?


*Token ID: 0xe5451c05231e1df43e4b199b5d12dbed820dfbea2769943bb593f874526eeb55
and I used Decimal = 8 when creating

**Comment by E-Coder1987** [comment]
> > Damn that's all so complicated for me sorry!
> 
> > 
> 
> > I bridged them into the wrong address the bnb and now they are an sudt.
> 
> > 
> 
> > Could you maybe be so very very kind as to guide me how I get those bnb out of my wallet and into my bsc metamask address?
> 
> > 
> 
> > On ckb.pw I don't see them when I connect: ![image](https://user-images.githubusercontent.com/100139700/167497447-87213a49-5363-4313-a056-c9f86921f05d.png)
> 
> 
> 
> I believe if you send your bnb to your YokaiSwap L1 Address, that should work and then you can use the bridge to correct it. I'm double checking on my end first to see if my dckb will. 
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/1677300/167536527-28ab16d5-9df5-40c5-a9fa-946f3667e47e.png)
> 
> 

Did you maybe get a chance to verify how to do it?
Here is the explorer link to my wallet... I need to get out those bnb into my metamask wallet again:

https://explorer.nervos.org/address/ckb1qyqgk6nz7hezdj670xzqpjjewktw0nta76aqtalv9p

Thanks in advance for your help!

**Comment by E-Coder1987** [comment]
> Hey guys. I had a customized asset in Neuron. I added a new SUDT [dCKB*] as per the video above.
> 
> Now when I try to send the asset, I get an error to state that "There isn't an account wallet associated with this address"
> 
> The address I'm trying to send my dCKB to is my Yokaiswap L1 address. Can anyone help?
> 
> *Token ID: 0xe5451c05231e1df43e4b199b5d12dbed820dfbea2769943bb593f874526eeb55 and I used Decimal = 8 when creating

I get this too, added my BNB in a new Asset Account with decimal 18
When I try to send them to L1 Address it says the same:

<img width="2546" alt="image" src="https://user-images.githubusercontent.com/100139700/167722021-9aa83901-fc28-4e01-8076-46be648616e5.png">

**Comment by yanguoyu** [comment]
> > Hey guys. I had a customized asset in Neuron. I added a new SUDT [dCKB*] as per the video above.
> > Now when I try to send the asset, I get an error to state that "There isn't an account wallet associated with this address"
> > The address I'm trying to send my dCKB to is my Yokaiswap L1 address. Can anyone help?
> > *Token ID: 0xe5451c05231e1df43e4b199b5d12dbed820dfbea2769943bb593f874526eeb55 and I used Decimal = 8 when creating
> 
> I get this too, added my BNB in a new Asset Account with decimal 18 When I try to send them to L1 Address it says the same:
> 
> <img alt="image" width="2000" src="https://user-images.githubusercontent.com/100139700/167722021-9aa83901-fc28-4e01-8076-46be648616e5.png">
> 
> Asset Account config is as follows: <img alt="image" width="558" src="https://user-images.githubusercontent.com/100139700/167722113-cb943e22-af85-47da-be40-18917b717568.png">

A sudt account can transfer to a ckb address or the same sudt type address.
Is the transfer address a ckb address? I can't see the tips like this.
<img width="1186" alt="image" src="https://user-images.githubusercontent.com/12881040/167748686-dea14b0f-6210-4276-977b-d4aecf5f1fa7.png">

**Comment by E-Coder1987** [comment]
> > > Hey guys. I had a customized asset in Neuron. I added a new SUDT [dCKB*] as per the video above.
> > > Now when I try to send the asset, I get an error to state that "There isn't an account wallet associated with this address"
> > > The address I'm trying to send my dCKB to is my Yokaiswap L1 address. Can anyone help?
> > > *Token ID: 0xe5451c05231e1df43e4b199b5d12dbed820dfbea2769943bb593f874526eeb55 and I used Decimal = 8 when creating
> > 
> > 
> > I get this too, added my BNB in a new Asset Account with decimal 18 When I try to send them to L1 Address it says the same:
> > <img alt="image" width="2000" src="https://user-images.githubusercontent.com/100139700/167722021-9aa83901-fc28-4e01-8076-46be648616e5.png">
> > Asset Account config is as follows: <img alt="image" width="558" src="https://user-images.githubusercontent.com/100139700/167722113-cb943e22-af85-47da-be40-18917b717568.png">
> 
> A sudt account can transfer to a ckb address or the same sudt type address. Is the transfer address a ckb address? I can't see the tips like this. <img alt="image" width="1186" src="https://user-images.githubusercontent.com/12881040/167748686-dea14b0f-6210-4276-977b-d4aecf5f1fa7.png">

Hi!

The Address I entered is my yokaiswap L1 Address (NOT Deposit Address) from when I connect with my Safepal app to Yokaiswap -> shall I input a different one?

The Tip like in you Screenshot doesn't show (Running on Mac OS).
As soon as I enter an amount the Error Shows up:
There isn't an account wallet associated with this address.

**Comment by finnj7** [comment]
> > > > Hey guys. I had a customized asset in Neuron. I added a new SUDT [dCKB*] as per the video above.
> > > > Now when I try to send the asset, I get an error to state that "There isn't an account wallet associated with this address"
> > > > The address I'm trying to send my dCKB to is my Yokaiswap L1 address. Can anyone help?
> > > > *Token ID: 0xe5451c05231e1df43e4b199b5d12dbed820dfbea2769943bb593f874526eeb55 and I used Decimal = 8 when creating
> > > 
> > > 
> > > I get this too, added my BNB in a new Asset Account with decimal 18 When I try to send them to L1 Address it says the same:
> > > <img alt="image" width="2000" src="https://user-images.githubusercontent.com/100139700/167722021-9aa83901-fc28-4e01-8076-46be648616e5.png">
> > > Asset Account config is as follows: <img alt="image" width="558" src="https://user-images.githubusercontent.com/100139700/167722113-cb943e22-af85-47da-be40-18917b717568.png">
> > 
> > 
> > A sudt account can transfer to a ckb address or the same sudt type address. Is the transfer address a ckb address? I can't see the tips like this. <img alt="image" width="1186" src="https://user-images.githubusercontent.com/12881040/167748686-dea14b0f-6210-4276-977b-d4aecf5f1fa7.png">
> 
> Hi!
> 
> The Address I entered is my yokaiswap L1 Address (NOT Deposit Address) from when I connect with my Safepal app to Yokaiswap -> shall I input a different one?
> 
> The Tip like in you Screenshot doesn't show (Running on Mac OS). As soon as I enter an amount the Error Shows up: There isn't an account wallet associated with this address.

Same goes for me. I've managed to convert the customized asset into an Account Asset for dCKB in Neuron. When I try to transfer it to Yokai L1 address I get the error message. I've played around with a few different addresses, it has the same error

**Comment by E-Coder1987** [comment]
> > Hey guys. I had a customized asset in Neuron. I added a new SUDT [dCKB*] as per the video above.
> 
> > 
> 
> > Now when I try to send the asset, I get an error to state that "There isn't an account wallet associated with this address"
> 
> > 
> 
> > The address I'm trying to send my dCKB to is my Yokaiswap L1 address. Can anyone help?
> 
> > 
> 
> > *Token ID: 0xe5451c05231e1df43e4b199b5d12dbed820dfbea2769943bb593f874526eeb55 and I used Decimal = 8 when creating
> 
> 
> 
> Hi @finnj7 , you're facing the same problem @E-Coder1987 is suffering.
> 
> 
> 
> > How to transfer sudt from neuron to yokaiswap
> 
> 
> 
> It cannot be done directly because neuron is more conservative and only lock scripts verified by time will be allowed. Specifically, only `secp256k1/blake160`, `anyone-can-pay` and `pwlock-acp` lock scripts are allowed to transfer sudt assets.
> 
> 
> 
> I've done some investigation and there're two solutions
> 
> 
> 
> The first one is a little complex and not suggested:
> 
>   1. You need some balance of the same sudt in force bridge of previous version(using pwlock)
> 
>   2. Send sudt from Neuron to the ckb address(pwlock) shown in force bridge
> 
>   3. use the tool(https://github.com/homura/pw-up) to migrate ckb address(pwlock) to ckb address(yokai)
> 
> 
> 
> The second one: 
> 
> 
> 
> yokai and force bridge of current version are both using a new lock script introduced with this hardfork, named `omni lock`(also mentioned in pw-up above), its strongly suggested now but not listed in RFC yet so neuron does not support it. I'll check in today's meeting that can we add it to the whitelist so neuron can send sudt to omni lock, including yokai address. If yes, we'll try our best to support yokai address in neuron and deliver it in the next version(should be in a month).
> 
> 

Thanks for you reply again!

Option 2 lets my assets be stuck one more month 😩

Could you elaborate how to do option one exactly?

**Comment by Keith-CY** [comment]
> > > Hey guys. I had a customized asset in Neuron. I added a new SUDT [dCKB*] as per the video above.
> > 
> > 
> > > 
> > 
> > 
> > > Now when I try to send the asset, I get an error to state that "There isn't an account wallet associated with this address"
> > 
> > 
> > > 
> > 
> > 
> > > The address I'm trying to send my dCKB to is my Yokaiswap L1 address. Can anyone help?
> > 
> > 
> > > 
> > 
> > 
> > > *Token ID: 0xe5451c05231e1df43e4b199b5d12dbed820dfbea2769943bb593f874526eeb55 and I used Decimal = 8 when creating
> > 
> > 
> > Hi @finnj7 , you're facing the same problem @E-Coder1987 is suffering.
> > > How to transfer sudt from neuron to yokaiswap
> > 
> > 
> > It cannot be done directly because neuron is more conservative and only lock scripts verified by time will be allowed. Specifically, only `secp256k1/blake160`, `anyone-can-pay` and `pwlock-acp` lock scripts are allowed to transfer sudt assets.
> > I've done some investigation and there're two solutions
> > The first one is a little complex and not suggested:
> > 
> > 1. You need some balance of the same sudt in force bridge of previous version(using pwlock)
> > 2. Send sudt from Neuron to the ckb address(pwlock) shown in force bridge
> > 3. use the tool([homura/pw-up](https://github.com/homura/pw-up)) to migrate ckb address(pwlock) to ckb address(yokai)
> > 
> > The second one:
> > yokai and force bridge of current version are both using a new lock script introduced with this hardfork, named `omni lock`(also mentioned in pw-up above), its strongly suggested now but not listed in RFC yet so neuron does not support it. I'll check in today's meeting that can we add it to the whitelist so neuron can send sudt to omni lock, including yokai address. If yes, we'll try our best to support yokai address in neuron and deliver it in the next version(should be in a month).
> 
> Thanks for you reply again!
> 
> Option 2 lets my assets be stuck one more month 😩
> 
> Could you elaborate how to do option one exactly?

Hi @E-Coder1987 , I posted this issue in meeting and discussed with other teams, they all disagreed with the first option strongly, because pwlock is not recommended and no one is going  to deploy a force bridge working with pwlock.

The option 2 (suppoting omnilock in neuron) also does not help, because yokaiswap is not using an official omnilock lock script.

To enable sending sudt to yokaiswap or addresses other than `secp256k1`, `anyone-can-pay`, `pwlock`, we're going to add a dev mode(temporarily named) to loosen restriction of verification. It takes about 2 weeks to develop and 1 week to test.

BTW, are you going to deposit your sudt into godwoken via yokaiswap? If yes, we also suggest you to do this one month later, because godwoken will upgrade to v1 after a month and v0, v1 are incompatible, so users have to withdraw their assets from godwoken v0 to ckb, and then deposit them to godwoken v1 again.

**Comment by finnj7** [comment]
> osit your sudt into go

Hey thanks for that, good to hear. I am not too bothered about when this is available as I know my assets are safe. It sounds complicated at the moment to resolve so I am happy to wait!

**Comment by E-Coder1987** [comment]
> > > > Hey guys. I had a customized asset in Neuron. I added a new SUDT [dCKB*] as per the video above.
> > > 
> > > 
> > > > 
> > > 
> > > 
> > > > Now when I try to send the asset, I get an error to state that "There isn't an account wallet associated with this address"
> > > 
> > > 
> > > > 
> > > 
> > > 
> > > > The address I'm trying to send my dCKB to is my Yokaiswap L1 address. Can anyone help?
> > > 
> > > 
> > > > 
> > > 
> > > 
> > > > *Token ID: 0xe5451c05231e1df43e4b199b5d12dbed820dfbea2769943bb593f874526eeb55 and I used Decimal = 8 when creating
> > > 
> > > 
> > > Hi @finnj7 , you're facing the same problem @E-Coder1987 is suffering.
> > > > How to transfer sudt from neuron to yokaiswap
> > > 
> > > 
> > > It cannot be done directly because neuron is more conservative and only lock scripts verified by time will be allowed. Specifically, only `secp256k1/blake160`, `anyone-can-pay` and `pwlock-acp` lock scripts are allowed to transfer sudt assets.
> > > I've done some investigation and there're two solutions
> > > The first one is a little complex and not suggested:
> > > 
> > > 1. You need some balance of the same sudt in force bridge of previous version(using pwlock)
> > > 2. Send sudt from Neuron to the ckb address(pwlock) shown in force bridge
> > > 3. use the tool([homura/pw-up](https://github.com/homura/pw-up)) to migrate ckb address(pwlock) to ckb address(yokai)
> > > 
> > > The second one:
> > > yokai and force bridge of current version are both using a new lock script introduced with this hardfork, named `omni lock`(also mentioned in pw-up above), its strongly suggested now but not listed in RFC yet so neuron does not support it. I'll check in today's meeting that can we add it to the whitelist so neuron can send sudt to omni lock, including yokai address. If yes, we'll try our best to support yokai address in neuron and deliver it in the next version(should be in a month).
> > 
> > 
> > Thanks for you reply again!
> > Option 2 lets my assets be stuck one more month 😩
> > Could you elaborate how to do option one exactly?
> 
> Hi @E-Coder1987 , I posted this issue in meeting and discussed with other teams, they all disagreed with the first option strongly, because pwlock is not recommended and no one is going to deploy a force bridge working with pwlock.
> 
> The option 2 (supporting omnilock in neuron) also does not help, because yokaiswap is not using an official omnilock lock script.
> 
> To enable sending sudt to yokaiswap or addresses other than `secp256k1`, `anyone-can-pay`, `pwlock`, we're going to add a dev mode(temporarily named) to loosen restriction of verification. It takes about 2 weeks to develop and 1 week to test.
> 
> BTW, are you going to deposit your sudt into godwoken via yokaiswap? If yes, we also suggest you to do this one month later, because godwoken will upgrade to v1 after a month and v0, v1 are incompatible, so users have to withdraw their assets from godwoken v0 to ckb, and then deposit them to godwoken v1 again.

Hm ok so i will have to wait again than :(

I Dont know what version or chain? I open up yokaiswap on my Safepal app and then click on wallet and search for the L1 Yokai Wallet address -> Is this godwoken or ckb ?

**Comment by VISQonSpotify** [comment]
@E-Coder1987 I didn't have any luck. Same issues as everyone else. I guess we will have to wait until the tool comes out.

**Comment by E-Coder1987** [comment]
Well then I'll wait - what else can I do :)

@Keith-CY : did the development start already? Is there an issue already created that i can track?
Thanks for the good work!

**Comment by Keith-CY** [comment]
Hi @E-Coder1987 @VISQonSpotify @finnj7 Sending sudt to yokai is supported in https://github.com/nervosnetwork/neuron/releases/tag/v0.103.1

https://user-images.githubusercontent.com/7271329/173234404-ad50cd60-56f1-4cde-9121-b77bb766acd2.mov

**Comment by E-Coder1987** [comment]
Cheers Mate that worked, I see them now. How do I send those BNB to my regular BSC Wallet?

**Comment by VISQonSpotify** [comment]
> Hi @E-Coder1987 @VISQonSpotify @finnj7 Sending sudt to yokai is supported in https://github.com/nervosnetwork/neuron/releases/tag/v0.103.1
> 
>  Screen.Recording.2022-06-12.at.20.54.02.mov

Sooo, I sent my dCKB to NexisDao thinking it will allow my dckb to be removed (I deposited ckb to get dckb) however, it's just sitting on this address and I have no access to it. It's saying it's not there at all via metamask.

https://explorer.nervos.org/address/ckb1qzl58smqy32hnrq6vxjedcxe2fugvnz497h7yvwqvwel40uh4rltcqgg2dv90ynzfd0es5m27njyjxme2kd2rlqgkhl3q

**Comment by Keith-CY** [comment]
> > Hi @E-Coder1987 @VISQonSpotify @finnj7 Sending sudt to yokai is supported in [`v0.103.1` (release)](https://github.com/nervosnetwork/neuron/releases/tag/v0.103.1)
> > Screen.Recording.2022-06-12.at.20.54.02.mov
> 
> Sooo, I sent my dCKB to NexisDao thinking it will allow my dckb to be removed (I deposited ckb to get dckb) however, it's just sitting on this address and I have no access to it. It's saying it's not there at all via metamask.
> 
> [explorer.nervos.org/address/ckb1qzl58smqy32hnrq6vxjedcxe2fugvnz497h7yvwqvwel40uh4rltcqgg2dv90ynzfd0es5m27njyjxme2kd2rlqgkhl3q](https://explorer.nervos.org/address/ckb1qzl58smqy32hnrq6vxjedcxe2fugvnz497h7yvwqvwel40uh4rltcqgg2dv90ynzfd0es5m27njyjxme2kd2rlqgkhl3q)

I'm not quite familiar with tools of NexisDao so I'm going to ask for help from NexisDao team

**Comment by Keith-CY** [comment]
> > Hi @E-Coder1987 @VISQonSpotify @finnj7 Sending sudt to yokai is supported in [`v0.103.1` (release)](https://github.com/nervosnetwork/neuron/releases/tag/v0.103.1)
> > Screen.Recording.2022-06-12.at.20.54.02.mov
> 
> Sooo, I sent my dCKB to NexisDao thinking it will allow my dckb to be removed (I deposited ckb to get dckb) however, it's just sitting on this address and I have no access to it. It's saying it's not there at all via metamask.
> 
> [explorer.nervos.org/address/ckb1qzl58smqy32hnrq6vxjedcxe2fugvnz497h7yvwqvwel40uh4rltcqgg2dv90ynzfd0es5m27njyjxme2kd2rlqgkhl3q](https://explorer.nervos.org/address/ckb1qzl58smqy32hnrq6vxjedcxe2fugvnz497h7yvwqvwel40uh4rltcqgg2dv90ynzfd0es5m27njyjxme2kd2rlqgkhl3q)

I was led to Nexis DAO discord channel and found you've asked about this case there. I think help from them would be more useful.

**Comment by finnj7** [comment]
> > Hi @E-Coder1987 @VISQonSpotify @finnj7 Sending sudt to yokai is supported in https://github.com/nervosnetwork/neuron/releases/tag/v0.103.1
> > Screen.Recording.2022-06-12.at.20.54.02.mov
> 
> Sooo, I sent my dCKB to NexisDao thinking it will allow my dckb to be removed (I deposited ckb to get dckb) however, it's just sitting on this address and I have no access to it. It's saying it's not there at all via metamask.
> 
> https://explorer.nervos.org/address/ckb1qzl58smqy32hnrq6vxjedcxe2fugvnz497h7yvwqvwel40uh4rltcqgg2dv90ynzfd0es5m27njyjxme2kd2rlqgkhl3q

You might need to wait for the epoch to finish. It's like it's deposited in the DAO, that can take up to 30 days.

**Comment by VISQonSpotify** [comment]
> > > Hi @E-Coder1987 @VISQonSpotify @finnj7 Sending sudt to yokai is supported in [`v0.103.1` (release)](https://github.com/nervosnetwork/neuron/releases/tag/v0.103.1)
> > > Screen.Recording.2022-06-12.at.20.54.02.mov
> > 
> > 
> > Sooo, I sent my dCKB to NexisDao thinking it will allow my dckb to be removed (I deposited ckb to get dckb) however, it's just sitting on this address and I have no access to it. It's saying it's not there at all via metamask.
> > [explorer.nervos.org/address/ckb1qzl58smqy32hnrq6vxjedcxe2fugvnz497h7yvwqvwel40uh4rltcqgg2dv90ynzfd0es5m27njyjxme2kd2rlqgkhl3q](https://explorer.nervos.org/address/ckb1qzl58smqy32hnrq6vxjedcxe2fugvnz497h7yvwqvwel40uh4rltcqgg2dv90ynzfd0es5m27njyjxme2kd2rlqgkhl3q)
> 
> I was led to Nexis DAO discord channel and found you've asked about this case there. I think help from them would be more useful.

Do you have a link to that specific case?

**Comment by Keith-CY** [comment]
> > > > Hi @E-Coder1987 @VISQonSpotify @finnj7 Sending sudt to yokai is supported in [`v0.103.1` (release)](https://github.com/nervosnetwork/neuron/releases/tag/v0.103.1)
> > > > Screen.Recording.2022-06-12.at.20.54.02.mov
> > > 
> > > 
> > > Sooo, I sent my dCKB to NexisDao thinking it will allow my dckb to be removed (I deposited ckb to get dckb) however, it's just sitting on this address and I have no access to it. It's saying it's not there at all via metamask.
> > > [explorer.nervos.org/address/ckb1qzl58smqy32hnrq6vxjedcxe2fugvnz497h7yvwqvwel40uh4rltcqgg2dv90ynzfd0es5m27njyjxme2kd2rlqgkhl3q](https://explorer.nervos.org/address/ckb1qzl58smqy32hnrq6vxjedcxe2fugvnz497h7yvwqvwel40uh4rltcqgg2dv90ynzfd0es5m27njyjxme2kd2rlqgkhl3q)
> > 
> > 
> > I was led to Nexis DAO discord channel and found you've asked about this case there. I think help from them would be more useful.
> 
> Do you have a link to that specific case?

https://discord.com/channels/879679105606516777/904928286273077311/1007733980914798592
