### ISSUE TITLE
dCKB (NexisDAO) stuck in Neuron Wallet - sUDT asset Support?

### ISSUE THREAD

**Issue by blockchainRick** [nervosnetwork/neuron#2224]
I sent 5000 dCKB minted at Nexis DAO to Yokaiswap initially before it was functional not realizing I couldn't use them there yet. When I couldn't send them back to Nexis, I sent them to Neuron Wallet not realizing it was not supported and now they are stuck in there inaccessible. Is there a way to make them available to send back out so I can unlock my CKB over at Nexis?

Transaction is viewable here:
https://explorer.nervos.org/transaction/0x440f9d780b92720a29f17f8088f11e8bd70280d48b9d0f14ce7488b06b36ee5d

**Comment by VISQonSpotify** [comment]
Please make a tool for people to access this, thanks!

**Comment by Keith-CY** [comment]
A new tool will be released by 2022/05/20, mentioned in https://github.com/nervosnetwork/neuron/issues/2223#issuecomment-1001901666

**Comment by blockchainRick** [comment]
@Keith-CY wonderful news. Thank you!

**Comment by E-Coder1987** [comment]
> A new tool will be released by 2022/05/20, mentioned in https://github.com/nervosnetwork/neuron/issues/2223#issuecomment-1001901666

Hi! Is this already confirmed?
I got wbnb stuck as sUDT on my wallet and cannot access it.
Thanks!

**Comment by Keith-CY** [comment]
Hi @blockchainRick @VISQonSpotify @E-Coder1987 

I leaf a comment about this feature in https://github.com/nervosnetwork/neuron/issues/2223#issuecomment-1121520873
