### ISSUE TITLE
why withdraw fail? and how about the subsidized rate during withdraw

### ISSUE THREAD

**Issue by compasses** [nervosnetwork/neuron#2225]
**Describe the bug** (Please enter details, the more detail the better)
have do the withdraw on '2021-11-19'，from the rule my asset should be unlocked yesterday.
But now it get locked again....
I really need it unlock right now,  So what can I do now?
![image](https://user-images.githubusercontent.com/10161171/147380781-71b0d8b9-cbc8-4c92-b370-1c8e8a98e850.png)

And during the withdraw process, can I still get the APC earnings ?

big thanks...

**Comment by VISQonSpotify** [comment]
Is your wallet fully synced?

**Comment by compasses** [comment]
> Is your wallet fully synced?
@VISQonSpotify 

Sure, Now it's fully synced. I think it's should be synced month ago when I withdraw it.
But in the middle I did upgrade the wallet. 
So I don't know why it's start withdraw again, it was supposed to be unlocked on 2021-12-23
big thanks

![image](https://user-images.githubusercontent.com/10161171/147727904-53e10f39-05e0-437e-8450-fc1037ca108e.png)

**Comment by compasses** [comment]
@VISQonSpotify Hi do you have any idea to make sure the withdraw will be succeed next time?
BTW, any other wallet to make change on my staking DAO?
big thanks.

**Comment by VISQonSpotify** [comment]
Sorry if this was already done but have you updated your neuron wallet? Go to settings and click update.

**Comment by VISQonSpotify** [comment]
> @VISQonSpotify Hi do you have any idea to make sure the withdraw will be succeed next time?
> 
> BTW, any other wallet to make change on my staking DAO?
> 
> big thanks.

You can use imToken wallet and use the site ckb.pw or something like that.

And there's also Yokaiswap for DeFi.

**Comment by compasses** [comment]
@VISQonSpotify 
Hi, Cannot use imToken, cannot open it..., seems the ckb.pw cannot reach inland.
Actually, I just want release my ckb in DAO to do farming on Yokaiswap, but cannot withdraw now.

Now seem the Neuron wallet cannot work, cannot sync block now,  the address is error ? 
![image](https://user-images.githubusercontent.com/10161171/148161218-59a5a98e-4c0b-430b-8c1b-2c2fbc90f1d8.png)

**Comment by VISQonSpotify** [comment]
> Sorry if this was already done but have you updated your neuron wallet? Go to settings and click update.

![image](https://user-images.githubusercontent.com/1677300/148221544-88ad940c-797b-45d9-8fa3-fde146dc2f2c.png)

Sorry if this was already done but have you updated your neuron wallet? Go to settings and click update.

**Comment by compasses** [comment]
@VISQonSpotify yes  already the newest version:
![image](https://user-images.githubusercontent.com/10161171/148243155-bf8a6a0e-ad58-4d1d-a549-f4d34d897050.png)

**Comment by compasses** [comment]
@VISQonSpotify 
Hi, this is the time begin, will it success this time?

![image](https://user-images.githubusercontent.com/10161171/149865422-101bbb08-88a2-4efb-9b7b-d25c27912c27.png)

Or any way to remedy ??
Big thanks :)

**Comment by VISQonSpotify** [comment]
@compasses yes, that is the correct time to withdraw. Then, after you withdraw, you'll wait some days and then you will come back and hit the "withdraw" again, and then it will remove it from the dao.

**Comment by compasses** [comment]
> @compasses yes, that is the correct time to withdraw. Then, after you withdraw, you'll wait some days and then you will come back and hit the "withdraw" again, and then it will remove it from the dao.

**Comment by compasses** [comment]
> @compasses yes, that is the correct time to withdraw. Then, after you withdraw, you'll wait some days and then you will come back and hit the "withdraw" again, and then it will remove it from the dao.

@VISQonSpotify  Hi, as you can see, I cannot do any actions now, I have withdraw two months ago :(, 
My question is will it success this time? And any way to do something to ensure that??

Big thanks.

**Comment by kellyshang** [comment]
Hi @compasses , on CKB the withdraw is a 2-phase process, after withdrawal, it still needs to wait for the lock period of 180 epoches to be complete before you can unlock it. 
Hope this doc can help you to understand the rule: 
https://docs.ckb.dev/docs/rfcs/0023-dao-deposit-withdraw/0023-dao-deposit-withdraw

**Comment by kellyshang** [comment]
@compasses Can you have a try to single-clear the cache? 
![image](https://user-images.githubusercontent.com/28836185/150246994-72dc119f-ca51-47ea-a113-2985df2b74cc.png)

**Comment by VISQonSpotify** [comment]
> Hi @compasses , on CKB the withdraw is a 2-phase process, after withdrawal, it still needs to wait for the lock period of 180 epoches to be complete before you can unlock it. Hope this doc can help you to understand the rule: https://docs.ckb.dev/docs/rfcs/0023-dao-deposit-withdraw/0023-dao-deposit-withdraw

Thanks for supplying the additional information 👍

**Comment by compasses** [comment]
> @compasses Can you have a try to single-clear the cache? ![image](https://user-images.githubusercontent.com/28836185/150246994-72dc119f-ca51-47ea-a113-2985df2b74cc.png)

@kellyshang My God ! thank you very much, that's work, and i can do the withdraw now...
that's confused me more than two months...
thanks again..

**Comment by compasses** [comment]
@kellyshang @VISQonSpotify  sorry to bother you again! 
As you can see in the following, the unlock process is meet expectation or some bad things happen? Do I need do something else? 
The transaction got stuck more than 24 hours ...

![image](https://user-images.githubusercontent.com/10161171/151092801-40ab15e5-9497-43c9-8f17-5ba3063c1af2.png)

![image](https://user-images.githubusercontent.com/10161171/151092727-e8447601-3535-4ee6-b9c1-1fa5601f3876.png)

**Comment by kellyshang** [comment]
Hi @compasses 
1. Does your Neuron's sync been completed? If not, should wait for the sync to be finalized.
2. If the synced has been completed but the tx still displayed as pending, it's because the transaction still not been broadcast to the chain network. Try restart the Neuron -- thus the pending transaction should be displayed as failed, then try to `Unlock` the DAO record again.

**Comment by compasses** [comment]
> Hi @compasses
> 
> 1. Does your Neuron's sync been completed? If not, should wait for the sync to be finalized.
> 2. If the synced has been completed but the tx still displayed as pending, it's because the transaction still not been broadcast to the chain network. Try restart the Neuron -- thus the pending transaction should be displayed as failed, then try to `Unlock` the DAO record again.

Yes ! thank you very much.
After restart the Neuron, the transaction is confirmed very soon..
Big thanks
