### ISSUE TITLE
Neuron wallet never syncs

### ISSUE THREAD

**Issue by kaceydoesdev** [nervosnetwork/neuron#2227]
I've restarted the program; deleted, and recreated wallets; restarted the computer; and deleted, and reinstalled the program. Nothing works. I've left it sitting for two days, and it never connects to the mainnet, or does any syncing. The issue is with an older iMac, but it has 10.13.6.

I have a new iMac with Monterey, and the wallet worked great. Took all day to sync, but it worked.

Figured I'd drop the debug info here.

Thanks!

[neuron_debug_1640908239191.zip](https://github.com/nervosnetwork/neuron/files/7794921/neuron_debug_1640908239191.zip)

**Comment by kellyshang** [comment]
Hi @kaceydoesdev , the bundled CKB node does not support the macOS version below `10.15`. You'd better upgrade your OS version or run on another PC which OS version is equal to or higher than `10.15`.

Or you can build the [CKB node](https://github.com/nervosnetwork/ckb) by yourself (not recommend).
