### ISSUE TITLE
Very very slow syncing

### ISSUE THREAD

**Issue by KaungMyatKyaw123** [nervosnetwork/neuron#2230]
I downloaded neuron wallet and opened new account all is okay but syncing rate is too slow I saw about 6 millions blocks on ckb explorer and my syncing rate is 1.5 millions in 2 days, why is this very slow ?

### my network is medium rate. window 10 OS

**Comment by kellyshang** [comment]
The syncing for Neuron including two parts: the sync of the bundled CKB node and the sync of the Neuron db from the CKB node. And the sync rate on Win OS is slower than Mac OS which is slower than Linux.
Also the sync rate will depend on your PC's performance & the network status. 
And you'd better keep the PC not sleeping when syncing.
