### ISSUE TITLE
Neuron 0.101.2 钱包一直显示 同步尚未开始

### ISSUE THREAD

**Issue by caitlingao** [nervosnetwork/neuron#2231]
**Describe the bug** (Please enter details, the more detail the better)
已同步区块0%， 0/0
同步尚未开始

**Debug info** (Please upload the debug info from `Help` - `Export Debug Information`)
OS & Version: [macOS Monterey 12.0.1]
Neuron Version [0.101.2]
Block Number:

**Screenshots** (If applicable, add screenshots to help explain your problem.)
[neuron_debug_1641797669242.zip](https://github.com/nervosnetwork/neuron/files/7837227/neuron_debug_1641797669242.zip)

**ps**
1. 关掉 Neuron
2. 删掉数据目录 ~/Library/Application/Support/Neuron/chains
3. 启动 Neuron 后仍不生效

**Comment by kellyshang** [comment]
@caitlingao 在退出 Neuron 后，你看一下活动监视器里是否还有 ckb 或者  ckb-indexer 进程在，如果有的话手动关闭一下，然后重启 Neuron 试试看。
（在 v0.101.1 版本有个遗留的 bug 就是在 Mac 系统上退出 Neuron 后 ckb 相关进程没有自动关闭，v0.101.2 应该修复了你可以再确认下）

**Comment by caitlingao** [comment]
把ckb和ckb-indexer进程杀掉后重启，开始同步区块了。谢谢

**Comment by kellyshang** [comment]
> @kellyshang 把ckb和ckb-indexer进程杀掉后重启，开始同步区块了。谢谢

好的不客气，要是没别的问题的话就先关闭这个 issue 了（有问题可以再 reopen）。
