### ISSUE TITLE
Neuron at 0% Block Synced, stuck connecting

### ISSUE THREAD

**Issue by Windwisperer** [nervosnetwork/neuron#2232]
Recently my established and fully synced wallet has started having issues.. The issue first started when I had to do a system restore to rollback a broken driver, then upon logging back in it never syncs with the blockchain. I have tried clearing cache, fully rebuild index, installed new version, installed microsoft c++ redist and nothing seems to work. I could see my DAO deposits before I updated to the new version, now nothing shows, and my balance doesn't show. Any thoughts on how to fix this? Do I need to completely uninstall? I'm nervous I may have irreparably messed something up somehow..

![Neuron_issue](https://user-images.githubusercontent.com/80657407/149048871-9869415a-f12a-4352-a4d7-c5ef29feb4ad.PNG)
[neuron_debug_1641951789115.zip](https://github.com/nervosnetwork/neuron/files/7850987/neuron_debug_1641951789115.zip)

**Comment by kellyshang** [comment]
From the log it indicates that your CKB node's db was corrupted. Maybe you need to delete the whole synced data and re-sync which may take a long time.

You can delete the whole synced data from the menu `Tools` - `Clear all synchronized data`: 
![image](https://user-images.githubusercontent.com/28836185/150083180-2e40c6d1-7ef1-436b-bbdc-d20c327184db.png)
