### ISSUE TITLE
messages.fields. is too short, it should be longer than or equal to .

### ISSUE THREAD

**Issue by stevencomerthornley** [nervosnetwork/neuron#2233]
I can not deposit 9025 ckb into the Nervos DAO, and I would like to

**Comment by kellyshang** [comment]
Update to the latest version of [v0.101.2](https://github.com/nervosnetwork/neuron/releases/tag/v0.101.2), and then try single-clear cache from `Settings` window:
![image](https://user-images.githubusercontent.com/28836185/150080978-7d68bd75-91dc-429a-bf92-155676c98507.png)
