### ISSUE TITLE
ckb Deposit from Binance not arrived

### ISSUE THREAD

**Issue by kamarajj** [nervosnetwork/neuron#2240]
ckb Deposit from Binance not arrived. The withdrawal completed successfully in Binance. But the CKB never arrived in the neuron walet.
Can you please help. Thanks

**Comment by kamarajj** [comment]
Here is the TxId for the transaction:

0x93def4bea3b2291b1d3be54ae3a0b9d5752bd1ce0d2e12188ac97f93d57342a4

**Comment by kamarajj** [comment]
Here is my walet address:
ckb1qyqx4jza6c75wc5r2yukxxjmjv52m4u95yxsxt2r29

**Comment by kellyshang** [comment]
The Neuron is a full-node wallet that needs to wait for a complete syncing before you can see your balance.
So please make sure that your Neuron's sync has been finalized. Or you can export the debug info from the menu from `Help` - `Export Debug Information` and drag it into here to let me have a look.

**Comment by PedPin** [comment]
I didn't receive my tokens in my wallet, what can I do?

**Comment by kellyshang** [comment]
> I didn't receive my tokens in my wallet, what can I do?

@PedPin Please try to refer to these [steps](https://github.com/nervosnetwork/neuron/issues/2245#issuecomment-1019518302) to check by your self
