### ISSUE TITLE
ckb Deposit from Binance not arrived me too

### ISSUE THREAD

**Issue by Sirys191** [nervosnetwork/neuron#2245]
**Describe the bug** (Please enter details, the more detail the better)
19.01.2022 sent CKB from binance to neuron wallet

**Debug info** (Please upload the debug info from `Help` - `Export Debug Information`)
txID: 0x8fb312c1444b986cc4bd57b07f4af54284096969435643dcb93c36bb62c2901a
![CKB не дошли](https://user-images.githubusercontent.com/98230277/150649726-d74e7801-52c2-4c7f-868d-2d47406a3ac2.jpg)

**Screenshots** (If applicable, add screenshots to help explain your problem.)

**Comment by kellyshang** [comment]
1. In the Neuron wallet, has the sync been finalized? ( check from the left bottom of the Neuron)
2. If the sync has not been finalized, please be patient to wait for the sync been completed.
3. If your balance still not show up after the sync finilized, export (from menu of `Help` - `Export Debug Information` ) and upload the debug info zip file into here and I will try to figure out what was the problem.

**Comment by Sirys191** [comment]
Hello!
Yep, th sync hadn’t finalized. Now done, ckb arrived, thank you and good luck !! 
 
 
--
Василий Трубачев
Отправлено из Почты  Mail.ru
