### ISSUE TITLE
CKB Neuron Wallet Unlock Staking Issue. Where are my tokens and staking rewards?

### ISSUE THREAD

**Issue by freespirit8614** [nervosnetwork/neuron#2248]
In my Neuron wallet, I unlocked my CKB tokens which were staking on 23/01/2022. There were 3 days to go before the current compensation period ended, and I pressed "unlock" button, and also see I paid the fee which shows in my History within the wallet.

I have waited 2 days and the wallet now shows 0 days to compensation period ends. My wallet is fully synched and up to date on the current version of the Neuron wallet.

However, my tokens I unlocked are nowhere in sight anywhere else on the wallet other than in the staked section? SHouldn't these tokens move to the Available section now the compensation period is ended and I paid the Nervos DAO fee and it was approved?

I have watched you tube tutorials and been to the Neuron and Nervos website and this issue is not covered in what I could find.

Can you guide me as to what to try next? Or perhaps clarify the CKB Neuron Wallet policy of returning staking tokens back into the available funds in the wallet? I was under the impression that if you withdrew the tokens before the compensation period ended, it would be an immediate transfer to being available of the original staking balance, plus the staking tokens earned over time, once the epochs all ended?

Thanks for your help!

Thanks!

**Comment by lewisrx** [comment]
我也遇到了同样的问题，解锁的ckb哪里都找不到。

**Comment by freespirit8614** [comment]
Please write your instructions in English. Thanks.

**Comment by kellyshang** [comment]
Here is the instruction of the Nervos DAO RFC: https://github.com/nervosnetwork/rfcs/blob/master/rfcs/0023-dao-deposit-withdraw/0023-dao-deposit-withdraw.md

There are two periods in Nervos DAO, and will be shown as `Withdraw` & `Unlock` button in Neuron, as below:
![image](https://user-images.githubusercontent.com/28836185/151118919-5c25f431-5a88-4e5e-b3c0-74bb748862f2.png)

If you clicked the `Withdraw` button, then the `Unlock` will be available until the current compensation period to be finished.
If you clicked the `Unlock` button, then the CKB will return to your current wallet, and there also will be a record displayed in the `Completed` tab on the DAO screen: 
![image](https://user-images.githubusercontent.com/28836185/151118334-a4d8a3c6-5c91-4262-ba9b-82f2a0fce515.png)

**Comment by lewisrx** [comment]
显示已提取，但是解锁的按钮一直不能继续点击，解锁是灰色不可用状态
![图片1(1)](https://user-images.githubusercontent.com/26849334/151153372-a5a67c18-5209-4d7a-8a10-a423d52e1b06.png)
。

**Comment by kellyshang** [comment]
@lewisrx That's because the current ‘Compensation cycle’ has not yet ended. Until when the current cycle ended then the `Unlock` button can be clickable: 
![image](https://user-images.githubusercontent.com/28836185/151155943-825d1a66-7b4e-4e75-b78b-3e2ee55b9cfb.png)
![image](https://user-images.githubusercontent.com/28836185/151156048-11d5f294-393e-43dc-9340-001b24a3915b.png)

**Comment by freespirit8614** [comment]
Thank you both very much for your help. All good now.
