### ISSUE TITLE
messages.fields. is too short , it should be longer than or equal to.   (error)

### ISSUE THREAD

**Issue by adoksos13** [nervosnetwork/neuron#2260]
I have an available balance or 20k CKBytes and every time i try to deposit them in Nervos DAO and put my password i get the message and it doesnt deposit them. 
What should i do?

( i put 19k instead of 20k because it needs a small fee to proceed )

**Comment by kellyshang** [comment]
Hi @adoksos13 , please try single-clearing the cache: 
![image](https://user-images.githubusercontent.com/28836185/152716112-0da3829a-fcb0-4c73-ab8f-dd490f1ff1e9.png)

**Comment by adoksos13** [comment]
Thank you very much for your respond!
I will try it asap when I go to office
