### ISSUE TITLE
Neuron wallet not syncing

### ISSUE THREAD

**Issue by simonsanchezj** [nervosnetwork/neuron#2265]
Neuron wallet is not syncing no matter what I try

![Captura de pantalla 2022-02-11 a las 13 48 06](https://user-images.githubusercontent.com/25982712/153610409-5d0ff07b-01e5-4981-819a-b798fe0da5e3.png)

**Comment by kellyshang** [comment]
@simonsanchezj Please export and upload the debug info zip file to let us check what was the exactly problem is. (the exporting step had been indicated when create a new issue, but you deleted them all)

**Comment by simonsanchezj** [comment]
Hello, I restarted my computer and everything is ok now. Thanks!
