### ISSUE TITLE
Feature Request: Include sUDT Managing, Sending, Receiving in Neuron Wallet

### ISSUE THREAD

**Issue by E-Coder1987** [nervosnetwork/neuron#2278]
Hi!

I sent bnb over forcebridge to the wrong address 
I used my safepal wallet address instead of my L1 deposit address 

I see them as a custom token (sUDT) on my wallet in the nervos chain explorer but I don't know how I can send them on to my l1 deposit address 

https://explorer.nervos.org/address/ckb1qyqgk6nz7hezdj670xzqpjjewktw0nta76aqtalv9p

As I heard in Nervos Discord, Neuron Wallet is working on implementing the management of sUDT and short addresses.

Is there a Roadmap available already?

Is there maybe currently any other way to get those sUDT BNB out of my Short-Address?

Thanks!

**Comment by merakmember** [comment]
same problem 

https://bscscan.com/tx/0x0c2501f62c3b2c4600f0ee8bac5ef77ae5b10ba628e849cb036842b78b5581c6

https://explorer.nervos.org/address/ckb1qyqw5az0fv2dwf9q7a080d5qgp4mrqwctzxs7gtxvf

**Comment by E-Coder1987** [comment]
> same problem 
> 
> 
> 
> https://bscscan.com/tx/0x0c2501f62c3b2c4600f0ee8bac5ef77ae5b10ba628e849cb036842b78b5581c6
> 
> 
> 
> https://explorer.nervos.org/address/ckb1qyqw5az0fv2dwf9q7a080d5qgp4mrqwctzxs7gtxvf

They said in May there will be a tool available 
https://github.com/nervosnetwork/neuron/issues/2223#issuecomment-1001901666

**Comment by Keith-CY** [comment]
Hi @merakmember 

I left a comment about this feature in https://github.com/nervosnetwork/neuron/issues/2223#issuecomment-1121520873
