### ISSUE TITLE
Neuron + Ledger Signing Transactions Issue

### ISSUE THREAD

**Issue by erikkvietelaitis** [nervosnetwork/neuron#2293]
New to GITHUB but felt this need to be addressed.

As the heading susggests i am using Neuron and Ledger and had been having a really good experince until recent.

I am sending the signing request from neuron (e.g DAO/or to send to anther wallet) to the ledger device but my Ledger device is currently not reciving signing requests, physically on the device. This then leaves the generated transaction in at state of waiting for a transaction confritamtion from the ledger, with nothing coming through it seems.

The ledger device "status" upon sending the transaction is confirmed that i am in the ledger nervos app, and happy to proceed. Further, with the transaction able to be canceled by leaving the ledger app as well.

My hypotheses is Neuron is sending the reuqest but the ledger software app (Nervos) is outdated for the current firmware version olf the ledger device (2.0.2) maybe a new security update? and intern unable to recive the inforamtion.

Ledger:Firmware: 2.0.2

Nervos App: 0.5.2

Neuron Wallet: Currently synced 100%.

Neuron Version: 0.101.2

CKB Version: v0.101.1

I had posted this on reddit and it seems like other uses have had the same issue as I and where able to work out that leaving the transaction active and letting the ledger goto "sleep" (30 min wait) and reactivate the ledger the transaction is able to be signed as long as it was maintained/active in Neuron wallet.

Please see the reddit dissucssion about this toipic:
https://www.reddit.com/r/NervosNetwork/comments/t3z23r/neuron_ledger_cant_physically_sign_transactions/hz132rw/

**Debug info** (Please upload the debug info from `Help` - `Export Debug Information`)
[neuron_debug_1646489043518.zip](https://github.com/nervosnetwork/neuron/files/8190822/neuron_debug_1646489043518.zip)
Not sure if this will help but i had downloaded the debug as i had just signed the transaction with nothing being displayed on the ledger

**Comment by gabisena424** [comment]
nao consigo retirar meus ckbs do NERVOS DAO 

NAO APARECEU A OPÇÃO UNLOCKED

C:\Users\gouve\AppData\Local\Temp\Temp1_neuron_debug_1646495257220 (2).zip\neuron_debug_1646495257220.zip
