### ISSUE TITLE
ckb_v0.101.6_x86_64 (Apple Darwin) fails to run on Mac OS 10.12 (dyld: Symbol not found: ____chkstk_darwin)

### ISSUE THREAD

**Issue by bits4fun** [nervosnetwork/neuron#2294]
**Describe the bug** (Please enter details, the more detail the better)
ckb and ckb-cli fails to execute. It reports:

**dyld: lazy symbol binding failed: Symbol not found: ____chkstk_darwin
  Referenced from: /Users/xxx/bin/ckb/./ckb
  Expected in: /usr/lib/libSystem.B.dylib**

Latest Neuron release (for Mac) probably suffers from same problem, it never synchronises the Nervos Node (keeps saying "Connecting" in GUI)

I'm on a MacOS Sierra 10.12.6

**Comment by bits4fun** [comment]
I have now tried to download all CKB released until v0.101.0, they all report the same problem. I suspect that the ckb and ckb-cli command line tools are built on a newer macOS 10.14 or higher.

**Comment by Keith-CY** [comment]
Hi @bits4fun , I've learned that the [released binaries for macOS](https://github.com/nervosnetwork/ckb/releases) of CKB are built by GitHub action with macOS 10.15, and maybe incompatible with macOS below 10.15.

The workaround is to build CKB on macOS 10.12 by yourself, but not recommended

Ref: https://github.com/nervosnetwork/neuron/issues/2128#issuecomment-938442066

**Comment by bits4fun** [comment]
Hi, 

That explains it 
You should update the minimum macOS version to 10.15, not 10.12 as it is currently written in release notes.

I took it for face value being 10.12 (which I still use).

Apps such as Google Chrome and LibreOffice make the effort of releasing binaries for old versions, typically for 10.12 (as of now).

Well, thanks for clarifying, cheers,
Gunther

**Comment by Keith-CY** [comment]
This misleading is quite annoying indeed and the CKB core team will fix the release note in the next version.

Appreciate your feedback.
