### ISSUE TITLE
Wallet won't sync to the Mainnet

### ISSUE THREAD

**Issue by baeringerj1** [nervosnetwork/neuron#2299]
My wallet had a signifcant amount of coins and now won't sync to the mainnet and I cannot view the contents of my wallet.
In the bottom left of the wallet I am being told it is syncing but there are no blocks and it has made any change in days. Can someone please help.

<img width="191" alt="Screen Shot 2022-03-09 at 11 29 56 AM" src="https://user-images.githubusercontent.com/61560639/157486023-aab389b4-6d96-429f-913f-ed6175eaa0e0.png">

**Comment by baeringerj1** [comment]
I have deleted the app, re-downloaded the newest version, re-imported my wallet seed, and cleared cache. I am on a mac machine. Unsure what else I can do.

**Comment by Keith-CY** [comment]
Hi @baeringerj1 , we need some logs which can be exported from `menu -> help -> export debug information` to locate the exception. The logs are insensitive and you can post them in this issue.

**Comment by baeringerj1** [comment]
I was able to get it synced! thanks!
