### ISSUE TITLE
Reconfig TSLint/ESLint to take effect

### ISSUE THREAD

**Issue by ashchan** [nervosnetwork/neuron#23]
Initially we configured TSLint. Ever since ESLint was added and `tslint.json` the the lint task is not checking anything.

**Comment by Keith-CY** [comment]
I'm not sure what you means that lint not work. It check when commit
![image](https://user-images.githubusercontent.com/7271329/52159656-54484e80-26e2-11e9-9129-20d5efa78f54.png)

**Comment by Keith-CY** [comment]
If you means tslint server not work in vscode, it's better to use eslint, cause tslint is going to be deprecated

**Comment by ashchan** [comment]
@Keith-CY Several things to mention when I said it's not working.

* yarn/lerna `lint` tasks were not updated when TSLint config was removed. (But I agree removing TSLint is a sound choice and I'm working on that)
* I'm not sure if husky hood requires some configuration; but if it's working why our `Network` feature was committed with a lot of issues?

```shell
yarn run eslint packages/react-app/src/components/Network/*.tsx
...
✖ 274 problems (274 errors, 0 warnings)
  237 errors and 0 warnings potentially fixable with the `--fix` option.
```

**Comment by ashchan** [comment]
Added `@typescript-eslint` plugin but should take some time to consider if it's necessary.

**Comment by Keith-CY** [comment]
We've already added `@typescript-eslint` in `.eslintrc` as a parser.
