### ISSUE TITLE
Migrating hardware service to a common package

### ISSUE THREAD

**Issue by Ahmedie-m** [nervosnetwork/neuron#2311]
Hello,

A common case for any developer is to integrate with Ledger and since the functionality already is written by yourselves within the services folder, it would be nice to move it to a separate and lighter package for other developers to utilize. Would that be possible?

Source: https://github.com/nervosnetwork/neuron/tree/develop/packages/neuron-wallet/src/services/hardware

Example: https://github.com/LedgerHQ/ledgerjs/tree/master/packages/hw-app-eth

Thanks.

**Comment by Keith-CY** [comment]
Hi @Ahmedie-m , appreciate your suggestion and we will start the work in the next month.

**Comment by Ahmedie-m** [comment]
Hey @Keith-CY , I am not sure if this is necessary anymore. There apparently is another package that does all the communications with Ledger: https://github.com/obsidiansystems/hw-app-ckb 

Thank you
