### ISSUE TITLE
Can not set up a new Neuron wallet

### ISSUE THREAD

**Issue by Nikned66** [nervosnetwork/neuron#2326]
I downloaded and installed the Neuron wallet on my Mac. When starting the app it loads but all functional fields from the drop-down menus of the app are inactive and I can not set up a new wallet. What could be the problem?

Thank you,
Nikolay

**Debug info** (Please upload the debug info from `Help` - `Export Debug Information`)

**Screenshots** (If applicable, add screenshots to help explain your problem.)

**Comment by Keith-CY** [comment]
Hi @Nikned66, could you post a screenshot and append `Debug Info` in this issue so that we can try to find out what's going wrong.

`Debug Info` could be exported by `help -> export debug information`
