### ISSUE TITLE
How can I take back my CKBs from a sUDT that I don't use more?

### ISSUE THREAD

**Issue by safe96** [nervosnetwork/neuron#2336]
How can I do that?

**Comment by Keith-CY** [comment]
Hi @safe96, turning an empty sUDT Asset Account into CKB balance is not supported yet. We've opened a feature request of it and expect it to be released within the next version(05/10)

Ref: https://github.com/nervosnet/neuron-public-issues/issues/9

**Comment by Keith-CY** [comment]
This feature has been merged and will be released in the next version
https://github.com/nervosnetwork/neuron/pull/2337

**Comment by merakmember** [comment]
when can this feature be used? so I can send sudt to yokai/forcebridge

**Comment by Keith-CY** [comment]
Hi @safe96 @merakmember this feature has been delivered with https://github.com/nervosnetwork/neuron/releases/tag/v0.103.0

When a sudt asset account has no balance, a `destroy` button will appear at the bottom of sending tab and allow you to turn the asset account cell into a normal cell(pure ckb asset)
![image](https://user-images.githubusercontent.com/7271329/171806295-15b59719-dbeb-4ab1-a46c-00bcd897d4c0.png)

**Comment by Keith-CY** [comment]
@merakmember I missed your second question, sending sudt to yokai/forcebridge is under testing and will be released next week(if tests are all green)
Function Pull Request: https://github.com/nervosnetwork/neuron/pull/2400
