### ISSUE TITLE
Neuron wallet addresses are inconsistent

### ISSUE THREAD

**Issue by zhb666** [nervosnetwork/neuron#2339]
I use the mnemonic words generated by @ CKB Lumos / HD, then generate the user's private key according to the generated mnemonic words, and then realize the address of CKB of the main network and CKT of the test network I want to generate with the private key.
But I use mnemonics to create a new wallet in neuron wallet. After creation, the collection address is different from the address I generated with CKB SDK. This is very confusing. Is the way neuron wallet generates the address different

**Comment by Keith-CY** [comment]
@classicalliu could you help on this?
