### ISSUE TITLE
sync stuck at 6.4%.

### ISSUE THREAD

**Issue by subhashrao1947** [nervosnetwork/neuron#2343]
Sync does not want to move beyond 6.4%. Trying to download update software but getting the following error;
![Screenshot 2022-04-25 at 08 17 09](https://user-images.githubusercontent.com/92733040/165039617-d3a80366-519e-48bf-a46e-e42458058684.png)
![Screenshot 2022-04-25 at 08 17 09](https://user-images.githubusercontent.com/92733040/165039674-c57a76ac-7bd8-4eeb-9425-66abc966d1e7.png)

Can I have link to update and sync my node

**Comment by subhashrao1947** [comment]
Yanguoyu, yes its is as described in 2314 as per aaomotayo <https://github.com/aaomotayo> commented on 27 Mar <https://github.com/nervosnetwork/neuron/issues/2314#issue-1182664781>

Do I need to delete the current version and download new version?

Any link from you to get me beack to where I was with my investment would be great.

Best wishes,

Sam Rao
+44 (0)7775 770 526
https://www.amazon.com/author/samrao

**Comment by yanguoyu** [comment]
@subhashrao1947 yeah, maybe you need to download the latest version from https://github.com/nervosnetwork/neuron/releases/tag/v0.103.2
