### ISSUE TITLE
Error message when trying to update to v101.3 

### ISSUE THREAD

**Issue by Thorstenschuf** [nervosnetwork/neuron#2348]
hello - 

on Mac I can't update out of v101.2 because I get the following error message (I already emptied the library - did not help) - thank you all - please see attached file

**Comment by Keith-CY** [comment]
Hi @Thorstenschuf, I think the attached files are not uploaded successfully.

**Comment by Keith-CY** [comment]
Hi @Thorstenschuf 

Although the attached files are not appended, I guess that you encountered an error related to signature validation which is introduced from Neuron@v0.101.3 for MacOS

We have updated Apple Developer Id Certificate so v0.101.2 cannot be upgraded by `check for updates` inside Neuron.

Please check the detail in release note https://github.com/nervosnetwork/neuron/releases/tag/v0.101.3

And please download the latest one to adopt the new certificate https://github.com/nervosnetwork/neuron/releases/tag/v0.103.0

**Comment by Thorstenschuf** [comment]
Hi Chen,

Thank you for following up. I have installed v100.3 meanwhile and it seems it works. I hope also for the fork.

Below please find attached the message I got before:

**Comment by Thorstenschuf** [comment]
Hi again 

Is it correct that also for version 0.101.3 you cannot check for updates within/inside the wallet?

**Comment by Keith-CY** [comment]
> Hi again Is it correct that also for version 0.101.3 you cannot check for updates within/inside the wallet?
> […](#)
> Am 15.05.2022 um 19:29 schrieb Chen Yu ***@***.***>: ﻿ Hi @Thorstenschuf Although the attached files are not appended, I guess that you encountered an error related to signature validation which is introduced from ***@***.*** for MacOS We have updated Apple Developer Id Certificate so v0.101.2 cannot be upgraded by check for updates inside Neuron. Please check the detail in release note [`v0.101.3` (release)](https://github.com/nervosnetwork/neuron/releases/tag/v0.101.3) And please download the latest one to adopt the new certificate [`v0.103.0` (release)](https://github.com/nervosnetwork/neuron/releases/tag/v0.103.0) — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.

Hi @Thorstenschuf 

There's a known bug in v0.101.3 that `check for updates` in setting panel doesn't work, you may upgrade neuron from menu

If you're using windows, it's in `menu -> help -> check for updates`
If you're using Mac or Linux, it's in `menu -> Neuron -> check for updates`

Ref: https://github.com/nervosnetwork/neuron/issues/2372

**Comment by Thorstenschuf** [comment]
It doesn’t work - see below

**Comment by Keith-CY** [comment]
> It doesn’t work - see below

I think you are going to append a screenshot in comment but it is not uploaded yet.

**Comment by Thorstenschuf** [comment]
Hi 

Can you please somehow update your update versions that it just runs through like in the past?

What does it mean to move the files out of the download folder? To where? 

I mean sorry, I am not a tech person and do not have the time to spend hrs on that. If you want adoption of ckb fix that… thank you.

Further what does it mean now for if I can’t update properly? Are my coins lost after the fork?

**Comment by Keith-CY** [comment]
I'm a little confused because I didn't mention something like `move files out of the download folder`

First of all, your coins are safe after the fork.

Then we can upgrade neuron from `v0.101.3` to `v0.103.0` by `check for updates` in menu
![image](https://user-images.githubusercontent.com/7271329/168550144-8e61e21a-51ca-4ac8-a66f-3401f18bdf4b.png)

**Comment by Thorstenschuf** [comment]
Hi Chen,

So it finally worked - neuron wallet 0.103.0 is the latest right? 

When I now check for updates as you advised it says no updates available and now I also see the new longer address format.

I should be fine now, right?

Thanks for your support!!

**Comment by Keith-CY** [comment]
> Hi Chen, So it finally worked - neuron wallet 0.103.0 is the latest right? When I now check for updates as you advised it says no updates available and now I also see the new longer address format. I should be fine now, right? Thanks for your support!!
> […](#)
> Am 16.05.2022 um 09:46 schrieb Chen Yu ***@***.***>: ﻿ It doesn’t work - see below I think you are going to append a screenshot in comment but it is not uploaded yet. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.

Yes, v0.103.0 is the latest one, and addresses are displayed in the new long address format since v0.103.0.

Your balance should be the same as before and it's all ready.

**Comment by Keith-CY** [comment]
> Hi Chen, Can you see the screenshots? See below - this was the message I got when I tried to update today…
> […](#)
> Am 16.05.2022 um 10:36 schrieb Chen Yu ***@***.***>: ﻿ Hi Chen, So it finally worked - neuron wallet 0.103.0 is the latest right? When I now check for updates as you advised it says no updates available and now I also see the new longer address format. I should be fine now, right? Thanks for your support!! … Am 16.05.2022 um 09:46 schrieb Chen Yu @.***>: ﻿ It doesn’t work - see below I think you are going to append a screenshot in comment but it is not uploaded yet. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned. Yes, v0.103.0 is the latest one, and addresses are displayed in the new long address format since v0.103.0. Your balance should be the same as before and it's all ready. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.

The screenshot is missing, I think
