### ISSUE TITLE
Neuron Wallet get's stuck at 96.65% synch. 

### ISSUE THREAD

**Issue by Jaimy99** [nervosnetwork/neuron#2349]
I;'ve downloaded the update
refreshed/cleared cache 3x

nothing works..

**Comment by yanguoyu** [comment]
Hi, @Jaimy99 
Can you provide debug information?
You can export by help->Export Debug Information

**Comment by Jaimy99** [comment]
Where can I find this (debug) information? / how do i do that on my windows laptop?

**Comment by yanguoyu** [comment]
Can you upload your debug information? If not, maybe you can try clean cache by follow steps.
1. Click Menu->Neuron->Preference
2. Clear cache
