### ISSUE TITLE
neuron wallet not syncing

### ISSUE THREAD

**Issue by aaronV81** [nervosnetwork/neuron#2376]
the wallet does not sync it stays stuck on connecting....

**Comment by aaronV81** [comment]
> the wallet does not sync it stays stuck on connecting....

[neuron_debug_1652284935110.zip](https://github.com/nervosnetwork/neuron/files/8671592/neuron_debug_1652284935110.zip)

**Comment by aaronV81** [comment]
![Screenshot (55)](https://user-images.githubusercontent.com/85458548/167895820-c609ced7-7782-436f-9df8-6ff75b054e71.png)

stuck at 75.73%

**Comment by aaronV81** [comment]
I found an update 

https://github.com/nervosnetwork/neuron/releases/tag/v0.103.0

**Comment by Keith-CY** [comment]
Hi @aaronV81 

I found the following in ckb log
```
2022-05-11 17:00:45.343 +01:00 GlobalRt-4 ERROR panic  thread 'GlobalRt-4' panicked at 'Internal(DataCorrupted(IO error: No space left on device: Failed to WriteFile: C:\.....db/018550.log: There is not enough space on the disk.
))': sync\src\utils.rs:93   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: <unknown>
  15: <unknown>
  16: <unknown>
  17: <unknown>
  18: <unknown>
  19: <unknown>
  20: <unknown>
  21: <unknown>
  22: <unknown>
  23: <unknown>
  24: <unknown>
  25: <unknown>
  26: <unknown>
  27: <unknown>
  28: <unknown>
  29: <unknown>
  30: <unknown>
  31: <unknown>
  32: <unknown>
  33: <unknown>
  34: <unknown>
  35: BaseThreadInitThunk
  36: RtlUserThreadStart

```

It says your computer runs out of disk space.

**Comment by aaronV81** [comment]
Ok thanks I sorted it now

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
