### ISSUE TITLE
It is not possible to withdraw from Binance to Neuron. Reason: inconsistent address

### ISSUE THREAD

**Issue by antoniogioia** [nervosnetwork/neuron#2381]
When trying to withdraw CKB from Binance to Neuron, the following message appears: The withdrawal address is not consistent with the network you selected. Please check again.

I don't know if the problem is with Binance not recognizing the new addresses of Neuron or if the problem is with the Neuron wallet.

**Comment by Keith-CY** [comment]
> When trying to withdraw CKB from Binance to Neuron, the following message appears: The withdrawal address is not consistent with the network you selected. Please check again.
> 
> I don't know if the problem is with Binance not recognizing the new addresses of Neuron or if the problem is with the Neuron wallet.

Binance will allow the new format of addresses soon.

You may get the deprecated format of a specific address from transaction detail by clicking the  lock script tag next to an address
![](https://user-images.githubusercontent.com/7271329/166137921-aeac13ef-78b7-4be8-8574-fd60b6cd92d7.png)

**Comment by Kempachi23** [comment]
> When trying to withdraw CKB from Binance to Neuron, the following message appears: The withdrawal address is not consistent with the network you selected. Please check again.
> 
> I don't know if the problem is with Binance not recognizing the new addresses of Neuron or if the problem is with the Neuron wallet.

https://github.com/nervosnetwork/neuron/issues/2397#issuecomment-1140488641

**Comment by Keith-CY** [comment]
Hi @antoniogioia 

We just released https://github.com/nervosnetwork/neuron/releases/tag/v0.103.1 which could display receiving address in the deprecated format with PR https://github.com/nervosnetwork/neuron/pull/2408

https://user-images.githubusercontent.com/7271329/173193753-92518744-f9db-4506-9355-733d8b118681.mov
