### ISSUE TITLE
Neuron wallet not syncing (macOS 12.3.1, Neuron 0.103.0)

### ISSUE THREAD

**Issue by mattsbennett** [nervosnetwork/neuron#2383]
**Describe the bug** (Please enter details, the more detail the better)
Syncs fine when freshly downloaded/installed, any subsequent reopening of the app, it won't sync. Only resolution is to re-install and sync from 0 again.

**Debug info** (Please upload the debug info from `Help` - `Export Debug Information`)
[neuron_debug_1652464486606.zip](https://github.com/nervosnetwork/neuron/files/8689913/neuron_debug_1652464486606.zip)

**Screenshots** (If applicable, add screenshots to help explain your problem.)

**Comment by Keith-CY** [comment]
@mattsbennett 

The log indicates Neuron cannot detect a running CKB Node, this happens but not often. There'a trick to re-detect running CKB, please add a network in `setting -> network -> add network` with `rpc url: http://localhost:8114` and `name: mainnet`, then switch to it. On network switch , neuron will reconnect to the running CKB node.

**Comment by mattsbennett** [comment]
@Keith-CY weird - it seems to happen consistently for me except on the first open after install. Tried your trick though, and it works great, thank you!
