### ISSUE TITLE
Transactions keep pending on Neuron v0.101.3

### ISSUE THREAD

**Issue by Keith-CY** [nervosnetwork/neuron#2384]
We've received several issues about pending transactions with Neuron@v0.101.3

The reason is that CKB Node has been harkforked since 2022-05-10 but Neuron@v0.101.3's internal one is not hardforked, so transactions sent from Neuron@v0.101.3 won't be accepted by most miners. Please upgrade to Neuron@v0.103.0 to send transactions.

How to [Check for Updates](https://github.com/nervosnetwork/neuron/issues/2372) in Neuron

**Comment by brain-dump** [comment]
Unfortunately I tried upgrading to 103, clearing cache and depositing... still doesn't get passed pending. I emailed deposit attempt with the 103 Neuron.

**Comment by Keith-CY** [comment]
> Unfortunately I tried upgrading to 103, clearing cache and depositing... still doesn't get passed pending. I emailed deposit attempt with the 103 Neuron.

Hi @brain-dump 

I got the point. The `status.json` in the debug info says your neuron is connecting a ckb node@v0.101.0, which is not hardforked.

Neuron@v0.103.0 has ckb node@v0.103.0 inside, the ckb node@v0.101.0 maybe not shut down correctly on upgrade, please kill it manually and restart neuron then have a look.

**Comment by brain-dump** [comment]
all set.  thanks!
