### ISSUE TITLE
Cannot update to 0.103.0 on Mac

### ISSUE THREAD

**Issue by panmoria** [nervosnetwork/neuron#2393]
[neuron_debug_1653290416917.zip](https://github.com/nervosnetwork/neuron/files/8752342/neuron_debug_1653290416917.zip)
<img width="250" alt="Bildschirmfoto 2022-05-23 um 14 15 52" src="https://user-images.githubusercontent.com/91946128/169765678-08c617c0-0722-4064-9050-80fc06dc5339.png">

**Comment by Keith-CY** [comment]
Hi @panmoria 
This is a known issue and you may download Neuron from the release page(https://github.com/nervosnetwork/neuron/releases/tag/v0.103.0) to adopt a new Apple Developer ID

For more detail: https://github.com/nervosnetwork/neuron/issues/2386
