### ISSUE TITLE
Ubuntu compatibility issues

### ISSUE THREAD

**Issue by thetdy** [nervosnetwork/neuron#2396]
18.04 and 22.04 LTS did not seem to work. 20.04 LTS works fine though

18.04 would not connect. couldn't find mainnet.

22.04 got stuck on "connecting" and couldn't clear cache

**Comment by Keith-CY** [comment]
> 18.04 and 22.04 LTS did not seem to work. 20.04 LTS works fine though
> 
> 18.04 would not connect. couldn't find mainnet.
> 
> 22.04 got stuck on "connecting" and couldn't clear cache

Hi @thetdy 

Could you please upload logs from `menu -> help -> export debug information` so we can learn more details like Neuron's version, are necessary dependencies installed, and most important, error message of not running.
