### ISSUE TITLE
WALLET IS NOT CONNECTING AND I HAVE THE LATEST VERSION

### ISSUE THREAD

**Issue by Billcrf** [nervosnetwork/neuron#2398]
**Describe the bug** (Please enter details, the more detail the better)

**Debug info** (Please upload the debug info from `Help` - `Export Debug Information`)

**Screenshots** (If applicable, add screenshots to help explain your problem.)

**Comment by Billcrf** [comment]
![Screenshot_6](https://user-images.githubusercontent.com/106275982/170352985-a078a071-f3ff-4e96-9068-ff0b4d32b14e.jpg)
I HAVE IT TWO DAYS LIKE THIS

**Comment by Cedar67** [comment]
@Billcrf Could you export Debug Information and post it here?

**Comment by Billcrf** [comment]
> @Billcrf Could you export Debug Information and post it here?

[main.log](https://github.com/nervosnetwork/neuron/files/8780462/main.log)

**Comment by Billcrf** [comment]
> @Billcrf Could you export Debug Information and post it here?

**Comment by Billcrf** [comment]
> @Billcrf Could you export Debug Information and post it here?

[neuron_debug_1653581716321.zip](https://github.com/nervosnetwork/neuron/files/8793860/neuron_debug_1653581716321.zip)

**Comment by Keith-CY** [comment]
> > @Billcrf Could you export Debug Information and post it here?
> 
> [neuron_debug_1653581716321.zip](https://github.com/nervosnetwork/neuron/files/8793860/neuron_debug_1653581716321.zip)

Hi @Billcrf 

Sadly the log(bundled-ckb.log) says nothing
```
File not found
```

It means the most basic infrastructure of the wallet, CKB Node, didn't work and it even didn't generate a log file.

In this case, we have to [run the CKB node](https://docs.nervos.org/docs/basics/guides/mainnet/) manually to see what error occurs.

**Comment by Billcrf** [comment]
> > > @Billcrf Could you export Debug Information and post it here?
> > 
> > 
> > [neuron_debug_1653581716321.zip](https://github.com/nervosnetwork/neuron/files/8793860/neuron_debug_1653581716321.zip)
> 
> Hi @Billcrf
> 
> Sadly the log(bundled-ckb.log) says nothing
> 
> ```
> File not found
> ```
> 
> It means the most basic infrastructure of the wallet, CKB Node, didn't work and it even didn't generate a log file.
> 
> In this case, we have to [run the CKB node](https://docs.nervos.org/docs/basics/guides/mainnet/) manually to see what error occurs.
If i make reinstall with new wallet....

**Comment by robkay01** [comment]
I have the same problem, here is my log file. Can someone please help advise how to fix this issue.
[neuron_debug_1654432074174.zip](https://github.com/nervosnetwork/neuron/files/8839948/neuron_debug_1654432074174.zip)

**Comment by robkay01** [comment]
My problem is now solved as I opened a new issue with the above and it was fixed there.

**Comment by milavm** [comment]
Hello, 
Same issue here, wallet does not sync. I just downloaded wallet couple days ago, it is most updated version.
Saw youtube videos #1 and #2 to create a wallet and deposit funds, but I can not move on since it does not sync 
It shows:
Block Synced 0%
0/3,524,00 (last number changes constantly)
Looking for assumed valid target
I am not into all this too tech details. I just need a functional and reliable wallet to use alongside my ledger to save the tokens. Any help here? Thanks.
Mila.

**Comment by Keith-CY** [comment]
> Looking for assumed valid target

Hi @milavm 

If neuron shows `Looking for assumed valid target`, it works well and will take less than an hour in this state(looking for assumed valid target). It's a feature of CKB to boost synchronization.

Neuron assumes the block https://explorer.nervos.org/block/0x6c914adcfd5289e8c4058e60e83555d5eb04ddc547b6184f1fae72d5f36929a3 is valid and won't be forked, then neuron downloads block headers fleetly from 0 to find out if the blockchain has the target block. Once the target block is hit, neuron assumes blocks before the target are all valid and skip validation during synchronization, which will ease CPU pressure and speed the synchronization up.

**Comment by milavm** [comment]
Hey Keith, Well, a day ago nothing moved for 7 hours, but actually now it started. Thanks for the explanation.

**Comment by frizzzdog** [comment]
I also have an issue but in this instance I cannot withdraw ckb as I get insufficient funds and do withhold 62 ckb for balance (see attached debug zip report for troubleshooting (version 0.103.0)

[neuron_debug_1658351785502.zip](https://github.com/nervosnetwork/neuron/files/9154577/neuron_debug_1658351785502.zip)
)
