### ISSUE TITLE
not syncing

### ISSUE THREAD

**Issue by Coolhand2117** [nervosnetwork/neuron#2399]
I have updated my Neuron Wallet but it will not sync

<img width="960" alt="image" src="https://user-images.githubusercontent.com/89916332/170578154-cca2b6ab-f16b-4d3b-b501-2a20867d2f9b.png">

**Comment by Keith-CY** [comment]
Hi @Coolhand2117 

From the screenshot, the `CKB Node` inside neuron has not started yet, logs from `menu -> help -> export debug information` is required to find out the reason.

**Comment by Nelx1** [comment]
sync stucked at 98.11% for several days.
clear cache twice and rebuilt index twice.
Turned off my firewall and VPN too.
I am using fiber optics cable with highspeed internet.
Please help. thank you.

**Comment by Keith-CY** [comment]
> sync stucked at 98.11% for several days. clear cache twice and rebuilt index twice. Turned off my firewall and VPN too. I am using fiber optics cable with highspeed internet. Please help. thank you. ![Screenshot 2022-05-31 151737](https://user-images.githubusercontent.com/90548548/171114929-29953d25-3b94-49e9-a115-b19bc8b03d62.png)

Hi @Nelx1 
could you post logs of neuron(`menu -> help -> export debug information`) here so we can find out why it stucked.

**Comment by Keith-CY** [comment]
> Ban peer "/ip4/47.110.15.57/tcp/8114/p2p/QmXS4Kbc9HEeykHUTJCm2tNmqghbvWyYpUp6BtE5b6VrAU" for 300 seconds, reason: BlockIsInvalid(401): Byte32(0x47bed7f43b2311368f5056b3f0b892e9b4809477e1bfce18284db6f97d4143fe), error: Block(BlockTransactions(BlockTransactionsError(index: 1, error: Transaction(Compatible: the feature "VM Version 1" is used in current transaction but not enabled in current chain))))2022-05-31 15:10:00.754 +08:00 GlobalRt-1188 INFO ckb_relay  RelayProtocol.disconnected peer=SessionId(6190)2022-05-31 15:10:00.754 +08:00 GlobalRt-1229 INFO ckb_relay  RelayProtocol.disconnected peer=SessionId(6190)2022-05-31 15:10:00.754 +08:00 GlobalRt-1224 INFO ckb_sync::synchronizer  SyncProtocol.disconnected peer=SessionId(6190)2022-05-31 15:10:26.918 +08:00 GlobalRt-1222 INFO ckb_relay  RelayProtocol(1).connected peer=SessionId(6191)2022-05-31 15:10:26.918 +08:00 GlobalRt-1219 INFO ckb_sync::synchronizer  SyncProtocol.connected peer=SessionId(6191)2022-05-31 15:10:26.918 +08:00 GlobalRt-1228 INFO ckb_relay  RelayProtocol(2).connected peer=SessionId(6191)2022-05-31 15:10:28.015 +08:00 GlobalRt-1224 INFO ckb_relay  RelayProtocol(1).connected peer=SessionId(6192)2022-05-31 15:10:28.015 +08:00 GlobalRt-1224 INFO ckb_sync::synchronizer  SyncProtocol.connected peer=SessionId(6192)2022-05-31 15:10:28.159 +08:00 GlobalRt-1224 INFO ckb_sync::synchronizer::get_headers_process  Ignoring getheaders from peer=SessionId(6192) because node is in initial block download2022-05-31 15:10:29.875 +08:00 GlobalRt-1163 INFO ckb_sync::synchronizer::in_ibd_process  getheader with ibd peer SessionId(6191)

Hi @Nelx1 
Seems that your neuron is out of date
```
Ban peer "/ip4/47.110.15.57/tcp/8114/p2p/QmXS4Kbc9HEeykHUTJCm2tNmqghbvWyYpUp6BtE5b6VrAU" for 300 seconds, reason: BlockIsInvalid(401): Byte32(0x47bed7f43b2311368f5056b3f0b892e9b4809477e1bfce18284db6f97d4143fe), error: Block(BlockTransactions(BlockTransactionsError(index: 1, error: Transaction(Compatible: the feature "VM Version 1" is used in current transaction but not enabled in current chain))))
```

Your neuron is not v0.103.0 so disconnected from miners after CKB hardfork on 2022/05/10

Please update it to v0.103.0
- If your neuron is of v0.101.3, it can be upgraded as https://github.com/nervosnetwork/neuron/issues/2372 says.
- If neuron is running on MacOS and before v0.101.3, you have to download it from the release page https://github.com/nervosnetwork/neuron/releases/tag/v0.103.0 since its apple developer id certificate has been updated in v0.101.3

**Comment by ahming123** [comment]
hi

**Comment by ahming123** [comment]
<img width="1182" alt="Screen Shot 2022-06-11 at 1 35 39 PM" src="https://user-images.githubusercontent.com/107288552/173174426-44e703d5-8a1b-4303-b405-9f3e7df8f7c7.png">
My neuron hv been stuck here after the update to v0.103.0

**Comment by ahming123** [comment]
can kindly help me
