### ISSUE TITLE
Godwoken 1000 usdc faucet bugs 

### ISSUE THREAD

**Issue by jcbm123143** [nervosnetwork/neuron#2401]
Godwoken 1000 usdc faucet 1000 usdc faucet doesn't work and I don't receive usdc

**Debug info**
<img width="960" alt="1000 USDC FAUCET" src="https://user-images.githubusercontent.com/22148449/170877698-8a8d82a9-b4f7-45aa-80ea-476758632980.PNG">

My wallet 
ckt1q3uljza4azfdsrwjzdpea6442yfqadqhv7yzfu5zknlmtusm45hpuq2lvu8xnzdxz2yw40yuryqkfzveky2njfgq63kvvs
0x5f670e6989a61288eabc9c1901648999b1153925

**Comment by Keith-CY** [comment]
I cannot reproduce this case because an error is thrown after signing `get 1000 usdc on L1` transaction
```
2.a22d9a1f.chunk.js:2 Uncaught (in promise) Error: Provided value must be an ArrayBuffer or can be transformed into ArrayBuffer!
    at n (2.a22d9a1f.chunk.js:2:598129)
    at p (2.a22d9a1f.chunk.js:2:601271)
    at m (2.a22d9a1f.chunk.js:2:601785)
    at Object.e.SerializeWitnessArgs (2.a22d9a1f.chunk.js:2:621239)
    at main.7166a7db.chunk.js:1:10906
    at async $ (main.7166a7db.chunk.js:1:10350)
    at async onClick (main.7166a7db.chunk.js:1:52572)
```

@Flouse could you have a look at this issue

https://user-images.githubusercontent.com/7271329/170885955-ae71851a-ab93-429f-93e7-d5657af97139.mov

**Comment by Flouse** [comment]
![image](https://user-images.githubusercontent.com/1297478/170960877-41c724fe-4c8e-40d1-9a17-723e301be02a.png)
I think it is a bug introduced by recent changes.

cc the maintainers of https://github.com/zhangyouxin/light-godwoken
@homura
