### ISSUE TITLE
Setting - Wallets list - buttons on the right are displayed incompletely

### ISSUE THREAD

**Issue by Cedar67** [nervosnetwork/neuron#2407]
**Describe:** 
User has to slide the horizontal scroll bar to click the right-most button.

<img width="1038" alt="image" src="https://user-images.githubusercontent.com/64718893/171183235-ca2a54f7-00a5-449e-93dc-910034214879.png">

**Expected** 
By default, all buttons are displayed completely without horizontal scrollbars.

**Neuron Version:** 
0.103.0

**Comment by yanguoyu** [comment]
https://github.com/nervosnetwork/neuron/pull/2409

**Comment by Cedar67** [comment]
Verified on https://github.com/nervosnetwork/neuron/pull/2409
<img width="900" alt="image" src="https://user-images.githubusercontent.com/64718893/172370030-11813aff-9260-49fc-8928-e2b909f83a40.png">
