### ISSUE TITLE
Neuron wallet stuck at block 7,150,910 

### ISSUE THREAD

**Issue by simonsanchezj** [nervosnetwork/neuron#2413]
My nuron wallet stopped syncing at this block and, consequently, I cannot access my funds. Any suggestions?

**Comment by simonsanchezj** [comment]
Picture attache
<img width="197" alt="Captura de pantalla 2022-06-02 a las 21 20 56" src="https://user-images.githubusercontent.com/25982712/171720796-4d2ef4f1-1a3b-4315-a467-5efd883d0df2.png">
d

**Comment by Keith-CY** [comment]
Hi @simonsanchezj 

Please add logs exported by `menu -> help -> export debug information` so we can find out the reason synchronization didn't start.

**Comment by simonsanchezj** [comment]
Problem solved. Just had to download the newest version of neuron. Thanks!
