### ISSUE TITLE
Neuron Wallet Not Connecting 0% Block Synced

### ISSUE THREAD

**Issue by robkay01** [nervosnetwork/neuron#2414]
Latest version of Neuron downloaded, Wallet not connecting and not syncing.
[neuron_debug_1654432074174.zip](https://github.com/nervosnetwork/neuron/files/8839965/neuron_debug_1654432074174.zip)

![image](https://user-images.githubusercontent.com/55883564/172050861-310d74f4-abd2-4766-9a80-dde5db002385.png)

**Comment by Keith-CY** [comment]
Hi @robkay01 

The log says
```
[2022-06-05 19:29:36.139] [error] CKB:	run fail: For optimal performance, CKB wants to migrate the data into new format.
You can use the old version CKB if you don't want to do the migration.
```

It happens when neuron is upgraded from version before https://github.com/nervosnetwork/neuron/releases/tag/v0.100.0

And the way to fix it is to synchronize from scratch, please clear data by `menu -> tools -> clear all synchronized data` and

**Comment by robkay01** [comment]
Hey @Keith-CY thanks that seems to have worked and I am now connected and syncing. Brilliant.
