### ISSUE TITLE
Cannot Deposit to Nervos DAO in Neuron Wallet

### ISSUE THREAD

**Issue by robkay01** [nervosnetwork/neuron#2416]
I cannot deposit CKB to Nervos DAO. I get an error message "TransactionFailedToResolve: Resolve failed Unknown"
![image](https://user-images.githubusercontent.com/55883564/172138679-f0c90ffd-4db8-4195-922b-fa757f3797b0.png)

[neuron_debug_1654509201036.zip](https://github.com/nervosnetwork/neuron/files/8843509/neuron_debug_1654509201036.zip)
n`)
Please can someone help?

**Comment by Keith-CY** [comment]
Hi @robkay01 

The error says a ckb cell located by `tx hash: 0xc1d139d3fffd9c509e04bcb209e046ee1ab4b99e985d330f3f871b005da02f30` and `index: 0x37` is not found on chain.

The cell is generated by tx https://explorer.nervos.org/transaction/0xc1d139d3fffd9c509e04bcb209e046ee1ab4b99e985d330f3f871b005da02f30#55

and consumed by tx https://explorer.nervos.org/transaction/0xf3a7cd4f2a6db7a57f55a5ae49b7a8aef396106ff48197215b425441a559e77b

That means the cell is dead and cannot be used again. There's something incorrect in Neuron's cache data. 

`Settings -> General -> Clear Cache` should fix this cache error and then you can have a try
