### ISSUE TITLE
neuron deposit will not unlock

### ISSUE THREAD

**Issue by 991walt** [nervosnetwork/neuron#2421]
I withdrew my deposit earlier however my internet crashed the next day my deposit was locked again. I figure I would wait for the next cycle to finish so I can unlock to add more ckb however it is staying locked. I downloaded the last updates however still not able to unlock. It does show I withdrew on 2022-05-19 however the tokens never moved. Any help would be a big help thank you so much for you time.
![2022-06-13 (2)](https://user-images.githubusercontent.com/107382668/173278924-40a4d74f-eb6f-4163-8e73-c8dd5a7ad0c8.png)
 

**Debug info** (Please upload the debug info from `Help` - `Export Debug Information`)

**Screenshots** (If applicable, add screenshots to help explain your problem.)

**Comment by Keith-CY** [comment]
Hi @991walt
Could you paste the tx hash of the withdrawal on 05-17 so I can have a look at the transaction

**Comment by 991walt** [comment]
went online tonight to get the information to you and i tried to unlock it again just in case and it did un-lock. I am good now so thank you for all your help in the matter. We all good now thanks
