### ISSUE TITLE
i send coins from kucoin to neuron but not able to it as balance

### ISSUE THREAD

**Issue by jithv198787** [nervosnetwork/neuron#2423]
**Describe the bug** (Please enter details, the more detail the better)

not able to see my balance 
ckb1qzda0cr08m85hc8jlnfp3zer7xulejywt49kt2rr0vthywaa50xwsq05rc9y9fs2499txmgngdfyyk7fsfpntscaeew7l
ckb1qyq0g8s2g2nq4222kdk3xs6jgfdunqjrxhpsd4gnrs

[0x9baac8e40cb3c29bdb2d7e6bfc007957e785eb794a54153f36780f851a88bafd](https://explorer.nervos.org/transaction/0x9baac8e40cb3c29bdb2d7e6bfc007957e785eb794a54153f36780f851a88bafd)

2 addres in my wallet i send it to the first one but no balance can be seen in my wallet , 
**Debug info** (Please u
[neuron_debug_1655311919154.zip](https://github.com/nervosnetwork/neuron/files/8911554/neuron_debug_1655311919154.zip)
pload the debug info from `Help` - `Export Debug Information`)

**Screenshots** (If applicable, add screenshots to help explain your problem.)

**Comment by Keith-CY** [comment]
Hi @jithv198787 
There's an error listed in the logs
```
[2022-06-15 21:50:44.380] [error] {
  constructor: 'Error',
  killed: false,
  code: 1,
  signal: null,
  cmd: 'REG QUERY HKEY_LOCAL_MACHINE\\SOFTWARE\\Microsoft\\VisualStudio\\14.0\\VC\\Runtimes\\x64',
  stdout: '',
  stderr: 'ERROR: The system was unable to find the specified registry key or value.\r\n',
  stack: 'Error: Command failed: REG QUERY HKEY_LOCAL_MACHINE\\SOFTWARE\\Microsoft\\VisualStudio\\14.0\\VC\\Runtimes\\x64\n' +
    'ERROR: The system was unable to find the specified registry key or value.\r\n' +
    '\n' +
    '    at ChildProcess.exithandler (node:child_process:406:12)\n' +
    '    at ChildProcess.emit (node:events:394:28)\n' +
    '    at maybeClose (node:internal/child_process:1064:16)\n' +
    '    at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)'
}
```
saying a required dependency `vc_redist` is missing, it(vc_redist.x64.exe) can be downloaded from https://docs.microsoft.com/en-US/cpp/windows/latest-supported-vc-redist?view=msvc-170

**Comment by jithv198787** [comment]
still having  the same issue

**Comment by Keith-CY** [comment]
If it shows like this
![image](https://user-images.githubusercontent.com/7271329/173887428-a7b9bdbb-5ef4-40de-9c5d-93424d2bb76a.png)
instead of a red alert, it works, and your balance will be updated once the synchronization is done(block number reaches 7,426,823)

**Comment by jithv198787** [comment]
can i use any other wallets and which one i can use

**Comment by Keith-CY** [comment]
> ![WhatsApp Image 2022-06-15 at 10 49 38 PM](https://user-images.githubusercontent.com/107573310/173887780-f79a6d85-29c2-4a73-98e5-ec6f4647beba.jpeg)

It starts working, and be patient the synchronization will take hours(because Neuron is a full-node wallet, which runs a ckb node as data source)

**Comment by jithv198787** [comment]
o ok 

thanks

**Comment by Keith-CY** [comment]
> can i use any other wallets and which one i can use

There're several mobile wallets for CKB, usually we recommend imtoken and safepal.

**Comment by Keith-CY** [comment]
> so in few days all will be good right so just chill and wait i can do that

Yes, your assets are safe if they can be found in your address on ckb explorer, Neuron is just used to manage your assets(sending/depositing them). And your assets will appear in Neuron when synchronization reaches block number at which your assets are received.

**Comment by packratllc** [comment]
Hey I have similar issue.  I tried transferring all my ckb from my kucoin wallet to my Neuron wallet.  Kucoin says that the transaction is complete on their end and there is nothing they can do about it. My neuron wallet shows 0 ckb. I tired clearing the catch and re- syncing the wallet. no luck.  I'm not sure what to do now, any help would be great! 
 
[bundled-ckb.log](https://github.com/nervosnetwork/neuron/files/9183106/bundled-ckb.log)
[hd_public_key_info.csv](https://github.com/nervosnetwork/neuron/files/9183108/hd_public_key_info.csv)
[main.log](https://github.com/nervosnetwork/neuron/files/9183109/main.log)


2022/07/21 15:08:51

ckb1qyqgykyk69mvxyc9mdmzt8n890y3lc2zq4rq90rvrc

TxHash: 0x500cac3fe3e19244e54dd0c45d2ae9cd4e6d18ea033cba3a691e0fee70f3c9f6

**Comment by Keith-CY** [comment]
> Hey I have similar issue. I tried transferring all my ckb from my kucoin wallet to my Neuron wallet. Kucoin says that the transaction is complete on their end and there is nothing they can do about it. My neuron wallet shows 0 ckb. I tired clearing the catch and re- syncing the wallet. no luck. I'm not sure what to do now, any help would be great!
> 
> [bundled-ckb.log](https://github.com/nervosnetwork/neuron/files/9183106/bundled-ckb.log) [hd_public_key_info.csv](https://github.com/nervosnetwork/neuron/files/9183108/hd_public_key_info.csv) [main.log](https://github.com/nervosnetwork/neuron/files/9183109/main.log)
> 
> 2022/07/21 15:08:51
> 
> ckb1qyqgykyk69mvxyc9mdmzt8n890y3lc2zq4rq90rvrc
> 
> TxHash: 0x500cac3fe3e19244e54dd0c45d2ae9cd4e6d18ea033cba3a691e0fee70f3c9f6

You CKB is absolutely transferred to `ckb1qyqgykyk69mvxyc9mdmzt8n890y3lc2zq4rq90rvrc` and can be checked in the explorer https://explorer.nervos.org/transaction/0x500cac3fe3e19244e54dd0c45d2ae9cd4e6d18ea033cba3a691e0fee70f3c9f6#0

From the explorer we can see the transaction happened at `7,686,543` while `bundled-ckb.log` says your neuron just synchronized to `716398`, you have to wait another `6970145` blocks to see the transaction appearing in neuron.
