### ISSUE TITLE
"Deposit rules" link in Neuron v0.103.1 is not working

### ISSUE THREAD

**Issue by alejandroRbit** [nervosnetwork/neuron#2435]
The "Deposit rules" link in Neuron version 0.103.1 is not working. 

![unknown-10](https://user-images.githubusercontent.com/94946624/177014140-b063d786-d573-4903-bf89-14e5a50b4a0e.png)

The link redirects to: 

 https://docs.nervos.org/docs/basics/guides/neuron#5-deposit-your-nervos-ckbyte-tokens-into-nervos-dao

**Comment by Keith-CY** [comment]
> The "Deposit rules" link in Neuron version 0.103.1 is not working.
> 
> ![unknown-10](https://user-images.githubusercontent.com/94946624/177014140-b063d786-d573-4903-bf89-14e5a50b4a0e.png)
> 
> The link redirects to:
> 
> [docs.nervos.org/docs/basics/guides/neuron#5-deposit-your-nervos-ckbyte-tokens-into-nervos-dao](https://docs.nervos.org/docs/basics/guides/neuron#5-deposit-your-nervos-ckbyte-tokens-into-nervos-dao)

Thanks, @alejandroRbit
The active link is https://docs.nervos.org/docs/basics/guides/crypto%20wallets/neuron/#deposit-ckb-into-nervos-dao and we'll fix it in the next version.
