### ISSUE TITLE
Cannot get to set CKB NODE DATA and CKB INDEXER DATA folders

### ISSUE THREAD

**Issue by virtueorvice** [nervosnetwork/neuron#2455]
**Describe the bug** (Please enter details, the more detail the better)
The new feature comes with two directories that we can set. However, whenever I set one of the above directories, the other is also set to the one I made for the previous one.

No syncing goes on and even with previously downloaded data, Neuron wallet wants to start syncing from afresh. 
**Debug info** (Please upload the debug info from `Help` - `Export Debug Information`)

**Screenshots** (If applicable, add screenshots to help explain your problem.)

**Comment by yanguoyu** [comment]
@Cedar67 Can you try to reproduce this problem? I can‘t reproduce this problem on Neuron 0.103.2

**Comment by Cedar67** [comment]
Hi, @virtueorvice 
Are the two directories you mentioned above the 1 and 2 patterns identified below?
The Settings 1 and 2 are independent and do not interfere with each other. I do not reproduce the appearance you mentioned `"The other is also set to the one I made for the previous one."`
Could you please provide the replayed screen recording so as to confirm the problem appearance?
Also, could you export and upload debug Info here? Thanks.

![image](https://user-images.githubusercontent.com/64718893/179646947-ad40b966-a359-47cc-8d82-4890f2da9f64.png)

**Comment by virtueorvice** [comment]
I had a backup of my Neuron folder in AppData/roaming. I deleted the local folder on windows and copied the backed-up Neuron and everything started working.

**Comment by Cedar67** [comment]
> I had a backup of my Neuron folder from AppData/roaming. I deleted the local folder and copied the backed-up Neuron folder and everything started working.

@virtueorvice  Feel like your problems have been solved?

**Comment by virtueorvice** [comment]
Yes
