### ISSUE TITLE
Deposit didn't arrive from CRYPTO.COM

### ISSUE THREAD

**Issue by pkf888** [nervosnetwork/neuron#2460]
hello, I ve spent hours on chat with crypto.com, I whitelisted my neuron CKB address (Ledger Nano X) in a deprecated format 2 days ago. I did a test and with the TXid 0x6508663ab373c83e8c158bc9b65ee3a72ab1ea0e6db67b344dc1e240a43a21d2, the test funds didn't arrive. 

Today I send from Neuron Wallet to Crypto.com and arrived. From Crypto.com they keep buzzing me to contact the neuron support. it is an issue on the receivers address they claim. I am afraid to move any more CKB from any other exchanges to neuron anymore.

**Comment by Keith-CY** [comment]
We can check the transaction `0x6508663ab373c83e8c158bc9b65ee3a72ab1ea0e6db67b344dc1e240a43a21d2` at https://explorer.nervos.org/transaction/0x6508663ab373c83e8c158bc9b65ee3a72ab1ea0e6db67b344dc1e240a43a21d2 and if one of the output is your whitelisted neuron CKB Address, the asset should be safe and appear in Neuron
![image](https://user-images.githubusercontent.com/7271329/182145630-1858dd7a-e4cd-4431-b6d9-d66e2580c69c.png)

And if it doesn't appear in Neuron, please `clear cache without rebuilding index` in `setting -> data`(v0.103.2) or `setting -> general`(other versions), it could be a problem of data-cache

**Comment by pkf888** [comment]
Hello Keith-CY, yes I checked the crypto.com whitelist address is the same as in my neuron (ledger) wallet. Though my question would be it is the shorter one (named deprecated) not the long one address. Do you think this could be an issue? 
I cleared cache as per the above details (thank you so much for this I appreciate it as I am new to neuron wallet)and still my balance is zero. I can see the successful transactions in and out using the long address inbound from Binance and outbound towards crypto.com they appear ok.

**Comment by pkf888** [comment]
It can't be done is gray., I double checked now and The address in my whitelist in crypto.com I had entered the shorter one deprecated. See below:

(Long) ckb1qzda0cr08m85hc8jlnfp3zer7xulejywt49kt2rr0vthywaa50xwsqtnfa827k2qaehzv4swwxdt0pju5hypn2q6p894f

 (Short) ckb1qyq8xn6w4av5pmnwyetquuv6k7r9efwgrx5qy74hsg


In the below TXid address I cannot see my address neither the short or long one. can you please check as well? Then Crypto.com must messed it up. Shouldn't they know from the short address the correct one?

https://explorer.nervos.org/transaction/0x6508663ab373c83e8c158bc9b65ee3a72ab1ea0e6db67b344dc1e240a43a21d2


<img width="380" alt="Screenshot 2022-08-01 at 19 23 04" src="https://user-images.githubusercontent.com/110395801/182197193-21655a33-5566-4ebf-9443-f3d11c5561ea.png">

**Comment by Keith-CY** [comment]
> I only have one address in my received <img alt="Screenshot 2022-08-01 at 19 28 47" width="1363" src="https://user-images.githubusercontent.com/110395801/182198184-38759b87-b5e7-40a3-9834-78795335b924.png">

My fault, I forgot that you are using a hardware wallet, which only has one address. Now I get your address, I'll delete the screenshot for your privacy

**Comment by Keith-CY** [comment]
This address should have `2,395.60100000 CKB` as its balance
It received `≈2,409 CKB` at block number 7747024 and sent them out at block number 7758846
Finally, it received `≈2,395` at block number 7761877, which means the total balance should be `0` until Neuron reaches 7761877.

From the screenshot in https://github.com/nervosnetwork/neuron/issues/2460#issuecomment-1201384127 we can see your neuron just reached 7761767, it requires synchronizing 110 more blocks to show your latest balance.

Once the number at the left-bottom corner is greater than 7761767, `Balance: 2395.6 CKB` should appear.

**Comment by pkf888** [comment]
I did add now from Binance this amount to check if it works. that's correct.

**Comment by pkf888** [comment]
The 10.000 CKB - 2CKB fees is still not present and missing from crypto.com to the address. I just contacted them and they don't recognise their mistake although I sent them screenshot that the address I had whitelisted was correct and it doesn't appear anywhere in the TXid.

**Comment by pkf888** [comment]
I think what I will do is convert my CKB to USDC in crypto.com, send it to kucoin and buy it there to send it to my neuron wallet. I don't trust them anymore with a huge amount (eg 20mil CKB). Its good I did I small amount test of 10k ckb to see if it works. What can I say...

**Comment by Keith-CY** [comment]
> The 10.000 CKB - 2CKB fees is still not present and missing from crypto.com to the address. I just contacted them and they don't recognise their mistake although I sent them screenshot that the address I had whitelisted was correct and it doesn't appear anywhere in the TXid.

From the explorer (https://explorer.nervos.org/address/ckb1qyq8xn6w4av5pmnwyetquuv6k7r9efwgrx5qy74hsg) we cannot find a transaction of `hash/id` `0x6508663ab373c83e8c158bc9b65ee3a72ab1ea0e6db67b344dc1e240a43a21d2` so this transaction should have nothing to do with your wallet.

Instead, the tx `0x6508663ab373c83e8c158bc9b65ee3a72ab1ea0e6db67b344dc1e240a43a21d2` sent CKB to 
```
# short addresses
output#0 ckb1qyq0r2nngcs3tdr6psrdq932m0h9ppa7w9yqp6g0ac
output#1 ckb1qyqv68gp2xu8cfd0nw60085sdww25uhk6z8sj649uk
# long addresses
output#0 ckb1qzda0cr08m85hc8jlnfp3zer7xulejywt49kt2rr0vthywaa50xwsq034fe5vgg4k3aqcpkszc4dhmjss7l8zjqgk9k6s
output#1 ckb1qzda0cr08m85hc8jlnfp3zer7xulejywt49kt2rr0vthywaa50xwsqwdr5q4rwruykhehd8hn6gxh892wtmdprcw3h3ce
```

None of them equals to your neuron address

**Comment by Keith-CY** [comment]
> I think what I will do is convert my CKB to USDC in crypto.com, send it to kucoin and buy it there to send it to my neuron wallet. I don't trust them anymore with a huge amount (eg 20mil CKB). Its good I did I small amount test of 10k ckb to see if it works. What can I say...

Sorry for that, and I'll contact with the core team to check if crypto.com is prone to parse addresses incorrectly.

**Comment by Keith-CY** [comment]
I'll mosaic your address in this issue for privacy

**Comment by pkf888** [comment]
I really honestly appreciate this support from your side it was more than I expected! Thank you so much!

**Comment by pkf888** [comment]
Just one last thing, is it possible to change my address now on my Neuron wallet (Ledger address)? for safety cause I understand I shouldn't share it .

**Comment by Keith-CY** [comment]
> Just one last thing, is it possible to change my address now on my Neuron wallet (Ledger address)? for safety cause I understand I shouldn't share it .

I'm afraid not, ledger supports a single private key that is mapped to a single ckb address, so we cannot derive another ckb address from it.

**Comment by Keith-CY** [comment]
Some analysis from the core team

1. The transaction (https://explorer.nervos.org/transaction/0x6508663ab373c83e8c158bc9b65ee3a72ab1ea0e6db67b344dc1e240a43a21d2) returned from crypto.com is valid from the perspective of crypto.com because the receiver (ckb1qyq0r2nngcs3tdr6psrdq932m0h9ppa7w9yqp6g0ac) had sent some transaction, so it's under control, not an improperly decoded address;
2. The receiver received 9998 ckb, the same as the amount you had set in your transfer(send 10k ckb and pay 2 ckb as fee);
3. You didn't receive 9998 ckb.

And a **"guess"** from me: the receiver is a special address because it kept receiving `X ckb` and sent them all to `ckb1qzda0cr08m85hc8jlnfp3zer7xulejywt49kt2rr0vthywaa50xwsqvmw2jqcuw44t2zgghea45572z8hgmkdrgkepvzr` within 1 hour, like a proxy address. Now it received 2 more txs but didn't sent them out for more than 12 hours, maybe its owner didn't know the 2 more txs.


The most possible case is that crypto.com decoded your address successfully but mapped it to another user's address, so 9998 ckb was sent to it.

**Comment by pkf888** [comment]
Thank you so much Keith! Immensely appreciated!!
