### ISSUE TITLE
[Synchronization] How to fill RPC URL?

### ISSUE THREAD

**Issue by felicityin** [nervosnetwork/neuron#2480]
### Detail of the issue

How to fill the RPC URL?
![1](https://user-images.githubusercontent.com/107106858/187820910-242f97a2-a6e4-4259-9b9e-b343532daa46.png)

**Comment by Keith-CY** [comment]
Hi @felicityin 

I can edit the `default node` with RPC URL `https://mainnet.ckb.dev/rpc` and add a new node named `another default node` with RPC URL `https://mainnet.ckb.dev/rpc`.

May I know the version of your neuron and the steps of adding/editing a network so I can try to reproduce this case and find out the reason.

**Comment by felicityin** [comment]
> Hi @felicityin
> 
> I can edit the `default node` with RPC URL `https://mainnet.ckb.dev/rpc` and add a new node named `another default node` with RPC URL `https://mainnet.ckb.dev/rpc` with Neuron@v0.103.2
> 
> May I know the version of your neuron and the steps of adding/editing a network so I can try to reproduce this case and find out the reason.

But when I added the RPC URL `https://mainnet.ckb.dev/rpc`, sync failed:
![1](https://user-images.githubusercontent.com/107106858/187831164-efd804cf-11ce-4cd3-a703-40906abd2dea.png)
Is the RPC URL of the mainnet wrong?

**Comment by Keith-CY** [comment]
> > Hi @felicityin
> > I can edit the `default node` with RPC URL `https://mainnet.ckb.dev/rpc` and add a new node named `another default node` with RPC URL `https://mainnet.ckb.dev/rpc` with Neuron@v0.103.2
> > May I know the version of your neuron and the steps of adding/editing a network so I can try to reproduce this case and find out the reason.
> 
> But when I added the RPC URL `https://mainnet.ckb.dev/rpc`, sync failed: ![1](https://user-images.githubusercontent.com/107106858/187831164-efd804cf-11ce-4cd3-a703-40906abd2dea.png) Is the RPC URL of the mainnet wrong?
> 
> Neuron version: ![1](https://user-images.githubusercontent.com/107106858/187831371-c428ee5e-bb10-4277-b329-c08efb93fad7.png)

So the real issue is not `cannot add/edit network with "name: default node", "rpc URL: https://mainnet.ckb.dev/rpc"`, but is `cannot connect to https://mainnet.ckb.dev/rpc`, am I right

**Comment by felicityin** [comment]
> > > Hi @felicityin
> > > I can edit the `default node` with RPC URL `https://mainnet.ckb.dev/rpc` and add a new node named `another default node` with RPC URL `https://mainnet.ckb.dev/rpc` with Neuron@v0.103.2
> > > May I know the version of your neuron and the steps of adding/editing a network so I can try to reproduce this case and find out the reason.
> > 
> > 
> > But when I added the RPC URL `https://mainnet.ckb.dev/rpc`, sync failed: ![1](https://user-images.githubusercontent.com/107106858/187831164-efd804cf-11ce-4cd3-a703-40906abd2dea.png) Is the RPC URL of the mainnet wrong?
> > Neuron version: ![1](https://user-images.githubusercontent.com/107106858/187831371-c428ee5e-bb10-4277-b329-c08efb93fad7.png)
> 
> So the real issue is not `cannot add/edit network with "name: default node", "rpc URL: https://mainnet.ckb.dev/rpc"`, but is `cannot connect to https://mainnet.ckb.dev/rpc`, am I right

Yes, you are right. My bad.

**Comment by Keith-CY** [comment]
> > > > Hi @felicityin
> > > > I can edit the `default node` with RPC URL `https://mainnet.ckb.dev/rpc` and add a new node named `another default node` with RPC URL `https://mainnet.ckb.dev/rpc` with Neuron@v0.103.2
> > > > May I know the version of your neuron and the steps of adding/editing a network so I can try to reproduce this case and find out the reason.
> > > 
> > > 
> > > But when I added the RPC URL `https://mainnet.ckb.dev/rpc`, sync failed: ![1](https://user-images.githubusercontent.com/107106858/187831164-efd804cf-11ce-4cd3-a703-40906abd2dea.png) Is the RPC URL of the mainnet wrong?
> > > Neuron version: ![1](https://user-images.githubusercontent.com/107106858/187831371-c428ee5e-bb10-4277-b329-c08efb93fad7.png)
> > 
> > 
> > So the real issue is not `cannot add/edit network with "name: default node", "rpc URL: https://mainnet.ckb.dev/rpc"`, but is `cannot connect to https://mainnet.ckb.dev/rpc`, am I right
> 
> Yes, you are right. My bad.

My neuron has connected to `https://mainnet.ckb.dev/rpc`, I think it might be a problem of network status

![image](https://user-images.githubusercontent.com/7271329/187833095-cd9c7a1c-0def-48c9-bd4b-a600f355c99e.png)

**Comment by Keith-CY** [comment]
> > > > > Hi @felicityin
> > > > > I can edit the `default node` with RPC URL `https://mainnet.ckb.dev/rpc` and add a new node named `another default node` with RPC URL `https://mainnet.ckb.dev/rpc` with Neuron@v0.103.2
> > > > > May I know the version of your neuron and the steps of adding/editing a network so I can try to reproduce this case and find out the reason.
> > > > 
> > > > 
> > > > But when I added the RPC URL `https://mainnet.ckb.dev/rpc`, sync failed: ![1](https://user-images.githubusercontent.com/107106858/187831164-efd804cf-11ce-4cd3-a703-40906abd2dea.png) Is the RPC URL of the mainnet wrong?
> > > > Neuron version: ![1](https://user-images.githubusercontent.com/107106858/187831371-c428ee5e-bb10-4277-b329-c08efb93fad7.png)
> > > 
> > > 
> > > So the real issue is not `cannot add/edit network with "name: default node", "rpc URL: https://mainnet.ckb.dev/rpc"`, but is `cannot connect to https://mainnet.ckb.dev/rpc`, am I right
> > 
> > 
> > Yes, you are right. My bad.
> 
> My neuron has connected to `https://mainnet.ckb.dev/rpc`, I think it might be a problem of network status
> 
> ![image](https://user-images.githubusercontent.com/7271329/187833095-cd9c7a1c-0def-48c9-bd4b-a600f355c99e.png)

To verify it, you may launch a mainnet node locally and connect neuron to the local node, if it works, neuron should have no problem to connect to a remote node

**Comment by felicityin** [comment]
> 

It is ok to connect to the local node.
