### ISSUE TITLE
transaction history export does not include dates

### ISSUE THREAD

**Issue by wazzutroy** [nervosnetwork/neuron#2496]
Each time I try to export my transaction history, it only includes:
-time
-block number
-transaction hash
-transaction type
-CKB amount
-UDT amount (entire column blank, no entries)
-description (entire column blank, no entries)

Is this typical or should more information be populated? Specifically, I was assuming the transaction dates would be included.
thanks.

**Comment by Cedar67** [comment]
Hi @wazzutroy 
The latest Neuron release includes date info. Please update it to [the latest version](https://github.com/nervosnetwork/neuron/releases/tag/v0.103.2) and confirm again.

<img width="941" alt="image" src="https://user-images.githubusercontent.com/64718893/192912735-99a7dcb1-68f6-4cfc-ac5f-c12bd89e48ba.png">

**Comment by wazzutroy** [comment]
This is what version I have installed since I updated last week, let me know if this is not the latest:

[cid:ef0c08ad-d672-4dc3-b246-52d46871ed92]
________________________________

**Comment by Cedar67** [comment]
@wazzutroy The version info is not fully displayed here. Could you pls send it again? 
And it is better to send the screenshot of the transaction exported file that contains the time field.

**Comment by wazzutroy** [comment]
I apologize for taking up your time, I realized it was just a formatting issue and I was able to get the date to display properly on my exported excel file. You can consider this issue (non-issue) resolved. I appreciate your help, thanks.
________________________________

**Comment by Cedar67** [comment]
> I apologize for taking up your time, I realized it was just a formatting issue and I was able to get the date to display properly on my exported excel file. You can consider this issue (non-issue) resolved. I appreciate your help, thanks.

It doesn't matter. Thanks for your feedback.

**Comment by wazzutroy** [comment]
Trying as attachments now instead of embedded, see if this comes through.
thanks,
Troy

________________________________
