### ISSUE TITLE
[Synchronization] **brief description**

### ISSUE THREAD

**Issue by RobertCruzo** [nervosnetwork/neuron#2497]
### Detail of the issue

 Neuron doesn't start syncing because the ckb node throws an exception.
 it is written that the ledger is connected to the neuron , but the tokens are not displayed

**Comment by yanguoyu** [comment]
![image](https://user-images.githubusercontent.com/12881040/194331221-6f1994d9-bfd0-457f-a08a-ac387a4bc1be.png)
I found the ckb node throw exception like this. 
Can you provide any help? @quake
