### ISSUE TITLE
Transaction failed to resolve

### ISSUE THREAD

**Issue by dicker14** [nervosnetwork/neuron#2498]
Attempting to deposit ckb from neuron wallet to Yokai L1 deposit address

neuron_debug_1665228524103

**Screenshots** (If applicable, add screenshots to help explain your problem.)
[neuron_debug_1665228524103.zip](https://github.com/nervosnetwork/neuron/files/9739102/neuron_debug_1665228524103.zip)

**Comment by Cedar67** [comment]
Hi @dicker14,
You can try the `clear cache` operation first (Preference / Data /  Clear Cache), and then make the transaction.

**Comment by dicker14** [comment]
Hi Thanks for the advice. I did this already and the result is the same error unfortunately

**Comment by yanguoyu** [comment]
@dicker14 Have you synced to 100% already? I found the Outpoint cell had cost.
https://explorer.nervos.org/transaction/0x68355c40c0e8f46d3257df2e5a4ecd16dd486e90d0f89447566bf37f5850589e 
this transaction used the cell.
