### ISSUE TITLE
my CKB coins didnt reach

### ISSUE THREAD

**Issue by whereismyckb** [nervosnetwork/neuron#2500]
### Detail of the issue

i sent CKB today and got nothing, all lost

**Comment by Keith-CY** [comment]
Hi @whereismyckb could you add some details like

CKB is sent from where to where(from neuron or to neuron)

If it's sent from neuron to elsewhere, could you post the transaction hash shown in neuron
If it's sent to neuron, could you post the transaction hash which is accessible on https://explorer.nervos.org/
