### ISSUE TITLE
Nervos Dao **Keep Hanging**

### ISSUE THREAD

**Issue by ahming123** [nervosnetwork/neuron#2523]
### Detail of the issue

Hi there,

So I am trying to withdraw the CKB neuron dao staking but it always says keep hanging once i click the withdraw button and need to force quit to run it again

I have tried clear the ckb_indexer_data but still face the same problem. i'm not sure if clear the ckb_indexer_data is the correct way.

I have cleared cache etch still doesnt work.

Please advised. Many thanks

[neuron_debug_1667968948000.zip](https://github.com/nervosnetwork/neuron/files/9967944/neuron_debug_1667968948000.zip)

**Comment by yanguoyu** [comment]
Hey, it keeps hanging after which action? After clicking `withdraw` or click `Confirm`?
<img width="1206" alt="image" src="https://user-images.githubusercontent.com/12881040/200782296-5b6578d6-00c9-4571-846b-afc724ad0a77.png">
<img width="671" alt="image" src="https://user-images.githubusercontent.com/12881040/200782327-e8342bcd-ea35-4c46-9554-01cb046ba7b1.png">

**Comment by ahming123** [comment]
both also same... sometime after click the withdraw it go through enter the password. once i click the confirm then it keep hang again. cannot submit at all. then keep force quit to restart and repeat the same process.

i wonder if i use PC to sync all over again will it help? currently is using IMAC

**Comment by yanguoyu** [comment]
> 

I'm sorry to tell you that this may not help. It may effect by other problems.
I will keep attention to it.

**Comment by yanguoyu** [comment]
@ahming123 When you withdraw from `Neuron`, does the `Neuron` sync to 100%?
I found that Neuron synced to `8371438` at `2022-11-08 19:24:01.028`. `8371438` block was created at `2022/10/30 10:03:59`.
Can you try to withdraw again after `Neuron` sync to 100%?

**Comment by ahming123** [comment]
Previously is sync 100% then only i withdraw. i try again and see

**Comment by ahming123** [comment]
on the neuron wallet overview is sync 100%, once i click into the the nervos dao the word that appear is  to "sync at 99.99% "and stuck at there. after wait for a long time, i decided to force quit it and relaunch back. after that the word "sync not started yet" appear. Seems to stuck at there for a long time also. Any advised pls? attached below is the log. Kindly help
[neuron_debug_1668079906104.zip](https://github.com/nervosnetwork/neuron/files/9980297/neuron_debug_1668079906104.zip)

**Comment by ahming123** [comment]
any other way that i can withdraw the staking?

**Comment by yanguoyu** [comment]
@ahming123 Can you join https://discord.gg/74XTE73R for instant communication?

**Comment by Keith-CY** [comment]
Has been resolved via discord channel
