### ISSUE TITLE
CKB from Binance to Neuron of Ledger not showing up.

### ISSUE THREAD

**Issue by Steveanderson315** [nervosnetwork/neuron#2528]
I sent some CKB from my binance to my ledger but it isn't showing up in my neuron wallet. On Binance it says completed.

Updated nervous app on ledger

Made sure wallet was fully synced

Made sure address is fully accurate.

I have a txid... not sure what's going on.  Any help would be appreciated. 

Thanks,

**Comment by Cedar67** [comment]
@Steveanderson315 Could you upload the txid and Neuron logs here for locating it?
