### ISSUE TITLE
Dependency Required

### ISSUE THREAD

**Issue by AIC-29** [nervosnetwork/neuron#2535]
**Describe the bug** (Please enter details, the more detail the better)

I get a popup when I start the program saying that my computer does not have the x64 Redistributable, which is not the case since I do have the x64 Redistributable installed. I tried uninstalling/reinstalling both Neuron and x64 Redistributable (both from Microsofot and Visual C++ Redistributable All-in-One from TechPowerUp) without success, restarting the computer after each step. I also deleted the information in \AppData\Roaming\Neuron after uninstalling but the problem persists. If I close the popup, Neuron closes as well. 

Processor: Intel(R) Core(TM) i5-4440 CPU @ 3.10GHz (4 CPUs), ~3.1GHz
Operating System: Windows 10 Pro 64-bit (10.0, Build 19044) 

**Debug info** (Please upload the debug info from `Help` - `Export Debug Information`)

[neuron_debug_1669412932439.zip](https://github.com/nervosnetwork/neuron/files/10095170/neuron_debug_1669412932439.zip)

**Screenshots** (If applicable, add screenshots to help explain your problem.)

![imagen](https://user-images.githubusercontent.com/90740496/204058269-abd7c4f8-99ec-4795-9d77-ecde4f07c814.png)

**Comment by yanguoyu** [comment]
@Cedar67 Can you try this problem?

**Comment by Cedar67** [comment]
@AIC-29 Can you confirm if the appropriate Visual C++ Redistributable is installed?
You may need to install the latest [Microsoft Visual C++ Redistributable for Visual Studio 2015, 2017 and 2019](https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads).

**Comment by AIC-29** [comment]
Yes, the appropriate Visual C++ Redistributable has been installed. I also used the all in one package from TechPowerUp.

**Comment by Cedar67** [comment]
@AIC-29 According to your screenshot and log, it is presumed that it is related to the setting of the operating system PATH environment variable.

![image](https://user-images.githubusercontent.com/64718893/204518378-5a14d385-1220-40db-b930-612ca68e09fc.png)

Solution: add the path C:\Windows\System32\ to the Environment Variables.

- Right click the My Computer icon then choose properties.
- Select the Advanced tab and then click Environment Variables.
- At the system variables panel, choose Path then click the Edit button.
- Add C:\Windows\System32\, the paths are separated by a semicolon.

Click [here](https://helpdeskgeek.com/how-to/fix-not-recognized-as-an-internal-or-external-command/) for more information.

**Comment by AIC-29** [comment]
That was the solution, thank you very much!
