### ISSUE TITLE
Transfer from Binance to Neuron using Ledger Nano S plus was not credited

### ISSUE THREAD

**Issue by Vitragesolaire** [nervosnetwork/neuron#2545]
The transfer from Binance Börse to the Neuron app using my Ledger Wallet Nano S plus has worked like expected, but the CKB transfer was finally not credited.
Could you help me?
Thanks
TxID: 0x1be6e0ce1f4bdb513fad5c19e09df113066d6b12907d03bcc168c7e447f8a02a
[neuron_debug_1670962309416.zip](https://github.com/nervosnetwork/neuron/files/10221737/neuron_debug_1670962309416.zip)

**Comment by yanguoyu** [comment]
https://explorer.nervos.org/transaction/0x1be6e0ce1f4bdb513fad5c19e09df113066d6b12907d03bcc168c7e447f8a02a
This is the transaction page, the transaction has success. You can't view it on `Neuron` maybe because it has not synced to 100%.

**Comment by Vitragesolaire** [comment]
Fine. Thank you very much.--Envoyé à partir d’un Smartphone Android avec WEB.DE Mail.Am 14.12.22, 01:15 schrieb "严国宇" ***@***.***>:

   
  https://explorer.nervos.org/transaction/0x1be6e0ce1f4bdb513fad5c19e09df113066d6b12907d03bcc168c7e447f8a02a This is the transaction page, the transaction has success. You can't view it on Neuron maybe because it has not synced to 100%.
