### ISSUE TITLE
Sync not connection after update

### ISSUE THREAD

**Issue by Pdixon1453** [nervosnetwork/neuron#2547]
### Detail of the issue

I updated the Neuron wallet on my PC (windows) and have tried everything to get it back to sync but failing.  Here is the debug report
[neuron_debug_1671051479035.zip](https://github.com/nervosnetwork/neuron/files/10231751/neuron_debug_1671051479035.zip)

**Comment by Pdixon1453** [comment]
![image](https://user-images.githubusercontent.com/120602684/207717760-88464aeb-5fec-4403-9a7a-d42fe9ecfd5c.png)

**Comment by yanguoyu** [comment]
I found these log `IO Error: Os { code: 5, kind: PermissionDenied, message: "Access is denied." }` in the main.log.
CKB node init failed, Maybe you have no access to write files in the data directory. Maybe you can set `ckb node data` path.
Follow these steps, Neuron -> preferences -> data.
Reference this [PR](https://github.com/nervosnetwork/neuron/pull/2433)

<img width="799" alt="image" src="https://user-images.githubusercontent.com/12881040/207763837-66f2f835-2fde-4ceb-8dee-e999d9b91c38.png">
