### ISSUE TITLE
[Synchronization] **Linux Mint 19.3 : Block synch stuck at 86,86%**

### ISSUE THREAD

**Issue by GCM15** [nervosnetwork/neuron#2548]
### Detail of the issue

The sync is stuck at block 7 611 480 / 8 763 038.
Left the machine on for hours but nothing moves.
My hard dis drive have enough free space (checked).
Please could you help me ?
I have been trying many times to restart neuron (using Neuron-v0.103.2-x86_64(1).AppImage) nothing changes.
[neuron_debug_1671364923289.zip](https://github.com/nervosnetwork/neuron/files/10253771

Thanks.

**Comment by yanguoyu** [comment]
@GCM15  I'm sorry to tell you I haven't seen the log you uploaded.

**Comment by GCM15** [comment]
Thanks but everything is ok now.
Good luck for the project :-)

**Comment by GCM15** [comment]
Problem Solved
