### ISSUE TITLE
[v0.106.0] Issues on upgrading to Neuron@v0.106.0

### ISSUE THREAD

**Issue by yanguoyu** [nervosnetwork/neuron#2557]
### Neuron needs to re-sync indexer data when update from early to 0.106

Because after `ckb node` update to 0.106, the indexer service has merge into `ckb-core`. So we remove the indexer data path from `Neuron` at 0.106. But the `ckb node` will not create indexer data when migrating old data to new data. So the indexer data will sync from the beginning. It will cost about 30~50 minutes to re-sync indexer data.

On the other hand, we strongly recommended you to backup the old data before migrating, the `ckb node` data path can be found by clicking `preference` -> `Data` -> `CKB Node Config & Storage`. Because once the migration started, the data will be no longer compatible with all older versions of` CKB`.

### Upgrade on macOS

`Neuron for macOS` has supported Apple silicon chips since v0.106.0, so there're two versions, `x64` for intel chips and `arm64` for apple silicon chips:
OS | Arch | Package | SHA256 Checksum
-- | -- | -- | --
macOS | x64 | [zip](https://github.com/nervosnetwork/neuron/releases/download/v0.106.0/Neuron-v0.106.0-mac-x64.zip) | <code>97ee83b8330515b77c53ac970181b942aea09b6664e913c02cd452cab0ec4635</code>
macOS | arm64 | [zip](https://github.com/nervosnetwork/neuron/releases/download/v0.106.0/Neuron-v0.106.0-mac-arm64.zip) | <code>5080518acdb733fbc0466cb8b7dba2d97d5d1fd1ab0022014c5d5b65de8279ec</code>
macOS | x64 | [DMG](https://github.com/nervosnetwork/neuron/releases/download/v0.106.0/Neuron-v0.106.0-x64.dmg) | <code>a27cb4546c57859c7e650b693920cda04cd64b274fd2d6419f1e535c7f864023</code>
macOS | arm64 | [DMG](https://github.com/nervosnetwork/neuron/releases/download/v0.106.0/Neuron-v0.106.0-arm64.dmg) | <code>25aac7745a49545593c7aa89ea0eecc82e8a132d7566baceac5031224ff35173</code>

➡️ For some reason, upgrading inside Neuron will download a **arch-mismatched version**, and the application will be unavailable. In this case, please download the correct one on the release page(https://github.com/nervosnetwork/neuron/releases/tag/v0.106.0) and replace the mismatched one.

![image](https://user-images.githubusercontent.com/7271329/211792984-c693abf3-7f45-4cee-8aec-3320e32bfda6.png)
![image](https://user-images.githubusercontent.com/7271329/211792710-392b52f0-7d3c-49f7-b569-63cd736481ed.png)

**Comment by wengby88** [comment]
我的钱包更新到 0.106 后，数据迁移了好几天，一直是正在数据迁移，正在链接节点，到底怎么了？？？

**Comment by yanguoyu** [comment]
@wengby88 迁移受硬件影响，可能时间会花费比较久，顺便可以导出日志看看我们看看是不是还在迁移，或者删除`偏好设置-> 数据 -> 节点配置和数据`文件夹，然后重新打开 `Neuron` 同步。
<img width="1326" alt="image" src="https://user-images.githubusercontent.com/12881040/212527199-a4c1a9d9-44b1-4a01-9397-b2fd7d952021.png">

**Comment by CryptoGumby** [comment]
My migration has been ongoing for over 24hrs, It says migrating and connecting. After 12 hrs or so I did a restart. My balance disappeared and its still in migrating/connecting mode. From the Neuron Wallet I went to help tab to report an issue which led me here. It recommends doing a back up prior to migration but I did not as the message only alerts you after you encountered the problem. Please advise..

**Comment by Keith-CY** [comment]
> My migration has been ongoing for over 24hrs, It says migrating and connecting. After 12 hrs or so I did a restart. My balance disappeared and its still in migrating/connecting mode. From the Neuron Wallet I went to help tab to report an issue which led me here. It recommends doing a back up prior to migration but I did not as the message only alerts you after you encountered the problem. Please advise..

Hi @CryptoGumby 

A 24-hour-long migration is likely to fail. Besides, migration transformed data so it's incompatible with Neuronv0.103.0. Now the only solution is to synchronize from scratch by `Menu -> Tools -> Clear all synchronized data`

Sorry for missing the warning message before running the migration, reason was mentioned in https://github.com/nervosnetwork/neuron/issues/2448#issuecomment-1385969665

> Due to our negligence in collaboration and the temporary absence of PM, point 1(notify users about the risk of migration) was mentioned(https://github.com/nervosnetwork/neuron/pull/2517#issuecomment-1303005526) but not delivered within the application. The caveat was included in [Release note](https://github.com/nervosnetwork/neuron/releases/tag/v0.106.0) / https://github.com/nervosnetwork/neuron/issues/2557

**Comment by yanguoyu** [comment]
Some users encountered this problem `messages.codes.SQLITE_MISUSE` when downloading the **arm64** 0.106 version or upgrading to the **arm64** 0.106 version with **Apple M1**.
It may be the same as https://github.com/nervosnetwork/neuron/issues/2575. You can try to click `Help -> Export debug information`, if you can't export debug information and see `messages.codes.SQLITE_MISUSE`. I'm so sure that your problem is the same as https://github.com/nervosnetwork/neuron/issues/2575. You can try to download the **x64** 0.106 version to replace your **arm64** application.
And we have fixed it by https://github.com/nervosnetwork/neuron/pull/2609 and will release it in the next version.
