### ISSUE TITLE
UI "Migrating" button should read "Migrate"

### ISSUE THREAD

**Issue by matt-nervos** [nervosnetwork/neuron#2562]
**Describe the bug** (Please enter details, the more detail the better)

typo

**Debug info** (Please upload the debug info from `Help` - `Export Debug Information`)

open Neuron after upgrading

**Screenshots** (If applicable, add screenshots to help explain your problem.)
<img width="637" alt="image" src="https://user-images.githubusercontent.com/88007636/210658853-f3712a43-f82c-49a8-aaf6-4766ecfeedbd.png">

**Comment by yanguoyu** [comment]
https://github.com/nervosnetwork/neuron/pull/2565
