### ISSUE TITLE
Neuron Not Connecting to Mainnet After Data Migration

### ISSUE THREAD

**Issue by NonSubscribed** [nervosnetwork/neuron#2570]
Hello,

I recently launched Neuron and got a message about "storage place changing" or something like that was told that a Neuron needed to perform a data migration that would last between 20-60 minutes. I started the process, however, it never ended and I believe something went wrong as Neuron now wont connect to mainnet. I'm attaching the debug log in the hope that someone will be able to figure out what went wrong and how to fix it. 

Thanks

[neuron_debug_1673464604229.zip](https://github.com/nervosnetwork/neuron/files/10407992/neuron_debug_1673464604229.zip)

**Comment by Keith-CY** [comment]
Hi @NonSubscribed , we just got the same issue yesterday and are working on it. I'll reply here once we find the solution.

**Comment by NonSubscribed** [comment]
Thanks

**Comment by NonSubscribed** [comment]
Would uninstalling/re-installing Neuron solve this issue?

**Comment by Keith-CY** [comment]
> Would uninstalling/re-installing Neuron solve this issue?

The data migration could be avoid by clearing all synchronized data and starting it from scratch.

The “clear all synchronized data” button is in “Menu => Tools => Clear all synchronized data”

——-

Uninstalling Neuron doesn’t remove data, so the migration is still inevitable.

**Comment by S0rci3r** [comment]
Hello, following the new update (0.106.0) the migration failed. So I deleted all the .config/Neuron directory to start again on a healthy basis. Despite this, the synchronization takes a long time, after 4 days, it is about 30%. I have a very good throughput, and I had no problem on previous versions.
I am running Manjaro Linux (Arch Base) with a 6.1.1 kernel.
Thx

[neuron_debug_1673792332898.zip](https://github.com/nervosnetwork/neuron/files/10420404/neuron_debug_1673792332898.zip)

**Comment by Keith-CY** [comment]
> Hello, following the new update (0.106.0) the migration failed. So I deleted all the .config/Neuron directory to start again on a healthy basis. Despite this, the synchronization takes a long time, after 4 days, it is about 30%. I have a very good throughput, and I had no problem on previous versions. I am running Manjaro Linux (Arch Base) with a 6.1.1 kernel. Thx
> 
> [neuron_debug_1673792332898.zip](https://github.com/nervosnetwork/neuron/files/10420404/neuron_debug_1673792332898.zip)

Hi @S0rci3r 

From the `bundled-ckb.log` we can see

```
2023-01-15 14:18:22.587 +00:00 BlockDownload INFO ckb_sync::synchronizer  best known header number: 7513008, hash: Byte32(0x5f5bec6e0936b8fb10b71eb89b023cd41509299fc29c052b72eb28b035ea3333), can't find assume valid target temporarily, hash: Byte32(0x076ffa81f8c6f2e1f22a778a1aa5d48531cc33bfd9b302e0d73fb2ce6fa4de3b) please wait
2023-01-15 14:18:26.489 +00:00 GlobalRt-3 INFO ckb_sync::synchronizer::get_headers_process  Ignoring getheaders from peer=SessionId(1) because node is in initial block download
2023-01-15 14:18:27.182 +00:00 GlobalRt-4 INFO ckb_sync::synchronizer::get_headers_process  Ignoring getheaders from peer=SessionId(2) because node is in initial block download
2023-01-15 14:18:27.242 +00:00 GlobalRt-2 INFO ckb_sync::synchronizer::get_headers_process  Ignoring getheaders from peer=SessionId(3) because node is in initial block download
2023-01-15 14:18:27.360 +00:00 GlobalRt-0 INFO ckb_sync::synchronizer::get_headers_process  Ignoring getheaders from peer=SessionId(8) because node is in initial block download
```

It means the built-in CKB node is still at the early stage of synchronization, which is looking for an assumed valid target block.

The log said it reached block 7513008, block hash is `0x5f5bec6e0936b8fb10b71eb89b023cd41509299fc29c052b72eb28b035ea3333`, and can be found on explorer https://explorer.nervos.org/block/0x5f5bec6e0936b8fb10b71eb89b023cd41509299fc29c052b72eb28b035ea3333

The target set in Neuron@v0.106.0 is block hash `0x076ffa81f8c6f2e1f22a778a1aa5d48531cc33bfd9b302e0d73fb2ce6fa4de3b` (https://github.com/nervosnetwork/neuron/blob/develop/packages/neuron-wallet/.env#L120), its block number is 8826940, and can be found on explorer https://explorer.nervos.org/block/0x076ffa81f8c6f2e1f22a778a1aa5d48531cc33bfd9b302e0d73fb2ce6fa4de3b

So it requires 1313932 more blocks to reach the assumed valid target block. Once the assumed valid target block is recognized, CKB node and Neuron will start actual synchronization.

The early stage(looking for assumed valid target block) is introduced to boost synchronization. Once the assumed valid target is found, CKB node will skip verification of blocks before the assumed valid target block and download data directly. Verification does take time.

Also from the log we can see

```
2023-01-15 14:04:26.608 +00:00 BlockDownload INFO ckb_sync::synchronizer  best known header number: 7493008, hash: Byte32(0xc95b021091462f1d40ed9f0b49507d68c89fadb05ecabd641b189264d6480382), can't find assume valid target temporarily, hash: Byte32(0x076ffa81f8c6f2e1f22a778a1aa5d48531cc33bfd9b302e0d73fb2ce6fa4de3b) please wait


2023-01-15 14:11:57.060 +00:00 BlockDownload INFO ckb_sync::synchronizer  best known header number: 7503008, hash: Byte32(0x50a886a36ba434d7bf624633de435213b1d4a1c9df8b2d107a9393e584392e00), can't find assume valid target temporarily, hash: Byte32(0x076ffa81f8c6f2e1f22a778a1aa5d48531cc33bfd9b302e0d73fb2ce6fa4de3b) please wait


2023-01-15 14:18:22.587 +00:00 BlockDownload INFO ckb_sync::synchronizer  best known header number: 7513008, hash: Byte32(0x5f5bec6e0936b8fb10b71eb89b023cd41509299fc29c052b72eb28b035ea3333), can't find assume valid target temporarily, hash: Byte32(0x076ffa81f8c6f2e1f22a778a1aa5d48531cc33bfd9b302e0d73fb2ce6fa4de3b) please wait
```

It keeps checking the assumed valid target every 10000 blocks(about 7 mins), so please be patient and wait for it reaches block number 8826940. The remaining 1313932 blocks take about `1313932 / 10000 * 7` mins, namely 15 hours.

**Comment by Keith-CY** [comment]
> > Hello, following the new update (0.106.0) the migration failed. So I deleted all the .config/Neuron directory to start again on a healthy basis. Despite this, the synchronization takes a long time, after 4 days, it is about 30%. I have a very good throughput, and I had no problem on previous versions. I am running Manjaro Linux (Arch Base) with a 6.1.1 kernel. Thx
> > [neuron_debug_1673792332898.zip](https://github.com/nervosnetwork/neuron/files/10420404/neuron_debug_1673792332898.zip)
> 
> Hi @S0rci3r
> 
> From the `bundled-ckb.log` we can see
> 
> ```
> 2023-01-15 14:18:22.587 +00:00 BlockDownload INFO ckb_sync::synchronizer  best known header number: 7513008, hash: Byte32(0x5f5bec6e0936b8fb10b71eb89b023cd41509299fc29c052b72eb28b035ea3333), can't find assume valid target temporarily, hash: Byte32(0x076ffa81f8c6f2e1f22a778a1aa5d48531cc33bfd9b302e0d73fb2ce6fa4de3b) please wait
> 2023-01-15 14:18:26.489 +00:00 GlobalRt-3 INFO ckb_sync::synchronizer::get_headers_process  Ignoring getheaders from peer=SessionId(1) because node is in initial block download
> 2023-01-15 14:18:27.182 +00:00 GlobalRt-4 INFO ckb_sync::synchronizer::get_headers_process  Ignoring getheaders from peer=SessionId(2) because node is in initial block download
> 2023-01-15 14:18:27.242 +00:00 GlobalRt-2 INFO ckb_sync::synchronizer::get_headers_process  Ignoring getheaders from peer=SessionId(3) because node is in initial block download
> 2023-01-15 14:18:27.360 +00:00 GlobalRt-0 INFO ckb_sync::synchronizer::get_headers_process  Ignoring getheaders from peer=SessionId(8) because node is in initial block download
> ```
> 
> It means the built-in CKB node is still at the early stage of synchronization, which is looking for an assumed valid target block.
> 
> The log said it reached block 7513008, block hash is `0x5f5bec6e0936b8fb10b71eb89b023cd41509299fc29c052b72eb28b035ea3333`, and can be found on explorer [explorer.nervos.org/block/0x5f5bec6e0936b8fb10b71eb89b023cd41509299fc29c052b72eb28b035ea3333](https://explorer.nervos.org/block/0x5f5bec6e0936b8fb10b71eb89b023cd41509299fc29c052b72eb28b035ea3333)
> 
> The target set in Neuron@v0.106.0 is block hash `0x076ffa81f8c6f2e1f22a778a1aa5d48531cc33bfd9b302e0d73fb2ce6fa4de3b` ([`develop`/packages/neuron-wallet/.env#L120](https://github.com/nervosnetwork/neuron/blob/develop/packages/neuron-wallet/.env#L120)), its block number is 8826940, and can be found on explorer [explorer.nervos.org/block/0x076ffa81f8c6f2e1f22a778a1aa5d48531cc33bfd9b302e0d73fb2ce6fa4de3b](https://explorer.nervos.org/block/0x076ffa81f8c6f2e1f22a778a1aa5d48531cc33bfd9b302e0d73fb2ce6fa4de3b)
> 
> So it requires 1313932 more blocks to reach the assumed valid target block. Once the assumed valid target block is recognized, CKB node and Neuron will start actual synchronization.
> 
> The early stage(looking for assumed valid target block) is introduced to boost synchronization. Once the assumed valid target is found, CKB node will skip verification of blocks before the assumed valid target block and download data directly. Verification does take time.
> 
> Also from the log we can see
> 
> ```
> 2023-01-15 14:04:26.608 +00:00 BlockDownload INFO ckb_sync::synchronizer  best known header number: 7493008, hash: Byte32(0xc95b021091462f1d40ed9f0b49507d68c89fadb05ecabd641b189264d6480382), can't find assume valid target temporarily, hash: Byte32(0x076ffa81f8c6f2e1f22a778a1aa5d48531cc33bfd9b302e0d73fb2ce6fa4de3b) please wait
> 
> 
> 2023-01-15 14:11:57.060 +00:00 BlockDownload INFO ckb_sync::synchronizer  best known header number: 7503008, hash: Byte32(0x50a886a36ba434d7bf624633de435213b1d4a1c9df8b2d107a9393e584392e00), can't find assume valid target temporarily, hash: Byte32(0x076ffa81f8c6f2e1f22a778a1aa5d48531cc33bfd9b302e0d73fb2ce6fa4de3b) please wait
> 
> 
> 2023-01-15 14:18:22.587 +00:00 BlockDownload INFO ckb_sync::synchronizer  best known header number: 7513008, hash: Byte32(0x5f5bec6e0936b8fb10b71eb89b023cd41509299fc29c052b72eb28b035ea3333), can't find assume valid target temporarily, hash: Byte32(0x076ffa81f8c6f2e1f22a778a1aa5d48531cc33bfd9b302e0d73fb2ce6fa4de3b) please wait
> ```
> 
> It keeps checking the assumed valid target every 10000 blocks(about 7 mins), so please be patient and wait for it reaches block number 8826940. The remaining 1313932 blocks take about `1313932 / 10000 * 7` mins, namely 15 hours.

The `synced block number` won't grow until the early stage is finished because at the early stage, no blocks are downloaded. It's just checking if the assumed valid target block is accessible.

**Comment by virtueorvice** [comment]
I am having the same issue.

It was better if you had warned us about backing up data before going through the migration. 

This is getting ridiculous. We have to go through a lot of data painful synchronization again just because you guys cannot make a stable/working version of Neuron wallet.

**Comment by Keith-CY** [comment]
> I am having the same issue.
> 
> It was better if you had warned us about backing up data before going through the migration.
> 
> This is getting ridiculous. We have to go through a lot of painful data synchronization again just because you guys cannot make a stable/working version of Neuron wallet.

Hi @virtueorvice

The point is absolutely correct that we should make the warning conspicuous and ahead of the action instead of simply asking users whether to migrate or not.

During the development of Neuron@v0.106.0, our PM is temporarily out, so these decisions are made from we developers' perspective, which makes the user experience terrible for normal users. I'm so sorry for that. Now the PM is back, and we'll try to correct these weird behaviors.

**Comment by virtueorvice** [comment]
Since this morning I have updated to version 0.106.0 but I am stuck on "migrating..." and nothing seems to work to start the sync.

**Comment by NonSubscribed** [comment]
@virtueorvice ,

My guess is that the same thing that happened to me it's happening to you. Migration probably stopped/failed at some point and now Neuron is in a loop where its waiting for migration to end before connecting to mainnet to sync. I followed @Keith-CY 's suggestion and went to Tools=>Clear all synchronized data, restarted Neuron and now it's syncing...currently at 70%. Good luck,

**Comment by virtueorvice** [comment]
I don't have enough data and memory to resync all over again. I will try to used CKBULL to restore my wallets.

**Comment by yanguoyu** [comment]
> I don't have enough data and memory to resync all over again. I will try to use CKBULL to restore my wallets.

From your uploaded image the migrating process runs failed. You can check if the LOCK file exists, if exist, delete it.
Close your `Neuron` and check there is no `ckb` process and restart `Neuron` to migrate again.
If it's still run failed, maybe you need to click `OK` to delete old data and resync from the beginning.
