### ISSUE TITLE
我的钱包更新到0.106后，数据迁移了好几天，一直是正在数据迁移，正在链接节点，到底怎么了？？？

### ISSUE THREAD

**Issue by wengby88** [nervosnetwork/neuron#2571]

**Comment by Keith-CY** [comment]
有可能是遇到了数据迁移失败, 在发布前我们也测试出过同样的问题, 尚未找到合适的解决方案. 由于 0.106.0 版本包含必要的更新, 我们依旧发布了 Neuron@v0.106.0

可以通过下面流程判断是否遇到了数据迁移失败
1. 通过 `菜单 => 帮助 => 导出 debug 信息` 导出 Neuron 的日志, 是个压缩包, 里面包含四个日志文件
2. 查看 `main.log` 日志, 如果里面包含例如
```
[2023-01-11 23:10:29.214] [info] CKB migrate:    starting...
[2023-01-11 23:10:29.568] [info] CKB:    process closed
```
即数据迁移开始后, 立即结束, 是遇到了迁移失败
3. 迁移失败后, 由于节点数据损坏, 需要重新同步节点
4. 可以通过 `菜单 => 工具 => 清除已同步数据` 来删除节点数据并重新开始同步, 因为是重新同步, 时间会花费比较久.

如果尚未解决, 请再次导出 Neuron 日志并附在此 issue, 我们可以通过日志判断 Neuron 所遇到的问题
