### ISSUE TITLE
Transaction sign issue on Ledger Nano X

### ISSUE THREAD

**Issue by 191855** [nervosnetwork/neuron#2583]
**Describe the bug** (Please enter details, the more detail the better)
Ledger Nano x is connected to the wallet but when I try to initiate a transaction, It is just stuck at "Connected, waiting for confirmation on device" and I see no pop-up on my ledger. And I see below error from debug logs,

[2023-02-04 14:01:12.836] [warn] API Controller:	channel handling error: Error: cannot open device with path \\?\hid#vid_2c97&pid_0004&mi_00#a&277ff074&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030} Error: cannot open device with path \\?\hid#vid_2c97&pid_0004&mi_00#a&277ff074&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}
    at HardwareController.connectDevice (C:\Users\Sree\AppData\Local\Programs\Neuron\resources\app.asar\dist\controllers\hardware.js:17:19)
    at async C:\Users\Sree\AppData\Local\Programs\Neuron\resources\app.asar\dist\controllers\api.js:442:17
    at async C:\Users\Sree\AppData\Local\Programs\Neuron\resources\app.asar\dist\controllers\api.js:517:33
    at async node:electron/js2c/browser_init:197:563
[2023-02-04 14:01:14.848] [info] Find devices:	 [ [ null ] ]
[2023-02-04 14:01:48.147] [info] Find devices:	 [
  [
    {
      isBluetooth: false,
      descriptor: '\\\\?\\hid#vid_2c97&pid_0004&mi_00#a&277ff074&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}',
      vendorId: 11415,
      manufacturer: 'Ledger',
      product: 'Nano X',
      addressIndex: 0,
      addressType: 0
    }
  ]
]
[2023-02-04 14:01:48.149] [info] Connect device:	 {
  isBluetooth: false,
  descriptor: '\\\\?\\hid#vid_2c97&pid_0004&mi_00#a&277ff074&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}',
  vendorId: 11415,
  manufacturer: 'Ledger',
  product: 'Nano X',
  addressIndex: 0,
  addressType: 0
}
[2023-02-04 14:01:49.667] [info] Connect device:	 {
  isBluetooth: false,
  descriptor: '\\\\?\\hid#vid_2c97&pid_0004&mi_00#a&277ff074&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}',
  vendorId: 11415,
  manufacturer: 'Ledger',
  product: 'Nano X',
  addressIndex: 0,
  addressType: 0
}

**Debug info** (Please upload the debug info from `Help` - `Export Debug Information)

**Screenshots** (If applicable, add screenshots to help explain your problem.)
This is where it stuck and does nothing.

![image](https://user-images.githubusercontent.com/124463425/216785734-09e30ed3-772d-4e80-bd42-960db3554bf9.png)

**Comment by Keith-CY** [comment]
Hi @191855 

Is the version of Ledger CKB App v0.5.5?

We've found an **Inconsistent address** issue((https://github.com/Magickbase/neuron-public-issues/issues/98#issuecomment-1412472909)) on connecting to **Ledger X & Ledger CKB App v0.5.5**. And during the debugging, we found **Ledger Nano X & Ledger CKB App v0.5.5** hung on signing a message.

Please degrade to v0.5.0, which works well with Neuron.

**Comment by 191855** [comment]
> Hi @191855
> 
> Is the version of Ledger CKB App v0.5.5?
> 
> We've found an **Inconsistent address** issue(([Magickbase/neuron-public-issues#98 (comment)](https://github.com/Magickbase/neuron-public-issues/issues/98#issuecomment-1412472909))) on connecting to **Ledger X & Ledger CKB App v0.5.5**. And during the debugging, we found **Ledger Nano X & Ledger CKB App v0.5.5** hung on signing a message.
> 
> Please degrade to v0.5.0, which works well with Neuron.

Yes on version v0.5.5 on my ledger. How do I degrade to v0.5.0?

**Comment by Keith-CY** [comment]
> > Hi @191855
> > Is the version of Ledger CKB App v0.5.5?
> > We've found an **Inconsistent address** issue(([Magickbase/neuron-public-issues#98 (comment)](https://github.com/Magickbase/neuron-public-issues/issues/98#issuecomment-1412472909))) on connecting to **Ledger X & Ledger CKB App v0.5.5**. And during the debugging, we found **Ledger Nano X & Ledger CKB App v0.5.5** hung on signing a message.
> > Please degrade to v0.5.0, which works well with Neuron.
> 
> Yes on version v0.5.5 on my ledger. How do I degrade to v0.5.0?

Our tester was trying to degrade it, too. I'll add the solution here if he succeeds. But it's the weekend there, so the reply would be 2 days later.

Or you can open a ticket in **Ledger Support**(https://support.ledger.com/hc/en-us/categories/4404369571601-Support?support=true), they should be more professional about it.

**Comment by Keith-CY** [comment]
Here's an article about downgrading, hope it helps

https://support.ledger.com/hc/en-us/articles/7446430773149-Downgrading-to-an-older-version-of-Ledger-Live?support=true

**Comment by 191855** [comment]
> > > Hi @191855
> > > Is the version of Ledger CKB App v0.5.5?
> > > We've found an **Inconsistent address** issue(([Magickbase/neuron-public-issues#98 (comment)](https://github.com/Magickbase/neuron-public-issues/issues/98#issuecomment-1412472909))) on connecting to **Ledger X & Ledger CKB App v0.5.5**. And during the debugging, we found **Ledger Nano X & Ledger CKB App v0.5.5** hung on signing a message.
> > > Please degrade to v0.5.0, which works well with Neuron.
> > 
> > 
> > Yes on version v0.5.5 on my ledger. How do I degrade to v0.5.0?
> 
> Our tester was trying to degrade it, too. I'll add the solution here if he succeeds. But it's the weekend there, so the reply would be 2 days later.
> 
> Or you can open a ticket in **Ledger Support**(https://support.ledger.com/hc/en-us/categories/4404369571601-Support?support=true), they should be more professional about it.



> Here's an article about downgrading, hope it helps
> 
> https://support.ledger.com/hc/en-us/articles/7446430773149-Downgrading-to-an-older-version-of-Ledger-Live?support=true

Thanks for the link. Do you think downgrading the neuron app to a particular version would help in any way?

**Comment by 191855** [comment]
> 

And also link you shared is related to Ledger live app. I'm not sure if downgrading the ledger live app itself downgrades CKB app to v0.5.0. Are you sure?

**Comment by Keith-CY** [comment]
> > > > Hi @191855
> > > > Is the version of Ledger CKB App v0.5.5?
> > > > We've found an **Inconsistent address** issue(([Magickbase/neuron-public-issues#98 (comment)](https://github.com/Magickbase/neuron-public-issues/issues/98#issuecomment-1412472909))) on connecting to **Ledger X & Ledger CKB App v0.5.5**. And during the debugging, we found **Ledger Nano X & Ledger CKB App v0.5.5** hung on signing a message.
> > > > Please degrade to v0.5.0, which works well with Neuron.
> > > 
> > > 
> > > Yes on version v0.5.5 on my ledger. How do I degrade to v0.5.0?
> > 
> > 
> > Our tester was trying to degrade it, too. I'll add the solution here if he succeeds. But it's the weekend there, so the reply would be 2 days later.
> > Or you can open a ticket in **Ledger Support**([support.ledger.com/hc/en-us/categories/4404369571601-Support?support=true](https://support.ledger.com/hc/en-us/categories/4404369571601-Support?support=true)), they should be more professional about it.
> 
> > Here's an article about downgrading, hope it helps
> > [support.ledger.com/hc/en-us/articles/7446430773149-Downgrading-to-an-older-version-of-Ledger-Live?support=true](https://support.ledger.com/hc/en-us/articles/7446430773149-Downgrading-to-an-older-version-of-Ledger-Live?support=true)
> 
> Thanks for the link. Do you think downgrading the neuron app to a particular version would help in any way?

To debug the **inconsistent address** issue mentioned above, we used **Ledger Nano X & Ledger CKB App v0.5.0** to connect Neuron, it succeeded; then we upgraded it to Ledger App v0.5.5 and go through the same steps, it failed.

Since our tester hasn't downgraded it to v0.5.0 for double-checking, I cannot say it will be 100% successful. I'll attach the result of downgrading here once he tests it.

**Comment by Keith-CY** [comment]
> > 
> 
> And also link you shared is related to Ledger live app. I'm not sure if downgrading the ledger live app itself downgrades CKB app to v0.5.0. Are you sure?

I cannot say that, but I'll share the solution of downgrading here once our tester succeeds.

**Comment by 191855** [comment]
Any idea from what version CKB started supporting ledger? I tried downgrading to multiple versions and had no luck with CKB app. Still shows v0.5.5 available to install on Ledger live app. Now I downgraded all the way to "Ledger Live 2.30.0" and I see CKB doesn't support this level.

**Comment by 191855** [comment]
FYI - Downgrading the ledger live to any older version did not help. Pretty much tried 5 - 6 older versions.

**Comment by 191855** [comment]
Curious to know if there is a workaround for this. I just need to transfer my ckb ASAP.  Are there any apps that support the ledger ckb hardware wallet?

**Comment by Keith-CY** [comment]
> Curious to know if there is a workaround for this. I just need to transfer my ckb ASAP. Are there any apps that support the ledger ckb hardware wallet?

I know that **ckb-cli**(https://github.com/nervosnetwork/ckb-cli) is supported by ledger, so you can export the transaction(<kbd>Export tx</kbd> in the screenshot) to disk and sign it with **ckb-cli & ledger**, @TheWaWaR is the developer of **ckb-cli** and could help

Ref:
https://github.com/obsidiansystems/ckb-plugin-ledger

**Comment by Keith-CY** [comment]
I have PM him to this issue

**Comment by 191855** [comment]
Did you hear back anything yet? I guess [ckb-plugin-ledger](https://github.com/obsidiansystems/ckb-plugin-ledger) is not up to date or something. "cargo build" itself is failing.

**Comment by Cedar67** [comment]
> Did you hear back anything yet? I guess [ckb-plugin-ledger](https://github.com/obsidiansystems/ckb-plugin-ledger) is not up to date or something. "cargo build" itself is failing.

@191855  As for the demotion solution of Ledger CKB App, I have submitted the order to Ledger. We know they're dealing with it, but we haven't received a solution yet. We will get back to you as soon as we receive the feedback.

**Comment by Keith-CY** [comment]
> Did you hear back anything yet? I guess [ckb-plugin-ledger](https://github.com/obsidiansystems/ckb-plugin-ledger) is not up to date or something. "cargo build" itself is failing.

I've reported it to the core team, waiting for the response too.

**Comment by Keith-CY** [comment]
> Did you hear back anything yet? I guess [ckb-plugin-ledger](https://github.com/obsidiansystems/ckb-plugin-ledger) is not up to date or something. "cargo build" itself is failing.

It's confirmed that `ckb-plugin-ledger` is out-of-date and will be updated by the core team.

Ref: https://github.com/nervosnetwork/ckb-cli/issues/542

**Comment by Keith-CY** [comment]
> Any idea from what version CKB started supporting ledger? I tried downgrading to multiple versions and had no luck with CKB app. Still shows v0.5.5 available to install on Ledger live app. Now I downgraded all the way to "Ledger Live 2.30.0" and I see CKB doesn't support this level.

Hi @191855
We got how to install Ledger CKB App@v0.5.0 manually, but we didn't run it successfully. Still be connecting to the ledger team, and any new update will be synced here.

CKB App@v0.5.0: https://github.com/LedgerHQ/app-nervos/tree/v0.5.0

**Comment by 191855** [comment]
Is it safe to try manually installing the app and doing a transaction?

**Comment by Keith-CY** [comment]
> Is it safe to try manually installing the app and doing a transaction?

It should be safe because it's the source code released by ledger, and they provided a guide on how to install it manually. Besides, our partner team had installed it manually to degrade ledger ckb app.

Before this, I would suggest setting 2 configurations that our partner team found useful to re-enable their ledger with app@v0.5.5. Maybe not be your case, but these 2 configurations are required to sign a message/transaction.

1. set `configuration => allow sign hash` to `on`
2. set `address for` to `mainnet`

---
We're still waiting for a response from ledger team about this case, any update will be synced here

**Comment by 191855** [comment]
Am I supposed to use ledger nano S to try this out or I can use nano X too? I'm facing the below error while trying to install the app to my ledger X. Ahy idea, why?


./install.sh app                                                                                                                                                                   ─╯

Installing Nervos version 0.5.0

+ appFlag=0x00
+ '[' nano_x == nano_x ']'
+ appFlag=0x240
+ python -m ledgerblue.loadApp --appFlags 0x240 --dataSize 256 --tlv --curve ed25519 --curve secp256k1 --curve prime256r1 --targetId 0x3304 --delete --path xxxxxx--fileName app/app.hex --appName Nervos --appVersion 0.5.0 --icon 010000000000000000fffffe11e038f81ffe8ffff7ff0f --targetVersion ''
Generated random root public key : b'keyyyyyyyyyyyyy'
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/username/ckb-cli/ledger/lib/python3.11/site-packages/ledgerblue/loadApp.py", line 132, in <module>
    raise Exception("Unknown curve " + curve)
Exception: Unknown curve prime256r1

**Comment by 191855** [comment]
Any update on this, please? It's so annoying. I can't even withdraw CKB no matter what I try.

**Comment by Keith-CY** [comment]
> Any update on this, please? It's so annoying. I can't even withdraw CKB no matter what I try.

Hi @191855 
Sorry that we haven't figured it out, and we are also blocked by other issues with Ledger + app@v0.5.5(listed in https://github.com/Magickbase/neuron-public-issues/issues/103)

This one was reported to the ledger team on 02/09 but no feedback yet.

**Comment by 191855** [comment]
So, the fix needs to come from the ledger team itself but not from neuron app devs?

**Comment by 191855** [comment]
> > Any update on this, please? It's so annoying. I can't even withdraw CKB no matter what I try.
> 
> Hi @191855 Sorry that we haven't figured it out, and we are also blocked by other issues with Ledger + app@v0.5.5(listed in [Magickbase/neuron-public-issues#103](https://github.com/Magickbase/neuron-public-issues/issues/103))
> 
> This one was reported to the ledger team on 02/09 but no feedback yet.

So, the fix needs to come from the ledger team itself but not from neuron app devs?

**Comment by Keith-CY** [comment]
> > > Any update on this, please? It's so annoying. I can't even withdraw CKB no matter what I try.
> > 
> > 
> > Hi @191855 Sorry that we haven't figured it out, and we are also blocked by other issues with Ledger + app@v0.5.5(listed in [Magickbase/neuron-public-issues#103](https://github.com/Magickbase/neuron-public-issues/issues/103))
> > This one was reported to the ledger team on 02/09 but no feedback yet.
> 
> So, the fix needs to come from the ledger team itself but not from neuron app devs?

I think yes, we're also seeking support from ledger team. Neuron@v0.106.0 works well with `Ledger Nano S`, `Ledger Nano S Plus`, and `Ledger Nano X & Ledger CKB App@v0.5.5`, so the logic inside Neuron should work.

Besides, the error message in this case shows

```
cannot open device with path \?\hid#vid_2c97&pid_0004&mi_00#a&277ff074&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030} Error: cannot open device with path \?\hid#vid_2c97&pid_0004&mi_00#a&277ff074&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}
...
descriptor: '\\?\hid#vid_2c97&pid_0004&mi_00#a&277ff074&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}',
```

The question mark in the path is suspicious, but it's from Ledger hardware. This is the question we're consulting with ledger team. Because we've tested our devices and found no one has a `descriptor/path` in a similar format.

**Device 1**
![image](https://user-images.githubusercontent.com/7271329/219880000-a1753989-e0c5-4e80-bfd3-67cb9c3d1670.png)

**Device 2**
![image](https://user-images.githubusercontent.com/7271329/219880011-9f962637-1de6-40d8-8cb4-fa4059b69fef.png)

**Comment by 191855** [comment]
> Am I supposed to use ledger nano S to try this out or I can use nano X too? I'm facing the below error while trying to install the app to my ledger X. Any idea, why?
> 
> ./install.sh app ─╯
> 
> Installing Nervos version 0.5.0
> 
> * appFlag=0x00
> * '[' nano_x == nano_x ']'
> * appFlag=0x240
> * python -m ledgerblue.loadApp --appFlags 0x240 --dataSize 256 --tlv --curve ed25519 --curve secp256k1 --curve prime256r1 --targetId 0x3304 --delete --path xxxxxx--fileName app/app.hex --appName Nervos --appVersion 0.5.0 --icon 010000000000000000fffffe11e038f81ffe8ffff7ff0f --targetVersion ''
>   Generated random root public key : b'keyyyyyyyyyyyyy'
>   Traceback (most recent call last):
>   File "", line 198, in _run_module_as_main
>   File "", line 88, in _run_code
>   File "/Users/username/ckb-cli/ledger/lib/python3.11/site-packages/ledgerblue/loadApp.py", line 132, in 
>   raise Exception("Unknown curve " + curve)
>   Exception: Unknown curve prime256r1

Any idea why I'm facing this error? This is when I'm trying to install  Nervos version 0.5.0.

**Comment by Keith-CY** [comment]
> > Am I supposed to use ledger nano S to try this out or I can use nano X too? I'm facing the below error while trying to install the app to my ledger X. Any idea, why?
> > ./install.sh app ─╯
> > Installing Nervos version 0.5.0
> > 
> > * appFlag=0x00
> > * '[' nano_x == nano_x ']'
> > * appFlag=0x240
> > * python -m ledgerblue.loadApp --appFlags 0x240 --dataSize 256 --tlv --curve ed25519 --curve secp256k1 --curve prime256r1 --targetId 0x3304 --delete --path xxxxxx--fileName app/app.hex --appName Nervos --appVersion 0.5.0 --icon 010000000000000000fffffe11e038f81ffe8ffff7ff0f --targetVersion ''
> >   Generated random root public key : b'keyyyyyyyyyyyyy'
> >   Traceback (most recent call last):
> >   File "", line 198, in _run_module_as_main
> >   File "", line 88, in _run_code
> >   File "/Users/username/ckb-cli/ledger/lib/python3.11/site-packages/ledgerblue/loadApp.py", line 132, in
> >   raise Exception("Unknown curve " + curve)
> >   Exception: Unknown curve prime256r1
> 
> Any idea why I'm facing this error? This is when I'm trying to install Nervos version 0.5.0.

After reading the source code, I've found that `prime256r1` was renamed to `secp256k1` 1.5 years ago, which made the installation broken.

The exception was thrown at https://github.com/LedgerHQ/blue-loader-python/blob/master/ledgerblue/loadApp.py#L132, it blamed that `prime267r1` was not a recognizable curve.

Ref: 
rename `prime256r1` to `secp256k1`: https://github.com/LedgerHQ/blue-loader-python/commit/6c39a89d0699ca5a799864447ddbadf40a49c95f

**Comment by 4jin** [comment]
> > Am I supposed to use ledger nano S to try this out or I can use nano X too? I'm facing the below error while trying to install the app to my ledger X. Any idea, why?
> > ./install.sh app ─╯
> > Installing Nervos version 0.5.0
> > 
> > * appFlag=0x00
> > * '[' nano_x == nano_x ']'
> > * appFlag=0x240
> > * python -m ledgerblue.loadApp --appFlags 0x240 --dataSize 256 --tlv --curve ed25519 --curve secp256k1 --curve prime256r1 --targetId 0x3304 --delete --path xxxxxx--fileName app/app.hex --appName Nervos --appVersion 0.5.0 --icon 010000000000000000fffffe11e038f81ffe8ffff7ff0f --targetVersion ''
> >   Generated random root public key : b'keyyyyyyyyyyyyy'
> >   Traceback (most recent call last):
> >   File "", line 198, in _run_module_as_main
> >   File "", line 88, in _run_code
> >   File "/Users/username/ckb-cli/ledger/lib/python3.11/site-packages/ledgerblue/loadApp.py", line 132, in
> >   raise Exception("Unknown curve " + curve)
> >   Exception: Unknown curve prime256r1
> 
> Any idea why I'm facing this error? This is when I'm trying to install Nervos version 0.5.0.

Did you finally solve it, I had the same problem

**Comment by Keith-CY** [comment]
> > > Am I supposed to use ledger nano S to try this out or I can use nano X too? I'm facing the below error while trying to install the app to my ledger X. Any idea, why?
> > > ./install.sh app ─╯
> > > Installing Nervos version 0.5.0
> > > 
> > > * appFlag=0x00
> > > * '[' nano_x == nano_x ']'
> > > * appFlag=0x240
> > > * python -m ledgerblue.loadApp --appFlags 0x240 --dataSize 256 --tlv --curve ed25519 --curve secp256k1 --curve prime256r1 --targetId 0x3304 --delete --path xxxxxx--fileName app/app.hex --appName Nervos --appVersion 0.5.0 --icon 010000000000000000fffffe11e038f81ffe8ffff7ff0f --targetVersion ''
> > >   Generated random root public key : b'keyyyyyyyyyyyyy'
> > >   Traceback (most recent call last):
> > >   File "", line 198, in _run_module_as_main
> > >   File "", line 88, in _run_code
> > >   File "/Users/username/ckb-cli/ledger/lib/python3.11/site-packages/ledgerblue/loadApp.py", line 132, in
> > >   raise Exception("Unknown curve " + curve)
> > >   Exception: Unknown curve prime256r1
> > 
> > 
> > Any idea why I'm facing this error? This is when I'm trying to install Nervos version 0.5.0.
> 
> Did you finally solve it, I had the same problem

This case was also reported to the ledger team, and we're waiting for their suggestion

**Comment by 191855** [comment]
> > > Am I supposed to use ledger nano S to try this out or I can use nano X too? I'm facing the below error while trying to install the app to my ledger X. Any idea, why?
> > > ./install.sh app ─╯
> > > Installing Nervos version 0.5.0
> > > 
> > > * appFlag=0x00
> > > * '[' nano_x == nano_x ']'
> > > * appFlag=0x240
> > > * python -m ledgerblue.loadApp --appFlags 0x240 --dataSize 256 --tlv --curve ed25519 --curve secp256k1 --curve prime256r1 --targetId 0x3304 --delete --path xxxxxx--fileName app/app.hex --appName Nervos --appVersion 0.5.0 --icon 010000000000000000fffffe11e038f81ffe8ffff7ff0f --targetVersion ''
> > >   Generated random root public key : b'keyyyyyyyyyyyyy'
> > >   Traceback (most recent call last):
> > >   File "", line 198, in _run_module_as_main
> > >   File "", line 88, in _run_code
> > >   File "/Users/username/ckb-cli/ledger/lib/python3.11/site-packages/ledgerblue/loadApp.py", line 132, in
> > >   raise Exception("Unknown curve " + curve)
> > >   Exception: Unknown curve prime256r1
> > 
> > 
> > Any idea why I'm facing this error? This is when I'm trying to install Nervos version 0.5.0.
> 
> Did you finally solve it, I had the same problem

No luck so far. I kinda give up and also I'm occupied to even think about it. This is so annoying as Ledger taking its own sweet time to address this issue. More than a month so far. I even sent out an email about it.

**Comment by 191855** [comment]
> 

Still no update on this issue? This is really sad.

**Comment by 191855** [comment]
Still no update on this issue? This is really sad. @Keith-CY

**Comment by Keith-CY** [comment]
> Still no update on this issue? This is really sad. @Keith-CY

The next version of ledger ckb app is ready to release, it’s been fully tested these days and I got this message yesterday. Maybe in the next several days.

**Comment by CountDooku415** [comment]
I have updated the ledger live app to 0.5.6 and no luck. Ledger live has also been updated and downgraded on both m1 and intel based Mac with no luck. Any update on this issue?

**Comment by Keith-CY** [comment]
> I have updated the ledger live app to 0.5.6 and no luck. Ledger live has also been updated and downgraded on both m1 and intel based Mac with no luck. Any update on this issue?

Please check if `configuration => allow sign hash` is `on`, it will be reset after upgrade

**Comment by CountDooku415** [comment]
It worked after closing, reopening, disconnecting, a bunch of times. And leaving it pending for minutes. It finally prompted the approve screen. Unfortunately, I was not able to add to Nervos DAO via ledger nano x and neuron. I had to transfer to CK Bull wallet.
