### ISSUE TITLE
neuron-ui storybook can't start success

### ISSUE THREAD

**Issue by cl510804194** [nervosnetwork/neuron#2584]
**Describe the bug** (Please enter details, the more detail the better)
after i into neuron-ui package, install all dependence and then execute `yarn storybook`,there are some error of webpack 

**Debug info** (Please upload the debug info from `Help` - `Export Debug Information`)
Node:v18.12.0
yarn: v1.22.10

**Screenshots** (If applicable, add screenshots to help explain your problem.)
![image](https://user-images.githubusercontent.com/42998038/216801565-9989716c-fdd1-442b-aa9c-8233a92db858.png)

**Comment by yanguoyu** [comment]
It has been fixed on the [new-ui-design branch](https://github.com/nervosnetwork/neuron/tree/new-ui-design) by https://github.com/nervosnetwork/neuron/pull/2506
