### ISSUE TITLE
Nervos DAO deposits seems stuck; dates, values, pin not changing / frozen

### ISSUE THREAD

**Issue by DKCasper** [nervosnetwork/neuron#2598]
### Detail of the issue

I have four deposits on the Nervos DAO, but they are not updating; by that I mean the date are 'stuck' and not moving toward the green part on the right side of the line. It is the same for all 4 of my depositis.

The block is now 100% synchronised.

Here are two screen shots taken af two different times and the values, date and location the pin on the line is exactly the same.

<img width="1343" alt="Screenshot 2023-03-02 at 20 03 25" src="https://user-images.githubusercontent.com/126886522/222738614-95d2aece-294f-4bb4-9378-b2a96a1370f7.png">

<img width="1343" alt="Screenshot 2023-03-02 at 19 17 42" src="https://user-images.githubusercontent.com/126886522/222738780-8a519393-452f-44cc-8a10-67651217c78b.png">

Can you please help me solve this issue? Thank you.

**Comment by yanguoyu** [comment]
@DKCasper Hi, actually the `Neuron` has not synced to 100%, the latest block number is more than 7,150,910. The pin was not moved because the synced block is the same in the two pictures.
As shown in the second picture, `Neuron` is finding the latest block and syncing it.

**Comment by DKCasper** [comment]
Thank you @yanguoyu .

I just checked again this morning and the the pin is still the same place and the block seem to be 100% synced. But at block 7,150,910.

<img width="1194" alt="Screenshot 2023-03-04 at 08 06 59" src="https://user-images.githubusercontent.com/126886522/222864479-fd81ae70-eabc-4a0b-a586-9bf81c5c9039.png">

So it seems that it stopped syncing at 7,150,910. I restarted Neuron several times and it continues to state that the block is 100% synced.

**Comment by yanguoyu** [comment]
> Thank you @yanguoyu .
> 
> I just checked again this morning and the the pin is still the same place and the block seem to be 100% synced. But at block 7,150,910.
> 
> <img alt="Screenshot 2023-03-04 at 08 06 59" width="1194" src="https://user-images.githubusercontent.com/126886522/222864479-fd81ae70-eabc-4a0b-a586-9bf81c5c9039.png">
> 
> So it seems that it stopped syncing at 7,150,910. I restarted Neuron several times and it continues to state that the block is 100% synced.

Can you upload the log for us to analyze it? You can export logs by clicking Help->Export debug information.

**Comment by DKCasper** [comment]
Please see attached debug information:
[neuron_debug_1677913041526.zip](https://github.com/nervosnetwork/neuron/files/10887678/neuron_debug_1677913041526.zip)

**Comment by yanguoyu** [comment]
@DKCasper Hi, I found that your `Neuron`'s version is 0.101.1, it's too older, maybe you need to download the [latest](https://github.com/nervosnetwork/neuron/releases/tag/v0.106.0) version to use it.
The latest `Neuron` version is 0.106.0, and the ckb version is 0.106.0, and from [this](https://github.com/nervosnetwork/ckb/releases/tag/v0.106.0) information, the 0.106.0 only compatible with that after 0.103.0. And most of the node has upgraded, so you need to update ckb version to sync data.
In the end, here is something you need to notice after updating to 0.106.0. https://github.com/nervosnetwork/neuron/issues/2557

<img width="593" alt="image" src="https://user-images.githubusercontent.com/12881040/222881859-e19330ce-3181-4d92-a435-c45aaa08d2e5.png">

**Comment by DKCasper** [comment]
Thank you. I will install the updated version. I get this error message when trying to update Neuron to the latest version:

Error: Code signature at URL file:///Users/caspertribler/Library/Caches/com.nervos.neuron.ShipIt/update.Te0aL9t/Neuron.app/ did not pass validation: code failed to satisfy specified code requirement(s)

I have instead downloaded the Neuron zip file for MacOS ready to install it myself, but if I do that will it install a completely new Neuron application and will my current profile automatically be transferred to the updated version?

**Comment by yanguoyu** [comment]
> if I do that will it install a completely new Neuron application and will my current profile automatically be transferred to the updated version?

Of cause, installing a new Neuron will not change old configs.

**Comment by DKCasper** [comment]
Dear GitHub community,

I manage to solve the above issue, but deleting the old Neuron Wallet and install the latest version. After installing in sync. the block (more than 100 mill. blocks) 100% and everything was fine.

I then closed down the app, as I needed to restart the laptop and I then started the Neuron wallet again to find out that the synced block is down to 0% and it has now been like that for a couple of hours:

<img width="1185" alt="Screenshot 2023-07-17 at 5 54 47 PM" src="https://github.com/nervosnetwork/neuron/assets/126886522/4e80611b-7acf-4b81-8a02-48160947c01d">

Is this normal that when you restart the Neuron Wallet that it will have to sync the complete block again and it takes hours where nothing is happening?

**Comment by yanguoyu** [comment]
> Dear GitHub community,
> 
> I managed to solve the above issue by deleting the old Neuron Wallet and install the latest version. After installing the new version it correctly started to sync. the block (more than 10 mill. blocks). All 100% were sync'ed and everything was fine.
> 
> I then closed down the Neuron app, as I needed to restart the laptop and I then started the Neuron app again to find out that the synced block is now down to 0% and it has now been like that for a couple of hours, and it seems to be stuck:
> 
> <img alt="Screenshot 2023-07-17 at 5 54 47 PM" width="1185" src="https://user-images.githubusercontent.com/126886522/254011849-4e80611b-7acf-4b81-8a02-48160947c01d.png">
> Is this normal when you restart the Neuron app that it will have to sync the complete block again from the beginning and it takes hours where nothing is happening? Or did something go wrong, and I have to delete the Neuron app again, install and see if it will start syncing the block all over again?

Could you export the debug information again so we can check why the synced block is down to 0? You can export logs by clicking Help->Export debug information.

On the other hand, I guess it seems as https://github.com/nervosnetwork/neuron/issues/2699, and maybe you can try with https://github.com/nervosnetwork/neuron/issues/2699#issuecomment-1578195810 to resolve it.

**Comment by yanguoyu** [comment]
> [neuron_debug_1689664581087.zip](https://github.com/nervosnetwork/neuron/files/12077348/neuron_debug_1689664581087.zip)
> 
> Thank you. Please see attached debug information. And I will look at the #2699 as well. Have a great day!

After reading the debug log, I'm so sure https://github.com/nervosnetwork/neuron/issues/2699#issuecomment-1578195810 can resolve it.

**Comment by DKCasper** [comment]
Dear yanguoyu,

Thank you. Yes, #2699, seems to have solved it and Neuron is up and running again.
