### ISSUE TITLE
Block stopped syncing-->Clear Cache-->Balance is 0

### ISSUE THREAD

**Issue by ishijan** [nervosnetwork/neuron#2601]
### Detail of the issue

I'm using Neuron V0.106. Block stopped syncing. I clicked on Clear Cache from data setting menu. Now my balance is gone as well as history transactions. I have 2 wallets and both balances are now 0. Please help me out. Thank you

**Comment by Keith-CY** [comment]
Hi @ishijan 
Could you upload the log of Neuron, which can be exported by `Menu => Help => Export Debug Information`, then we can figure out what happened under the hood.

**Comment by ishijan** [comment]
Here is debug information
[neuron_debug_1678080701722.zip](https://github.com/nervosnetwork/neuron/files/10894705/neuron_debug_1678080701722.zip)

**Comment by yanguoyu** [comment]
@ishijan Hi, from your log, the ckb node is restarting always, this happened because the ckb node stop signal was captured by Neuron but the ckb node start signal was missing. So neuron stopped itself because it thought ckb node stopped. It's a recently found technical issue but not mentioned in document, so the solution was missing in Neuron. The exception will be fixed by https://github.com/nervosnetwork/neuron/pull/2574 and delivered in the next version.

Now you can resolve it by these steps currently:
1. stop Neuron
2. check if ckb program is running in the task manager, close it if yes; if ckb is closed, it may not cause by the above problem.
3. start Neuron again.

**Comment by ishijan** [comment]
Stop Neuron by closing the program? After I closed the program, ckb program is not running in the tast manager. I reopened the ckb program, neuron appears in the task manager. But still not syncing. What do I do next?

**Comment by yanguoyu** [comment]
> Stop Neuron by closing the program? After I closed the program, ckb program is not running in the tast manager. I reopened the ckb program, neuron appears in the task manager. But still not syncing. What do I do next?

Do you start the ckb program by yourself but not by Neuron? If you start ckb program by yourself, you may need to add `--indexer` parameter when starting the `ckb`.
If you only start Neuron and wait for a while, it also does not start syncing, you can upload logs again. Maybe there exist others problems.

**Comment by ishijan** [comment]
Sorry I meant "Neuron program". 
After I closed the neuron program, neuron program is not running in the task manager. I reopened the neuron program, neuron appears in the task manager. But still not syncing. Here is the debug information.  
[neuron_debug_1678085252634.zip](https://github.com/nervosnetwork/neuron/files/10895134/neuron_debug_1678085252634.zip)

**Comment by yanguoyu** [comment]
I'm sorry for my inaccurate description, Neuron includes `neuron` program, and it starts a ckb node to sync data, the program's name is ckb. After you close the neuron, you need to ensure the ckb program is closed.
This is the Neuron program:

<img width="631" alt="image" src="https://user-images.githubusercontent.com/12881040/223040246-3d7d86ae-99d7-4dce-8672-c69501b8bec8.png">


And here is the ckb program:

<img width="633" alt="image" src="https://user-images.githubusercontent.com/12881040/223040032-e8b6a007-0b5c-4a55-a537-7834f81a1398.png">

**Comment by ishijan** [comment]
When Neuron program is open, the ckb program kept appearing in the task manager for a few second and then disappeared. The ckb program will appear in the task manager and disappear again after a few second. It kept going on like this. 
![image](https://user-images.githubusercontent.com/127076197/223041686-d96f95f5-cf45-4680-b79c-0d417ebdd3e0.png)
![image](https://user-images.githubusercontent.com/127076197/223041724-d29c37bf-7cea-4111-b95a-055c5a0d93f9.png)

**Comment by yanguoyu** [comment]
@ishijan Can you try to start ckb program alone? Here is the step:

### Run a mainnet node
1. visit https://github.com/nervosnetwork/ckb/releases/tag/v0.106.0, download `[ckb_v0.106.0_x86_64-pc-windows-msvc.zip](https://github.com/nervosnetwork/ckb/releases/download/v0.106.0/ckb_v0.106.0_x86_64-pc-windows-msvc.zip)` and unzip it
2. open a terminal and go to the unzipped ckb node directory
3. execute `ckb run -C C:\Users\JJ\AppData\Roaming\Neuron\chains\mainnet --assume-valid-target 0x4e53fcf61c1250249bc201101bcc8c904b7fcd455f8db395bdb4bbe02502a499 --indexer` to start synchronization, `--assume-valid-target 0x4e53fcf61c1250249bc201101bcc8c904b7fcd455f8db395bdb4bbe02502a499` is used to boost
Ref: [Run a CKB Mainnet Node](https://docs.nervos.org/docs/basics/guides/mainnet/)

After the mainnet node start success, you can try to start Neuron again.

If this works, you can close the ckb and neuron program and try to restart the Neuron again.

**Comment by ishijan** [comment]
I downloaded ckb_v0.106.0_x86_64-pc-windows-msvc.zip and already unzipped it. I don't understand step 3. Please clarify.

**Comment by yanguoyu** [comment]
> I downloaded ckb_v0.106.0_x86_64-pc-windows-msvc.zip and already unzipped it. I don't understand step 3. Please clarify.

Step 3 is used to run a ckb local node. Here is my run success example.
`./ckb` means run ckb in the current direction. `-C 'your mainnet data path'` means the ckb data is in the path. `--indexer` means start ckb program with ckb indexer. `--assume-valid-target 0x4e53fcf61c1250249bc201101bcc8c904b7fcd455f8db395bdb4bbe02502a499` is used to boost.
And I have updated something in the comment. https://github.com/nervosnetwork/neuron/issues/2601#issuecomment-1455588840

<img width="1293" alt="image" src="https://user-images.githubusercontent.com/12881040/223059967-d292e94a-c6ef-4aa7-9879-9243f49740b0.png">

**Comment by ishijan** [comment]
Step 2 - Here you want to open command prompt or open ckb-cli.exe from the unzipped folder?
Step 3- So I just opened open command prompt and type 
./ckb run -C 'C:\Users\JJ\AppData\Roaming\Neuron\chains\mainnet' --indexer --assume-valid-target 0x4e53fcf61c1250249bc201101bcc8c904b7fcd455f8db395bdb4bbe02502a499 
It didn't work. Which part I did wrong?

**Comment by yanguoyu** [comment]
> Step 2 - Here you want to open command prompt or open ckb-cli.exe from the unzipped folder? Step 3- So I just opened open command prompt and type ./ckb run -C 'C:\Users\JJ\AppData\Roaming\Neuron\chains\mainnet' --indexer --assume-valid-target 0x4e53fcf61c1250249bc201101bcc8c904b7fcd455f8db395bdb4bbe02502a499 It didn't work. Which part I did wrong?

Can you show me what happened?
Step 2 is two combinations by two operations. 
1. open a terminal
2. go to the unzipped folder in the opened terminal
So when typing ./ckb can find the ckb.exe binary file.

**Comment by ishijan** [comment]
What about changing to a new computer and install neuron? Will my unfinished sync wallet work on a new computer? What do I have to do?

**Comment by yanguoyu** [comment]
> What about changing to a new computer and install neuron? Will my unfinished sync wallet work on a new computer? What do I have to do?

If you use a hard wallet, you can easy to use a new computer by importing the hard wallet into the new computer.
Or else if you know your wallet's mnemonic, you can also import by mnemonic in the new computer.
Or else you should backup your wallet, and import by keystore in the new computer.

**Comment by yanguoyu** [comment]
> 

Wallet seed is a group of 12 or 24 words? If so, `wallet's mnemonic` means wallet seed.

**Comment by ishijan** [comment]
Hi there,

After I run ckb by following your instructions, this is what happened. Does this mean it is completed?
![image](https://user-images.githubusercontent.com/127076197/224641836-8e45f86f-2d5a-4d67-b636-2f9bd7551bf1.png)

I opened Neuron program without closing ckb. What to do next? 
![image](https://user-images.githubusercontent.com/127076197/224642263-f38b8c51-005d-41f5-a28a-e77479e3c9d7.png)

**Comment by yanguoyu** [comment]
> Hi there,
> 
> After I run ckb by following your instructions, this is what happened. Does this mean it is completed? ![image](https://user-images.githubusercontent.com/127076197/224641836-8e45f86f-2d5a-4d67-b636-2f9bd7551bf1.png)
> 
> I opened Neuron program without closing ckb. What to do next? ![image](https://user-images.githubusercontent.com/127076197/224642263-f38b8c51-005d-41f5-a28a-e77479e3c9d7.png)

It's strange why the ckb process has stopped. The ckb process should keep running then Neuron can keep in sync.

**Comment by ishijan** [comment]
So, are you saying the ckb process is not finished? What does it suppose to look like when the ckb process is finished? 
Please suggest the next step. Can I close ckb program and re-open the neuron program? Or do I keep both programs open?

How come block hasn't started syncing and what does "Syncing, ~- left" mean?
![image](https://user-images.githubusercontent.com/127076197/224662653-9d5622ed-77a7-44d5-83e0-dd10aec6a60e.png)

**Comment by yanguoyu** [comment]
> So, are you saying the ckb process is not finished? What does it suppose to look like when the ckb process is finished? Please suggest the next step. Can I close ckb program and re-open the neuron program? Or do I keep both programs open?
> 
> How come block hasn't started syncing and what does "Syncing, ~- left" mean? ![image](https://user-images.githubusercontent.com/127076197/224662653-9d5622ed-77a7-44d5-83e0-dd10aec6a60e.png)

You can close Neuron and ckb, and check all the ckb has closed. Then try to only open Neuron.

**Comment by ishijan** [comment]
So, I closed ckb and neuron, checked that all ckb has closed. Then, open only Neuron, the ckb is shown in task manager. Is this normal?
![image](https://user-images.githubusercontent.com/127076197/224723188-be11f588-96f1-48a2-8c0c-758207dcfc00.png)

**Comment by yanguoyu** [comment]
> So, I closed ckb and neuron, checked that all ckb has closed. Then, open only Neuron, the ckb is shown in task manager. Is this normal? ![image](https://user-images.githubusercontent.com/127076197/224723188-be11f588-96f1-48a2-8c0c-758207dcfc00.png) ![image](https://user-images.githubusercontent.com/127076197/224723742-d7603228-e353-4f94-bb30-c393ae64a21a.png)

Of cause, Neuron will start a ckb process for it to sync. And as your see, it keeps syncing.

**Comment by ishijan** [comment]
I was wondering does the block start from 0 every time I re-open Neuron program? If yes, it will take forever to finish syncing.


The first picture was before I closed the ckb and neuron. It shows the block was uploaded to 9,272,023 blocks
![image](https://user-images.githubusercontent.com/127076197/224879973-12622209-3266-4ed8-b393-092b793fd7c5.png)


The second picture is after I closed ckb and neuron program. However, when I re-open the neuron program, block starts to upload from 0/0 again. As you can see, I took this screenshot after I re-open Neuron for a while. The block which was previously uploaded to 9,272,023 blocks, didn't start upload from where it finished. 
![image](https://user-images.githubusercontent.com/127076197/224881173-0d9aac24-fe61-42d7-9d4a-9abaecc0960a.png)

Please help me understand the usual process. Thank you

**Comment by yanguoyu** [comment]
> I was wondering does the block start from 0 every time I re-open Neuron program? If yes, it will take forever to finish syncing.
> 
> The first picture was before I closed the ckb and neuron. It shows the block was uploaded to 9,272,023 blocks ![image](https://user-images.githubusercontent.com/127076197/224879973-12622209-3266-4ed8-b393-092b793fd7c5.png)
> 
> The second picture is after I closed ckb and neuron program. However, when I re-open the neuron program, block starts to upload from 0/0 again. As you can see, I took this screenshot after I re-open Neuron for a while. The block which was previously uploaded to 9,272,023 blocks, didn't start upload from where it finished. ![image](https://user-images.githubusercontent.com/127076197/224881173-0d9aac24-fe61-42d7-9d4a-9abaecc0960a.png)
> 
> Please help me understand the usual process. Thank you

The first number is that the block number has synced. And the second number is the best-known block number. The second number gets by https://github.com/nervosnetwork/ckb/blob/master/rpc/README.md#method-sync_state, and the code is [here](https://github.com/nervosnetwork/neuron/blob/5ff057c63fee41de0c38b370110304983378acad/packages/neuron-wallet/src/controllers/sync-api.ts#L108-L125)
And Neuron will start syncing from the last synced block number after restarting.

**Comment by ishijan** [comment]
10,794 blocks synced and won't continue for two full days already. Here is the debug information. Please help me resolve the issue. 
[neuron_debug_1678809376898.zip](https://github.com/nervosnetwork/neuron/files/10970777/neuron_debug_1678809376898.zip)

**Comment by Keith-CY** [comment]
> 10,794 blocks synced and won't continue for two full days already. Here is the debug information. Please help me resolve the issue. [neuron_debug_1678809376898.zip](https://github.com/nervosnetwork/neuron/files/10970777/neuron_debug_1678809376898.zip)

Hi @ishijan 

From the log(bundled-ckb.log) we can see

```
2023-03-14 15:50:42.425 +00:00 BlockDownload INFO ckb_sync::synchronizer  best known header number: 8700794, hash: Byte32(0xaa500badb3dc8a8af9caa73c450843fe1d8b61b513b2a9012d3798f941f73406), can't find assume valid target temporarily, hash: Byte32(0x076ffa81f8c6f2e1f22a778a1aa5d48531cc33bfd9b302e0d73fb2ce6fa4de3b) please wait
```

It means the built-in ckb node is still at the early stage to find a specific block from network, the target block number is `8826940`(https://github.com/nervosnetwork/neuron/blob/develop/packages/neuron-wallet/.env#L120), yours reached `8700794`. So the synchronization doesn't start yet. This stage is called `looking for assumed valid target`, which should be prompted at the left bottom corner.

Detailed explanation could be found at https://github.com/nervosnetwork/neuron/issues/2570#issuecomment-1383166598

---

It takes about 6mins to scan 10,000 blocks(based on logs) and the remaining block count is `126146`, so the synchronization is expected to start after `126146 blocks / 10000 blocks * 6 mins / 60 mins = 1.2 hours`.

**Comment by ishijan** [comment]
Thank you @Keith-CY 
Block continue to sync but slowly. At this rate, I assume it would take about 90 hours to finish syncing, correct?

And one more question. If I close the Neuron program before it finishes syncing, close the computer, restart Neuron, will block start from 0 again? I've encountered this problem earlier before, so I'm a bit scared to turn off my computer. You see my computer has been on for 5 days now. What would you suggest me to do?

**Comment by yanguoyu** [comment]
> Thank you @Keith-CY Block continue to sync but slowly. At this rate, I assume it would take about 90 hours to finish syncing, correct?
> 
> And one more question. If I close the Neuron program before it finishes syncing, close the computer, restart Neuron, will block start from 0 again? I've encountered this problem earlier before, so I'm a bit scared to turn off my computer. You see my computer has been on for 5 days now. What would you suggest me to do?

No problem with turning off your computer, it will continue to sync from the last block number when you start it again.
