### ISSUE TITLE
transaction not showing up

### ISSUE THREAD

**Issue by dao1234567** [nervosnetwork/neuron#2611]
**Describe the bug** (Please enter details, the more detail the better)

**Debug info** (Please upload the debug info from `Help` - `Export Debug Information`)

**Screenshots** (If applicable, add screenshots to help explain your problem.)

**Comment by yanguoyu** [comment]
Hi, does your Neuron synced to 100%? If not, maybe you need to wait.
If yes, can you upload the debug information from `Help - Export Debug Information`

**Comment by dao1234567** [comment]
The isseu has Bin resolved, it was just an delay of Some kind. Thank you

Op zo 19 mrt. 2023 om 00:51 schreef 严国宇 ***@***.***>
