### ISSUE TITLE
Not arrived Token / Balance 0$

### ISSUE THREAD

**Issue by Coccoce81** [nervosnetwork/neuron#2622]
*Hello everyone. I connected my Ledger X to the Neuron wallet and sent CKB tokens from Binance to the address verified in the Neuron wallet. The transaction can be seen under 0x3bb6e9876591899b8590fa591efae94c510ed42863942129a59a3f400b73bc22
Unfortunately, this is not visible on the Neuron wallet and the balance is still at $0. This is now 7 hours ago.
Does anyone have an idea why this didn't work, or whether this even arrived on the ledger?
Thanks for your help
Best regards

**Comment by yanguoyu** [comment]
@Coccoce81 
From this https://explorer.nervos.org/transaction/0x3bb6e9876591899b8590fa591efae94c510ed42863942129a59a3f400b73bc22, we can ensure that this tx has broadcast success, but it does not show in your Neuron. Maybe because your neuron is not synced to 100%.

**Comment by Coccoce81** [comment]
hello yanguoyu, thanks for your reply. I thought so too. However, does this mean that the balance is on the wallet but is not displayed. Or has not been lost? What can I do now so that the credit is displayed to me? Many thanks in advance

**Comment by yanguoyu** [comment]
> Or has not been lost? What can I do now so that the credit is displayed to me?

Hi, it will not be lost, after your Neuron sync to 100%, you will see your CKB.

**Comment by yanguoyu** [comment]
> and what do I have to do so that the neuron synchronizes completely? Or do I just have to wait? It's been 24 hours now and the balance is still showing as $0. Thank you and best regards

From the left-bottom of Neuron, you can see the sync progress. How about it now?

**Comment by Coccoce81** [comment]
![Fortschritt Neuron](https://user-images.githubusercontent.com/129405735/229070711-5f97bed2-f0a0-4bf2-9f56-4c678e302b1f.PNG)

**Comment by yanguoyu** [comment]
> ![Fortschritt Neuron](https://user-images.githubusercontent.com/129405735/229070711-5f97bed2-f0a0-4bf2-9f56-4c678e302b1f.PNG)

That's cool, it really needs more time to sync it, because it runs a full node. Most of the time, it needs about 3~4 days to finish the sync. And it needs to keep the network online and synchronized, if the computer turns off the network after sleep, the sync progress will stop util turned on the network.

**Comment by Coccoce81** [comment]
perfect, thank you very much for the explanation and have a great day
Best regards

**Comment by Coccoce81** [comment]
for 5 days the progress remains at 99.59%. Is this no longer possible or do I need/ to do something? Thank you for your help

**Comment by Coccoce81** [comment]
for 5 days the progress remains at 99.59%. Is this no longer possible or do I need to do something? Thank you for your help

**Comment by yanguoyu** [comment]
> for 5 days the progress remains at 99.59%. Is this no longer possible or do I need/ to do something? Thank you for your help

Can you upload the Debug information by clicking `Help -> Export debug information`? And by the way, can you upload the sync progress screenshot?

**Comment by Coccoce81** [comment]
![Unbenannt](https://user-images.githubusercontent.com/129405735/233278151-de735f46-6d8a-4246-ac3c-eaa4f5106816.PNG)

**Comment by Coccoce81** [comment]
[neuron_debug_1681972478523.zip](https://github.com/nervosnetwork/neuron/files/11280555/neuron_debug_1681972478523.zip)

**Comment by yanguoyu** [comment]
@Coccoce81 Hi, I think your problem is the same as https://github.com/nervosnetwork/neuron/issues/2601#issuecomment-1455530637, you can try to resolve it following the steps in this comment.

**Comment by Coccoce81** [comment]
thank you very much, I'll try this

**Comment by Coccoce81** [comment]
Perfect. Thank you
