### ISSUE TITLE
[Synchronization] **brief description**

### ISSUE THREAD

**Issue by mihirbax** [nervosnetwork/neuron#2625]
### Detail of the issue

[bundled-ckb.log](https://github.com/nervosnetwork/neuron/files/11128610/bundled-ckb.log)
[main.log](https://github.com/nervosnetwork/neuron/files/11128611/main.log)
[renderer.log](https://github.com/nervosnetwork/neuron/files/11128616/renderer.log)

Please help Syn stoped. Its not even Connecting I have moved the data but it failed 
![WhatsApp Image 2023-04-01 at 11 58 50 AM](https://user-images.githubusercontent.com/9369613/229269745-6d3d5597-7af7-44a9-83e3-e7b18c40e887.jpeg)

**Comment by Keith-CY** [comment]
Hi @mihirbax 

The logs you've uploaded are empty, please upload the zip file exported from Neuron or copy-paste them in the `bundled-ckb.log`, `main.log`, `status.log` fields in the issue

PS: please wrap pasted contents with ``` so the word count will not be limited, as follows

```
Lorem ipsum dolor sit amet, 
consectetur adipisicing elit, 
sed do eiusmod tempor incididunt 
ut labore et dolore magna aliqua. 
Ut enim ad minim veniam, quis nostrud 
exercitation ullamco laboris nisi ut 
aliquip ex ea commodo consequat. 
Duis aute irure dolor in reprehenderit 
in voluptate velit esse cillum dolore 
eu fugiat nulla pariatur. Excepteur 
sint occaecat cupidatat non proident, 
sunt in culpa qui officia deserunt 
mollit anim id est laborum.
```
