### ISSUE TITLE
[Synchronization]stuck at 59 Percent

### ISSUE THREAD

**Issue by Jinxsyns** [nervosnetwork/neuron#2633]
### Detail of the issue

Sync is stuck at 59ish% have tried everything I could find with no fix. I can't remember how to get the debug report or I'd already have the link for y'all
![Neuron bug picture](https://user-images.githubusercontent.com/130711085/231898311-f3611e09-f2db-4ea2-a7b0-65e734eecdc5.png)
[neuron_debug_1681425633587.zip](https://github.com/nervosnetwork/neuron/files/11227052/neuron_debug_1681425633587.zip)

**Comment by Jinxsyns** [comment]
Sorry I forgot to remove that I didn't know how to get the debug info because the github showed me how to later in the process.

**Comment by Keith-CY** [comment]
> ### Detail of the issue
> Sync is stuck at 59ish% have tried everything I could find with no fix. I can't remember how to get the debug report or I'd already have the link for y'all ![Neuron bug picture](https://user-images.githubusercontent.com/130711085/231898311-f3611e09-f2db-4ea2-a7b0-65e734eecdc5.png) [neuron_debug_1681425633587.zip](https://github.com/nervosnetwork/neuron/files/11227052/neuron_debug_1681425633587.zip)
> 
> ### bundled-ckb.log
> _No response_
> 
> ### main.log
> _No response_
> 
> ### status.log
> _No response_

Hi @Jinxsyns I believe the progress is moving now.

The last informative log in `bundled-ckb.log` is

```
2023-04-13 22:33:38.981 +00:00 BlockDownload INFO ckb_sync::synchronizer  best known header number: 8825930, hash: Byte32(0xa4aba0a25714cd0c03a29a08b1e79a50d0fcc6a8025090006b0772fc0f147bf4), can't find assume valid target temporarily, hash: Byte32(0x076ffa81f8c6f2e1f22a778a1aa5d48531cc33bfd9b302e0d73fb2ce6fa4de3b) please wait
```

Note the keywords: `best known header number: 8825930`, `can't find assume valid target temporarily`.

it was looking for an assumed valid block to boost the synchronization, and reached block `8,825,930`

We've set the assumed valid block at https://github.com/nervosnetwork/neuron/blob/develop/packages/neuron-wallet/.env#L120, its block hash is `0x076ffa81f8c6f2e1f22a778a1aa5d48531cc33bfd9b302e0d73fb2ce6fa4de3b` and block number is `8,826,940`(https://explorer.nervos.org/block/0x076ffa81f8c6f2e1f22a778a1aa5d48531cc33bfd9b302e0d73fb2ce6fa4de3b), so the built-in ckb node hadn't found it yet.

Once the built-in ckb node find the assumed valid block, it will start downloading data and skip verification of blocks prior to the assumed valid one, which reduces time in synchronization.

**Comment by Jinxsyns** [comment]
No it's still stuck the screenshot is og where it' stuck at not that it's moving  24 hours still stuck

**Comment by Keith-CY** [comment]
> No it's still stuck the screenshot is of where it' stuck at not that it's moving 24 hours still stuck

May I have the latest debug info for a comparison to the previous one

**Comment by Jinxsyns** [comment]
[neuron_debug_1681496641512.zip](https://github.com/nervosnetwork/neuron/files/11236003/neuron_debug_1681496641512.zip)

**Comment by Keith-CY** [comment]
> [neuron_debug_1681496641512.zip](https://github.com/nervosnetwork/neuron/files/11236003/neuron_debug_1681496641512.zip)

The `bundled-ckb.log` is full of

```
2023-04-14 17:50:11.719 +00:00 GlobalRt-0 INFO ckb_sync::synchronizer::get_headers_process  Ignoring getheaders from peer=SessionId(17) because node is in initial block download
```
which means the data synced from other ckb nodes(peers) are discarded because the peers you've connected to are also in the progress of synchronization. So the synchronization of your ckb node hangs.

However, it's the first time I see all peers are not ready, and I'll check this with ckb node team tomorrow. It's Saturday for most developers, so the reply may be two days later.

**Comment by Jinxsyns** [comment]
Yeah that would explain the Weird behavior thank you so expect something Monday?

**Comment by Keith-CY** [comment]
> Yeah that would explain the Weird behavior thank you so expect something Monday?

Yes, we'll have the reply by Monday at the latest.

**Comment by Keith-CY** [comment]
> Yeah that would explain the Weird behavior thank you so expect something Monday?

Hi @Jinxsyns 

It's probably a bug revealed in ckb node@v0.106.0 and we've two solutions

1. easy but cannot avoid it 100%: start synchronization from scratch to connect to new peers, it can be done by **Menu => Tools => Clear all synchronized data**. Since it's still at the early stage of synchronization, it won't take much time.

2. require a bit of technical work: replace the built-in ckb node with the latest one(https://github.com/nervosnetwork/ckb/releases/tag/v0.108.1), which fixed this bug:
    1. Download the latest ckb node from https://github.com/nervosnetwork/ckb/releases/tag/v0.108.1
    2. Find out the built-in ckb node, the directory may be `C:\{Username}\NeuronVersion\Install\bin` or `C:\Program Files\Neuron/bin`, depending on how you've installed neuron
    
![SR3iZfJ8dAVy2Lzs](https://user-images.githubusercontent.com/7271329/232190382-03755378-2dfc-41c4-9eed-64c5976662a4.png)
![nVa01Kvfqhq4C8Yz](https://user-images.githubusercontent.com/7271329/232190384-85eb0550-6081-4cdb-9da5-4d9184af02f2.png)
    3. Replace the built-in one with the newly downloaded one
    4. Restart Neuron, it requires a data migration which takes several minutes, and then the synchronization should start.

**Comment by Jinxsyns** [comment]
Sorry busy week. Is there maybe someone on the team with a testbench that could make some rudimentary install guide? There is many files in what I downloaded to replace the Node and the only thing you pointed me to was the ckb.exe. I just need to know what Files I need to replace.

**Comment by Keith-CY** [comment]
> Sorry busy week. Is there maybe someone on the team with a testbench that could make some rudimentary install guide? There is many files in what I downloaded to replace the Node and the only thing you pointed me to was the ckb.exe. I just need to know what Files I need to replace.

Sure, the `ckb.exe` locates at `{Neuron_Installed_Path}\bin\ckb.exe` and `Downloads\ckb_v0.109.0_x86_64-pc-windows-msvc.zip\ckb_v0.109.0_x86_64-pc-windows-msvc\ckb.exe`, where `{Neuron_Installed_Path}` depends on how it's installed as mentioned above.

Replacing the former one with the latter one upgrades the built-in CKB node

https://user-images.githubusercontent.com/7271329/233770855-25dbd0ca-eb3c-44e2-bfa3-59407b8e8bde.mov
