### ISSUE TITLE
update for batch variable rename

### ISSUE THREAD

**Issue by doitian** [nervosnetwork/neuron#264]
https://github.com/nervosnetwork/ckb/pull/533

## Block:
commit_transactions -> transactions
proposal_transactions -> proposals

## Header:
txs_commit -> transactions_root
txs_proposal -> proposals_root

## OutPoint:
hash -> tx_hash

## CellInput:
valid_since -> since

## Script:
binary_hash -> code_hash

Note: CKB has a bug that RPC types still have `hash` from `OutPoint` instead of `tx_hash`.

**Comment by ashchan** [comment]
Remaining `OutPoint.hash` -> `OutPoint.tx_hash` fix/update:

https://github.com/nervosnetwork/ckb/blob/develop/util/jsonrpc-types/src/blockchain.rs#L93
