### ISSUE TITLE
Block Synced 100% (Sync is slow) Neuron Version 0.101.2

### ISSUE THREAD

**Issue by cdungan** [nervosnetwork/neuron#2678]
I've had trouble getting a completely functioning wallet for quite some time. It says block synced 7,150,910, however the balance is incorrect and I have no balance listed on my Locked CKB. I've tried to update to 0.106.0 however when I try, I get an error message on my mac "...code failed to satisfy specified code requirement(s)"

<img width="201" alt="Screen Shot 2023-05-22 at 4 55 23 PM" src="https://github.com/nervosnetwork/neuron/assets/69976720/0dd241b7-0230-4a11-910c-e63d6fe9a189">
<img width="252" alt="Screen Shot 2023-05-22 at 4 56 51 PM" src="https://github.com/nervosnetwork/neuron/assets/69976720/ff7d9826-77e3-4c5c-8888-e54e7adb4900">

**Comment by yanguoyu** [comment]
Hi, @cdungan 
It causes by we've updated the Apple Developer Id Certificate of Neuron which is distributed by [Nervina Labs](https://github.com/nervina-labs/) and authorized by [Developer ID - G2 (Expiring 09/17/2031 00:00:00 UTC)](https://www.apple.com/certificateauthority/DeveloperIDG2CA.cer). With this update, a warning may appear on updating Neuron by check for updates inside Neuron.

But don't worry about this, you can download the latest version from [here](https://github.com/nervosnetwork/neuron/releases/tag/v0.106.0) to adopt the new certificate.

**Comment by cdungan** [comment]
Thank you for such a quick response. Sorry for the confusion. If I download the updated wallet, not from within my current wallet, will I have to move my wallet with my pass phrase?

**Comment by yanguoyu** [comment]
> Thank you for such a quick response. Sorry for the confusion. If I download the updated wallet, not from within my current wallet, will I have to move my wallet with my pass phrase?

You do not need to move the wallet, because installing a new Neuron will not remove the config of Neuron.

**Comment by cdungan** [comment]
Thank you, it looks like the migration is in progress. I appreciate you helping me so quickly.
