### ISSUE TITLE
Use Neuron with manually internal ckb node

### ISSUE THREAD

**Issue by yanguoyu** [nervosnetwork/neuron#2701]
1. Windows
     1. Right-click when hovering on the `Neuron` startup icon, and click `open the file location`
     2. After the system opens a directory, try to find and open the directory named `bin`, and copy the full path of `ckb.exe` as **ckb_node_path**
     3. Open Neuron and click `Help -> Setting -> Data`, then hover on the data path and click to copy it as **ckb_data_path**, then close Neuron

        <img width="881" alt="image" src="https://github.com/nervosnetwork/neuron/assets/12881040/29837852-b853-4a4b-aa3f-804847090cee">
     4. open a terminal program, Powershell is usually delivered with windows
     5. type `ckb_node_path(from step 2) run -C ckb_data_path(from step 3) --indexer` and hit Enter to start the node
     6.  After the ckb node run success, restart Neuron.
2. Mac
     1. Right-click when hovering on the `Neuron` application, and click `show package contents`
     2. Go to `content -> bin`, and copy the full path of `ckb` as **ckb_node_path**
     3. Open Neuron and click `Preference -> Data`, then hover on the data path and click to copy it as **ckb_data_path**, then close Neuron

        <img width="881" alt="image" src="https://github.com/nervosnetwork/neuron/assets/12881040/29837852-b853-4a4b-aa3f-804847090cee">
     4. open a terminal program,  type `ckb_node_path(from step 2) run -C ckb_data_path(from step 3) --indexer` and hit Enter to start the node
     6.  After the ckb node run success, restart Neuron.
  
3. Linux
     1. Open Neuron and click `Preference -> Data`, then hover on the data path and click to copy it as **ckb_data_path**, then close Neuron

        <img width="881" alt="image" src="https://github.com/nervosnetwork/neuron/assets/12881040/29837852-b853-4a4b-aa3f-804847090cee">
     2. Download the release ckb from https://github.com/nervosnetwork/ckb/releases/tag/v0.110.0
     3. Unzip the ckb tar.gz and goto the unzipped directory
     4. open a terminal program in current directory,  type `./ckb run -C ckb_data_path(from step 1) --indexer` and hit Enter to start the node
     6.  After the ckb node run success(when you see this log `Listen HTTP RPCServer on address 127.0.0.1:8114`), restart Neuron.

**Comment by rx2347** [comment]
Thanks for posting, can confirm this works on MacOS.

**Comment by 0xfather** [comment]
![QQ图片20230703091108](https://github.com/nervosnetwork/neuron/assets/29141899/297dbd41-4abb-4844-b65e-f35e1385c6e5)
Using the above method, it can run for a period of time, but there will still be abnormal situations where the node will be restarted. It is uncertain whether it was restarted by Neuron or indexer

**Comment by yanguoyu** [comment]
> ![QQ图片20230703091108](https://user-images.githubusercontent.com/29141899/250445709-297dbd41-4abb-4844-b65e-f35e1385c6e5.jpg) Using the above method, it can run for a period of time, but there will still be abnormal situations where the node will be restarted. It is uncertain whether it was restarted by Neuron or indexer

Don't worry, the restart log only means connecting to the ckb node failed currently, it doesn't restart actually. Because Neuron uses the external ckb so it will not restart ckb node. We'd better optimize the log output.
