### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'startsWith')

### ISSUE THREAD

**Issue by FrankFang** [nervosnetwork/neuron#2705]
**Describe the bug** (Please enter details, the more detail the better)

1. use `yarn start` to start the app
2. click button "转账" in the navbar
3. see the error log in terminal console 

Besides, my .env.local file is empty. Maybe some empty env varable leads to this bug.

**Debug info** (Please upload the debug info from `Help` - `Export Debug Information`)

[neuron_debug_1686120785459.zip](https://github.com/nervosnetwork/neuron/files/11673477/neuron_debug_1686120785459.zip)

**Screenshots** (If applicable, add screenshots to help explain your problem.)

![image](https://github.com/nervosnetwork/neuron/assets/839559/8339ee06-5d96-43b8-bcb7-fb589b40fad5)

**Comment by Keith-CY** [comment]
@FrederLu @silySuper @littleLip520 please check if it is reproducible

**Comment by silySuper** [comment]
I have tried click '转账'   and then export debug log,the same  error is shown in main.log,I used new UI version and  CKB node is ckb_v0.108.1_x86_64-apple-darwin-portable.

this is my log zip:
[neuron_debug_1686129124342.zip](https://github.com/nervosnetwork/neuron/files/11675031/neuron_debug_1686129124342.zip)

**Comment by FrederLu** [comment]
<img width="1008" alt="image" src="https://github.com/nervosnetwork/neuron/assets/25676576/4c42f525-275a-49d8-89c3-02e3ddfc5823">
The problem can be reproduced by installing the steps described by the user.

[neuron_debug_1686130742296.zip](https://github.com/nervosnetwork/neuron/files/11675280/neuron_debug_1686130742296.zip)
