### ISSUE TITLE
[Synchronization] **brief description** 

### ISSUE THREAD

**Issue by NBMB1** [nervosnetwork/neuron#2706]
### Detail of the issue

 windows... updated to 0.110.1 wont connect or start to sync at all please help..

![Screenshot (1)](https://github.com/nervosnetwork/neuron/assets/107458834/4eefc54e-90eb-4933-9385-2875561c7b18)
![Screenshot (2)](https://github.com/nervosnetwork/neuron/assets/107458834/6652f5c4-9b3a-4257-b792-cb3166dbc06b)
[bundled-ckb-lignt-client.log](https://github.com/nervosnetwork/neuron/files/11685150/bundled-ckb-lignt-client.log)
![Screenshot (1)](https://github.com/nervosnetwork/neuron/assets/107458834/40b0126b-93e5-40f2-9992-4f9436f71309)
![Screenshot (2)](https://github.com/nervosnetwork/neuron/assets/107458834/5b54acdf-539a-477e-914c-ceda0df5b96c)

**Comment by yanguoyu** [comment]
Hi, Could you help us to upload the full log files? Download the debug information by clicking `help -> Export debug information`.

**Comment by NBMB1** [comment]
[neuron_debug_1686208764095.zip](https://github.com/nervosnetwork/neuron/files/11685285/neuron_debug_1686208764095.zip)

**Comment by NBMB1** [comment]
Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by yanguoyu** [comment]
Hi, @NBMB1 this problem is the same as https://github.com/nervosnetwork/neuron/issues/2699.
We can reference https://github.com/nervosnetwork/neuron/issues/2699#issuecomment-1578195810 to resolve it.

**Comment by NBMB1** [comment]
Sync Has started now... thank you for your help..
