### ISSUE TITLE
[Synchronization] **Really slow**

### ISSUE THREAD

**Issue by NBMB1** [nervosnetwork/neuron#2707]
### Detail of the issue

please advise any help as the sync is going really slow not even1% in 5 hours ..any help would be gratefully accepted.
![Screenshot (3)](https://github.com/nervosnetwork/neuron/assets/107458834/3be8483a-23d1-42fb-9f52-b8d048fccf31)

**Comment by NBMB1** [comment]
[neuron_debug_1686234494240.zip](https://github.com/nervosnetwork/neuron/files/11689632/neuron_debug_1686234494240.zip)

**Comment by yanguoyu** [comment]
From the log, it displays that Neuron is finding assume valid target temporarily.
More information about `find assume valid target temporarily` can be found at https://github.com/nervosnetwork/neuron/issues/2504#issuecomment-1279958221 and https://github.com/nervosnetwork/neuron/issues/2398#issuecomment-1160335164.
