### ISSUE TITLE
TransactionFailedToResolve: Resolve failed unknown 

### ISSUE THREAD

**Issue by robkay01** [nervosnetwork/neuron#2726]
**Describe the bug** (Please enter details, the more detail the better)
When I try to deposit to the DAO I get an error message as above "TransactionFailedToResolve: Resolve Failed Unknown. I am 100% Synced and latest version of Neuron.

**Debug info** (Please upload the debug info from `Help` - `Export Debug Information`)
See attached

**Screenshots** (If applicable, add screenshots to help explain your problem.)
See attached
![Screenshot 2023-06-19 201024](https://github.com/nervosnetwork/neuron/assets/55883564/abcf527d-3d4f-4343-93c5-7889f31b12fc)

**Comment by yanguoyu** [comment]
Hi, @robkay01 can you upload the debug information to help us? You can download debug information by click `Help -> Export Debug Information`

**Comment by robkay01** [comment]
> Hi, @robkay01 can you upload the debug information to help us? You can download debug information by click `Help -> Export Debug Information`

Hi sorry I thought I did that already, please see attached.
[neuron_debug_1687176517222.zip](https://github.com/nervosnetwork/neuron/files/11794913/neuron_debug_1687176517222.zip)

**Comment by yanguoyu** [comment]
Hi, @robkay01 
From the log, I find that the `OutPoint 0x59e4494b9db5dff7d07d9b8a969f51102747a73241e74e59a2e0b47a7c3c6c68ac000000 ` has been used. Can you try to clear cache without `Fully rebuild index` by clicking `Help -> Settings -> Data -> Clear Cache`?

<img width="868" alt="image" src="https://github.com/nervosnetwork/neuron/assets/12881040/2635b14b-5ae5-4e50-bd52-8cf8378b1797">
