### ISSUE TITLE
[Synchronization] Stuck on block 8,951,720 for days

### ISSUE THREAD

**Issue by kove92** [nervosnetwork/neuron#2758]
### Detail of the issue

Hello Everyone,

my neuron app is stuck on block 8,951,720 for days and not syncing anymore. 
I had several issues before like stuck on connecting wich i resolve by removing the addr_manager.db and it started syncing again till this block. 

I've looked in this forum to try and resolve my problem but nothing seems to work.  Could you help me resolve it please ? 

[neuron_debug_1681496641512.zip](https://github.com/nervosnetwork/neuron/files/11939625/neuron_debug_1681496641512.zip)

![Neuron Sync Stuck](https://github.com/nervosnetwork/neuron/assets/138514657/54eb61db-ddac-4594-be86-951719a48ab4)

**Comment by yanguoyu** [comment]
Hi, @kove92 
I see many such logs `INFO ckb_sync::synchronizer::get_headers_process  Ignoring getheaders from peer=SessionId(15) because node is in initial block download` from `2023-04-14 16:30:16.243 +00:00` to `2023-04-14 18:22:58.029 +00:00` in the `bundled-ckb.log`. And I see that your `Neuron` version is 0.106.0, Could you try to update your Neuron to the latest version from https://github.com/nervosnetwork/neuron/releases/tag/v0.110.1

**Comment by kove92** [comment]
Thank you for your reply. 
My neuron app is updated but still the same issue 
![neuron version](https://github.com/nervosnetwork/neuron/assets/138514657/eb160bea-b0da-4c2e-b19c-19fe3496c230)

Do you have any clue on how to resolve that get_header problem ?

**Comment by yanguoyu** [comment]
> Thank you for your reply. My neuron app is updated but still the same issue ![neuron version](https://user-images.githubusercontent.com/138514657/250850622-eb160bea-b0da-4c2e-b19c-19fe3496c230.jpg)
> 
> Do you have any clue on how to resolve that get_header problem ?

I'm sorry for that. Could you upload the debug information again after updating Neuron to 0.110.1? Thank you.

**Comment by Keith-CY** [comment]
> Thank you for your reply. My neuron app is updated but still the same issue ![neuron version](https://user-images.githubusercontent.com/138514657/250850622-eb160bea-b0da-4c2e-b19c-19fe3496c230.jpg)
> 
> Do you have any clue on how to resolve that get_header problem ?

It was a known issue of the built-in CKB node, and has been reported to the CKB core team.

The only solution that might work is to resync from scratch, which can be done by **Menu => Tool => Clear all synchronized data**

But it's the panacea, and the problem may come back(https://github.com/nervosnetwork/ckb/issues/4009)

We do have a trick to avoid it, please send an e-mail to neuron@magickbase.com so we can reply with the trick.

**Comment by kove92** [comment]
> > Thank you for your reply. My neuron app is updated but still the same issue ![neuron version](https://user-images.githubusercontent.com/138514657/250850622-eb160bea-b0da-4c2e-b19c-19fe3496c230.jpg)
> > Do you have any clue on how to resolve that get_header problem ?
> 
> I'm sorry for that. Could you upload the debug information again after updating Neuron to 0.110.1? Thank you.

Here it is, Thank you again.

[neuron_debug_1688465407335.zip](https://github.com/nervosnetwork/neuron/files/11947949/neuron_debug_1688465407335.zip)

**Comment by yanguoyu** [comment]
> > > Thank you for your reply. My neuron app is updated but still the same issue ![neuron version](https://user-images.githubusercontent.com/138514657/250850622-eb160bea-b0da-4c2e-b19c-19fe3496c230.jpg)
> > > Do you have any clue on how to resolve that get_header problem ?
> > 
> > 
> > I'm sorry for that. Could you upload the debug information again after updating Neuron to 0.110.1? Thank you.
> 
> Here it is, Thank you again.
> 
> [neuron_debug_1688465407335.zip](https://github.com/nervosnetwork/neuron/files/11947949/neuron_debug_1688465407335.zip)

Maybe you try to refer to https://github.com/nervosnetwork/neuron/issues/2701, please let me know the result whether it works or not.
