### ISSUE TITLE
[Synchronization] wont show my CKB in balance

### ISSUE THREAD

**Issue by verycoolpotato1** [nervosnetwork/neuron#2768]
### Detail of the issue

had an issue with synchronization today got it resolved by putting addr_manager.dll to desktop now it wont show my 1.2+ million CKB in balance.

**Comment by verycoolpotato1** [comment]
[neuron_debug_1688951804493.zip](https://github.com/nervosnetwork/neuron/files/11996924/neuron_debug_1688951804493.zip)

**Comment by yanguoyu** [comment]
Hi, @verycoolpotato1 
Have you clicked `clear all synchronize data`? I found that `Neuron` init a new ckb config, then the `Neuron` will start syncing from block 0.

**Comment by verycoolpotato1** [comment]
> Hi, @verycoolpotato1 Have you clicked `clear all synchronize data`? I found that `Neuron` init a new ckb config, then the `Neuron` will start syncing from block 0.

Yes I have cleared all synchronized data but when it reached 100% my balance was still at 0

**Comment by yanguoyu** [comment]
From the log, I see that the `Neuron` sync to 95494 currently. If next time it reached 100% and the balance is not shown correctly, you can try to click `Help -> Settings -> Data -> Clear Cache` without `Fully rebuild index` to rebuild local data, but not `cleared all synchronized data`. Because re-download all the synchronized data may cost a lot of time. `Clear Cache` to rebuild local data is much faster.

<img width="951" alt="image" src="https://github.com/nervosnetwork/neuron/assets/12881040/49e11c65-b0a9-4095-bab4-318ee4215b0f">

**Comment by verycoolpotato1** [comment]
> From the log, I see that the `Neuron` sync to 95494 currently. If next time it reached 100% and the balance is not shown correctly, you can try to click `Help -> Settings -> Data -> Clear Cache` without `Fully rebuild index` to rebuild local data, but not `cleared all synchronized data`. Because re-download all the synchronized data may cost a lot of time. `Clear Cache` to rebuild local data is much faster.
> 
> <img alt="image" width="951" src="https://user-images.githubusercontent.com/12881040/252197500-49e11c65-b0a9-4095-bab4-318ee4215b0f.png">

okay thanks will try this right now, will let you know if it worked

**Comment by verycoolpotato1** [comment]
It is at 100% and it still won't show my CKB balance i had over 1.2+ million. 
![image](https://github.com/nervosnetwork/neuron/assets/139079625/67033017-f788-4de9-8f0b-e4cef6b65c74)

**Comment by Keith-CY** [comment]
> It is at 100% and it still won't show my CKB balance i had over 1.2+ million. ![image](https://user-images.githubusercontent.com/139079625/252351493-67033017-f788-4de9-8f0b-e4cef6b65c74.png) is it possible that my CKB is all gone?

Hi @verycoolpotato1 

As mentioned by @yanguoyu at https://github.com/nervosnetwork/neuron/issues/2768#issuecomment-1627986316 , the log exported at https://github.com/nervosnetwork/neuron/issues/2768#issuecomment-1627913482 showed that Neuron was not fully synced so the balance was reasonable to be 0.

But now we've reached block 10,422,663, the progress is 100%, the balance is expected to be positive but it's not. Could you export the debug information again so we can check why the balance is 0 even the wallet is fully synced?

**Comment by verycoolpotato1** [comment]
[neuron_debug_1691201151282.zip](https://github.com/nervosnetwork/neuron/files/12265882/neuron_debug_1691201151282.zip)



here you go sorry for replying late i was on vacation

**Comment by verycoolpotato1** [comment]
i just send 101 ckb tokens to the wallet adress and it received it but the balance i had is gone

![image](https://github.com/nervosnetwork/neuron/assets/139079625/9f3c4c09-999b-4f8c-8ce6-e2a436068899)

**Comment by yanguoyu** [comment]
> i just send 101 ckb tokens to the wallet adress and it received it but the balance i had is gone
> 
> ![image](https://user-images.githubusercontent.com/139079625/258558644-9f3c4c09-999b-4f8c-8ce6-e2a436068899.png)

It's strange, could you join our discord channel https://discord.gg/fkK2bseh, and send this issue, we will create a private channel, then upload the extended public key for us to debug it.

**Comment by verycoolpotato1** [comment]
alright i joined my discord is felon#7619

**Comment by yanguoyu** [comment]
This issue has been resolved in discord channel.
