### ISSUE TITLE
neuron ne se synchrinise pas et bloque 8268267/79,09%

### ISSUE THREAD

**Issue by LBOBY3** [nervosnetwork/neuron#2771]
### Detail of the issue

Bonjour,neuron ne se synchronise pas et bloque 8268267/79,09% cela fais 3 fois que je recommence debuit le début je ne sais plus quoi faire !!! Aidez-Moi s'il vous plait ?Merci 
[neuron_debug_1689410196517.zip](https://github.com/nervosnetwork/neuron/files/12060969/neuron_debug_1689410196517.zip)

**Comment by LBOBY3** [comment]
<img width="227" alt="Capture d’écran 2023-07-15 104153" src="https://github.com/nervosnetwork/neuron/assets/116883033/7c352bfc-7e11-4df3-b401-855643357e66">

**Comment by yanguoyu** [comment]
In my knowledge, it's the same as https://github.com/nervosnetwork/neuron/issues/2699.
I believe you can refer to https://github.com/nervosnetwork/neuron/issues/2699#issuecomment-1578195810 to resolve it.

**Comment by LBOBY3** [comment]
Merci oui c'est bon 👍
