### ISSUE TITLE
I see my CKB on a public key but not receive on my Wallet Neuron (via Ledger) 

### ISSUE THREAD

**Issue by Orionstell** [nervosnetwork/neuron#2781]
everything is ok when I got 99% I received my CKBs, the subject is closed.

              Hello, I made the same mistake as @verycoolpotato1 , my CKB was at 0, and it was impossible to Synced, I followed yanguoyu's instructions commented on Jun 6 • 

"Hi, @Drazzerss
Due to the impact of hard disk and CPU performance, the built-in ckb nodes are processing data for a period of time after startup and cannot connect.
You can temporarily solve it according to the following steps:
Open Neuron and click Preference/Settings -> Data, then click the directory icon to open the ckb node data directory, close Neuron.
After the system open the ckb node data directory, go to ./data/network/peer_store, and backup and remove addr_manager.db
RestartNeuron."

 It worked but I don't receive my CKBs that I withdrew 3 days ago from a platform. I have my balance from before appear, but not the CKB I send 3 days ago. I can see on my public address that the CKBs are indeed added to the amount before CKB, but the problem they do not appear in the Neuron wallet. I use the ledger. What to do to receive them on my Neuron wallet, somebody know why ? thanks in advance for your answer .

_Originally posted by @Orionstell in https://github.com/nervosnetwork/neuron/issues/2699#issuecomment-1643971666_

**Comment by itoolsbit** [comment]
Very good, allowed in my case.
Days trying.
I installed 3x the neuron 5 days synchronizing and nothing.
Now it's ok.

**Comment by Keith-CY** [comment]
Hi @Orionstell I see the last modification of this issue is adding

> everything is ok when I got 99% I received my CKBs, the subject is closed.

May I treat this issue resolved?
