### ISSUE TITLE
Hello.I have sent two days ago my CKB coins from CRYPTO.COM to Neuron Wallet ,and still didn't received them since. But the status is showing is : pending. The Crypto.com Customer service direct me to contact you (Neuron Network Team ) to sort the my problem with it. Could you please fix the issue with my transaction ? Thank you for your time. With regards. E.Eren

### ISSUE THREAD

**Issue by Eren1034** [nervosnetwork/neuron#2790]
**Describe the bug** (Please enter details, the more detail the better)

**Debug info** (Please upload the debug info from `Help` - `Export Debug Information`)

**Screenshots** (If applicable, add screenshots to help explain your problem.)

**Comment by yanguoyu** [comment]
Hi, @Eren1034 
The neuron is a full node wallet, the neuron may not show your ckb before syncing to the block number that includes your transaction. After the neuron sync to that block number, you will find your ckb.
On the other hand, you can also find your balance on the Explorer by your address. The explorer includes a full node at the back end. https://explorer.nervos.org/.

**Comment by Eren1034** [comment]
Hi .
Thank you for your prompt reply.
I am waiting reply from Crypto.com about my issue with the transaction. As still showing:pending in Neuron wallet , and still the money didn’t appear. The address what I usual using is : ckb1qyqqvt9ayq92fmgtshee2780s6 sappuzcc7s53074v

I have holding currently 5,6 million ckb coins all I use this wallet address 

Could you please help me and check it for where my coins are ? 
Thank you for your time .
E.Eren

**Comment by yanguoyu** [comment]
Hi, @Eren1034 Could you upload the debug information for us to find out why the Neuron showing pending? You can download the debug information by clicking `Help -> Export Debug Information`.

And you can view your address balance at https://explorer.nervos.org/address/ckb1qyqqvt9ayq92fmgtshee2780s6sappuzcc7s53074v. You can replace the last string with your wallet address to view addresses' balances.

<img width="1285" alt="image" src="https://github.com/nervosnetwork/neuron/assets/12881040/da26f98f-d81d-413c-9ee8-55c5f1253ce3">
