### ISSUE TITLE
[Synchronization] **brief description**

### ISSUE THREAD

**Issue by Juninhotvr** [nervosnetwork/neuron#2825]
### Detail of the issue

I'm trying to solve this problem, but unfortunately I'm not succeeding, does anyone know how to do it?

### bundled-ckb.log

```shell
INFO ckb_sync::types  header_map.memory_limit 600MB
INFO ckb_bin::subcommand::run  ckb version: 0.110.0 
INFO ckb_launcher  Miner is disabled, edit ckb.toml to enable it
```

**Comment by yanguoyu** [comment]
Hi, @Juninhotvr 
Do these logs repeat print and the neuron is always connecting? If so, I believe [#2699 (comment)](https://github.com/nervosnetwork/neuron/issues/2699#issuecomment-1578195810) can help you.
And we will fix it in the next version by updating the ckb version.

**Comment by Juninhotvr** [comment]
Yes, these logs repeat, but Neuron does not synchronize. I'll try the steps in #2699. Thank you for your attention.
