### ISSUE TITLE
Tried withdrawing to another wallet from neuron . error message

### ISSUE THREAD

**Issue by AydenPeh** [nervosnetwork/neuron#2854]
### Detail of the issue

i tried to withdraw unlock ckbs from neuron. but there is error message

**Comment by AydenPeh** [comment]
<img width="968" alt="image" src="https://github.com/nervosnetwork/neuron/assets/145603440/a8c3900a-81ad-4fb7-a8ed-2280b54bd521">

**Comment by yanguoyu** [comment]
Hi, @AydenPeh Could you upload the debug information? We can download the debug information by clicking Help -> Export Debug Information.

From https://github.com/nervosnetwork/ckb-script-error-codes/blob/main/by-data-hash/709f3fda12f561cfacf92273c57a98fede188a3f1a59b1f888d113f9cce08649.md#-31, it means the signature does not match the input.lock. If you use a hard wallet, could you try to verify the address on the address page?

**Comment by AydenPeh** [comment]
solve it thanks guoyu
