### ISSUE TITLE
Neuron Wallet will not sync. 

### ISSUE THREAD

**Issue by Pnipper** [nervosnetwork/neuron#2857]
Neuron wallet will not sync. I have been waiting for 3 days. I have changed wallet due to losing over 500 coins. I still have 400 in the wallet but it can't be pulled due to not syncing. I have done everything from restarting the wallet over 2 to 3 time with nothing. 
Please help.

**Debug info** (Please upload the debug info from `Help` - `Export Debug Information`)

**Screenshots** (If applicable, add screenshots to help explain your problem.)

**Comment by yanguoyu** [comment]
Hi, @Pnipper  Could you upload the debug information? We can download the debug information by clicking Help -> Export Debug Information.
