### ISSUE TITLE
Channel Integration

### ISSUE THREAD

**Issue by ndzik** [nervosnetwork/neuron#2878]
We would like to integrate Perun channels according to its [specification](https://github.com/perun-network/perun-wallet-spec) into Neuron and propose our idea in this issue.

The things that have to be integrated are the following:

1. **Wallet Callback handler (WCH)**:
   Essentially a RPC service exposed by the Neuron wallet. To aid the implementation of these endpoints we will provide [perun-wallet-wrapper](https://github.com/perun-network/perun-wallet-wrapper). This repository will contain the interfaces and types as well as their conversions. We will also provide a higher-level interface to make it even easier for integration.
   Question remaining: How would we expose any RPC interface in Neuron and how does it fit into your current architecture?
2. **Channel Service Adapter (CSA)**:
   A client implementation calling the endpoints of the [perun-channel-service](https://github.com/perun-network/channel-service). The client implementation will also be contained in [perun-wallet-wrapper](https://github.com/perun-network/perun-wallet-wrapper).
   Additionally, we will create a high-level interface, which the client implements. This eases splitting up the work-packages and lets someone else implement a UI against the interface.
3. **UI tying together CSA & WCH**:
   Naively, we think of a tab within Neuron presenting the possibility to use Perun channels to the user.
   Actions a user can take:
   * Opening a channel
   * Updating a channel
   * Closing a channel
   * Bonus features:
     * Listing all open channels
     * History of all channels
   
   The WCH might receive notifications from the externally running channel-service. E.g.: The channel-service requests a signature on some payload. This would call an endpoint in WCH and it would be nice if the WCH would ultimately propagate this signing request to the user. Might be via a popup or something else.
   Actions triggered externally by the channel-service like this might be a component of their own. It is also possible to use dependency injection and create an interface for a _notification_ service which the implementation of WCH expects and calls when necessary. This is up for discussion.
   
Eager to see your replies (:

**Comment by yanguoyu** [comment]
@Keith-CY @homura @yanguoyu

**Comment by homura** [comment]
> Question remaining: How would we expose any RPC interface in Neuron and how does it fit into your current architecture?

The architecture of Neuron is not complicated. Neuron is based on Electron, so we can simply treat it as a web application but with the ability to interact with the OS, and its server is able to push messages to the UI. From a bird's view, it looks like this


<image width="300" src="https://github.com/nervosnetwork/neuron/assets/7511174/04d38c16-7fdc-4f28-82f4-e4dd386464e9" />

The arrows mean the directions of responsive messages

<image width="150" src="https://github.com/nervosnetwork/neuron/assets/7511174/80201178-f5a8-4786-8554-3271afe01d7c" />

So I imagine that, to integrate with Perun, Neuron needs

- run a _perun-channel-service_ in the background when Neuron is launched
- implement a [`ChannelServiceAdapter`](https://github.com/perun-network/perun-wallet-spec/blob/0a01e2834a33bbe88a48582f6b75effc1b2527c0/src/proto/perun-wallet.proto#L10) in Neuron's _Services_ layer to help users to request to _perun-channel-service_, such as open, update, or close channels
- implement a [`PerunServiceCallbackHandler`](https://github.com/perun-network/perun-wallet-spec/blob/0a01e2834a33bbe88a48582f6b75effc1b2527c0/src/proto/perun-wallet.proto#L114)(a bit like the _Sync_ in the above illustration) module to handle requests from other users (or technically, from _perun-channel-service_), to ask users if they accept opening, closing, or updating channels
 

<image width="300" src="https://github.com/nervosnetwork/neuron/assets/7511174/62df8139-deb1-455c-8cff-9df1ee2d2db9" />

**Comment by yanguoyu** [comment]
I have one question about the WCH:
Is the RPC service opened by Neuron a local service? If it's a local service, it can not be called by perun channel service. I guess creating a web socket to listen to Perun service's event is better. @ndzik

**Comment by ndzik** [comment]
Thank you for your response and the illusttration. The WCH serves a RPC Interface which can easily be done via a websocket connection.

It is correct that Neuron would in the best case start the channel service similar to the way it allows starting a default node IIRC.

I will take a deeper look at your architecture and get back to you later today 🙏

**Comment by yanguoyu** [comment]
Thank you for your response. Here is my understanding:`SimpleChannelServiceClient` is a service used to send requests to the `perunService`, and the `WalletServiceServer` responds the `perunService` and then notifies users. And I have no further questions.

**Comment by Keith-CY** [comment]
Hi @ndzik I'm slightly confused by the following statement

> Upon receiving a request on a specific port for Neuron it should be possible to tie that connection to an instance running the gRPC server. If you could confirm/deny, that would be nice.

I just had an inspection at https://github.com/perun-network/perun-wallet-wrapper/blob/main/src/services.ts#L161 and it returns a grpc server that connected to the channel service. Which detail should we check for it?

**Comment by ndzik** [comment]
> Hi @ndzik I'm slightly confused by the following statement
> 
> > Upon receiving a request on a specific port for Neuron it should be possible to tie that connection to an instance running the gRPC server. If you could confirm/deny, that would be nice.
> 
> I just had an inspection at https://github.com/perun-network/perun-wallet-wrapper/blob/main/src/services.ts#L161 and it returns a grpc server that connected to the channel service. Which detail should we check for it?

Hi @Keith-CY, as you can see in the referenced constructor it receives a `WalletBackend<MessageType>`. The question we have is how we could display notifications or prompts to the user of Neuron, i.e. do you already have some internal framework for displaying signing requests to the user or do we just come up with something of our own?

Furthermore, where would be the best place to create that `grpc` server in your applications data-flow. E.g. you might have some initializer module or similar which handles all of that.

Thanks for your help :muscle:

**Comment by Keith-CY** [comment]
> > Hi @ndzik I'm slightly confused by the following statement
> > > Upon receiving a request on a specific port for Neuron it should be possible to tie that connection to an instance running the gRPC server. If you could confirm/deny, that would be nice.
> > 
> > 
> > I just had an inspection at [perun-network/perun-wallet-wrapper@`main`/src/services.ts#L161](https://github.com/perun-network/perun-wallet-wrapper/blob/main/src/services.ts?rgh-link-date=2023-10-31T10%3A46%3A51Z#L161) and it returns a grpc server that connected to the channel service. Which detail should we check for it?
> 
> Hi @Keith-CY, as you can see in the referenced constructor it receives a `WalletBackend<MessageType>`. The question we have is how we could display notifications or prompts to the user of Neuron, i.e. do you already have some internal framework for displaying signing requests to the user or do we just come up with something of our own?
> 

Got it, currently there isn't a unified API to inform users about a coming transaction request.
Neuron has similar functions for reference:

1. import a transaction to sign: https://github.com/nervosnetwork/neuron/blob/develop/packages/neuron-wallet/src/controllers/api.ts#L743-L745
```js
    handle('sign-transaction-only', async (_, params) => {
      return this.#offlineSignController.signTransaction(params)
    })
```
It can be accessed by **Menu => Tools => Offline sign**

2. get sign request from dapp via wallet connect(on a feature branch): https://github.com/nervosnetwork/neuron/pull/2880/files#diff-6d296ae0608e078c2b37ecc6f77f4e596ca59022c02d09e635a161c66f39ad63R838-R840
```js
    handle('wc-approve-request', async (_, params) => {
      return this.#walletConnectController.approveRequest(params)
    })
```
It's demonstrated in the first video in PR(https://github.com/nervosnetwork/neuron/pull/2880) message

> Furthermore, where would be the best place to create that `grpc` server in your applications data-flow. E.g. you might have some initializer module or similar which handles all of that.

Any suggestion about the architecture @yanguoyu @homura

**Comment by ndzik** [comment]
Thank you for your input @Keith-CY !
