### ISSUE TITLE
What is a signed transaction in Neuron?

### ISSUE THREAD

**Issue by Sven-TBD** [nervosnetwork/neuron#2904]
In Neuron, there are two types of signatures. One is signing a message, typically used to prove ownership of an account. The other is signing a transaction, which is a step in the process of sending a transaction.
When you need to make a transfer, you typically need to sign a transaction.

**Comment by yanguoyu** [comment]
> como faço ta ter assinatura de uma transação ? seria diferente da senha ? ou é uma segurança a mais que coloco para sacar os ativos?

Hi, sign for a transaction that uses your private key to sign for the transaction. Then others can use the public key to verify that the sign transaction is correct. The password is used to get the private key, for an HD wallet, you should not tell anyone the mnemonic words and you should not tell anybody your password with the Keystore.

Here is the detailed doc about HD wallet. https://github.com/ethereumbook/ethereumbook/blob/develop/05wallets.asciidoc
