### ISSUE TITLE
How to generate multsig addresses and handle multisig transactions

### ISSUE THREAD

**Issue by Sven-TBD** [nervosnetwork/neuron#2907]
### Creating a Multisig address

1. You can create a multisig address in the menu/tools.
2. When creating a multisig address, you can specify the number of addresses to sign and the required number of valid signatures according to your needs.
3. Click "Next" and input the signature addresses as needed and confirm the necessary signature addresses in the total wallet according to your requirements.
4. Continue to complete the wallet creation.

### Handle a multisig transaction

- You can find the multisig address you want to use in the menu/tools/multi-signature address and copy it for receiving funds.
- Similarly, you can find the multi-signature address for your existing assets in the menu/tools/multisig address. After ensuring that the assets at this address meet the transfer conditions, you can use this address to initiate a transfer. At this point, you need to use the signing and exporting function, use an address belonging to the multisig address in the connected wallet to sign it, and pass the partially signed transaction file to the next user who needs to sign it. When the required number of signatures is reached, and all necessary addresses have signed, the transaction can be broadcast to the blockchain when the last signature address signs it.

**Comment by jordanmack** [comment]
I just created a 1/1 multisig address for testing. I tried to send and I can't figure out how to sign and broadcast. Documentation is needed.

**Comment by Keith-CY** [comment]
@Danie0918 Please check

**Comment by Keith-CY** [comment]
A link to the guide has been added by https://github.com/nervosnetwork/neuron/pull/3194 and will be delivered in the next release(scheduled on Aug. 12)

<img width="849" alt="image" src="https://github.com/user-attachments/assets/6f235451-4980-4f82-8a3f-f14ba87d300d">
