### ISSUE TITLE
Withdrawal from binance successful but could not see it in neuron

### ISSUE THREAD

**Issue by AydenPeh** [nervosnetwork/neuron#2920]
HI i did a withdrawal from binance . Binance  has reflected as successful . but i could not see the deposit in neuron

**Comment by Keith-CY** [comment]
> HI i did a withdrawal from binance . Binance has reflected as successful . but i could not see the deposit in neuron

Hi @AydenPeh, **debug information** of Neuron would help us check its status. The debug information could be exported by **Menu => Help => Export debug information** and can be uploaded by drag&drop it into the text field

**Comment by AydenPeh** [comment]
Thanks keith thanks for your reply. i export and show you . tqvm

**Comment by AydenPeh** [comment]
0x92b197aa1fba0f63633922c61c92375c9c074a93e85963554f5499fe1450d0e5
2023-09-25 18:58:17.270 +00:00 main INFO ckb_sync::types  header_map.memory_limit 600MB
2023-09-25 18:58:45.442 +00:00 main INFO ckb_bin::subcommand::run  ckb version: 0.110.0 (0679b11 2023-05-16)
2023-09-25 18:58:45.442 +00:00 main INFO ckb_launcher  Miner is disabled, edit ckb.toml to enable it
2023-09-25 18:58:47.441 +00:00 main INFO ckb_memory_tracker::process  track current process: unsupported
2023-09-25 18:58:47.442 +00:00 main INFO ckb_launcher  chain genesis hash: 0x92b197aa1fba0f63633922c61c92375c9c074a93e85963554f5499fe1450d0e5
2023-09-25 18:58:47.442 +00:00 main INFO ckb_sync::types  header_map.memory_limit 600MB
2023-09-25 18:59:15.510 +00:00 main INFO ckb_bin::subcommand::run  ckb version: 0.110.0 (0679b11 2023-05-16)
2023-09-25 18:59:15.510 +00:00 main INFO ckb_launcher  Miner is disabled, edit ckb.toml to enable it
2023-09-25 18:59:17.460 +00:00 main INFO ckb_memory_tracker::process  track current process: unsupported
2023-09-25 18:59:17.460 +00:00 main INFO ckb_launcher  chain genesis hash: 0x92b197aa1fba0f63633922c61c92375c9c074a93e85963554f5499fe1450d0e5
2023-09-25 18:59:17.460 +00:00 main INFO ckb_sync::types  header_map.memory_limit 600MB
2023-09-25 18:59:45.437 +00:00 main INFO ckb_bin::subcommand::run  ckb version: 0.110.0 (0679b11 2023-05-16)
2023-09-25 18:59:45.437 +00:00 main INFO ckb_launcher  Miner is disabled, edit ckb.toml to enable it
2023-09-25 18:59:47.217 +00:00 main INFO ckb_memory_tracker::process  track current process: unsupported
2023-09-25 18:59:47.218 +00:00 main INFO ckb_launcher  chain genesis hash: 0x92b197aa1fba0f63633922c61c92375c9c074a93e85963554f5499fe1450d0e5
2023-09-25 18:59:47.218 +00:00 main INFO ckb_sync::types  header_map.memory_limit 600MB

**Comment by AydenPeh** [comment]
not sure if this is what you need keith . i export the debug infomation. and in the bundled ckb are these strings of words

**Comment by Keith-CY** [comment]
> 0x92b197aa1fba0f63633922c61c92375c9c074a93e85963554f5499fe1450d0e5 2023-09-25 18:58:17.270 +00:00 main INFO ckb_sync::types header_map.memory_limit 600MB 2023-09-25 18:58:45.442 +00:00 main INFO ckb_bin::subcommand::run ckb version: 0.110.0 (0679b11 2023-05-16) 2023-09-25 18:58:45.442 +00:00 main INFO ckb_launcher Miner is disabled, edit ckb.toml to enable it 2023-09-25 18:58:47.441 +00:00 main INFO ckb_memory_tracker::process track current process: unsupported 2023-09-25 18:58:47.442 +00:00 main INFO ckb_launcher chain genesis hash: 0x92b197aa1fba0f63633922c61c92375c9c074a93e85963554f5499fe1450d0e5 2023-09-25 18:58:47.442 +00:00 main INFO ckb_sync::types header_map.memory_limit 600MB 2023-09-25 18:59:15.510 +00:00 main INFO ckb_bin::subcommand::run ckb version: 0.110.0 (0679b11 2023-05-16) 2023-09-25 18:59:15.510 +00:00 main INFO ckb_launcher Miner is disabled, edit ckb.toml to enable it 2023-09-25 18:59:17.460 +00:00 main INFO ckb_memory_tracker::process track current process: unsupported 2023-09-25 18:59:17.460 +00:00 main INFO ckb_launcher chain genesis hash: 0x92b197aa1fba0f63633922c61c92375c9c074a93e85963554f5499fe1450d0e5 2023-09-25 18:59:17.460 +00:00 main INFO ckb_sync::types header_map.memory_limit 600MB 2023-09-25 18:59:45.437 +00:00 main INFO ckb_bin::subcommand::run ckb version: 0.110.0 (0679b11 2023-05-16) 2023-09-25 18:59:45.437 +00:00 main INFO ckb_launcher Miner is disabled, edit ckb.toml to enable it 2023-09-25 18:59:47.217 +00:00 main INFO ckb_memory_tracker::process track current process: unsupported 2023-09-25 18:59:47.218 +00:00 main INFO ckb_launcher chain genesis hash: 0x92b197aa1fba0f63633922c61c92375c9c074a93e85963554f5499fe1450d0e5 2023-09-25 18:59:47.218 +00:00 main INFO ckb_sync::types header_map.memory_limit 600MB

The entire debug information should be a compressed file, and it can be uploaded directly, e.g. https://github.com/nervosnetwork/neuron/issues/2416#issue-1261618757

But the snippet matches a known issue and you may try https://github.com/nervosnetwork/neuron/issues/2699#issuecomment-1578195810 before uploading the debug information again

**Comment by AydenPeh** [comment]
i did 2699 comment 
<img width="647" alt="image" src="https://github.com/nervosnetwork/neuron/assets/145603440/1054906b-a39a-438c-87bd-d1116203a0c6">

**Comment by AydenPeh** [comment]
there is no add mangr to remove. 
neuron is synching 100% no issue 
Just that the deposit never arrived .

**Comment by Keith-CY** [comment]
> there is no add mangr to remove. neuron is synching 100% no issue Just that the deposit never arrived .

Then it should be another issue, please upload the entire debug information compressed file and I will check it

**Comment by AydenPeh** [comment]
<img width="426" alt="image" src="https://github.com/nervosnetwork/neuron/assets/145603440/9d0efc1b-bda7-47eb-9e57-4bfdb99e0dab">

**Comment by AydenPeh** [comment]
its 100 percent synced

**Comment by AydenPeh** [comment]
[neuron_debug_1699031045030.zip](https://github.com/nervosnetwork/neuron/files/13252890/neuron_debug_1699031045030.zip)

**Comment by AydenPeh** [comment]
keith , attached is the neuron debug file. is that what you need :

**Comment by AydenPeh** [comment]
do i need to attached the nervos explorer for you to see. Binance told me to check with receipient (neuron) on the nervos explorer

**Comment by Keith-CY** [comment]
> do i need to attached the nervos explorer for you to see. Binance told me to check with receipient (neuron) on the nervos explorer

It would expose your address, so you may send it to neuron@magickbase.com, better with the transaction hash so I can copy it instead of typing down manually(prone to type incorrectly)

**Comment by AydenPeh** [comment]
thanks keith appreciate your help on this. Cause it been couple of hours. i shall do just that i send to the above email address. tqvm

**Comment by AydenPeh** [comment]
hi keith i have send the nervos explorer and the accompanying txid to above email address. neuron@magicbase.com.
Please kindly help me take a look . thanks a lot

**Comment by Keith-CY** [comment]
> hi keith i have send the nervos explorer and the accompanying txid to above email address. [neuron@magicbase.com](mailto:neuron@magicbase.com). Please kindly help me take a look . thanks a lot

Got it, and I have confirmed (by code) that the withdrawal has been sent to your wallet. So the question is why Neuron didn't show it.

I will check the debug information, meanwhile you may try **Settings => data => Clear Cache** to flush data, **Fully rebuild index** can be **unchecked**

**Comment by AydenPeh** [comment]
yah thats very weird because for previous withdrawal from binance , all ended successfull . only this time it did not land .
thanks keith i shall do as above.  Settings => data => Clear Cache to flush data, Fully rebuild index can be unchecked

**Comment by AydenPeh** [comment]
i did as per above thanks keith waiting for the progress of the synching

**Comment by AydenPeh** [comment]
thanks keith . Settings => data => Clear Cache to flush data, Fully rebuild index can be unchecked
this works. yeah 谢谢你。 
Everything is in. tqvm for your time :)

Cheers

**Comment by AydenPeh** [comment]
Have a good weekend. Shall not disturb you further . sorry took up so much of your time.
Have a good night :)

**Comment by Keith-CY** [comment]
> Have a good weekend. Shall not disturb you further . sorry took up so much of your time. Have a good night :)

Glad to hear that and have a good weekend too :) We will go through this case again and try to strip it from Neuron.
