### ISSUE TITLE
Ledger device: UNKNOWN_ERROR (0x9405)

### ISSUE THREAD

**Issue by JaicoC** [nervosnetwork/neuron#2922]
Hello when I want to withdraw my CKB of nervos DAO staking on Neuron with my ledger I have the message "Ledger device: UNKNOWN_ERROR (0x9405)" My app on ledger is updated , how I can resolve the problem ?

<img width="829" alt="Snag_49e7d29" src="https://github.com/nervosnetwork/neuron/assets/150130999/bc6f5b95-bd61-4e7e-a1ef-45acaf7f6688">

**Comment by yanguoyu** [comment]
Hi, @JaicoC  Could you show your Nervos setting? Is it `Addresses for mainnet`, `Allow sign hash ` On, `Allow Contract data` on? If not, could you set these options' values as that and try again? After setting those options on, I send success. 
If it also sends failed. Debug information of the native wallet would help us check the status, it can be exported by Menu => Help => Export debug information.

**Comment by JaicoC** [comment]
Hi @yanguoyu  My settings was on Addresses for mainnet, Allow sign hash  On, Allow Contract data on, Ican send and receive tokens but the problment is just to withdraw , in this settings which network I have to use I was by default, on the default node
<img width="861" alt="Snag_1cfd91" src="https://github.com/nervosnetwork/neuron/assets/150130999/a0cb59ac-0ffc-4076-ac31-fd416703e7e1">

**Comment by yanguoyu** [comment]
Hi, in my opinion, the mainnet light client or the full mainnet node will work well. If you send success by ledger, but withdraw failed by ledger, could you upload the debug information for us to find out what happened? it can be exported by Menu => Help => Export debug information.

**Comment by JaicoC** [comment]
hi @yanguoyu please find attached the debug information
[bundled-ckb.log](https://github.com/nervosnetwork/neuron/files/13304874/bundled-ckb.log)
[bundled-ckb-lignt-client.log](https://github.com/nervosnetwork/neuron/files/13304875/bundled-ckb-lignt-client.log)
[hd_public_key_info.csv](https://github.com/nervosnetwork/neuron/files/13304876/hd_public_key_info.csv)
[main.log](https://github.com/nervosnetwork/neuron/files/13304877/main.log)
[status.json](https://github.com/nervosnetwork/neuron/files/13304878/status.json)

**Comment by yanguoyu** [comment]
Hi, @JaicoC I find the same issue as you. https://github.com/nervosnetwork/neuron/issues/2578.
After that, Nervos released a version 0.5.6. Do you try to update your Nervos version with ledger?

**Comment by JaicoC** [comment]
Hi @yanguoyu version 0.5.6 is the one that I have already... I'm stuck

**Comment by yanguoyu** [comment]
@Keith-CY Do you have any ideas? @FrederLu Could you check Neuron with your Ledger Nano X?

**Comment by FrederLu** [comment]
> @Keith-CY Do you have any ideas? @FrederLu Could you check Neuron with your Ledger Nano X?

I can use "Ledger Nano X" to perform withdrawal and deposit operations on Nerovs Dao normally.
The version is also 0.5.6.

**Comment by Keith-CY** [comment]
> @Keith-CY Do you have any ideas? @FrederLu Could you check Neuron with your Ledger Nano X?

Unfortunately, it's the only case not solved by ledger team https://github.com/Magickbase/neuron-public-issues/issues/103#issue-1579302655 and I will check with them again

**Comment by JaicoC** [comment]
Ok I'm still waiting for your news

**Comment by JaicoC** [comment]
Hi @Keith-CY @yanguoyu  I managed to solve the problem by creating a new small deposit, this allowed me to withdraw the old , deposit I don't know why

**Comment by Keith-CY** [comment]
> Hi @Keith-CY @yanguoyu I managed to solve the problem by creating a new small deposit, this allowed me to withdraw the old , deposit I don't know why

Hi @JaicoC glad to hear that.
Would you mind sharing us the withdrawal transaction so we can have some tests on the sample variants? If sure, you may send the **transaction hash** to neuron@magickbase.com so the transaction won't be public, thank you anyway.

**Comment by JaicoC** [comment]
Of course I will
