### ISSUE TITLE
[Synchronization] **Sync failed**

### ISSUE THREAD

**Issue by p2dak** [nervosnetwork/neuron#2929]
### Detail of the issue

I logged into Neuron for the first time in a while now and it says: Sync failed, please check network. 
However my network is fine and I'm up to date on the latest Neuron version. 
Any help is appreciated. 

[neuron_debug_1699603541615.zip](https://github.com/nervosnetwork/neuron/files/13317037/neuron_debug_1699603541615.zip)

**Comment by p2dak** [comment]
I also tried clearing the cache, which also didnt do anything

**Comment by p2dak** [comment]
I also saw #2699 and am not sure where and how to click the directory icon to open the ckb node data directory

**Comment by yanguoyu** [comment]
Hi, @p2dak ```The "path" argument must be of type string. Received undefined``` It's weird, could you show the `ckb.toml` file? We can open the ckb data path by clicking here. Then the `ckb.toml` file can be found in the opened directory.

<img width="950" alt="image" src="https://github.com/nervosnetwork/neuron/assets/12881040/ffba13a6-a6e5-4882-a14d-65d0f02d9bb5">

**Comment by p2dak** [comment]
> Hi, @p2dak `The "path" argument must be of type string. Received undefined` It's weird, could you show the `ckb.toml` file? We can open the ckb data path by clicking here. Then the `ckb.toml` file can be found in the opened directory.
> 
> <img alt="image" width="950" src="https://user-images.githubusercontent.com/12881040/282004492-ffba13a6-a6e5-4882-a14d-65d0f02d9bb5.png">

is it possible at all that the file ckb.toml doesnt exist? it didnt show up for me in the directory

**Comment by yanguoyu** [comment]
> is it possible at all that the file ckb.toml doesnt exist? it didnt show up for me in the directory

Hi, Does the Neuron has selected the internal node? If not, Could you try to switch the Internal Node?

<img width="1242" alt="image" src="https://github.com/nervosnetwork/neuron/assets/12881040/c0e332e5-8d58-4cc1-9ffb-92fb33f532ee">

**Comment by p2dak** [comment]
it was on default node, but i switched to internal node

**Comment by yanguoyu** [comment]
Could you show the setting file? The setting file path is `/Users/{username}/Library/Application Support/Neuron/settings.json`. Or stop the Neuron, delete the setting file then start Neuron again.

**Comment by p2dak** [comment]
<img width="668" alt="Screenshot 2023-11-10 at 11 28 43 AM" src="https://github.com/nervosnetwork/neuron/assets/95294235/26cbd144-012f-4c71-8203-5975a14d594b">

i cant seem to find the file path you want

**Comment by yanguoyu** [comment]
> i cant seem to find the file path you want

Maybe your system file is not the same as mine. Could you click here to open a directory, then jump to the parent directory? Then you will see the setting.json.
![image](https://github.com/nervosnetwork/neuron/assets/12881040/f3648b5a-3241-44ba-b5f1-b5a73c5708e1)

**Comment by p2dak** [comment]
<img width="669" alt="Screenshot 2023-11-10 at 11 42 42 AM" src="https://github.com/nervosnetwork/neuron/assets/95294235/16e229a6-ef35-4e88-b457-332c0117a845">

even here it doesnt show up for me , anything else i can do?

**Comment by yanguoyu** [comment]
> <img alt="Screenshot 2023-11-10 at 11 42 42 AM" width="669" src="https://user-images.githubusercontent.com/95294235/282035496-16e229a6-ef35-4e88-b457-332c0117a845.png">
> even here it doesnt show up for me , anything else i can do?

Here is my way to open the directory.

https://github.com/nervosnetwork/neuron/assets/12881040/9eb245e0-f822-4a4e-9680-2a8b135b6063

**Comment by yanguoyu** [comment]
@Keith-CY Do you have any suggestions? The user's directory seems different from mine.

**Comment by p2dak** [comment]
> > <img alt="Screenshot 2023-11-10 at 11 42 42 AM" width="669" src="https://user-images.githubusercontent.com/95294235/282035496-16e229a6-ef35-4e88-b457-332c0117a845.png">
> > even here it doesnt show up for me , anything else i can do?
> 
> Here is my way to open the directory.
> 
>  issue.mov

I tried some more over the weekend and could not find the settings.json file, I have to admit :/

**Comment by Keith-CY** [comment]
> <img alt="Screenshot 2023-11-10 at 11 28 43 AM" width="668" src="https://user-images.githubusercontent.com/95294235/282032405-26cbd144-012f-4c71-8203-5975a14d594b.png">
> i cant seem to find the file path you want

Please select **Users** in the left column first, it's where users' data are placed, the active one in the screenshot is for system level data.

Once **Users** is selected, there will be another **Library** folder in the middle column

**Comment by yanguoyu** [comment]
After the Neuron directory display. https://github.com/nervosnetwork/neuron/issues/2936 may help you.
