### ISSUE TITLE
[Synchronization] **brief description**

### ISSUE THREAD

**Issue by AZCChris** [nervosnetwork/neuron#2934]
### Detail of the issue

I see a balance from my wallet, but.. it will not sync.. have cleared cache, etc..  
[neuron_debug_1699908527130.zip](https://github.com/nervosnetwork/neuron/files/13341231/neuron_debug_1699908527130.zip)

**Comment by yanguoyu** [comment]
Hi, @AZCChris 
Could you show the ckb data setting? We can find it by clicking `Settings` and scroll to the end.

<img width="1255" alt="image" src="https://github.com/nervosnetwork/neuron/assets/12881040/5c0b3467-3732-4cf8-abce-bf9297a722eb">

And the local file can be found at `C:\Users\${username}\AppData\Roaming\Neuron\settings.json.`

**Comment by AZCChris** [comment]
[settings.json](https://github.com/nervosnetwork/neuron/files/13432460/settings.json)

**Comment by AZCChris** [comment]
![image](https://github.com/nervosnetwork/neuron/assets/150736304/1b4c3a35-c7ec-44e8-9541-ba389c6c9a25)

**Comment by yanguoyu** [comment]
> ![image](https://user-images.githubusercontent.com/150736304/284759810-1b4c3a35-c7ec-44e8-9541-ba389c6c9a25.png)

Hi, thank you for your reply. For some reason, we mistakenly migrated the settings.json. There is a simple way to repair it, quit the Neuron delete the `settings.json` then start the Neuron. The `CKB Node Config & Storage` path will shown.

**Comment by AZCChris** [comment]
So I did this - and now the money that it said I had is no longer there...  can you help me with this?

**Comment by yanguoyu** [comment]
> So I did this - and now the money that it said I had is no longer there... can you help me with this?

Could you clear cache with the default option? Click the settings, and scroll to the end. The `clear cache` button disappears.
![image](https://github.com/nervosnetwork/neuron/assets/12881040/88f41fd2-398f-4601-8b62-fbb3c0417281)
![image](https://github.com/nervosnetwork/neuron/assets/12881040/2b7ba868-79fe-42da-9c2b-090639aecde6)

If after that, the balance does not show. Could you please export the debugging information again?
