### ISSUE TITLE
bc1qndtll87c4u586cxmyyhszvmv63dwxa38a65yz3k3w09l3z69p9ys8fnyx9

### ISSUE THREAD

**Issue by 05385619789** [nervosnetwork/neuron#2938]
**Describe the bug** (Please enter details, the more detail the better)

**Debug info** (Please upload the debug info from `Help` - `Export Debug Information`)

**Screenshots** (If applicable, add screenshots to help explain your problem.)

**Comment by Keith-CY** [comment]
> **Describe the bug** (Please enter details, the more detail the better)
> 
> **Debug info** (Please upload the debug info from `Help` - `Export Debug Information`)
> 
> **Screenshots** (If applicable, add screenshots to help explain your problem.)

Hi @05385619789 

Could you append detailed info of this issue? Cuz `bc1qndtll87c4u586cxmyyhszvmv63dwxa38a65yz3k3w09l3z69p9ys8fnyx9` is hard to get its meaning
