### ISSUE TITLE
Cannot Deposit to Nervos DAO

### ISSUE THREAD

**Issue by robkay01** [nervosnetwork/neuron#2942]
**Describe the bug** (Please enter details, the more detail the better)
I get an error "TransactionFailedtoResolve: Resolve
 Failed"  when attempting to deposit into the Nervos DAO using the latest version of the Nervos Wallet. Screenshot of error message popup attached.
![Screenshot 2023-11-16 062233](https://github.com/nervosnetwork/neuron/assets/55883564/cae01b12-6403-4296-a2d4-05849cb3d793)

**Debug info** (Please upload the debug info from `Help` - `Export Debug Information`)
Attached.

**Screenshots** (If applicable, add screenshots to help explain your problem.)
Attached.
[neuron_debug_1700086606298.zip](https://github.com/nervosnetwork/neuron/files/13370180/neuron_debug_1700086606298.zip)

**Comment by yanguoyu** [comment]
Hi, @robkay01 
Could you try to clear the cache with the default option? Goto the settings page, and scroll to the end. The `clear cache` button disappears.

![image](https://github.com/nervosnetwork/neuron/assets/12881040/de134a84-cef7-4b4b-bd99-dfde5da67683)
![image](https://github.com/nervosnetwork/neuron/assets/12881040/c544c593-28c3-48de-ba98-65840d1bdc42)

**Comment by robkay01** [comment]
Hi @yanguoyu thanks for the quick reply! I've cleared the cache and now the transaction was able to process. Thanks again mate.
