### ISSUE TITLE
[Synchronization]

### ISSUE THREAD

**Issue by panmoria** [nervosnetwork/neuron#2950]
### Detail of the issue

Sync doesn't start at all, despite restart and different connections.

Cannot attach or insert the logs, how to proceed?

**Comment by panmoria** [comment]
[bundled-ckb.log](https://github.com/nervosnetwork/neuron/files/13432858/bundled-ckb.log)
[hd_public_key_info.csv](https://github.com/nervosnetwork/neuron/files/13432859/hd_public_key_info.csv)
[main.log](https://github.com/nervosnetwork/neuron/files/13432860/main.log)
[status.json](https://github.com/nervosnetwork/neuron/files/13432861/status.json)
[bundled-ckb-lignt-client.log](https://github.com/nervosnetwork/neuron/files/13432862/bundled-ckb-lignt-client.log)

**Comment by yanguoyu** [comment]
> [bundled-ckb.log](https://github.com/nervosnetwork/neuron/files/13432858/bundled-ckb.log) [hd_public_key_info.csv](https://github.com/nervosnetwork/neuron/files/13432859/hd_public_key_info.csv) [main.log](https://github.com/nervosnetwork/neuron/files/13432860/main.log) [status.json](https://github.com/nervosnetwork/neuron/files/13432861/status.json) [bundled-ckb-lignt-client.log](https://github.com/nervosnetwork/neuron/files/13432862/bundled-ckb-lignt-client.log)

Hi, @panmoria 
I guess you want to use Neuron with the internal node, select the `Internal Node` will be ok. With others networks excepted `Internal Node` and `Light Client` needs start an external ckb node.

**Comment by panmoria** [comment]
Oh gosh dummy me, you're right, but so far since the latest update worked with that other network. Thanks heaps!

**Comment by panmoria** [comment]
See? Now same thing happens again. Updated the wallet, and Internal Node doesn't sync, have to use the External Node. Bug?
<img width="1147" alt="Bildschirmfoto 2023-12-07 um 09 11 01" src="https://github.com/nervosnetwork/neuron/assets/91946128/bab9e656-fd87-4bc6-a375-3058f23b677a">
<img width="1141" alt="Bildschirmfoto 2023-12-07 um 09 11 18" src="https://github.com/nervosnetwork/neuron/assets/91946128/8c57c5e1-12f2-42e0-b380-4a2f60339458">

**Comment by Keith-CY** [comment]
> See? Now same thing happens again. Updated the wallet, and Internal Node doesn't sync, have to use the External Node. Bug? <img alt="Bildschirmfoto 2023-12-07 um 09 11 01" width="1147" src="https://private-user-images.githubusercontent.com/91946128/288603552-bab9e656-fd87-4bc6-a375-3058f23b677a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE5MjMwNzAsIm5iZiI6MTcwMTkyMjc3MCwicGF0aCI6Ii85MTk0NjEyOC8yODg2MDM1NTItYmFiOWU2NTYtZmQ4Ny00YmM2LWEzNzUtMzA1OGYyM2I2NzdhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA3VDA0MTkzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU4MmQ4MjAwMGZkNGM1ZThmZjA0MzdmMDlkMWY4YjFmMzYyMmZmNzJlOWJjNTA3MTgxNTJjNDM5MTRkN2IxOWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uw4jeUDWnJg8pg09eM_wfuwk9TOT-O14E07wxvyXCiY"> <img alt="Bildschirmfoto 2023-12-07 um 09 11 18" width="1141" src="https://private-user-images.githubusercontent.com/91946128/288603565-8c57c5e1-12f2-42e0-b380-4a2f60339458.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE5MjMwNzAsIm5iZiI6MTcwMTkyMjc3MCwicGF0aCI6Ii85MTk0NjEyOC8yODg2MDM1NjUtOGM1N2M1ZTEtMTJmMi00MmUwLWIzODAtNGEyZjYwMzM5NDU4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA3VDA0MTkzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE2NmFlZDVmOTE0Mjg2YzEzYTRiYTVmZmNiNzc5MDYxN2FlNDExMTZiNDU4OWE2YjNiMzhlZTdjMmIzYWY1Y2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KUkqpSeglE3rtMrzopMFNc5vOsZt8kP2wL4UVGmEUlM">

Hi @panmoria 
I found the address of the internal node was changed from `:8114` to `:8116`, which means the address of the internal node conflicted. It requires debug information to check why, but I have a quick fix for it
1. switch to the <kbd>internal node</kbd> option and close Neuron first;
2. open `monitor.app`, it's a pre-installed app on MacOS, check if there's a program named `ckb` running, if yes, quit it forcely;
3. open `terminal.app`, it's a pre-installed app, type **lsof -i :8114**, hit `Enter` to run it and make sure nothing is printed. If something printed, please copy&paste it in this issue.
4. Restart neuron and wait for a while

**Comment by Keith-CY** [comment]
> > See? Now same thing happens again. Updated the wallet, and Internal Node doesn't sync, have to use the External Node. Bug? <img alt="Bildschirmfoto 2023-12-07 um 09 11 01" width="1147" src="https://private-user-images.githubusercontent.com/91946128/288603552-bab9e656-fd87-4bc6-a375-3058f23b677a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE5MjMwNzAsIm5iZiI6MTcwMTkyMjc3MCwicGF0aCI6Ii85MTk0NjEyOC8yODg2MDM1NTItYmFiOWU2NTYtZmQ4Ny00YmM2LWEzNzUtMzA1OGYyM2I2NzdhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA3VDA0MTkzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU4MmQ4MjAwMGZkNGM1ZThmZjA0MzdmMDlkMWY4YjFmMzYyMmZmNzJlOWJjNTA3MTgxNTJjNDM5MTRkN2IxOWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uw4jeUDWnJg8pg09eM_wfuwk9TOT-O14E07wxvyXCiY"> <img alt="Bildschirmfoto 2023-12-07 um 09 11 18" width="1141" src="https://private-user-images.githubusercontent.com/91946128/288603565-8c57c5e1-12f2-42e0-b380-4a2f60339458.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE5MjMwNzAsIm5iZiI6MTcwMTkyMjc3MCwicGF0aCI6Ii85MTk0NjEyOC8yODg2MDM1NjUtOGM1N2M1ZTEtMTJmMi00MmUwLWIzODAtNGEyZjYwMzM5NDU4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA3VDA0MTkzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE2NmFlZDVmOTE0Mjg2YzEzYTRiYTVmZmNiNzc5MDYxN2FlNDExMTZiNDU4OWE2YjNiMzhlZTdjMmIzYWY1Y2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KUkqpSeglE3rtMrzopMFNc5vOsZt8kP2wL4UVGmEUlM">
> 
> Hi @panmoria I found the address of the internal node was changed from `:8114` to `:8116`, which means the address of the internal node conflicted. It requires debug information to check why, but I have a quick fix for it
> 
> 1. switch to the internal node option and close Neuron first;
> 2. open `monitor.app`, it's a pre-installed app on MacOS, check if there's a program named `ckb` running, if yes, quit it forcely;
> 3. open `terminal.app`, it's a pre-installed app, type **lsof -i :8114**, hit `Enter` to run it and make sure nothing is printed. If something printed, please copy&paste it in this issue.
> 4. Restart neuron and wait for a while

I'd like to add one more check in step 1: after switching to the <kbd>internal node</kbd>, please check if **Settings => Data => CKB Node Config & Storage** is blank. If yes, please set it where you want the blockchain data stored. The default path is `/Users/{Username}/Library/Application Support/Neuron/chains/mainnet`(notice the Username should be replaced with yours)

**Comment by panmoria** [comment]
Did as instructed. Address of the internal node changed to :8114 but still no syncing. When I changed back to the external node, the internal node address changes back to :8116

Attached two screenshots and the debug file
<img width="1149" alt="Bildschirmfoto 2023-12-07 um 14 30 33" src="https://github.com/nervosnetwork/neuron/assets/91946128/15187342-6e6f-4782-9046-dcd4b4bbfea3">
<img width="1140" alt="Bildschirmfoto 2023-12-07 um 14 32 56" src="https://github.com/nervosnetwork/neuron/assets/91946128/771beb20-6f49-4aa0-9076-1252eff109bc">
[neuron_debug_1701934386013.zip](https://github.com/nervosnetwork/neuron/files/13596918/neuron_debug_1701934386013.zip)

**Comment by panmoria** [comment]
And this is printed in Terminal app after the command lsof -i :8114:

COMMAND   PID      USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
ckb     53929 f00001099  486u  IPv4 0x2b79931969f4c7a3      0t0  TCP 192.168.1.247:58235->20.151.143.237:8114 (ESTABLISHED)
ckb     53929 f00001099  570u  IPv4 0x2b799319698da7db      0t0  TCP 192.168.1.247:58230->161.107.236.35.bc.googleusercontent.com:8114 (ESTABLISHED)
ckb     53929 f00001099  571u  IPv4 0x2b799319698447a3      0t0  TCP 192.168.1.247:58232->ec2-13-37-172-80.eu-west-3.compute.amazonaws.com:8114 (ESTABLISHED)
ckb     53929 f00001099  598u  IPv4 0x2b79931969f167db      0t0  TCP 192.168.1.247:58237->40.115.75.216:8114 (ESTABLISHED)
ckb     53929 f00001099  599u  IPv4 0x2b7993196a2cc7a3      0t0  TCP 192.168.1.247:58239->ec2-13-234-144-148.ap-south-1.compute.amazonaws.com:8114 (ESTABLISHED)
ckb     53929 f00001099  666u  IPv4 0x2b79931969aebd0b      0t0  TCP 192.168.1.247:58238->143.120.64.34.bc.googleusercontent.com:8114 (ESTABLISHED)
ckb     53929 f00001099  687u  IPv4 0x2b79931969a7a7db      0t0  TCP 192.168.1.247:58240->ec2-52-59-155-249.eu-central-1.compute.amazonaws.com:8114 (ESTABLISHED)
ckb     53929 f00001099  695u  IPv4 0x2b79931969c647a3      0t0  TCP 192.168.1.247:58241->23.101.191.12:8114 (ESTABLISHED)
ckb     53929 f00001099 1239u  IPv4 0x2b79931969c6fd0b      0t0  TCP localhost:8114 (LISTEN)
f00001099@n-aml00073 ~ %

**Comment by panmoria** [comment]
Hmm... node path seems correct, but this is the message in Terminal, and Neuron Internal Node still doesn't work:

f00001099@n-aml00073 ~ % rm /Users/f00001099/Library/Application Support/Neuron/chains/mainnet/data/db/LOCK
rm: /Users/f00001099/Library/Application: No such file or directory
rm: Support/Neuron/chains/mainnet/data/db/LOCK: No such file or directory
f00001099@n-aml00073 ~ % 

Only having the issue since the last two Neuron updates. What to do?

**Comment by Keith-CY** [comment]
> Removed the LOCK file, now also the External Node doesn't sync anymore!!
> 
> Syncing stopped the moment I removed the file LOCK.
> 
> Please suggest a way that works.
> 
> <img alt="Bildschirmfoto 2023-12-07 um 16 15 41" width="400" src="https://private-user-images.githubusercontent.com/91946128/288703335-bddd0230-731c-4053-acfd-3994adb44490.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE5NDEwODksIm5iZiI6MTcwMTk0MDc4OSwicGF0aCI6Ii85MTk0NjEyOC8yODg3MDMzMzUtYmRkZDAyMzAtNzMxYy00MDUzLWFjZmQtMzk5NGFkYjQ0NDkwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA3VDA5MTk0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBjNWY2NTQzNDFiNThkNWJlYzk3MzgyODI1OGZkZGZlZGM3OTI5YmRjODU5ZmQ5NTc3N2E1OGU3YmIyMzIxMTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Warz0Kj6rf7NV9sExw1wpD3wyYFP1J23A1dnJGyQ14g">

Could you join the discord at https://discord.gg/N9nZ3JE2Gg and add `chen.yu` in the server so we can provide real-time support
