### ISSUE TITLE
Issue on UI withdrawing from NervosDao

### ISSUE THREAD

**Issue by nam-dam** [nervosnetwork/neuron#2954]
**Describe the bug** (Please enter details, the more detail the better)
click withdraw fund from NervosDao

1. Wrong typos from **Withdraw** to **Withdrawn**
2. Incorrect **{days}** in the placeholder info 

**Debug info** (Please upload the debug info from `Help` - `Export Debug Information`)
No debug error, just UI error

**Screenshots** (If applicable, add screenshots to help explain your problem.)

![image](https://github.com/nervosnetwork/neuron/assets/9479593/f0cd0876-6f33-42b8-948e-57f8b834bcea)

**Comment by devchenyan** [comment]
fixed: https://github.com/nervosnetwork/neuron/pull/2952
