### ISSUE TITLE
Can't import my wallet with seed phrase

### ISSUE THREAD

**Issue by dkralj** [nervosnetwork/neuron#2960]
### Detail of the issue

Every time I try to import my wallet with my seed phrase, new wallet constantly gets created and it doesn't sync with my wallet. How to fix this?

**Comment by yanguoyu** [comment]
Hi,
Debug information of the native wallet would help us check why the neuron doesn't sync with your wallet, it can be exported by Menu => Help => Export debug information.

**Comment by dkralj** [comment]
Hey, it was my mistake, asked the same question on reddit and one user suggested to fully sync blockchain with the app and that worked. So you can close the issue. Thanks.
