### ISSUE TITLE
I had a two device both had neuron installed until last month I see storage of qty good but both wallet fully synchronized but not showing qty as before even I try full node and light both since 5 days last month I stored that's qty not showing in neuron ,

### ISSUE THREAD

**Issue by nick3666** [nervosnetwork/neuron#2984]

**Comment by yanguoyu** [comment]
Hi, @nick3666 
Could you try to clear the cache with the default option? Click the settings, and scroll to the end. The `clear cache` button disappears. If after clearing the cache, it does not show your balance. 
Debug information of the native wallet would help us check why the balance does not show, it can be exported by Menu => Help => Export debug information.

**Comment by Drazzerss** [comment]
Hey guys i have the exact same issue, i deleted my wallet and put it back but again it's like i have no CKB and no history at all, IDK what to do. It was working perfectly last month when i transfered some CKB to stack.
Please help me ....
