### ISSUE TITLE
[Bug Report] **CKB Balance not displayed** 

### ISSUE THREAD

**Issue by Cia000** [nervosnetwork/neuron#3008]
### Topic Type

Cannot Synchronize

### Detail of the issue

Neuron Wallet will not display any data related to my two wallets.

- CKB Balance
- History 
- Nervous DAO 

[neuron_debug_1704178806531.zip](https://github.com/nervosnetwork/neuron/files/13807902/neuron_debug_1704178806531.zip)

**Comment by Keith-CY** [comment]
Hi @Cia000 

I can see that the internal node has been fully synced, and your assets are visible on CKB Explorer. So the data should be fixed by **Settings => Data => Cache => Clear Cache** with **Fully rebuild index** in the dialog **unchecked**.

Before flusing the cache, we'd better check if the **Settings => Data => CKB Node Config & Storage** is set(in rare case it will be cleared). And I will append a detailed solution if it's empty.

**Comment by Cia000** [comment]
In **Settings** => **Data** => **CKB Node Config & Storage** it displays:

C:\Users\NAME\AppData\Roaming\Neuron\chains\main....

But when I click on **Set Path** is blank?

**Comment by Cia000** [comment]
What is the full path that needs to be set?

C:\Users\NAME\AppData\Roaming\Neuron\chains\mainnet\data?????

**Comment by Keith-CY** [comment]
> C:\Users\NAME\AppData\Roaming\Neuron\chains\mainnet\

**C:\Users\NAME\AppData\Roaming\Neuron\chains\mainnet\** is correct

**Comment by Cia000** [comment]
What are my next steps?

![CKB Storage](https://github.com/nervosnetwork/neuron/assets/155423251/69abe87f-3abf-47ec-97ef-e573a8c3d788)

**Comment by yanguoyu** [comment]
> What are my next steps?
> 
> ![CKB Storage](https://private-user-images.githubusercontent.com/155423251/293650252-69abe87f-3abf-47ec-97ef-e573a8c3d788.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQxODM1MzUsIm5iZiI6MTcwNDE4MzIzNSwicGF0aCI6Ii8xNTU0MjMyNTEvMjkzNjUwMjUyLTY5YWJlODdmLTNhYmYtNDdlYy05N2VmLWU1NzNhOGMzZDc4OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwMlQwODEzNTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MWExMDIyNDAyNGRhMjdjOWM2MDU2ZjUyZDQyYTU4MjdjY2I4YmI0ODA5Y2RlNTMzZmM4NGYyOGExY2Y5MTE2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.l0352vNb_i1BrsqT7D0Z1tnR9EP3NfP2mF7fwwP362c)

Hi,
If the config path is `C:\Users\NAME\AppData\Roaming\Neuron\chains\mainnet`, please do not change it.
It's may better to click `Settings -> Clear Cache` with the default option to clear the local cache. After the local data rebuild, maybe your balance will show again.
![image](https://github.com/nervosnetwork/neuron/assets/12881040/780e299f-35e7-4aec-a65c-af6cfe0d30a2)
![image](https://github.com/nervosnetwork/neuron/assets/12881040/52e5ab07-7edc-4183-9551-1b323c01a66b)

**Comment by Cia000** [comment]
Thank you, @yanguoyu 🙏 It worked flawlessly. Everything is working properly now, thanks again.
