### ISSUE TITLE
[Feature Request] Asking chain configuration before data synchronization at first run.

### ISSUE THREAD

**Issue by yangby-cryptape** [nervosnetwork/neuron#3015]
### Topic Type

Other

### Detail of the issue

When users start Neuron at first run, it starts to sync directly.

But, consider the current size of the chain data, Neuron should ask users before data synchronization and warn them about that size of chain data.

At least, Neuron should check if the disk where Neuron put chain data in, should be larger than 1.2 times of the current size of chain data (at the Neuron release date).

If a new user doesn't know about the size of chain data, and his/her disk becomes full after 80% chain data synced, he/she will feel terrible.
A worse case, their normal data are broken since the disk is full.

**Comment by yanguoyu** [comment]
Thank you for your suggestion. [Here](https://github.com/Magickbase/neuron-public-issues/issues/255) is an issue that may be the same. And https://github.com/nervosnetwork/neuron/pull/3005 is the PR.

**Comment by yangby-cryptape** [comment]
Also, please give a tip when a user changes the network.
Don't delete caches directly.

I try selecting light client, then select full node back, I have to re-sync all data again.

**Comment by yanguoyu** [comment]
> Also, please give a tip when a user changes the network. Don't delete caches directly.
> 
> I try selecting light client, then select full node back, I have to re-sync all data again.
> 
> 4 GiB caches are lost without asking.

Hi, `4 GiB caches` mean ckb node cache or Neuron local cache? If you mean the Neuron local cache, after https://github.com/nervosnetwork/neuron/pull/2915 merged, the full node local cache will save in a different location with the light client node. Then switching network type will not clean the old local cache.

**Comment by yangby-cryptape** [comment]
> Hi, `4 GiB caches` mean ckb node cache or Neuron local cache? ...

Awesome works! Exactly what I want!
