### ISSUE TITLE
[Bug Report] **Please describe the bug shortly**

### ISSUE THREAD

**Issue by SZhaoNan** [nervosnetwork/neuron#3028]
### Topic Type

Other

### Detail of the issue

在Neuron DAO 中发起提取->点击下一步 后  弹窗消失 没反应了  没有出现输入密码弹窗

**Comment by Keith-CY** [comment]
Hi @SZhaoNan 是否方便上传调试信息文件, 这样我们可以看到是否有程序错误被记录下来, Debug Information 文件可以通过 `菜单 => 帮助 => 导出调试信息` 获得, 并通过拖拽到文本框上传

**Comment by yanguoyu** [comment]
Hi, If you don't have enough balance to pay for the withdrawn transaction, it should be the same as https://github.com/Magickbase/neuron-public-issues/issues/350. It will be fixed in the next version.

**Comment by SZhaoNan** [comment]
好的 谢谢



At 2024-01-24 11:32:50, "严国宇" ***@***.***> wrote:

Hi, If you don't have enough balance to pay for the withdrawn transaction, it should be the same as Magickbase/neuron-public-issues#350. It will be fixed in the next version.
