### ISSUE TITLE
Sync Failed check network

### ISSUE THREAD

**Issue by Gxdzilla87** [nervosnetwork/neuron#3034]
Hello

I had to turn off my power supply to my ckb miner for 2 days and once I had turned it back on the neuron wallet failed to sync. It says "sync failed, check network". I tried following the guide but nothing has worked.

**Comment by yanguoyu** [comment]
Hi, Debug information of the native wallet would help us check what happened, it can be exported by Menu => Help => Export debug information.

**Comment by Gxdzilla87** [comment]
> Hi, @Gxdzilla87 Debug information of the native wallet would help us check what happened, it can be exported by Menu => Help => Export debug information.

Sounds good.
 Under the (bundled ckb) folder it says: The "path" argument must be of type string. Received undefined
Under (main) shows: saved sync block with the #
under (renderer) it shows: stop sync block queue
[neuron_debug_1707175932164.zip]

(https://github.com/nervosnetwork/neuron/files/14173765/neuron_debug_1707175932164.zip)

**Comment by yanguoyu** [comment]
> > Hi, @Gxdzilla87 Debug information of the native wallet would help us check what happened, it can be exported by Menu => Help => Export debug information.
> 
> Sounds good. Under the (bundled ckb) folder it says: The "path" argument must be of type string. Received undefined Under (main) shows: saved sync block with the # under (renderer) it shows: stop sync block queue [neuron_debug_1707175932164.zip]
> 
> (https://github.com/nervosnetwork/neuron/files/14173765/neuron_debug_1707175932164.zip)

I got that, For some reason, the network configuration is not the same as before. Could you try to switch to the Internal Node?
Go to the settings page, and switch to the Internal Node. The internal node means Neuron will start an internal ckb node.

If we select a node that is not internal, we need to start an external ckb node.

![image](https://github.com/nervosnetwork/neuron/assets/12881040/f1b3accf-c108-4a6d-a3d5-5b3eee125797)

**Comment by Gxdzilla87** [comment]
Okay. I'm trying that right now. How log should it usually take to connect? It's been about 10 minutes so far. Still says "connecting"

**Comment by yanguoyu** [comment]
> Okay. I'm trying that right now. How log should it usually take to connect? It's been about 10 minutes so far. Still says "connecting"

It may caused by another problem. Could you download and upload the Debug Information again?

**Comment by Gxdzilla87** [comment]
yes no problem 
[neuron_debug_1707186438541.zip](https://github.com/nervosnetwork/neuron/files/14173965/neuron_debug_1707186438541.zip)

**Comment by yanguoyu** [comment]
> yes no problem [neuron_debug_1707186438541.zip](https://github.com/nervosnetwork/neuron/files/14173965/neuron_debug_1707186438541.zip)

Hi, from the log the Neuron should pop up a migrate dialog to migrate the old ckb data. But I don't know whether the migrate dialog shows.

If the migrate dialog shows, click ok to migrate the old ckb data. If the migrate dialog is not shown, maybe you need to migrate the old ckb data manually.
https://github.com/nervosnetwork/neuron/issues/2868#issue-1938970527 will help you how to migrate the old ckb data manually.

**Comment by Gxdzilla87** [comment]
Okay, it does show. I selected migrate

**Comment by Gxdzilla87** [comment]
> > yes no problem [neuron_debug_1707186438541.zip](https://github.com/nervosnetwork/neuron/files/14173965/neuron_debug_1707186438541.zip)
> 
> Hi, from the log the Neuron should pop up a migrate dialog to migrate the old ckb data. But I don't know whether the migrate dialog shows.
> 
> If the migrate dialog shows, click ok to migrate the old ckb data. If the migrate dialog is not shown, maybe you need to migrate the old ckb data manually. [#2868 (comment)](https://github.com/nervosnetwork/neuron/issues/2868#issue-1938970527) will help you how to migrate the old ckb data manually.

do you want me to send the debug info again? It still just says migrating

**Comment by yanguoyu** [comment]
> > > yes no problem [neuron_debug_1707186438541.zip](https://github.com/nervosnetwork/neuron/files/14173965/neuron_debug_1707186438541.zip)
> > 
> > 
> > Hi, from the log the Neuron should pop up a migrate dialog to migrate the old ckb data. But I don't know whether the migrate dialog shows.
> > If the migrate dialog shows, click ok to migrate the old ckb data. If the migrate dialog is not shown, maybe you need to migrate the old ckb data manually. [#2868 (comment)](https://github.com/nervosnetwork/neuron/issues/2868#issue-1938970527) will help you how to migrate the old ckb data manually.
> 
> do you want me to send the debug info again? It still just says migrating

Hi, after the `migrating` end, it will start sync again. Usually, the migration process will cost about 20~30 minutes.
If Neuron is stuck at migrating for a long time, it's better to send the debug info again.

**Comment by Gxdzilla87** [comment]
okay, it's almost done. Around 95% I can now see my wallet amount but the deposit is from November. I'll wait until it's 100% to see if all of the deposits have been updated

**Comment by Gxdzilla87** [comment]
the sync seems to be stuck around 99% and most of my deposits have been updated but i'm still missing some for jan and feb this year. Should i try switching back to the default mainnet node? I'll attach the debug info
[neuron_debug_1707359448930.zip](https://github.com/nervosnetwork/neuron/files/14203640/neuron_debug_1707359448930.zip)

**Comment by yanguoyu** [comment]
> the sync seems to be stuck around 99% and most of my deposits have been updated but i'm still missing some for jan and feb this year. Should i try switching back to the default mainnet node? I'll attach the debug info [neuron_debug_1707359448930.zip](https://github.com/nervosnetwork/neuron/files/14203640/neuron_debug_1707359448930.zip)

```
2024-02-08 02:30:54.609 +00:00 GlobalRt-9 INFO ckb_indexer::service  append 11991319, Byte32(0xdc1be3a266e2b94854a620739c5c40afb72c15a625abf7bb528495b449d2b0bf)
2024-02-08 02:30:55.068 +00:00 GlobalRt-9 INFO ckb_indexer::service  append 11991320, Byte32(0xabe24aee914bc3c3e2e153c34fef69cc8eb52f2f9a655a39eb036e578ed56744)
```
Hi, from the log, the ckb node reached 11991320 at 2024-02-08 02:30:55.068 +00:00, and I haven't found any unexpected logs. Maybe you'd better wait for a while.

**Comment by Gxdzilla87** [comment]
the mainnet internal node is now 100% synced and the balances are up to date. Should I switch back to the mainnet default node?

**Comment by yanguoyu** [comment]
> the mainnet internal node is now 100% synced and the balances are up to date. Should I switch back to the mainnet default node?

If you will not start an external ckb node by yourself, it's better to select the `Internal Node`. The `Internal Node` is the mainnet with the Neuron internal ckb node. `Light Client` is [a light client node](https://github.com/nervosnetwork/ckb-light-client) in Neuron.

**Comment by Keith-CY** [comment]
Addition to https://github.com/nervosnetwork/neuron/issues/3034#issuecomment-1935312667

You can keep using the `internal node` because it was previously the `default node`.

It's been renamed since Neuron@v0.110.3(https://github.com/nervosnetwork/neuron/releases/tag/v0.110.3)

> ◆ **default node** has been renamed to **Internal Node** for clarity.

The `default node` option was expected to be removed but in your case it wasn't, for a known reason we've fixed.

**Comment by Gxdzilla87** [comment]
okay thank you very much!
