### ISSUE TITLE
[Synchronization] **brief description**

### ISSUE THREAD

**Issue by Rudegyalcrypto** [nervosnetwork/neuron#3042]
System has been syncing for 4 days, it's only on 8,753,602. Task manager only shows ckb not ckb indexer. Please assist.

**Comment by yanguoyu** [comment]
> System has been syncing for 4 days, it's only on 8,753,602. Task manager only shows ckb not ckb indexer. Please assist.

Hi, after 106 versions, the `ckb-indexer` has merged into the `ckb`, so the `ckb-indexer` will not show in the task manager.
If the sync process is stuck, the Debug information of the native wallet would help us check what happened, it can be exported by Menu => Help => Export debug information.

**Comment by Simon-Sturges** [comment]
Hi, My synchronization was stuck at 99% despite rebooting. I uploaded the latest version and migrated as suggested. After a day 'importing' i decided to clear cache and I cannot see any of my CKB. History blank, Nervos DAO blank and on the latest version i cannot see if it is synching. I have attached my debug zip file.

Grateful for any assistance you can give
S
[neuron_debug_1709057683610.zip](https://github.com/nervosnetwork/neuron/files/14424180/neuron_debug_1709057683610.zip)

**Comment by yanguoyu** [comment]
> Hi, My synchronization was stuck at 99% despite rebooting. I uploaded the latest version and migrated as suggested. After a day 'importing' i decided to clear cache and I cannot see any of my CKB. History blank, Nervos DAO blank and on the latest version i cannot see if it is synching. I have attached my debug zip file.
> 
> Grateful for any assistance you can give S [neuron_debug_1709057683610.zip](https://github.com/nervosnetwork/neuron/files/14424180/neuron_debug_1709057683610.zip)

@Simon-Sturges 
Hi, from the log, I get that the migration has not finished yet. You can see the migrate status from the right-top of the Neuron.
After the migration is finished, Neuron will start syncing again.

**Comment by yanguoyu** [comment]
> Thank you, however 48 hours later it is still migrating..

Hi, could you refer to https://github.com/nervosnetwork/neuron/issues/2868#issue-1938970527 for manual migration?

**Comment by Simon-Sturges** [comment]
Hi, have tried this, but it hasn't worked..

**Comment by yanguoyu** [comment]
> Hi, have tried this, but it hasn't worked..

Hi, Do you manually migrate successfully?
If not, what problem happens during manual migration?
If yes, after the successful migration, could you open the Neuron again, and then download and upload the Debug information again?

**Comment by Simon-Sturges** [comment]
Morning, I think it may have migrated as the Top RHS now says syncing 0.00% and the blocks are rising but still 0/12000000 looking for assumed valid target.
Please see attached debug information
[neuron_debug_1709463767791.zip](https://github.com/nervosnetwork/neuron/files/14472646/neuron_debug_1709463767791.zip)

**Comment by yanguoyu** [comment]
Hi, @Simon-Sturges ,

This is the log from `bundled-ckb.log`
> 2024-03-03 10:18:47.442 +00:00 BlockDownload INFO ckb_sync::synchronizer  best known header number: 3760000, hash: Byte32(0x25e28230faa9764e060b3e2632396c1679b6ad9b3edb7c12b45ebc115ea8ea98), can't find assume valid target temporarily, hash: Byte32(0x1d46fe5bb62d19a004eadd7ba40564c45620905ab260d8a546a9e4b9d7cc0f85) please wait

It means the Neuron is in the early stage of synchronization and the first number in xxx/xxx will increase once the Neuron finds an assumed valid target(when the second number is greater than 11,616,377). This process will speed up the full neuron sync.

**Comment by Simon-Sturges** [comment]
Hi yanguoyu,

So it got to 0.017% and now TRHS states 'sync is slow'.
Been running for 7 days now. Assume that I can't turn off the laptop?
[Nervos screenshot 09032024.docx](https://github.com/nervosnetwork/neuron/files/14546353/Nervos.screenshot.09032024.docx)

Presumably I just have to keep it running? Another week or so?

**Comment by yanguoyu** [comment]
> Hi yanguoyu,
> 
> So it got to 0.017% and now TRHS states 'sync is slow'. Been running for 7 days now. Assume that I can't turn off the laptop? [Nervos screenshot 09032024.docx](https://github.com/nervosnetwork/neuron/files/14546353/Nervos.screenshot.09032024.docx)
> 
> Presumably I just have to keep it running? Another week or so?

Hi, when the computer screen locks, the Neuron may stop syncing, so you'd better keep the screen awake when the Neuron syncing. The full node ckb node needs about 2~3 days to finish the sync, and it needs over 50GB of space disk. And it also depends on the computer's performance and network status.

**Comment by Simon-Sturges** [comment]
Hi, been syncing for 2 weeks now. TRH side back to saying 'sync is slow' but not showing blocks synced. Last seen blocks synced only 320,000. System somewhat old but have over 50GB space disk,
I see there is v0.114.2 NEW in settings. Do I download and go through whole migration process again?
Any further recommendations?

**Comment by yanguoyu** [comment]
> Hi, been syncing for 2 weeks now. TRH side back to saying 'sync is slow' but not showing blocks synced. Last seen blocks synced only 320,000. System somewhat old but have over 50GB space disk, I see there is v0.114.2 NEW in settings. Do I download and go through whole migration process again? Any further recommendations?

Update to the latest will be better. If the Neuron still shows `sync is slow`, could you upload the Debug Information again?
Additionally, the Neuron includes a light client node. The light client node will sync faster than the full node and needs less disk space because it only subscribes to your address. It can set the start block number to speed up the sync process.
The start block number should be set to lower than the first block number of your wallet.
If you want to use the light client click setting and scroll to the Network setting, then choose Light Client, which will switch to the Light Client.
![image](https://github.com/nervosnetwork/neuron/assets/12881040/fec290ab-07af-4795-b7b8-c8b1f99f7d55)

**Comment by Simon-Sturges** [comment]
Thank you for your assistance Yanguoyu,
I set my start block at 2,000,000 on lite client node and saw my first deposit within minutes. All now fully synced.
