### ISSUE TITLE
transferi ckb pra neuron wallet antes de concluir a sincronizacao

### ISSUE THREAD

**Issue by vicentinigui** [nervosnetwork/neuron#3049]
### Topic Type

Cannot Synchronize

### Detail of the issue

transferi ckb da corretora para a carteria neuron wallet antes de concluir a sincronização. Perdi tudo ou da pra recuperar ela quando terminar a sincronização ?

**Comment by yanguoyu** [comment]
Hi, after syncing to 100%, you will see your CKBs. If the sync is stuck, the Debug information of the native wallet would help us check what happened, it can be exported by Menu => Help => Export debug information.
