### ISSUE TITLE
[Bug Report] **Please describe the bug shortly**

### ISSUE THREAD

**Issue by korbendallas66** [nervosnetwork/neuron#3051]
### Topic Type

Other

### Detail of the issue

I sent CKB from my Binance account and still not receive them synchronisation is at 58% so far and it has been almost 24 hours.
[neuron_debug_1709310985534.zip](https://github.com/nervosnetwork/neuron/files/14463576/neuron_debug_1709310985534.zip)

<img width="1364" alt="Screenshot 2024-03-01 at 17 34 12" src="https://github.com/nervosnetwork/neuron/assets/161865968/0dbcaa7b-8168-41dc-b7d2-3e53cd086e25">

**Comment by yanguoyu** [comment]
Hi, @korbendallas66 

Hi, Neuron includes a full ckb node and a light client node.
The full node ckb node needs more time and disk space because it is a full ckb node that includes all of the chain data, it needs about 2~3 days to finish the sync, and it needs over 50GB space disk.
The light client node will sync faster than the full node and needs less disk space because it only subscribes to your address. It can set the start block number to speed up the sync process.

If you want to use the light client click `setting` and scroll to the Network setting, then choose Light Client, which will switch to the Light Client.

![image](https://github.com/nervosnetwork/neuron/assets/12881040/efb21a41-f5a9-4368-862f-26b336dbdf68)

**Comment by korbendallas66** [comment]
Hello

I was 99.9 % and now the syncing percentage is going down in reverse.

<img width="1360" alt="Screenshot 2024-03-02 at 13 50 26" src="https://github.com/nervosnetwork/neuron/assets/161865968/0b060c46-5d00-4aee-a81f-869efd9cf58d">
<img width="1363" alt="Screenshot 2024-03-02 at 13 50 03" src="https://github.com/nervosnetwork/neuron/assets/161865968/4f37249a-5d99-4e8d-854e-b6adfc67b147">

**Comment by yanguoyu** [comment]
> Hello
> 
> I was 99.9 % and now the syncing percentage is going down in reverse.
> 
> <img alt="Screenshot 2024-03-02 at 13 50 26" width="1360" src="https://private-user-images.githubusercontent.com/161865968/309474247-0b060c46-5d00-4aee-a81f-869efd9cf58d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkzODQ1OTksIm5iZiI6MTcwOTM4NDI5OSwicGF0aCI6Ii8xNjE4NjU5NjgvMzA5NDc0MjQ3LTBiMDYwYzQ2LTVkMDAtNGFlZS1hODFmLTg2OWVmZDljZjU4ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwMlQxMjU4MTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01OGJlYzgwMDA0ZjNiOTYxYjUwMGZmYThkYWQzMWZkZDQ5ZmI0OTE0NjFkZGU4NDNkOGM2MjAzZGVlOGMxMWJmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.YC6znQDCvgbTDgwBtTOpr2AqY7U9w6HvxtxLsbAi_30"> <img alt="Screenshot 2024-03-02 at 13 50 03" width="1363" src="https://private-user-images.githubusercontent.com/161865968/309474249-4f37249a-5d99-4e8d-854e-b6adfc67b147.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkzODQ1OTksIm5iZiI6MTcwOTM4NDI5OSwicGF0aCI6Ii8xNjE4NjU5NjgvMzA5NDc0MjQ5LTRmMzcyNDlhLTVkOTktNGU4ZC04NTRlLWI2YWRmYzY3YjE0Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwMlQxMjU4MTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMWFhZjMxNTczNDVkY2QxZjcxODg1ZmNiZThkZjcwMzI5MzhhNTE2ZmY1ODcwODYzN2JkNDRmNGIzZjc3NzFiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Z8Gp_krGufOxGe2OAMbZ4E_QwrzUpjj5cKslF1RcaF0">

Hi, because the chain's latest block number is increasing, the denominator will also increase. The synchronization percentage will temporarily decrease when the denominator's growth rate exceeds the numerator's. After the synced number grows to the latest block number, it will become stable
