### ISSUE TITLE
[Bug Report] **Please describe the bug shortly**

### ISSUE THREAD

**Issue by alibasket251** [nervosnetwork/neuron#3056]
### Topic Type

Incorrect Balance

### Detail of the issue

I clicked the clear all syncorized button on tools and now my ckb and all dao is gone and i went into mainnet internal node jts 100% and its hows only 44,132 ckb but i had more its all missing what should i do …

**Comment by alibasket251** [comment]
How long does it take after i clicked the clear all synorchized data

**Comment by alibasket251** [comment]
Hello need help anyone there

**Comment by alibasket251** [comment]
this is very stressful matter my I clicked the clear all synorchized data and it was under the tools at the neuron app , i am running the latest version and wallet says 100% Syncing still and how long does it take and is my ckb lost ... Need Help

**Comment by yanguoyu** [comment]
Hi, @alibasket251 Do you click the menu `Clear all synchronized data`? If so, it will start to sync from zero.

1. If you select the Internal node
It's a full node, the full node ckb node needs more time and disk space because it is a full ckb node that includes all of the chain data, it needs about 2~3 days to finish the sync, and it needs over 50GB of space disk.
2. If you select the Light Client
The light client node will sync faster than the full node and needs less disk space because it only subscribes to your address. It can set the start block number to speed up the sync process.

If you want to use the light client click `setting` and scroll to the Network setting, then choose Light Client, which will switch to the Light Client.
![image](https://github.com/nervosnetwork/neuron/assets/12881040/912987e4-2213-49c9-889e-af260d4e0730)

**Comment by alibasket251** [comment]
I DID DO LIGHT CLIENT AND NOTHING THERE

**Comment by alibasket251** [comment]
ITS 100% SYNCING

**Comment by alibasket251** [comment]
BUT NOT SYNC

**Comment by alibasket251** [comment]
IT DOESNT GO TO THE BLOCK I AM INPUTTING

**Comment by alibasket251** [comment]
OR DO I WAIT 100% SYNC AND THEN INPUT THE BLOCK #

**Comment by alibasket251** [comment]
[neuron_debug_1709597847376.zip](https://github.com/nervosnetwork/neuron/files/14488633/neuron_debug_1709597847376.zip)

**Comment by yanguoyu** [comment]
Hi, To improve synchronization speed the light client only syncs one wallet at the same time. The start block number we should set to the first transaction's block number on the current wallet. If the start block number is bigger than the first transaction's block number, Neuron may lose some transactions. If you have set greater than the first transaction block number, we can reset the start block number again and then click `Clear all synchronized data`.

Locating the first transaction can help you to find the first block number of your current wallet.

<img width="821" alt="image" src="https://github.com/nervosnetwork/neuron/assets/12881040/debbb4ac-6d06-49c5-a4dc-01739e78c417">

In addition, if you find the local data may not be correct, you can try to `clear cache` but not `Clear all synchronized data`, `clear cache` will only clear local data and it will rebuild faster. Click the settings, and scroll to the end. The `clear cache` button disappears. 
<img width="1027" alt="image" src="https://github.com/nervosnetwork/neuron/assets/12881040/4f74e6aa-a6f3-4eff-9841-4d384ab4cd59">

**Comment by alibasket251** [comment]
so i did that and it will not take the block #

**Comment by alibasket251** [comment]
can you give me example ?

**Comment by alibasket251** [comment]
if the first transaction starts at 5,000,000 and i have input that number but it wont take it

**Comment by yanguoyu** [comment]
Hi, @alibasket251 Here is the example for setting the start block number, after you set the start block number, it will be better to click `Clear all synchronized data`, and then after about one minute, the first block number will start increase, after it syncs to 100%, then you will see all of your balance.
https://github.com/nervosnetwork/neuron/assets/12881040/ecfada63-c722-43d9-b892-df173a16ec83

**Comment by alibasket251** [comment]
ok i just did that and now wait till every thing gets synced

**Comment by alibasket251** [comment]
ok thank you its started ...

**Comment by alibasket251** [comment]
do I need to make another problem for anther issue ? my seed phrase and i misplaced it but I have my password

**Comment by alibasket251** [comment]
i made a new wallet should i just wait the dao ends at the 30 day cycle to unlock it and then it to the new wallet

**Comment by yanguoyu** [comment]
> do I need to make another problem for anther issue ? my seed phrase and i misplaced it but I have my password

That will be better to create a new issue. Besides, of course, it will be safer to transfer to a wallet that you remember the seed phrase, then if you lose your computer, you can recover the wallet by seed phrase.

**Comment by alibasket251** [comment]
ok
