### ISSUE TITLE
Syncing Issues

### ISSUE THREAD

**Issue by EITFox** [nervosnetwork/neuron#3065]
### Topic Type

Cannot Synchronize

### Detail of the issue

Taking forever to Sync. Have cleared Cache, updated version restart. Still cannot see my assets. Using Mac
[neuron_debug_1709930176383.zip](https://github.com/nervosnetwork/neuron/files/14542973/neuron_debug_1709930176383.zip)

**Comment by yanguoyu** [comment]
Hi, Neuron includes a full ckb node and a light client node.
1. The full node ckb node needs more time and disk space because it is a full ckb node that includes all of the chain data, it needs about 2~3 days to finish the sync, and it needs over 50GB of disk space. From the log I get your Neuron has synced to about 4,839,007, the latest block number is 12,413,316.
2. The light client node will sync faster than the full node and needs less disk space because it only subscribes to your address. It can set the start block number to speed up the sync process.

If you want to use the light client click `setting` and scroll to the Network setting, then choose Light Client, which will switch to the Light Client.

![image](https://github.com/nervosnetwork/neuron/assets/12881040/a6d73bb4-090f-4db0-bc4d-e4d9f133f8c4)

**Comment by Nicko81** [comment]
hello, I wanted to withdraw my ckb from the DAO, but I lost my password, so I created a new wallet. I saw but active and I wanted to update the cache and nothing more it's been more than 2 hours and the synchronization is still at zero someone could help me
THANKS

**Comment by Nicko81** [comment]
[neuron_debug_1712898273731.zip](https://github.com/nervosnetwork/neuron/files/14954200/neuron_debug_1712898273731.zip)

**Comment by yanguoyu** [comment]
> [neuron_debug_1712898273731.zip](https://github.com/nervosnetwork/neuron/files/14954200/neuron_debug_1712898273731.zip)

Hi, @Nicko81  what is the start block number you set? Could you try to `clear all synchronized data` on the `Tools` when selecting the `Light Client`?

**Comment by Nicko81** [comment]
Ok I am ah work when I come back at home I look
Thanks you very much for your help

**Comment by Nicko81** [comment]
Hi,my starting block is 12,466,227 and I just refreshed my cache

**Comment by Nicko81** [comment]
synchronization has just resumed by deleting all data

**Comment by Nicko81** [comment]
Synchronization is 100% but my ckb balance is still at zero, the same for my nervos DAO

**Comment by Nicko81** [comment]
> > [neuron_debug_1712898273731.zip](https://github.com/nervosnetwork/neuron/files/14954200/neuron_debug_1712898273731.zip)
> 
> 
> 
> Hi, @Nicko81  what is the start block number you set? Could you try to `clear all synchronized data` on the `Tools` when selecting the `Light Client`?

You can help me ?

**Comment by yanguoyu** [comment]
> > > [neuron_debug_1712898273731.zip](https://github.com/nervosnetwork/neuron/files/14954200/neuron_debug_1712898273731.zip)
> > 
> > 
> > Hi, @Nicko81  what is the start block number you set? Could you try to `clear all synchronized data` on the `Tools` when selecting the `Light Client`?
> 
> You can help me ?

Hi, @Nicko81  from https://explorer.nervos.org/address/ckb1qzda0cr08m85hc8jlnfp3zer7xulejywt49kt2rr0vthywaa50xwsqws9clquy8tgjqttltmtuaxntvhp00tg5quxrkav?sort=time I get that your first transaction block number is  12,466,120, so it's better to set the start block number to 12,466,100 and `clear all synchronized data` again.

**Comment by Nicko81** [comment]
> > > > [neuron_debug_1712898273731.zip](https://github.com/nervosnetwork/neuron/files/14954200/neuron_debug_1712898273731.zip)
> 
> > > 
> 
> > > 
> 
> > > Hi, @Nicko81  what is the start block number you set? Could you try to `clear all synchronized data` on the `Tools` when selecting the `Light Client`?
> 
> > 
> 
> > You can help me ?
> 
> 
> 
> Hi, @Nicko81  from https://explorer.nervos.org/address/ckb1qzda0cr08m85hc8jlnfp3zer7xulejywt49kt2rr0vthywaa50xwsqws9clquy8tgjqttltmtuaxntvhp00tg5quxrkav?sort=time I get that your first transaction block number is  12,466,120, so it's better to set the start block number to 12,466,100 and `clear all synchronized data` again.

thank you very much yanguoyu I found all but balance thanks to the block number that you gave me
THANKS

**Comment by Nicko81** [comment]
I come frome France Google translator it's not the best 🤣
