### ISSUE TITLE
Nueron wallet not showing any transactions or balance

### ISSUE THREAD

**Issue by MarioLisbona** [nervosnetwork/neuron#3067]
### Topic Type

Incorrect Balance

### Detail of the issue

Havnt used the wallet in a few year. Updated to:
- Neuron Version: 0.112.0
- CKB Client Version: v0.112.1
- CKB Light Client Version: v0.3.2

Initially it was showing the same balance as the old wallet version (balance was less than CKB received, and showed transactions with CKB received but not showing in the balance). This new wallet would never fully sycn to the network, would always stall around 97-99% range.

I cleared the cache, deleted the walled and used the seed phrase to create the wallet again. tried this numerous times and the balance and transaction history was the same.

Finally tried this again and the wallet synced to both mainnet and light mainnet. Now the wallet shows an empty balance and no transaction history at all
[neuron_debug_1710148762037.zip](https://github.com/nervosnetwork/neuron/files/14556272/neuron_debug_1710148762037.zip)

**Comment by yanguoyu** [comment]
Hi, @MarioLisbona 
from the log, I get that your last selected network is Light client, do you set the start block number when using Light client? If the start block number is bigger than 6,725,505, the light client may miss some transactions. Because your wallet's first transaction block number is 6,725,505. If so, switch to the light client if the current network is not, change the start block to 6,725,500, and then Clear all synchronized data.

For the full node, I get the log, the 12430236 block was packaged at 2024-03-11T09:03:44. It means that your wallet has reached the blockchain's latest block at 2024-03-11T09:03:59. But I can not get the full ckb node run log. Could you upload the full ckb node log? It can be found at `~/Library/Application Support/Neuron/chains/mainnet/data/logs/run.log`. I guess If your full node has synced to 100%, it will be better to use the full node. 
```
[2024-03-11T09:03:59.083Z] [info]  Database:	saved synced block #12430236
```

**Comment by MarioLisbona** [comment]
Ah ok thanks for that info.

Ok so the issue now is that my wallet is not showing the full balance. Its only showing a balance of 268.60951115 CKB. I have  transferred over 82,000 CKB to this wallet. I can see in the transaction history that +82,269.60953637 CKB has been received but but the balance isn't reflecting this.

<img width="1157" alt="ckb-wallet" src="https://github.com/nervosnetwork/neuron/assets/101855037/8d4b6fa0-2d5c-4012-ba8f-de969b69b861">

If i open that transaction i get the following screen

<img width="1141" alt="ckb-transaction-history" src="https://github.com/nervosnetwork/neuron/assets/101855037/445592e9-be2e-48b4-b2e1-7cb75d8dc2e5">

The transaction hash is `0x49b855bd18c1e04a2ec322783cc2ec8aabffeb090baf966f8e70e0ae5b33c3e5`

Do you have any idea why the balance wouldn't be correct?

Thanks again

Mario

**Comment by yanguoyu** [comment]
> Ah ok thanks for that info.
> 
> Ok so the issue now is that my wallet is not showing the full balance. Its only showing a balance of 268.60951115 CKB. I have transferred over 82,000 CKB to this wallet. I can see in the transaction history that +82,269.60953637 CKB has been received but but the balance isn't reflecting this.
> 
> <img alt="ckb-wallet" width="1157" src="https://private-user-images.githubusercontent.com/101855037/312021088-8d4b6fa0-2d5c-4012-ba8f-de969b69b861.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAyNDI3NTUsIm5iZiI6MTcxMDI0MjQ1NSwicGF0aCI6Ii8xMDE4NTUwMzcvMzEyMDIxMDg4LThkNGI2ZmEwLTJkNWMtNDAxMi1iYThmLWRlOTY5YjY5Yjg2MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxMlQxMTIwNTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lYzQ2YjI4NzdkZjc4MGI5ZDQzOWEwZGMzNWI1OWU4YTA3Mjc3Y2JkNGZkNjlhOGYyZjgzN2QwNjc4NzQ0MjBlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.KJJSiDnUyB3WEohaU1T20EmUj6RFhHRxGt8-EypoDNY">
> If i open that transaction i get the following screen
> 
> <img alt="ckb-transaction-history" width="1141" src="https://private-user-images.githubusercontent.com/101855037/312021525-445592e9-be2e-48b4-b2e1-7cb75d8dc2e5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAyNDI3NTUsIm5iZiI6MTcxMDI0MjQ1NSwicGF0aCI6Ii8xMDE4NTUwMzcvMzEyMDIxNTI1LTQ0NTU5MmU5LWJlMmUtNDhiNC1iMmUxLTdjYjc1ZDhkYzJlNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxMlQxMTIwNTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zZDFiMmNkZTE3ZDQ2NTkwMjEwMTZhM2YzNGM0NDliNmE0N2Y2ZmIwNjhhMWZmZTJkMjIyNDE2NWJiNmVhYmY2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.hmHDmCrpupG6iLsrRZ56Z6VX6uMFaPjxQVQMHot2j0Y">
> The transaction hash is `0x49b855bd18c1e04a2ec322783cc2ec8aabffeb090baf966f8e70e0ae5b33c3e5`
> 
> Do you have any idea why the balance wouldn't be correct?
> 
> Thanks again
> 
> Mario

I got that, the overview page only shows the ckb that you can use now. I get that the latest two transactions are Nervos DAO, the deposit ckb is locked in DAO, so they will not show on the overview page. They can be found on the `Nervos DAO` page. 
Click the `Nervos DAO`, then you will see the deposit balance.
