### ISSUE TITLE
Issues of regression in  amend feature package 

### ISSUE THREAD

**Issue by silySuper** [nervosnetwork/neuron#3070]
1.In history page,confirmation is started from negative number.

<img width="974" alt="截屏2024-03-13 16 19 17" src="https://github.com/nervosnetwork/neuron/assets/25971273/20e12736-5ece-4986-b153-9ce93508209d">

**Comment by yanguoyu** [comment]
> 1.In history page,search by date is disabled.

I didn't get the point of this.

**Comment by yanguoyu** [comment]
https://github.com/nervosnetwork/neuron/pull/3071
