### ISSUE TITLE
nervos dao  display bug

### ISSUE THREAD

**Issue by 7dog7** [nervosnetwork/neuron#3088]
### Topic Type

User Experience

### Detail of the issue

nervos dao  display bug
This situation occurs after updating the latest version
![image](https://github.com/nervosnetwork/neuron/assets/50615524/0d32c673-3436-4caf-8a42-28c94aeb796b)

**Comment by Keith-CY** [comment]
@silySuper please have a check

**Comment by 7dog7** [comment]
> @silySuper请检查一下

The light node client used

**Comment by silySuper** [comment]
When my light client node sync is 100%：
<img width="1164" alt="截屏2024-03-20 15 32 09" src="https://github.com/nervosnetwork/neuron/assets/25971273/799c1e47-a3df-4122-9289-e185eeb8d963">

I do not appear this bug after depositing  ckb today：
<img width="1167" alt="截屏2024-03-20 15 29 33" src="https://github.com/nervosnetwork/neuron/assets/25971273/7dfcf837-479f-4e68-ad81-ae14938f096e">

You would better offer your sync status and operation if this bug is appear and stay always~

**Comment by Keith-CY** [comment]
> When my light client node sync is 100%： <img alt="截屏2024-03-20 15 32 09" width="1164" src="https://private-user-images.githubusercontent.com/25971273/314409847-799c1e47-a3df-4122-9289-e185eeb8d963.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA5MjA1OTcsIm5iZiI6MTcxMDkyMDI5NywicGF0aCI6Ii8yNTk3MTI3My8zMTQ0MDk4NDctNzk5YzFlNDctYTNkZi00MTIyLTkyODktZTE4NWVlYjhkOTYzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIwVDA3MzgxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRmNTFkYzZiMTAzYTAwYmRhOTRhYTc4NTM4MWZkMjI3OTZlZWJiN2QwYWVkODk3MWIxN2Y1N2MwZmZhMjllN2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.aNt_gLmiHq1khISa0wrhJ2QJRYHs3hYCyxRf7yKDJ3U">
> 
> I do not appear this bug after depositing ckb today： <img alt="截屏2024-03-20 15 29 33" width="1167" src="https://private-user-images.githubusercontent.com/25971273/314409302-7dfcf837-479f-4e68-ad81-ae14938f096e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA5MjA1OTcsIm5iZiI6MTcxMDkyMDI5NywicGF0aCI6Ii8yNTk3MTI3My8zMTQ0MDkzMDItN2RmY2Y4MzctNDc5Zi00ZTY4LWFkODEtYWUxNDkzOGYwOTZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIwVDA3MzgxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY4M2RhYmI5Nzg3ZmE0YzI0YmNiMzRmZGRhMmIzNTk1OGMxODU1N2QwM2JiNDc0NmVjOTA3MWZjNWZhNWIxOWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gbZLY5Ncic0J-Ko1iP0a1qWMh60cUkM1niYsmAgcuKE">
> 
> You would better offer your sync status and operation if this bug is appear and stay always~

Please check if the `number` is displayed correctly when the light client is off

**Comment by silySuper** [comment]
I have exited ckb-client progress manually and does not see this bug：

https://github.com/nervosnetwork/neuron/assets/25971273/7c671c94-d0ce-49b1-b2b4-1de8444f04fd

**Comment by yanguoyu** [comment]
Hi, @7dog7 We cannot reproduce your issue, could you provide more information about your Neuron?
1. Neuron sync status, can be found at the right-top of the Neuron
2. The Neuron version, click `Neuron -> About Neuron` will show the versions.

It would be better if you could upload the native debug information of Neuron. It can be exported by Menu => Help => Export debug information.

**Comment by 7dog7** [comment]
It has been restored in about half an hour after my feedback, which may be due to a problem with the loading of some interface.
