### ISSUE TITLE
nervos dao display bug

### ISSUE THREAD

**Issue by Leedija** [nervosnetwork/neuron#3089]
### Topic Type

Cannot Synchronize

### Detail of the issue

After update, in nervos dao unlock button is inactive, 
![2024-03-20_09-46-00](https://github.com/nervosnetwork/neuron/assets/153084989/5b596cc0-b4bb-4253-8095-a6005f6c07e6)

**Comment by Keith-CY** [comment]
> ### Topic Type
> Cannot Synchronize
> 
> ### Detail of the issue
> After update, in nervos dao unlock button is inactive, ![2024-03-20_09-46-00](https://private-user-images.githubusercontent.com/153084989/314413489-5b596cc0-b4bb-4253-8095-a6005f6c07e6.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA5MjEzNTQsIm5iZiI6MTcxMDkyMTA1NCwicGF0aCI6Ii8xNTMwODQ5ODkvMzE0NDEzNDg5LTViNTk2Y2MwLWI0YmItNDI1My04MDk1LWE2MDA1ZjZjMDdlNi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyMFQwNzUwNTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lODA3OTI5YTZiMzgwYzM1YTE2MWY5MTcxYzE0YTU1NzdkYTc0YWExNjFmZDc5N2ZjOTI1ODdmNjUyZGIxMmI4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.aUmvxumwSjULKkDQ77bZOItfQy_6r15b5sS6xO1fAyQ)
> 
> ### bundled-ckb.log
> _No response_
> 
> ### bundled-ckb-light-mainnet.log
> _No response_
> 
> ### main.log
> _No response_
> 
> ### status.log
> _No response_

Hi @Leedija As prompted in the progress bar(beneath it), your asset could be unlocked after 18 days.

It conforms to the rule of Nervos DAO that 

> **Final Withdrawal Transaction** — This is the transaction which withdraws your initial CKByte deposit + rewards accrued from the Nervos DAO. It must be done in a deposit period after the **Initial Withdrawal Transaction**.

Ref: https://medium.com/nervosnetwork/nervos-dao-explained-95e33898b1c

The deposit period mentioned above is typically 30 days, so your asset can be unlocked after 30d, 90d, 120d ... since the deposit.

**Comment by yanguoyu** [comment]
Hi, the DAO deposit needs two steps to withdraw it. For the phase 1 withdrawal, you can start at any time. For phase 2, we must wait for 180 epochs(about 30 days) at longest.
The detailed docs can be found here.https://github.com/nervosnetwork/rfcs/blob/master/rfcs/0023-dao-deposit-withdraw/0023-dao-deposit-withdraw.md#withdraw

Currently, you have withdrawn the DAO, from the picture we know you should wait for about 18 days to unlock the DAO. After about 18 days and Neuron synced to 100%, the unlock button will be enabled, and then you can unlock the DAO, after that, you will receive your deposit and Interest.

If the Neuron does not sync, the information of the native wallet would help us check what happened, it can be exported by Menu => Help => Export debug information.
