### ISSUE TITLE
 Could NOT specify network information manually.

### ISSUE THREAD

**Issue by chaoticlonghair** [nervosnetwork/neuron#3098]
### Topic Type

User Experience

### Detail of the issue

When I added a new network, Neuron never asked me for the network information: mainnet or testnet, full node or light client.

Neuron just set the network information as it imagined.

**Comment by Keith-CY** [comment]
`Self-hosted Light client` is not allowed to be connected to Neuron as mentioned at https://github.com/Magickbase/neuron-public-issues/issues/90#issuecomment-1377030781

> It's not recommended to allow users to set the entrypoint of a light client freely because light client and full node are based on different security assumptions.

We could make it clear in the dialog cc @Danie0918 

---

`Chain type` of a full node is detected via its RPC response https://github.com/nervosnetwork/ckb/tree/develop/rpc#stats-get_blockchain_info, `chain: ckb` for mainnet and `chain: ckb_testnet` for testnet.
