### ISSUE TITLE
Neuron Wallet syncing backwards/wont fully sync 

### ISSUE THREAD

**Issue by basement5k** [nervosnetwork/neuron#3113]
### Topic Type

Cannot Synchronize

### Detail of the issue

ive never had an issue. been using light client on mac OS.  I have the latest updated wallet software.  Also when i click on the history tab - go down to my first transaction and click "details" the wallet/app basically has an aneurysm. see video here: https://www.youtube.com/watch?v=-1mgh-nNupo

When this happens. i hard quit the app, and i get this error pop up
[message.txt](https://github.com/nervosnetwork/neuron/files/14911747/message.txt)
<img width="445" alt="Screenshot 2024-04-08 at 7 26 14 PM" src="https://github.com/nervosnetwork/neuron/assets/166455736/e89efec0-a556-4f7f-9359-c49cf6a6a74a">

with that said, my wallet simply wont sync its actually going backwards..   should i uninstall the wallet software/app and reinstall?

**Comment by silySuper** [comment]
Hi～
Thank you for your feedback，I notice that  the network status is connecting when the problem shows, and debug information of the native wallet would help us check what happened, it can be exported by Menu => Help => Export debug information.

**Comment by basement5k** [comment]
The file size is too large to attach.  I unzipped the file.  Is there a specific piece you need? how do you suggest i proceed to give you guys the info you need to help?  Thaks
<img width="961" alt="Screenshot 2024-04-09 at 10 05 43 AM" src="https://github.com/nervosnetwork/neuron/assets/166455736/8bdfde49-b908-40dd-9f73-9c76c2a10555">

**Comment by basement5k** [comment]
any update or guidance here?

**Comment by Keith-CY** [comment]
> any update or guidance here?

Hi @basement5k 

The log file is abnormally huge(recently I found several cases like this, probably an issue of the latest release). Following is the step to clear the log file manually

1. Keep Neuron off;
2. Open a built-in app named `Terminal.app`;
3. Type **open /Users/{Username}/Library/Logs/Neuron**, noted that `{Username}` should be replaced by your system username, hit <kbd>Enter</kbd>
4. Finder.app should open the directory where logs are, and delete `light_client_mainnet.log`, which is abnormally huge.
5. Restart Neuron.app and retry the step to generate a new log

**Comment by basement5k** [comment]
Thank you that was helpful.  Here are the logs
[light_client_mainnet.log](https://github.com/nervosnetwork/neuron/files/14932025/light_client_mainnet.log)
[main.log](https://github.com/nervosnetwork/neuron/files/14932026/main.log)
[main.old.log](https://github.com/nervosnetwork/neuron/files/14932027/main.old.log)

**Comment by basement5k** [comment]
can you confirm I've provided you with what you need to diagnose the issue?

**Comment by yanguoyu** [comment]
@basement5k Hi, from https://github.com/nervosnetwork/neuron/issues/3113#issue-2232308652, you have two issues with your description.
1. After clicking the detail of the transaction, this page will refresh frequently.
2. When quit the Neuron, it will throw an exception.

For the first problem, could you try to click `overview` and try it again?
The second problem, it's a bug, we have fixed it at develop branch https://github.com/nervosnetwork/neuron/pull/3103, and it will be released in next version.

**Comment by basement5k** [comment]
when i click "overview" what exactly am i "trying agian"
What are are proceses here:

I currently have the wallet open.  Do i quit it, and then how should i proceed?

**Comment by yanguoyu** [comment]
> when i click "overview" what exactly am i "trying agian" What are are proceses here:
> 
> I currently have the wallet open. Do i quit it, and then how should i proceed?

Quit or not is ok, after clicking `overview` in the menu, could you try to click the detail again? Does it still refresh frequently?

**Comment by basement5k** [comment]
<img width="1360" alt="Screenshot 2024-04-11 at 12 43 50 PM" src="https://github.com/nervosnetwork/neuron/assets/166455736/73579a42-669f-450f-bb44-2c51e489fcbb">

When i click overview this is what i see.  by "detail" do you mean the upper right sync button?

**Comment by basement5k** [comment]
Ok it finally synced.  Im going to close this.  Thank you all for the support!
