### ISSUE TITLE
[Enhance User Experience] Automatically fill all blank when paste the complete recovery phrase.

### ISSUE THREAD

**Issue by yangby-cryptape** [nervosnetwork/neuron#3115]
### Description

Recently, I have tried many wallets.

I found that most of them have a good feature: when a user pastes a complete secret recovery phrase into the wallet, all corresponding blank will be filled automatically.

But in Neuron, I have to paste each word into the corresponding blank one by one.

### Comparison

<details><summary>Click HERE to the the comparison.</summary>

- MetaMask

  ![MetaMask](https://github.com/nervosnetwork/neuron/assets/30993023/3b9d9aa9-fd37-45c0-8bb1-ce5f87850919)

- Neuron

  ![Neuron](https://github.com/nervosnetwork/neuron/assets/30993023/3076f3f7-49f8-463c-adda-3abdd98b1041)

</details>

### Another Issue

Neuron doesn't hide the secret recovery phrase after input.

**Comment by yanguoyu** [comment]
For better safety, we remove the copy-and-paste phrase seeds. If you copy your phrase seeds once, other unsafety apps may read your clipboard. So it's better to enter phrase seed words one by one.

**Comment by Keith-CY** [comment]
> If Neuron wants to avoid password leak via the clipboard, Neuron should disable copy rather than disable paste.

Agreed, please have a consideration @Danie0918 

The suggestion at https://github.com/nervosnetwork/neuron/issues/3115#issuecomment-2048796731 is a bit further.

I would suggest optimization as follows

1. Disable the copy function of the mnemonics;
2. Fill words into each field when the wallet is imported by pasting mnemonics;
3. Display options along with characters being inputted, e.g. https://developer.mozilla.org/en-US/docs/Web/HTML/Element/datalist
4. Leave some fields empty(not all fields empty) when a user inputs the mnemonics a second time for confirmation. By doing so, users have to write down all words but only need to type some of them.

**Comment by Danie0918** [comment]
WIP https://github.com/Magickbase/neuron-public-issues/issues/381
