### ISSUE TITLE
[Bug Report] Unable to withdraw DAO CKB continuously, but have to wait for some time

### ISSUE THREAD

**Issue by dzhback** [nervosnetwork/neuron#3130]
### Topic Type

Other

### Detail of the issue

I deposited CKB into DAO by several TXes. But I'm unable to unlock CKB continuously, have to wait for some time(~ 1 min) till next withdraw operation.

**Comment by Keith-CY** [comment]
> ### Topic Type
> Other
> 
> ### Detail of the issue
> I deposited CKB into DAO by several TXes. But I'm unable to unlock CKB continuously, have to wait for some time(~ 1 min) till next withdraw operation.
> 
> ### bundled-ckb.log
> _No response_
> 
> ### bundled-ckb-light-mainnet.log
> _No response_
> 
> ### main.log
> _No response_
> 
> ### status.log
> _No response_

Hi @dzhback 

It's reasonable in some scenarios, e.g.

1. You have 1 **free UTXO** and 3 **nervos dao UTXOs**
2. 1 of the **nervos dao UTXOs** is being withdrawn, and the **free UTXO** is used to pay the transaction fee
3. When the transaction is not committed on the chain, you have 0 **free UTXOs** for next withdrawal to pay the transaction fee, so you have to wait for the previous one committed.
4. Once the transaction in step 2 is committed, you have 1 **free UTXO** again, and can start the next withdrawal transaction.

This is just one of the cases.

If you have many live UTXOs to pay the fee, your transactions could be submitted sequentially.

This is just an example of why transactions cannot be performed concurrently.

**Comment by dzhback** [comment]
got it. thx
