### ISSUE TITLE
[Bug Report] **Please describe the bug shortly**

### ISSUE THREAD

**Issue by ludovicpriso** [nervosnetwork/neuron#3136]
### Topic Type

Cannot Synchronize

### Detail of the issue

Hi everyone,

I'm encountering an issue with my Neuron wallet and would appreciate some help. Here's my situation:

I had staked my CKB tokens in my Neuron wallet on my previous computer that dont work anymore. Recently, I switched to a new computer (downloaded the latest version of neuron) and synced my Neuron wallet, but I'm not seeing my staked CKB tokens anymore.

I've already tried the following troubleshooting steps:

1. Ensured that my new computer's Neuron wallet is fully synced with the blockchain.
2. Imported my wallet using the recovery phrase, but still no luck.

Despite these efforts, I'm unable to see my CKB balance. Has anyone else encountered a similar issue with the Neuron wallet? Any suggestions on what I can do next to resolve this?

I appreciate any help or guidance you can provide. Thanks in advance!

**Comment by yanguoyu** [comment]
Hi, @ludovicpriso 
Debug information of the native wallet would help us check what happened, it can be exported by Menu => Help => Export debug information.
