### ISSUE TITLE
Trying to withdrawl CKB from DAO with ledger leads to error 0x9405

### ISSUE THREAD

**Issue by maynardbarber** [nervosnetwork/neuron#3140]
### Topic Type

Cannot Synchronize

### Detail of the issue

I'm trying to withdraw my CKB from the DAO and it keeps giving the error. There is less than one day left before the cycle restarts and I've updated the wallet, ledger, and computer and still it won't work. i also tried changing usb slots.

**Comment by yanguoyu** [comment]
Hi, @maynardbarber  [Here](https://github.com/nervosnetwork/neuron/issues/3057) seems to be the same question.
https://github.com/nervosnetwork/neuron/issues/3057#issuecomment-2016848899 or https://github.com/nervosnetwork/neuron/issues/3057#issuecomment-1977652097 may help you.
If these don't work, Debug information of the native wallet would help us check what happened, it can be exported by Menu => Help => Export debug information.

**Comment by Keith-CY** [comment]
Hi @maynardbarber 
We've proposed a simple solution that uses Neuron as a cold wallet to circumvent this problem, hope it helps.
Ref: https://github.com/nervosnetwork/neuron/issues/3285
