### ISSUE TITLE
0.116.2 - DAO screen can't display

### ISSUE THREAD

**Issue by eek-nz** [nervosnetwork/neuron#3191]
### Topic Type

User Experience

### Detail of the issue

Fresh install of both windows11 and windows 10 with a full sync complete. Transactions display normally. Clicking on the DAO page and the busy cursor jumps from the 9 o'clock to the 12 o'clock position quickly and the app becomes barely responsive. Occasionally it will flash an unsynced DAO screen, but is otherwise unusable. System is a hyper-V guest. The same host has an older Win10 guest running 0.103 and it works flawlessly. Clicking blindly where the Overview button is likely to be will take it back to a fully synced transaction list.
[neuron_debug_1718703973473.zip](https://github.com/user-attachments/files/15884048/neuron_debug_1718703973473.zip)

**Comment by eek-nz** [comment]
https://github.com/nervosnetwork/neuron/assets/90128334/8b549b8f-eaa6-4fad-b09c-913cdee6fa7a

Here is a tiny MP4 of it faulting

**Comment by yanguoyu** [comment]
@eek-nz 
Hi, We are unable to reproduce your issue, perhaps you can try clearing the cache. Clicking the `Settings` menu and scroll to the end, the `refresh` button will show. Click `Refresh` to clear the cache.
If that does not help you, could you join our [discord](https://discord.gg/kFqQ7PZB) and send the read-only wallet to us to help us reproduce that problem?
Thank you.

**Comment by eek-nz** [comment]
That's crazy. Clearing the Cache on the Win10 has worked fine. What's crazy is the fresh build of Win 11 and Win 10 both did it once synced up. But not it's fine. Thanks.
