### ISSUE TITLE
[Bug Report] **Please describe the bug shortly**

### ISSUE THREAD

**Issue by Bahadorshabani** [nervosnetwork/neuron#3241]
### Topic Type

Incorrect Balance

### Detail of the issue

Hello, I had ckb in my bitpie wallet, and its withdrawal was closed, and I started recovering with the 12 private words I had in the neuron wallet, and I did it through the lighet client, and all the blocks were completed 100%, but unfortunately, I still have the balance. It shows zero

adres 
 
ckb1qypqytypq6clg8z4e5pv2y78lgrzl7unu3hqe2t7gp
![Uploading IMG_0787.jpeg…]()

### bundled-ckb-light-mainnet.log

```shell
Hello, I had ckb in my bitpie wallet, and its withdrawal was closed, and I started recovering with the 12 private words I had in the neuron wallet, and I did it through the lighet client, and all the blocks were completed 100%, but unfortunately, I still have the balance. It shows zero

adres 
 
ckb1qypqytypq6clg8z4e5pv2y78lgrzl7unu3hqe2t7gp
```

**Comment by Bahadorshabani** [comment]
Hello, I had ckb in my bitpie wallet, and its withdrawal was closed, and I started recovering with the 12 private words I had in the neuron wallet, and I did it through the lighet client, and all the blocks were completed 100%, but unfortunately, I still have the balance. It shows zero

**Comment by Bahadorshabani** [comment]
![Uploading image.jpg…]()

**Comment by yanguoyu** [comment]
@Bahadorshabani 
Hi,
Debug information of the native wallet would help us check what happened, it can be exported by Menu => Help => Export debug information.

**Comment by Bahadorshabani** [comment]
I will send you a message via mobile when I enter the setting

**Comment by Bahadorshabani** [comment]
![Uploading image.jpg…]()

**Comment by yanguoyu** [comment]
@Bahadorshabani Hi, I didn't receive the image, it uploads failed.

**Comment by Bahadorshabani** [comment]
![IMG_0783](https://github.com/user-attachments/assets/cfac55cd-efce-4ff8-b9f6-90539b38c197)

**Comment by Bahadorshabani** [comment]
> @Bahadorshabani Hi, I didn't receive the image, it uploads failed.

![Uploading IMG_0783.jpeg…]()

**Comment by yanguoyu** [comment]
@Bahadorshabani Could you upload the Debug information of the native wallet? it can be exported by Menu => Help => Export debug information.  I can not get the problem only from the picture.

**Comment by Bahadorshabani** [comment]
photo
![Uploading IMG_0783.jpeg…]()

**Comment by Bahadorshabani** [comment]
Does it mean that I enter the help section from inside the computer?

**Comment by yanguoyu** [comment]
> Does it mean that I enter the help section from inside the computer?

That's right

**Comment by Bahadorshabani** [comment]
> @Bahadorshabani Could you upload the Debug information of the native wallet? it can be exported by Menu => Help => Export debug information. I can not get the problem only from the picture.

I simply don't know

**Comment by Keith-CY** [comment]
> > @Bahadorshabani Could you upload the Debug information of the native wallet? it can be exported by Menu => Help => Export debug information. I can not get the problem only from the picture.
> 
> I simply don't know

Hi @Bahadorshabani 

Please select the **Export debug information** from **Help** in the top menu.

<img width="647" alt="image" src="https://github.com/user-attachments/assets/16e37fdc-7676-4b0a-83b3-c7048588249b">

A zip file should be generated, it includes the log file of Neuron. Please send it to neuron@magickbase.com and we can try to find how to fix it.

**Comment by Bahadorshabani** [comment]
![IMG_0783](https://github.com/user-attachments/assets/68014db6-ff87-4c70-a96b-4c2c45654f66)

**Comment by Bahadorshabani** [comment]
It shows zero balance

**Comment by ALI57100** [comment]
good evening team
I restored my neuron wallet on a new laptop using the seed phrase because my old laptop is broken.
after having correctly synchronized the nodes and after clearing the cache, my sole CKB is 0.
My ckb tokens were in staking.
My new address shows me a 0 balance.
Could someone help me please?
