### ISSUE TITLE
[Bug Report] The unlock button is always unclickable

### ISSUE THREAD

**Issue by sunchengzhu** [nervosnetwork/neuron#3242]
### Topic Type

Unable to unlock Nervos DAO

### Detail of the issue

2024.09.13 15:03
![image](https://github.com/user-attachments/assets/aae2dca4-1142-4dae-9baf-dc7ff7d97337)

2024.09.13 15:18
![image](https://github.com/user-attachments/assets/b27bf504-f669-4be0-9c50-2942cd509481)

After the compensation period is over, I still need to wait another 30 days. This has already happened twice. I will never be able to unlock my CKB !!!!!!

**Comment by sunchengzhu** [comment]
unlock tx hash: https://explorer.nervos.org/transaction/0x2766086f8b34607d14ee10100fe17e4376536b7e381fbeafdc339579958284c1

**Comment by Keith-CY** [comment]
I found this issue resolved in Discord, can we close this issue now?

**Comment by sunchengzhu** [comment]
> I found this issue resolved in Discord, can we close this issue now?

@Keith-CY @yanguoyu 

I can close this issue now. Additionally, I am making a note here that I resolved the problem by refreshing the date cache.
<img width="840" alt="image" src="https://github.com/user-attachments/assets/473fc183-6ea5-4fa3-824e-75549fdb04df">
