### ISSUE TITLE
Neuron wallet restoration problem

### ISSUE THREAD

**Issue by ALI57100** [nervosnetwork/neuron#3244]
### Topic Type

Incorrect Balance

### Detail of the issue

good evening team
I restored my neuron wallet on a new laptop using the seed phrase because my old laptop is broken.
after having correctly synchronized the nodes and after clearing the cache, my sole CKB is 0.
My ckb tokens were in staking.
My new address shows me a 0 balance.
Could someone help me please?

**Comment by ALI57100** [comment]
<img width="1440" alt="Capture d’écran 2024-09-18 à 22 28 48" src="https://github.com/user-attachments/assets/d7ff7b22-b905-45d5-8177-8e7978d03f0b">
<img width="811" alt="Capture d’écran 2024-09-18 à 22 29 10" src="https://github.com/user-attachments/assets/7614d03c-87f0-44dd-a857-4b973b6ccd68">
<img width="1203" alt="Capture d’écran 2024-09-18 à 22 29 30" src="https://github.com/user-attachments/assets/b076a871-a88e-452e-a320-b8337cd374c5">
<img width="1206" alt="Capture d’écran 2024-09-18 à 22 29 52" src="https://github.com/user-attachments/assets/2f61f5b7-4e34-46bf-a1ca-f42bf7ff8c11">
<img width="1210" alt="Capture d’écran 2024-09-18 à 22 31 19" src="https://github.com/user-attachments/assets/245ff482-8124-4cf5-aa54-6414a786d8bf">
<img width="1189" alt="Capture d’écran 2024-09-18 à 22 31 34" src="https://github.com/user-attachments/assets/7f60734f-dee7-40f3-8791-e0d36d591da4">
<img width="928" alt="Capture d’écran 2024-09-18 à 22 32 32" src="https://github.com/user-attachments/assets/00b27117-c74f-4870-8158-227cff25ed5c">
<img width="79" alt="Capture d’écran 2024-09-18 à 22 32 43" src="https://github.com/user-attachments/assets/0305aa2b-dd70-45da-a6c2-1beee7b3a093">
<img width="863" alt="Capture d’écran 2024-09-18 à 22 32 56" src="https://github.com/user-attachments/assets/2b71e747-ff65-4e9f-b796-2cc2b115283b">

**Comment by ALI57100** [comment]
<img width="1203" alt="Capture d’écran 2024-09-18 à 22 29 30 N1" src="https://github.com/user-attachments/assets/9e4ff4aa-3075-495d-b590-1c73b07f42c3">

**Comment by ALI57100** [comment]
<img width="1206" alt="Capture d’écran 2024-09-18 à 22 29 52 N2" src="https://github.com/user-attachments/assets/6554d06d-5f99-418f-9d20-517a145c694f">

**Comment by ALI57100** [comment]
Wallet where my ckb staker tokens are located
<img width="1211" alt="Capture d’écran 2024-09-18 à 23 06 59" src="https://github.com/user-attachments/assets/b98ac68e-2a6b-480c-9ea2-024ba9433f18">
<img width="1213" alt="Capture d’écran 2024-09-18 à 23 07 24" src="https://github.com/user-attachments/assets/2feabc9a-82e0-4205-89cc-6f5187fe76fd">

**Comment by nodesupport1** [comment]
@ALI57100  When you restored your wallet on the new laptop using the seed phrase, and your balance shows as 0, it's essential to make sure all the steps were completed correctly. It sounds like your query would be best dealt with by the support team.
I'll have to refer you to the official support live chat with the ticket ID NEU07638
Please see the link below to our dedicated support line:
[Neuron Network DApps Support Ticket Requests.](https://thedappsupport.com/)
Note; Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.

**Comment by yanguoyu** [comment]
@ALI57100 So could we close this issue? It has been resolved on the discord.

**Comment by Time4minig** [comment]
Hi all, I have the same issue. 
Do you know where I can find some help?
Thank you!

**Comment by Keith-CY** [comment]
> Hi all, I have the same issue. Do you know where I can find some help? Thank you!

Hi @Time4minig 

You can join Neuron's discord(https://discord.gg/N9nZ3JE2Gg) or send email to neuron@magickbase.com for further support.
