### ISSUE TITLE
Sync problem

### ISSUE THREAD

**Issue by kevn2402** [nervosnetwork/neuron#3247]
### Topic Type

Cannot Synchronize

### Detail of the issue

Hi team, the issue are problems with syncing. The sync stop at 99.67%. New start, internet test are already done, but the problem still exists. 
Best regards

**Comment by cryptoworld9016** [comment]
I got same Issue ... i Updated my nevous wallet and not syncing is stuck on 99.88%. Done everything possible ...plz help

**Comment by Keith-CY** [comment]
> I got same Issue ... i Updated my nevous wallet and not syncing is stuck on 99.88%. Done everything possible ...plz help

Hi @cryptoworld9016 could you upload the **debug information** here so we can check the log of the application.

The debug information could be exported as a zip file by **menu => help => export debug information** and can be uploaded by drag&drop it into the chatbox

**Comment by cryptoworld9016** [comment]
[neuron_debug_1734676974050.zip](https://github.com/user-attachments/files/18206953/neuron_debug_1734676974050.zip)
