### ISSUE TITLE
[Bug Report] 离线签名报错

### ISSUE THREAD

**Issue by rink1969** [nervosnetwork/neuron#3256]
### Topic Type

Other

### Detail of the issue

gen a account in Neuron
for example ckt1qzda0cr08m85hc8jlnfp3zer7xulejywt49kt2rr0vthywaa50xwsq2xzy6qe9d7fq98cy5x2jl7ct3qyx69jmqrz3gfw

build tx with ckb-cli：
tranfer some ckb to the account
```
$ ckb-cli wallet transfer --from-account 0x39879dfd37f2fa8f0a50bf1088d2d5734dadcf14 --to-address ckt1qzda0cr08m85hc8jlnfp3zer7xulejywt49kt2rr0vthywaa50xwsq2xzy6qe9d7fq98cy5x2jl7ct3qyx69jmqrz3gfw --capacity 400.01
Password:
0x0387527012a1ea797ec3275c12cfdc8eb59840c5834bb1612183a7aef0f51191
```
init tx
```
ckb-cli tx init --tx-file tx.json

ckb-cli tx add-input --tx-hash 0x0387527012a1ea797ec3275c12cfdc8eb59840c5834bb1612183a7aef0f51191 --index 0 --tx-file tx.json

$ ckb-cli tx info --tx-file tx.json
[input] ckt1qzda0cr08m85hc8jlnfp3zer7xulejywt49kt2rr0vthywaa50xwsq2xzy6qe9d7fq98cy5x2jl7ct3qyx69jmqrz3gfw => 400.01, (data-length: 0, type-script: none, lock-kind: sighash(secp))
input_total: 400.01 (CKB)
output_total: 0.0 (CKB)
tx_fee: 400.01 (CKB)
```

到Neuron中对这个交易进行离线签名，加载tx.json之后可以正常是被，但是输入密码之后，报签名失败的错误。

Neuron的离线签名功能需要的json格式跟ckb-cli生成的有差异吗？

**Comment by yanguoyu** [comment]
@rink1969  确实有差异，如果离线签名需要确定 input 的 script 才能找到对应的 path，导出的没有，另外 Neuron 的 json 文件变量名是驼峰不是下划线。

@Danie0918 看下是否需要适配，但是如果 ckb-cli 导出的时候不带 input.lock 就不能离线签名，因为没办法根据 `outPoint` 确定 input 的 lock 从而确定 path

这是 Neuron 导出的格式

```
{
    "transaction": {
        "cellDeps": [
            {
                "outPoint": {
                    "txHash": "0xf8de3bb47d055cdf460d93a2a6e1b05f7432f9777c8c474abf4eec1d4aee5d37",
                    "index": "0"
                },
                "depType": "depGroup"
            }
        ],
        "headerDeps": [

        ],
        "inputs": [
            {
                "previousOutput": {
                    "txHash": "0x5280a7b097c324bc90b0323eb909bcefd2d688351778d0e5f0eac717646e031b",
                    "index": "0"
                },
                "since": "0",
                "capacity": "10000000000",
                "lock": {
                    "args": "0xebee504faf76661fed63f4db51fb42cbe57c875a",
                    "codeHash": "0x9bd7e06f3ecf4be0f2fcd2188b23f1b9fcc88e5d4b65a8637b17723bbda3cce8",
                    "hashType": "type"
                },
                "lockHash": "0xa3b998bdef6dfc8871532557a35bd2fbdcfa9f94082f5e89b8a2c6b18fe3ab9d",
                "status": "live"
            },
            {
                "previousOutput": {
                    "txHash": "0x5280a7b097c324bc90b0323eb909bcefd2d688351778d0e5f0eac717646e031b",
                    "index": "1"
                },
                "since": "0",
                "capacity": "30000999327",
                "lock": {
                    "args": "0xf6f0e7b1b58d320b48a7d420a1404633c97e4c69",
                    "codeHash": "0x9bd7e06f3ecf4be0f2fcd2188b23f1b9fcc88e5d4b65a8637b17723bbda3cce8",
                    "hashType": "type"
                },
                "lockHash": "0x4b9bd0940defed36ffadf71c9dab4582a53371c3f35a75da355f237efb476bbd",
                "status": "live"
            }
        ],
        "outputs": [
            {
                "capacity": "10000000000",
                "lock": {
                    "args": "0xc4a0dc550760aa4d296ca1e959a5c90bccf14a25",
                    "codeHash": "0x9bd7e06f3ecf4be0f2fcd2188b23f1b9fcc88e5d4b65a8637b17723bbda3cce8",
                    "hashType": "type"
                },
                "lockHash": "0xad6552baf1ccfd3ff7dd29d2ae3da084d87fda5a9b4c414f6b0cb796198628a3",
                "data": "0x"
            },
            {
                "capacity": "30000998513",
                "lock": {
                    "args": "0x638187b9a1180eea6b2ea149a2543b1983dec12f",
                    "codeHash": "0x9bd7e06f3ecf4be0f2fcd2188b23f1b9fcc88e5d4b65a8637b17723bbda3cce8",
                    "hashType": "type"
                },
                "lockHash": "0x7921be745cc70dab0e0e90e7be0f700b0e6fa5940755317119814f5cd6512890",
                "data": "0x",
                "isChangeCell": true
            }
        ],
        "witnesses": [

        ],
        "description": "",
        "nervosDao": false,
        "signatures": {

        },
        "hash": "0x60ec4d80e7d97d82eafd62dc891f07b5d2c34637341eb8fdfe08bab0131d2fb6",
        "version": "0",
        "fee": "814",
        "outputsData": [
            "0x",
            "0x"
        ],
        "size": 601
    },
    "type": "Regular",
    "status": "Unsigned"
}
```

**Comment by Keith-CY** [comment]
> @rink1969 确实有差异，如果离线签名需要确定 input 的 script 才能找到对应的 path，ckb-cli 导出的没有，另外 Neuron 的 json 文件变量名是驼峰不是下划线。
> 
> @Danie0918 看下是否需要适配，但是如果 ckb-cli 导出的时候不带 input.lock 就不能离线签名，因为没办法根据 `outPoint` 确定 input 的 lock 从而确定 path
> 
> 这是 Neuron 导出的格式
> 
> ```
> {
>     "transaction": {
>         "cellDeps": [
>             {
>                 "outPoint": {
>                     "txHash": "0xf8de3bb47d055cdf460d93a2a6e1b05f7432f9777c8c474abf4eec1d4aee5d37",
>                     "index": "0"
>                 },
>                 "depType": "depGroup"
>             }
>         ],
>         "headerDeps": [
> 
>         ],
>         "inputs": [
>             {
>                 "previousOutput": {
>                     "txHash": "0x5280a7b097c324bc90b0323eb909bcefd2d688351778d0e5f0eac717646e031b",
>                     "index": "0"
>                 },
>                 "since": "0",
>                 "capacity": "10000000000",
>                 "lock": {
>                     "args": "0xebee504faf76661fed63f4db51fb42cbe57c875a",
>                     "codeHash": "0x9bd7e06f3ecf4be0f2fcd2188b23f1b9fcc88e5d4b65a8637b17723bbda3cce8",
>                     "hashType": "type"
>                 },
>                 "lockHash": "0xa3b998bdef6dfc8871532557a35bd2fbdcfa9f94082f5e89b8a2c6b18fe3ab9d",
>                 "status": "live"
>             },
>             {
>                 "previousOutput": {
>                     "txHash": "0x5280a7b097c324bc90b0323eb909bcefd2d688351778d0e5f0eac717646e031b",
>                     "index": "1"
>                 },
>                 "since": "0",
>                 "capacity": "30000999327",
>                 "lock": {
>                     "args": "0xf6f0e7b1b58d320b48a7d420a1404633c97e4c69",
>                     "codeHash": "0x9bd7e06f3ecf4be0f2fcd2188b23f1b9fcc88e5d4b65a8637b17723bbda3cce8",
>                     "hashType": "type"
>                 },
>                 "lockHash": "0x4b9bd0940defed36ffadf71c9dab4582a53371c3f35a75da355f237efb476bbd",
>                 "status": "live"
>             }
>         ],
>         "outputs": [
>             {
>                 "capacity": "10000000000",
>                 "lock": {
>                     "args": "0xc4a0dc550760aa4d296ca1e959a5c90bccf14a25",
>                     "codeHash": "0x9bd7e06f3ecf4be0f2fcd2188b23f1b9fcc88e5d4b65a8637b17723bbda3cce8",
>                     "hashType": "type"
>                 },
>                 "lockHash": "0xad6552baf1ccfd3ff7dd29d2ae3da084d87fda5a9b4c414f6b0cb796198628a3",
>                 "data": "0x"
>             },
>             {
>                 "capacity": "30000998513",
>                 "lock": {
>                     "args": "0x638187b9a1180eea6b2ea149a2543b1983dec12f",
>                     "codeHash": "0x9bd7e06f3ecf4be0f2fcd2188b23f1b9fcc88e5d4b65a8637b17723bbda3cce8",
>                     "hashType": "type"
>                 },
>                 "lockHash": "0x7921be745cc70dab0e0e90e7be0f700b0e6fa5940755317119814f5cd6512890",
>                 "data": "0x",
>                 "isChangeCell": true
>             }
>         ],
>         "witnesses": [
> 
>         ],
>         "description": "",
>         "nervosDao": false,
>         "signatures": {
> 
>         },
>         "hash": "0x60ec4d80e7d97d82eafd62dc891f07b5d2c34637341eb8fdfe08bab0131d2fb6",
>         "version": "0",
>         "fee": "814",
>         "outputsData": [
>             "0x",
>             "0x"
>         ],
>         "size": 601
>     },
>     "type": "Regular",
>     "status": "Unsigned"
> }
> ```

https://neuron.magickbase.com/tools#raw_transaction_conversion 这个工具是否可以支持将 CKB-CLI 导出的交易转换成 Neuron 支持离线签名的格式

**Comment by yanguoyu** [comment]
> https://neuron.magickbase.com/tools#raw_transaction_conversion 这个工具是否可以支持将 CKB-CLI 导出的交易转换成 Neuron 支持离线签名的格式

可以的

**Comment by rink1969** [comment]
好的，我试一下那个转换工具

**Comment by rink1969** [comment]
我试了一下，那个转换工具是可以的。

但是有另外一个问题，就是我们的场景是2-3的多签，我想把tx.json用这个转换工具转成tx_new.json之后
让签署者分别用Neuron对交易进行部分签名
然后提取出各自的签名，依然用ckb-cli完善交易并发送。

我看了一下Neuron部分签名之后得到的是类似下面的内容
```
        "witnesses": [
            {
                "lock": "0x000002034ebb5e1aedb1cc3f35d033895209b4c92ed34c613dfd1e85ce86e6cdcaab956376c1c1def736dd744611340c95be480a7c128654bfec2e2021b4596c446c69cdaa9b86ce8b46fe3e709e5dbf21a6941df933f67645cc084f65b020555c32483dedb2c043f99fe5187f7cc7837c47cddc50e8bc2d199373fe845c4f8c00"
            }
        ],
        "description": "",
        "nervosDao": false,
        "signatures": {
            "0x460437697baa8978064fd940a05855439b2764daba14fe964c945edc62b1b111": [
                "0x3dfd1e85ce86e6cdcaab956376c1c1def736dd74"
            ]
        },
```

但是ckb-cli是：
```
$ ckb-cli tx sign-inputs --from-account ckt1qzda0cr08m85hc8jlnfp3zer7xulejywt49kt2rr0vthywaa50xwsqvm52pxjfczywarv63fmjtyqxgs2syfffq2348ad --tx-file tranfer-tx.json
Password:
- lock-arg: 0x9ba28269270223ba366a29dc96401910540894a4
  signature: 0x2207291086454794ce0f7ff6f63e15dc5610b999f02d63caae5dbf38fda20247384a64a7f96270f2abef7e37e444faa434a9e6c3e428eb9bdd02a13104cdc6f100

$ ckb-cli tx add-signature --lock-arg 0x9ba28269270223ba366a29dc96401910540894a4 --signature 0x2207291086454794ce0f7ff6f63e15dc5610b999f02d63caae5dbf38fda20247384a64a7f96270f2abef7e37e444faa434a9e6c3e428eb9bdd02a13104cdc6f100 --tx-file tranfer-tx.json
```

我猜测signature就在Neuron签名后的json中的witnesses.lock中，但是不知道这个lock是个什么结构？

**Comment by rink1969** [comment]
我解决了
看了下代码，Neuron签名后的json中的witnesses.lock就是签名，只不过是signRecoverable的，把pubkey加在前面了，取后半部分65字节就可以用到ckb-cli里了
