### ISSUE TITLE
empty wallet 

### ISSUE THREAD

**Issue by francis219** [nervosnetwork/neuron#3257]
### Topic Type

Incorrect Balance

### Detail of the issue

Good morning,
I emptied the cache of my Nervos wallet, and I have no more balance in my wallet. I can't even synchronise my wallet anymore.

I can't even connect, but in the settings there's no update to do.

thank you for your invaluable help .

<img width="791" alt="Capture 1" src="https://github.com/user-attachments/assets/020fd505-0330-46a4-88f2-d29cee26a1c6">
<img width="783" alt="Capture 2" src="https://github.com/user-attachments/assets/e85e6054-9575-4e54-a8fa-235d794029b6">

### bundled-ckb.log

```shell
I've copied you on the message that appears when I try to export the debug information
```

**Comment by francis219** [comment]
I received this file
[neuron_debug_1729973204777.zip](https://github.com/user-attachments/files/17531842/neuron_debug_1729973204777.zip)

**Comment by yanguoyu** [comment]
> I received this file [neuron_debug_1729973204777.zip](https://github.com/user-attachments/files/17531842/neuron_debug_1729973204777.zip)

Hi, From the log, the ckb node has not been fully started, so it is restarting the node all the time, resulting in very slow synchronization. You can try to close Neuron then close all Neuron and CKB related tasks in the task manager, and then try to start Neuron. If that doesn't work, let me know.

**Comment by francis219** [comment]
Good evening,

everything is in order now, thank you very much for your precious help.


Joël Francis Njudja
***@***.***
0764883615
________________________________
De : 严国宇 ***@***.***>
Envoyé : dimanche, 27 octobre 2024 03:40
À : nervosnetwork/neuron ***@***.***>
Cc : francis219 ***@***.***>; Author ***@***.***>
Objet : Re: [nervosnetwork/neuron] empty wallet (Issue #3257)


I received this file neuron_debug_1729973204777.zip<https://github.com/user-attachments/files/17531842/neuron_debug_1729973204777.zip>

Hi, From the log, the ckb node has not been fully started, so it is restarting the node all the time, resulting in very slow synchronization. You can try to close Neuron then close all Neuron and CKB related tasks in the task manager, and then try to start Neuron. If that doesn't work, let me know.
