### ISSUE TITLE
Where can the AppImage be downloaded?

### ISSUE THREAD

**Issue by probonopd** [nervosnetwork/neuron#590]
https://github.com/nervosnetwork/neuron/blob/c77d72cf3b57b3597d6b0cf188770f2fcd698ccd/packages/neuron-wallet/electron-builder.yml#L52

Reference:
https://github.com/AppImage/appimage.github.io/pull/1668

**Comment by ashchan** [comment]
From next alpha release AppImage binary will be provided along with deb.

**Comment by ashchan** [comment]
@probonopd We have auto build/release setup which includes the AppImage binary. Please look at https://github.com/nervosnetwork/neuron/releases/tag/v0.1.0-alpha.2 for an example.
