### ISSUE TITLE
Fix ESLint/Prettier conflict rules

### ISSUE THREAD

**Issue by ashchan** [nervosnetwork/neuron#61]
There's still conflict when ESLint and Prettier try to fix an import with multiple properties.

<img width="678" alt="screen shot 2019-02-19 at 9 40 12" src="https://user-images.githubusercontent.com/1391/52982652-9aafe400-342a-11e9-9da1-3406b6c02aa8.png">

<img width="586" alt="screen shot 2019-02-19 at 9 40 45" src="https://user-images.githubusercontent.com/1391/52982654-9daad480-342a-11e9-9874-714636cc2e04.png">

Note this has been very annoying and a road blocker when submitting new code changes.

**Comment by ashchan** [comment]
My guess is `object-curly-newline` conflicts with `printWidth`.

**Comment by ashchan** [comment]
Possible fixed via #62.

**Comment by wuyuyue** [comment]
![image](https://user-images.githubusercontent.com/40381396/52991146-64805d80-3446-11e9-9218-bf7471a40748.png)
can not submit now, would you please check this?
