### ISSUE TITLE
Built App cannot run in mac and win

### ISSUE THREAD

**Issue by Keith-CY** [nervosnetwork/neuron#78]
node_module `electron-window-state` cannot be resolved
![image](https://user-images.githubusercontent.com/7271329/53139281-1db87200-35c4-11e9-9fc1-886df83ffb3a.png)

**Comment by wuyuyue** [comment]
yarn build: wallet    tsc can not include electron-window-state; maybe we need webpack to include 3rd module while building

**Comment by ashchan** [comment]
Temporarily solved with #90. We'll improve the packaging tool to make it better later.
