### ISSUE TITLE
余额显示有问题

### ISSUE THREAD

**Issue by yuanaichi** [nervosnetwork/neuron#969]
收到ckb后 显示正确的余额
当再次打开钱包后 ckb余额显示为0， 再次接收到ckb后 余额显示正确

**Comment by classicalliu** [comment]
可以提供下 Neuron 的版本，所用 CKB 的版本，和 CKB 是否启用了 Indexer RPC 模块的信息么？

**Comment by VVanaheim** [comment]
钱包难做又容易出bug，现在都在用优盾了吧，安全功能又完善

**Comment by ashchan** [comment]
Closing due to no reply from author.
