### ISSUE TITLE
Balance not showing in wallet

### ISSUE THREAD

**Issue by ButteryGuitars** [nervosnetwork/neuron#971]
I setup a ckb 0.22.0 node. Node is fully synchronized with latest blocks. I created a wallet in Neuron and input receive address into the faucet. Explorer shows transaction is confirmed for 5,000 testnet ckb. However, the Neuron wallet does not show the transaction. I've double verified receive address was correct. I delete blockchain for ckb node and resynchronized. Still no luck.

I'm not sure what else to do at this point to make the funds visible...

**Comment by Keith-CY** [comment]
Currently, the Neuron App(v0.21.0-beta.1) supports up to CKB@0.21 while there're some incompatible updates from 0.22 to 0.21, which makes the App work improperly.

We'll upgrade the App in these few days to support CKB@0.22.

**Comment by ButteryGuitars** [comment]
That's very helpful! Thank you for the information. Will transactions sent on 0.22.0 just show up once it's supported?

**Comment by Keith-CY** [comment]
> That's very helpful! Thank you for the information. Will transactions sent on 0.22.0 just show up once it's supported?

Absolutely 😁

**Comment by ashchan** [comment]
We're releasing [v0.22.0](https://github.com/nervosnetwork/neuron/pull/973).

**Comment by ButteryGuitars** [comment]
I've confirmed the balance is available in 0.22.0 Neuron now. Thanks all!
